### ISSUE TITLE
Search by project

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#10]
I'd like to be able to limit searches to certain projects to avoid cases where I have thousands of unwanted results.

You could add a drop down menu like Visual Studio 'Search entire Solution' or 'Current project' (where 'current' comes from the active source file), but I think a potentially more powerful solution would be to allow filtering within the search box itself.

e.g. "FindMe +proj:MyProj" could filter projects that have MyProj in it, similarly use -proj:xxx to exclude projects. This is similar to Entrian search I mentioned in the multiple searches bug.

**Comment by slynch8** [comment]
you can ready filter results using the IN keyword. For example:
FindMe IN .h
FindMe IN myprojectname       - finds anything with myprojectname in the path
see here for a full list of keywords:
[https://www.puredevsoftware.com/fastfind/features.htm](https://www.puredevsoftware.com/fastfind/features.htm)

**Comment by Muzza** [comment]
Fantastic, I didn't know this existed already.
