### ISSUE TITLE
don't parse files if they are too big

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#1018]
There can be a big slowdown parsing files with huge arrays. It can take a long time to open files in 10x_notepad

**Comment by slynch8** [comment]
also, profile parsing of large arrays. Maybe it can be improved

**Comment by hstokholm** [comment]
I ran into this issue on some autogenerated files I opened accidently. This was a ~500 KB file of the form
```
namespace NS {
extern const unsigned long size= 467957;
extern const unsigned char data[] = {
0x78, 0x9C, 0xEC, 0xBD, 0x5B, 0xAF, 0x25, 0xB7, 0x91, ......
};}
``` 
It is not a critical issue for me because it is not something I should ever manually look at, but wanted to let you know.

**Comment by slynch8** [comment]
there is now a ParserMaxFileSize setting, which defaults to 10MB
