### ISSUE TITLE
FVector not working in UE5 pre-built

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#1040]

**Comment by slynch8** [comment]
needs support for __VAR_ARG__ macros

**Comment by TurtleSimos** [comment]
This is a much bigger issue.

UE_DECLARE_LWC_TYPE which requires VAR_ARG support is used a lot.

Case I was just seeing:
	UE::Math::TBox<float>	Bounds(OldVertexArray);
	FBox		Bounds(OldVertexArray);

The explicity one works, the FBox one goes via VAR_ARG so doesn't.

**Comment by TurtleSimos** [comment]
This mostly works now - version 0.33.36
Goto definition sometimes goes to a forward declaration, rather than the class.

For example:
C:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\AugmentedReality\Private\ARDebugDrawHelpers.h
UE_DECLARE_LWC_TYPE(Vector, 3);

**Comment by slynch8** [comment]
is this still an issue?

**Comment by TurtleSimos** [comment]
Yes, still the same in 0.35.6 as 0.33.36

**Comment by slynch8** [comment]
Can you give an example of a file where it goes to the declaration

**Comment by TurtleSimos** [comment]
Using a UE engine fle as an example so you have it.
\Engine\Source\Developer\LogVisualizer\Private\LogVisualizer.cpp
Line 153 is:
	FVector CurrentLocation = Entries[DBRow.GetCurrentItemIndex()].Entry.Location;
Click goto definition on the FVector there and it does to ARDebugDrawHelpers.h - 
C:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\AugmentedReality\Private\ARDebugDrawHelpers.h
UE_DECLARE_LWC_TYPE(Vector, 3);

**Comment by slynch8** [comment]
A work-around is to set `Parser.GotoDefResolvesTypedefs` to true. I'm going to see if I can get it to always resolve when it's in a preprocessed line

**Comment by slynch8** [comment]
it's done, seems to work well (0.35.10)
