### ISSUE TITLE
Key mappings for toggling showing the search results, build output, etc.

### ISSUE THREAD

**Issue by dangmoody** [slynch8/10x#1062]
So we have Ctrl+Shift+E (by default) to toggle the explorer tree.  I would love to have the same thing for windows like the search results (1-4), build output, etc.

Search results in particular, because I find it's a really common thing for me where I go searching for a term, do whatever, only to then want to go back into the search results.

I think this would be really handy to have, personally.

**Comment by septag** [comment]
another up vote on this.
I also have put my output/find panels on the bottom, it would be neat to be able to toggle them 
![image](https://user-images.githubusercontent.com/5081921/182815997-b9a77f20-49eb-4ad6-a913-b0f7cab5e8f8.png)

**Comment by slynch8** [comment]
done (0.33.6)
