### ISSUE TITLE
Toggle Comments breaks when commenting 'around' comments

### ISSUE THREAD

**Issue by detritivore** [slynch8/10x#1063]
having a comment on the starting line of the 'toggle comment area' will break the toggle.

with CommentBlockUsesLineComments = false, having a space between the 'comment-tags' seems to fix it.

with CommentBlockUsesLineComments = true, things are worse, since it actually breaks the code of the  affected lines.

**Comment by slynch8** [comment]
Hi. Could you give some example code for this?

**Comment by detritivore** [comment]
sure, if you look at the vids on discord, you can see it in action too, i've since discovered that it also breaks with a space between old and new comment, depending on the indenture of the code block

`	// comment
	if (1)
	{
		int a;

		int b;

		int c = a+b;
	}`

**Comment by slynch8** [comment]
sorry, I somehow missed your post on discord

**Comment by slynch8** [comment]
fixed (0.33.6)
