### ISSUE TITLE
Parser.AlignUsesSpaces doesn't work when a newline is inserted inbetween function arguments

### ISSUE THREAD

**Issue by stan680** [slynch8/10x#1070]
![20220808_154529](https://user-images.githubusercontent.com/8442114/183446086-0ff26d37-eb95-4f08-9917-e71d213a4567.gif)

Hopefully this gif shows, when I initially insert a newline and then add text to the empty new line, spaces are used, but when I move existing text onto a newline, tabs are used (until I replace the semi-colon, then it switches back to spaces).

**Comment by stan680** [comment]
Also, is there any chance of getting this to only use spaces for the alignment part but use tabs for standard alignment like this:
![image](https://user-images.githubusercontent.com/8442114/183446942-4ef7a55d-0500-4ad7-ab59-fc9af2038b64.png)

This is the behaviour you see in Sublime Text and it ensures that you don't need to reformat code to handle different Tab Width settings.

**Comment by stan680** [comment]
Maybe it's worth me connecting this with  #1068
Although that stuff is less fundemental

**Comment by slynch8** [comment]
done (0.33.27)
