### ISSUE TITLE
UIDs for breakpoints

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#1079]
RemedyBG recently added a new method to drive it via named pipes. I've been working to write a new python extension for 10x to control RemedyBG via pipes (previously I could control it via command line - but it was limited and slow). One of the main goals is reliable syncing of breakpoints.
RemedyBG has a UID for each breakpoint. It would be useful if 10x exposed something similar. Keeping a map between 10x and RemedyBGs breakpoints would be more reliable than working with filename/lines (which change during the course of editing).

**Comment by Muzza** [comment]
I noticed you added this, and it seems to be working, but I could do with a RemoveBreakpointByID command please.

**Comment by Muzza** [comment]
Also would be good if AddBreakpoint returned an ID

**Comment by Muzza** [comment]
The Breakpoint Updated function is called as soon as any editing is done on a file. For the purposes of syncing with a debugger, this function would ideally only be called as a file is saved to disk.

**Comment by septag** [comment]
just merged new rewrite of the remedybg NamedPipe implementation to the plugins. check it out.
Also now there is a #remedybg in the discord channel for further discussions.

**Comment by slynch8** [comment]
Thanks septag

links:
https://github.com/slynch8/10x/blob/main/PythonScripts/RemedyBG/RemedyBG.py

discord channel:
https://discord.com/channels/732150926810546186/1010858654787981372

**Comment by slynch8** [comment]
done (0.33.23)
- made BreakpointUpdated callback only happen when file is saved
- made python API AddBreakpoint function reutnr the id of the breakpoint
- added RemoveBreakpointById to python API
