### ISSUE TITLE
HighlightSelectedWordInScrollBar does not match Editor.HighlightSelectedWord

### ISSUE THREAD

**Issue by JeanGeffroy** [slynch8/10x#1082]
`Editor.HighlightSelectedWord` requires full word matching, but `HighlightSelectedWordInScrollBar` also highlights words containing the selected word, as illustrated by the following example.
 
![image](https://user-images.githubusercontent.com/100929413/185384759-075f7b7a-58ae-4e73-afbd-b4d2e5b1fe63.png)

This is with `HighlightSelectedWordInScrollBar: true` and `Editor.HighlightSelectedWord: true` in build 0.33.16. Note that `someVariableButDifferent` is highlighted in the map view when `someVariable` is selected, but not in the code view. There are benefits to either approach (full vs substring), and maybe that could be a separate setting, but the behavior in the map and code views should ideally match.

**Comment by slynch8** [comment]
fixed (0.33.21)

**Comment by JeanGeffroy** [comment]
Really nitpicking now, but it appears that there still is a mismatch with case sensitivity. See following example:
![image](https://user-images.githubusercontent.com/100929413/186079255-0b888377-9b09-456d-b371-542e5161d019.png)

`Editor.HighlightSelectedWord` is case sensitive, but `HighlightSelectedWordInScrollBar` isn't, so you can see that `someVar` and `SomeVar` are matching in the map view but not in the text view.

**Comment by slynch8** [comment]
word case fixed (0.33.23)
