### ISSUE TITLE
Can't move multiple cursors on one line down/up

### ISSUE THREAD

**Issue by stan680** [slynch8/10x#1086]
If I have multiple cursors on the same line and hit up or down, only the most recent cursor survives.

**Comment by moosichu** [comment]
Have also come across this! Although it's more complex - all the cursors survive but they will end up stacked in the same position (i.e. if you start typing you will get N characters where N is the number of cursors you had on the line before).

**Comment by Wassimulator** [comment]
also having this issue, would appreciate a fix! thanks Stewart :)

**Comment by slynch8** [comment]
fixed (1.0.45)
- fixed cursors moving to same char when moving up/down
- fixed multiple cursors overlapping
