### ISSUE TITLE
Cursor jumping multiple lines from text selection when regions are collapsed

### ISSUE THREAD

**Issue by Botondar** [slynch8/10x#1116]
Version is 0.33.36.

- When the cursor is at the beginning of the selection then moving the cursor downwards (e.g. w/ down-arrow) also moves the cursor up by however many lines have been collapsed above the current cursor position.
- When the cursor is at the end of the selection then moving the cursor upwards exhibits the same behavior (cursor is additionally moved up by the # of collapsed lines).

I hope my wording is clear enough to reproduce this issue.

**Comment by slynch8** [comment]
Hi, I can't get this. Could you provide a gif showing the problem?

**Comment by Botondar** [comment]
Here's the behavior moving the cursor down one line. The important thing is that this only happens when the selection is right-to-left:
![10x-rtl-jump](https://user-images.githubusercontent.com/16489781/187942257-455de273-01ca-4050-ac94-a693257b5995.gif)

And here's the behavior moving the cursor up one line when the selection is left-to-right:
![10x-ltr-jump](https://user-images.githubusercontent.com/16489781/187942785-4bfac15d-49e3-4898-82f9-4e99fcabe1e3.gif)

**Comment by slynch8** [comment]
Fixed (0.33.38)
