### ISSUE TITLE
Code folding fails if a declaration of the type: `My_Struct var = {0}`

### ISSUE THREAD

**Issue by AndreaBoroni** [slynch8/10x#1172]
The code folding takes the `}` in '{0}' as the closing parenthesis instead of finding the proper '}' later on. This happens in functions and for loops, so I am assuming it happens everywhere. Should be an easy fix.

**Comment by slynch8** [comment]
Is this still an issue? I can't get it to happen

**Comment by AndreaBoroni** [comment]
Just updated 10x and it seems fixed for me as well
