### ISSUE TITLE
New visual glitches and collision issues in latest build(0.34.19.0) (Windows 7)

### ISSUE THREAD

**Issue by kayakakan** [slynch8/10x#1195]
On Windows 7, with a 1080p monitor, the mouse doesn't collide properly with 10x's window size/move buttons. I'm talking specifically about the minimize, maximize/restore and close buttons. Only the left, top and bottom edges seem to pick-up the mouse hover for the first two buttons; the close button can only get hovered, and therefore somewhat used when pointing at its top edge and bottom edge. When inside the buttons, no hover happens and the buttons cannot  get clicked. Some Windows 95 buttons even appear if you try clicking then; they get drawn over 10x's buttons. The default Windows 7 frame gets drawn around 10x's window except for the top part. When maximized, 10x hides the taskbar if its set to auto-hide(which is an old bug that was fixed and re-appeared now). Here's an image to illustrate some of those glitches : 
![10x_glitches](https://user-images.githubusercontent.com/70589747/193479609-f7920151-ece9-4206-a952-f11f1b6e3988.png)
PS: I hope this isn't too frustrating, I saw you being so triumphant on Twitter, I feel bad for killing the mood...

**Comment by slynch8** [comment]
no problem, I expected some minor problems :-) Do the Windows buttons only appear if you hover over them?

**Comment by kayakakan** [comment]
No, you have to click to see them appear, but you have to be inside 10x's own rendered buttons. These additional buttons even animate as you click.

**Comment by slynch8** [comment]
Can you try this build, I'm hoping it will fix:
- borders
- hiding of the task bar
- buttons

https://e1.pcloud.link/publink/show?code=XZKp18ZG8wuUYCJFE7fCUvvOoJQajUae8xV

**Comment by kayakakan** [comment]
It fixed the Windows 95-ish buttons: they don't appear anymore. But, that's about it. The collision is still wrong in the same way, the taskbar is still inaccessible and the default Windows 7 frame still shows in restored for all window borders except the top one.
One at a time, I guess...

**Comment by kayakakan** [comment]
It's at the bottom. And to be frank, I feel like it worked at first, but every time I try it now, it doesn't work. Did I imagine it, or was it simply not maximized properly when it appeared to work? I'm as confuse as you are about this, maybe I did something by moving it or something.

**Comment by slynch8** [comment]
Do you have 2 monitors?

**Comment by kayakakan** [comment]
No, just one. I don't think I have anything fancy or special about my setup.

**Comment by slynch8** [comment]
Can you try this exe, it should show a grey window with a green border
https://e1.pcloud.link/publink/show?code=XZ4Jn8ZXAGlw2rz7zkrwVYHowb3nVHFuR2X

![image](https://user-images.githubusercontent.com/7141856/193809864-5f80e896-ec1b-4818-ba51-f8ca5b529e91.png)

**Comment by kayakakan** [comment]
Yes this works, as you can see : 
![BorderlessWindow](https://user-images.githubusercontent.com/70589747/193853497-f62175cd-0928-472b-b1b6-f027197f2b6f.png)
And the dropshadow too!

**Comment by slynch8** [comment]
awesome! I'll get this integrated into 10x

**Comment by slynch8** [comment]
Could you give this a try please. It should get rid of the border problem, and maybe fix a few other things too.
https://e1.pcloud.link/publink/show?code=XZB498Z4s7yisyOCkjAQ2E2cfdo4V5RzxbV

**Comment by kayakakan** [comment]
It works just as expected now : 
![10x_fixed](https://user-images.githubusercontent.com/70589747/193950397-2b5cfeec-e697-4105-870c-cff7f00db283.png)

**Comment by slynch8** [comment]
Great, thanks for checking. I'll take a look at the FancyZones problem next. Interesting that the borderless window exe works.

**Comment by slynch8** [comment]
done (0.34.20)

**Comment by kayakakan** [comment]
Congratulations on all of this. 10x finally integrates seamlessly with Windows after all these years 🎉.

**Comment by slynch8** [comment]
Thanks! :-) Just for fun I decided to try and get Win7 running again on a VM, but unfortunately I couldn't get it to connect to the internet so the installer failed. I had to give up in the end.

**Comment by kayakakan** [comment]
I don't remember it needing the Internet, that's weird. But you can trust me on this, everything works like it should. This editor feels very polished and professional!
