### ISSUE TITLE
Inconsistent c++ cast formatting

### ISSUE THREAD

**Issue by SirTimothy** [slynch8/10x#1200]
I've noticed the formatter seems to be inconsistent with what it does for the C++ style casts, adding or removing spacing in some parts, leaving others untouched (v 0.34.24)

```
static_cast<int>(a);             -->   static_cast<int>(a);
static_cast < int > ( a );       -->   static_cast<int > (a);

reinterpret_cast<int>(a);        -->  reinterpret_cast < int > (a);
reinterpret_cast < int > ( a );  --> reinterpret_cast < int > (a);
    
const_cast<int>(a);              -->  const_cast < int > (a);
const_cast < int > ( a );        --> const_cast < int > (a);

dynamic_cast<int>(a);            --> dynamic_cast<int>(a);
dynamic_cast < int > ( a );      --> dynamic_cast<int > (a);
```

`static_cast` and `dynamic_cast` seem to leave the spacing around `>` alone while collapsing `<` and the parentheses. `reinterpret_cast` and `const_cast` seem to be always expanding with whitespace everywhere.

**Comment by slynch8** [comment]
fixed (0.34.32)
