### ISSUE TITLE
Inconsistent and frustrating file open

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#1201]
When I open a file with the "Find file" window, I can never predict in which panel the file is going to be opened. Sometimes it's the one that is current focused (this is the behavior I want), sometimes it opens in a new vertical panel, sometimes in a new horizontal panel, sometimes it opens 2 new panels and place the file in the last one, sometimes it opens the file in the panel where my "build" and "find in files" windows are.

It doesn't even seem to be related to where the file was opened last, because each time a file is opened at the wrong place, I drag it to my main window, but when I reopened it it's placed again in a wrong panel.

I tried to change the options in View > Columns and View > Vertical Panels but it doesn't change the inconsistent file opening.

One last thing, my files are C#, I don't know if that changes anything.

**Comment by slynch8** [comment]
I'll be taking a look at this tomorrow. For now try clearing the UI.Column0Files settings. It should remember where the file was when it last opened, but there seems to be a but where it will favor the bottom panel for some reason.

**Comment by slynch8** [comment]
In build (0.34.27) I've removed all the code that chooses where to open a file, it should now always open at (0, 0). Hopefully that's better.

I've also added these settings which default to false:
```
OpenFileInActivePanel:
RememberFilePanelPos:
```
