### ISSUE TITLE
Function args tooltip doesn't show parameters when split across lines in definition

### ISSUE THREAD

**Issue by SirTimothy** [slynch8/10x#1215]
(v0.34.29)
In this case the parameters are correctly shown:

<img width="305" alt="image" src="https://user-images.githubusercontent.com/6760500/195767271-35461ce8-6f92-4f13-99fd-546b806b1359.png">

But if the parameters are on multiple lines, they don't show up:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/6760500/195767404-4cf1e490-4306-4268-91c8-58665bef0416.png">

**Comment by slynch8** [comment]
fixed (0.35.6)
