### ISSUE TITLE
Releasing LMB outside the window while selecting text, does not stop the selection.

### ISSUE THREAD

**Issue by philipkatis** [slynch8/10x#1218]
When selecting text using the mouse, if the left mouse button is released while the cursor is outside the window, the WM_LBUTTONUP message is not registered. So when the cursor enters the window, you are able to select text without having the left mouse button pressed.

This could be fixed by using `SetCapture()` on WM_LBUTTONDOWN and `ReleaseCapture()` on WM_LBUTTONUP.

**Comment by slynch8** [comment]
fixed (0.34.32)
