### ISSUE TITLE
Add a shortcut for toggling line comments

### ISSUE THREAD

**Issue by mateberes** [slynch8/10x#1229]
Currently you can either use ToggleComments, which use line / block comment depending on the selection, or the CommentLine / UncommentLine pair.

It would be nice, if there was a specific shortcut only for toggling line comments, so you didn't have to carefully select the lines you want to comment / uncomment.

Thanks!

**Comment by slynch8** [comment]
I'm not sure I follow, CommentLine comments the current line and doesn't require selection

**Comment by slynch8** [comment]
I see. I think you can get the behavior you want by setting `UI.CommentBlockUsesLineComments` to true

**Comment by mateberes** [comment]
Ah nice, sorry didn't know about that. 
Thanks!
