### ISSUE TITLE
how to remove the ".h" file pannel?

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#1232]
Hi! first of all, congrats for 10x, the speed is awesome!
When I open a cpp it always go to the left pannel, and when opening a .h it always go to the right pannel.
Is there a way to have a single and larger pannel, displaying all files? (whatever .cpp or .h) 

thanks in advance!

**Comment by slynch8** [comment]
Hi, thanks very much.

To stop headers opening in the right panel you need to clear these settings

![image](https://user-images.githubusercontent.com/7141856/197749053-feeea296-0046-4231-b9bc-3d69f3d0a3b2.png)

Also, you might need to set RememberFilePanelPos to false.

**Comment by arnaud-carre** [comment]
awesome! 

Another two small things I noticed, maybe there is already a way to configure/change behavior:
- when typing #include "xxxx" there is no automatic completion of include path. Any option to activate?
- I'm use to "CTRL-D" in visual studio to dupplicate a line (without nuking the current copy/paste clipboard). Is there a way to do that?

thanks!

**Comment by arnaud-carre** [comment]
just tested auto completion again: it works if you start to write #include from scratch. But let's say you already have:

#include "foo1/foo2/foo3.h"

and you erase back to :

#include "foo1/foo2

type "/" again after foo2, and then you don't have auto completion

**Comment by arnaud-carre** [comment]
awesome!
