### ISSUE TITLE
findfile issue when it contains numbers

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#1233]
I'm used to find file "alt shit o", and it also supports lazy naming like typing "a b" to find any "a*b" file.

However, if I have a file named "DrawBuffersD3D11.cpp" and type "draw 11" it doesn't find the file. ( visual assist does ).

I have the feeling there is an issue when it contains some numbers.

**Comment by slynch8** [comment]
fixed (0.35.0)
