### ISSUE TITLE
Character literals with digits not parsing properly

### ISSUE THREAD

**Issue by Botondar** [slynch8/10x#1234]
Issue can be seen here:
![image](https://user-images.githubusercontent.com/16489781/197967946-57ab1bc0-09d9-4bc6-9e62-7dbad9450472.png)

Version is 0.34.39, though I'm guessing this was introduced in 0.34.36 when digit separators were added.

**Comment by slynch8** [comment]
good catch, yes it will be the digit separators change. I'll get this fixed.

**Comment by slynch8** [comment]
fixed (0.34.40)
