### ISSUE TITLE
where is located pannel layout config file?

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#1235]
I'm testing 10x using existing visual studio .sln files. It works very well! I change a bit pannel settings ( like 1 pannel only instead of 2). I just noticed that my custom layout is automatically saved "somewhere", and it seems to be "per sln". Where is located that layout config file so I can revised it?

**Comment by slynch8** [comment]
yes, they're stored in %appdata%\10x\Workspaces\

**Comment by arnaud-carre** [comment]
thks
