### ISSUE TITLE
Opening a folder is ommiting a subfolder in Workspace Tree 

### ISSUE THREAD

**Issue by alexgrpds** [slynch8/10x#1240]
I tried to drag and drop Quake 2's source code folder (git cloned from "https://github.com/id-Software/Quake-2") to the editor, all folders are showing at the Workspace Tree with the exception of the "win32" folder which is omitted completely. When I try to drag and drop only this specific folder on a newly opened instance of the program, the folder also does not show up at all and no logging in "10x output" is generated. 

The same thing happens when I choose the folder from "File->Open Folder". 

![10x](https://user-images.githubusercontent.com/69468239/198327574-41e0258d-0453-4ebe-aac7-c30257ddc48d.jpeg)

**Comment by slynch8** [comment]
You need to remove Win32 from the Exclude Filter in the Workspace Settings. Right click on the folder in the workspace tree and select "Settings...". I think I'll remove that from the default list.

**Comment by alexgrpds** [comment]
Thanks!

**Comment by slynch8** [comment]
win32 removed from the default list (0.35.0)
