### ISSUE TITLE
Independent settings for each workspace/solution

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#1244]
I always work with at least 2 opened solutions which have different `Parser.AdditionalIncludePaths` and `Build.VisualStudioEnvBat`. Is there any way to not to override `%AppData%/10x/Settings/Settings.10x_settings` file, but just use local one that is located near `.sln` or `.10x_workspace` file? Or maybe just make a `.10x` folder or something in the working directory that will contain all the settings you need (maybe some more useful stuff?) which will be used instead of/with global ones?

So the whole thing is about to make something like:
1. If local setting is found use local one instead of the global one and do not write it to global file.
2. If local setting is found use local + global setting (useful with include paths) and do not write it to global file.

**Comment by slynch8** [comment]
You can do this with by adding a 10x.10x_settings file to the same folder as the sln. It will override any settings in the appdata settings file.

**Comment by Roman-Skabin** [comment]
Yeah, and I do do that. But ideally I'd like to not to override global settings.

**Comment by slynch8** [comment]
If the setting is not in the 10x.10x_settings file it will use the global setting

**Comment by Roman-Skabin** [comment]
Oh, nice. Works perfectly. Just as I wanted to. I still were using OverrideSettings.py script, so that's why global settings file were overwriting all the time. Now it doesn't.
