### ISSUE TITLE
Scroll bar doesn't update when closing region

### ISSUE THREAD

**Issue by JackWesleyNelson** [slynch8/10x#1248]
When I close a region (at least for a struct, didn't really test this with anything else) the scroll bar for the currently viewed page (and a bit more) goes blank. Sometimes scrolling the page a bit will update the scroll bar to the correct view, while other times it doesn't. Opening the region back up seems to always restore it to it's previous state.

Default:
![image](https://user-images.githubusercontent.com/8739573/199371999-1979dc27-8901-4801-bbbd-cfe8a2923527.png)
After closing struct region:
![image](https://user-images.githubusercontent.com/8739573/199372092-cdc803b5-5f5a-4d6a-9bec-eb1c93093c9a.png)
After scrolling:
![image](https://user-images.githubusercontent.com/8739573/199372158-63e8290c-538c-4dc6-8ddd-5e21e9ccafb5.png)
After Re-Opening struct region: 
![image](https://user-images.githubusercontent.com/8739573/199371999-1979dc27-8901-4801-bbbd-cfe8a2923527.png)

**Comment by slynch8** [comment]
fixed (0.35.6)
