### ISSUE TITLE
Region won't collapse if line begins with a #defined keyword

### ISSUE THREAD

**Issue by JackWesleyNelson** [slynch8/10x#1249]
Given three functions, the first two close just fine, but the third will not because it begins with the defined word internal. Even though the second and third are otherwise equivalent. The option to close still appears, it simply does nothing if clicked.

![image](https://user-images.githubusercontent.com/8739573/199375156-d52832a0-c125-4bd6-9d21-6c095b7f2cde.png)

**Comment by slynch8** [comment]
fixed (0.35.6)
