### ISSUE TITLE
`using` keyword combined with `__declspec` (or any other attribute) doesn't parse correctly

### ISSUE THREAD

**Issue by septag** [slynch8/10x#1256]
it doesn't work with any other attributes either.

<img width="178" alt="image" src="https://user-images.githubusercontent.com/5081921/201921416-37ff7bde-0a5c-4f36-903f-807126b2bd81.png">

<img width="286" alt="image" src="https://user-images.githubusercontent.com/5081921/201921368-d7249636-5f75-4410-8906-6ec8c4b5eefe.png">

**Comment by slynch8** [comment]
I think I fixed this
