### ISSUE TITLE
New Bug: MSBuild.exe is not recognized

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#1262]
After updating to version 0.35.39 my build system is broken because MSBuild.exe can't be found, even though I have configured VisualStudioEnvBat to "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat".

**Comment by slynch8** [comment]
someone else just had the same issue but it mysteriously went away.

Is this the error you are seeing? `Build failed. VSEnvBat not setup. Check your 'VisualStudioEnvBat' setting`

**Comment by slynch8** [comment]
Can you try closing 10x. Open 10x without any workspace. Wait a few seconds, then open the sln

**Comment by bousquetm** [comment]
This is the build output I have:

`----- Build Debug x64 -----
Executing build command:
MSBuild.exe ../VS/LD33_x64.sln -target:Build -p:Configuration=Debug;Platform=x64 -verbosity:minimal
'MSBuild.exe' n'est pas reconnu en tant que commande interne
ou externe, un programme ex‚cutable ou un fichier de commandes.
===== Fail : 1 errors, 0 warnings =====`

I don't use the sln directly, I have a proper .10x workspace that has the following Build Command:

`MSBuild.exe ../VS/LD33_$(Platform).sln -target:Build -p:Configuration=$(Configuration);Platform=x64 -verbosity:minimal`

I tried to close 10x, reopen it with no workspace and then load the .10x file but it doesn't change anything.

**Comment by slynch8** [comment]
Ah ok. This is a 10x workspace. I've stopped it using the VisualStudioEnvBat setting for 10x workspaces, the setting is only for VS projects. Although I can see it would be useful in cases like this. I can add a setting for it. Or you could create a bat file that calls VsDevCmd.bat first.

**Comment by bousquetm** [comment]
I've changed my workspace Build Command to `"C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/Tools/VsDevCmd.bat" && MSBuild.exe ../VS/LD33_$(Platform).sln -target:Build -p:Configuration=$(Configuration);Platform=x64 -verbosity:minimal` so that it starts the VS env every time and it works... However it takes 1 second or 2 to start every time and this is not ideal.

I could live like that, it's up to you if you want to add another settings.

Cheers

**Comment by slynch8** [comment]
ok, I'll add a setting

**Comment by bousquetm** [comment]
Wait, now when I press F5, nothing happens after the build and I have this error after maybe 10s:

`Failed to connect to VosualStudio instance`

edit: thanks for the settings

**Comment by slynch8** [comment]
I think that's related to the same thing, it needs VisualStudioEnvBat to be set

**Comment by slynch8** [comment]
fixed (0.35.40)

I've added the new setting and fixed the debugger not starting

![image](https://user-images.githubusercontent.com/7141856/203162469-3ea5a006-a982-433c-aed3-a0c5380e4cd6.png)

**Comment by bousquetm** [comment]
Thank you
