### ISSUE TITLE
command to show the mouse hover tooltip so it can be bound to a key

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#1270]

**Comment by arnaud-carre** [comment]
that would be great. Probably also a dupplicate of this request: https://github.com/slynch8/10x/issues/1243

**Comment by slynch8** [comment]
I forgot to close this, it went in a few versions back. It's bound to `control+K,control+I` by default

**Comment by arnaud-carre** [comment]
oh sorry then maybe it's not the exact same. What I tried to request is this use case: Let's say you're moving into the code with cursor key only ( not using mouse ). And you put the cursor over a function call. In this case you don't see the function prototype anywhere. ( unless you grab your mouse and put the mouse over the function call, and you get a tooltip).
I was wondering if it could be possible to have like a status line somewhere in the editor, that is always displaying what the mouse tooltip would have displayed?

**Comment by slynch8** [comment]
yes, I've closed this bug but left the other one open

**Comment by arnaud-carre** [comment]
awesome! thanks
