### ISSUE TITLE
.10x_workspace file is being rewritten on open workspace

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#1276]
I have a .10x_workspace for shaders in a project. The structure of a file looks like this:
```xml
<?xml version="1.0"?>
<N10X>
	<Workspace>
		<FileTypes>Shaders (*.fx,*.fxh)</FileTypes>
		<ExcludeFilters>
			<!-- A lot of folders, that are being added to a workspace tree that do not have <FileTypes> files in it I do not want to see. -->
		</ExcludeFilters>
		<SyncFiles>true</SyncFiles>
		<Recursive>true</Recursive>
		<IsVirtual>false</IsVirtual>
		<IsFolder>false</IsFolder>
		<UseVisualStudioEnvBat>false</UseVisualStudioEnvBat>
		<!-- Some build, rebuild, clean commands, a pair of configurations, platforms, additional include paths, defines -->
		<Children>
			<Folder>
				<Name>Formats</Name>
				<Path>relative/path/to/folder/here</Path>
				<FileTypes>xml (*.xml)</FileTypes>
				<SyncFiles>true</SyncFiles>
				<Recursive>true</Recursive>
				<IsVirtual>true</IsVirtual>
				<IsFolder>true</IsFolder>
			</Folder>
		</Children>
	</Workspace>
</N10X>
```

The problem is when I open it 10x opens the workspace, but without `Formats` folder. I've opened this workspace but with 10x notepad, just to see what's wrong with it. And have seen that It became look like this:
```xml
<?xml version="1.0"?>
<N10X>
	<Workspace>
		<FileTypes>Shaders (*.fx,*.fxh)</FileTypes>
		<ExcludeFilters>
			<!-- A lot of folders, that are being added to a workspace tree that do not have <FileTypes> files in it I do not want to see. -->
		</ExcludeFilters>
		<SyncFiles>true</SyncFiles>
		<Recursive>true</Recursive>
		<IsVirtual>false</IsVirtual>
		<IsFolder>false</IsFolder>
		<UseVisualStudioEnvBat>false</UseVisualStudioEnvBat>
		<!-- Some build, rebuild, clean commands, a pair of configurations, platforms, additional include paths, defines -->
		<Children>
			<!-- Exclude filters from the above for each folder in the working directory -->
			<!-- Removed "Formats" folder from the original file -->
		</Children>
	</Workspace>
</N10X>
```

I'm not sure that a lot of new exclude filters is an issue, but the removal of the `Formats` folder I think it is.
Also it's being rewritten without any "Do you want to save new changes in workspace file?" or something. It just being changed at startup without any permissions.

\
\---------------------
Version: 0.35.44

**Comment by slynch8** [comment]
I did change the way 10x workspace folders work a few versions back. You can't add relative folders to sync'd folders anymore. If SyncFiles is true then 10x will sync that folder and write out the sync'd children, replacing anything you have added there. So you either need to disable SyncFiles or use another folder. SyncFiles is badly named, it also sync's folders.

Are you saying that the excluded files/folders are appearing in Children now? That shouldn't be the case, the exclude filters should work as before.

**Comment by Roman-Skabin** [comment]
Also I think that workspace tree contains all folders from a project, but not just those that have `<FileTypes>` files when you set `<Recursive>` to `true` is an error too. Because if you want your workspace to contain all the `.hlsl` files from your project I think you have to just set `<Recursive>` to `true` and set `<FileTypes>` to `*.hlsl` and see only those folders that contain `.hlsl` files. Maybe I'm wrong and there is already a way to do that without creating dozens of exclude filters.

**Comment by Roman-Skabin** [comment]
`Are you saying that the excluded files/folders are appearing in Children now? `
\- Yes

**Comment by Roman-Skabin** [comment]
And just a question what do `SyncFiles`, `Recursive`, `IsVirtual` and `IsFolder` stand for? `Recursive` I think is clear - it just scans for each file type from the `<FileTypes>` recursively. But what do others stand for?

**Comment by slynch8** [comment]
That's a good point about not adding folders that don't contain any files in FileTypes. I'll change that.

Each child folder will write out all the folder settings, SyncFiles, Recursive, etc. Although for folders that are sync'd these should be ignored and it should use the root sync'd folder settings. Basically, every folder of workspace is a Node and there is just one Node::Write function that always gets called. The SyncFiles makes things behave a bit differently. Ideally, for sync'd folders I wouldn't write these settings out and it would be less confusing.

I'll be writing all this up soon, and I'm still not 100% sure I've got the design right, but how it works now is:

`FileTypes` this is the include filter. Only files that match these filters will be included
`SyncFiles` if this is true child files and folders will be sync'd from disk. If it is false you can add files and folders yourself
'Recursive' if SyncFiles is true, files and folders will be sync'd recursively

`IsFolder` and `IsVirtual` are not used anymore and have been removed.

There is a new `AutosaveWorkspace` setting that defaults to true, you can turn this off.

One thing that might be a bit confusing (I'm still thinking about this) is that for sync'd folders (`SyncFiles` is true) it won't normally write out any children. This is so that the .10x file doesn't need to change each time files are added/removed. However, if the children are re-ordered it will write them out so that the order can be saved. If `SyncFiles` is true and there are Children it assumes the children have been re-ordered, which led to the confusion in your case.

I really must rename `SyncFiles` to just `Sync` or `SyncFolder`

**Comment by Roman-Skabin** [comment]
Ok, so let's say I want to make a workspace for `.ext1` and `.ext2` files, but for `.ext2` files only from a specific folder. So I'm gonna write something like this:
```xml
<Workspace>
    <FileTypes>ext1 files (*.ext1)</FileTypes>
    <Recursive>true</Recursive>
    <Children>
        <Folder>
            <FileTypes>ext2 files (*.ext2)</FileTypes>
            <Path>relative/path/to/folder/with/ext2/files</Path>
            <Recursive>true</Recursive>
        </Folder>
    </Children>
</Workspace>
```
Without `SyncFiles` it won't work, but with `SyncFiles` it will remove `ext2 files` folder. So how? I cannot manually add all `.ext1` files into workspace because there are dozens of them and they can differ from branch to branch. There are not that many `.ext2` files, but anyway from branch to branch they differ too, so I can easily miss some of them if I will add them manually as well.

**Comment by Roman-Skabin** [comment]
### About `SyncFiles` setting:

I think it's redundant: you either want to have `<FileTypes>` files recursively or not. So if you set `<Recursive>` to `false`, then you have to add all the files manually, if not, then they will be added automatically according to `<FileTypes>` setting.
Also, it seems like if you set `<Recursive>` to `false` `<FileTypes>` setting has no sense anymore and you can ignore it since you add all the files manully.

**Comment by Roman-Skabin** [comment]
But there is a situation when you want `<FileTypes>` files only from the current folder, and not recursively. In that case you can just have only 1 setting: `<Sync>` or something that will have several values, like sync recursively,  sync only current directory or no sync at all.

I think that should be that best way.

**Comment by slynch8** [comment]
I see, you're trying to set settings on a sync'd folder. I'll have a think and see if I can find a nice way of doing that.

I think you're right, that it's redundant. It was mostly just done for clarity. If someone wanted to turn syncing off it might not be obvious that they have to clear the FileTypes setting. But you're right, if SyncFiles is false the FileTypes setting is ignored. I'll have a think about this. It might just grey out the setting in the UI.

**Comment by slynch8** [comment]
If you set Recursive to false then FileTypes should still apply to the files in the current folder.

**Comment by Roman-Skabin** [comment]
Hmm, also, maybe there is a sense to make `<SyncFiles>` setting `<SyncDepth>` or something: you just tell how deep you want to sync `<FileTypes>` files in the `<Path>`. 0 for no sync, 1 for current directory and so forth.

**Comment by slynch8** [comment]
Would it be acceptable to have the .ext1 files and .ext2 files under different folders, or would that be confusing?
```
Root
    Ext1Folders
        Folder
            file.ext1
    Ext2Folders
        Folder
            file.ext2
```

**Comment by Roman-Skabin** [comment]
That would be good I think

**Comment by Roman-Skabin** [comment]
You mean I can create 2 child folders and sync them instead of syncing workspace?

**Comment by slynch8** [comment]
yes

**Comment by Roman-Skabin** [comment]
It doesn't work:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/40520199/204293333-b6d1ce81-1073-4975-866e-d34a08a9130f.png">

.10x_workspace file:
```xml
<?xml version="1.0"?>
<N10X>
	<Workspace>
		<FileTypes>ext1, ext2, ext3 files (*.ext1,*.ext2,*.ext3)</FileTypes>
		<SyncFiles>false</SyncFiles>
		<Recursive>false</Recursive>
		<AutosaveWorkspace>false</AutosaveWorkspace>
		<!-- build, rebuild, configs, defines, ... -->
		<Children>
			<Folder>
				<Name>ext1, ext2 files</Name>
				<Path>.</Path>
				<FileTypes>ext1, ext2 files (*.ext1,*.ext2)</FileTypes>
				<SyncFiles>true<SyncFiles>
				<Recursive>true<Recursive>
			</Folder>
			<Folder>
				<Name>ext3 files</Name>
				<Path>relative/path/to/some/folder</Path>
				<FileTypes>ext3 files (*.ext3)</FileTypes>
				<SyncFiles>true<SyncFiles>
				<Recursive>true<Recursive>
			</Folder>
		</Children>
	</Workspace>
</N10X>
```

**Comment by slynch8** [comment]
It looks like it should do. Can you try closing 10x and deleting the %appdata%\10x\workspaces\<workspace> folder?

**Comment by Roman-Skabin** [comment]
Still doesn't
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/40520199/204295807-144c70b2-7fb8-48a1-9311-74f839565fb8.png">

**Comment by slynch8** [comment]
I'm not sure what's different, but here's a workspace that works

[WorkspaceTest2.zip](https://github.com/slynch8/10x/files/10104354/WorkspaceTest2.zip)

**Comment by slynch8** [comment]
`FileTypes` has renamed to `IncludeFilter` but the old name and format should still work

**Comment by slynch8** [comment]
```
<N10X>
	<Workspace>
		<IncludeFilter>*.c,*.cc,*.cpp,*.c++,*.cp,*.cxx,*.h,*.hh,*.hpp,*.h++,*.hp,*.hxx,*.inl,*.cs,*.rs,*.java,*.jav,*.js,*.jsc,*.jsx,*.json,*.cls,*.py,*.rpy,*.php,*.php3,*.phl,*.phtml,*.rhtml,*.tpl,*.phps,*.lua,*.html,*.html5,*.htm,*.xml,*.xaml,*.css,*.ssi,*.haml,*.yaml,*.bat,*.wbf,*.wbt,*.txt,*.cmake,*.make,*.makefile,*.mak,*.mk,*.sh,*.bash,*.csv,*.asp,*.pl,*.mac,*.ws,*.vbs,*.perl,*.src,*.rss,*.inc,*.f,*.go,*.prl,*.plx,*.rb,*.lsp,*.lpx,*.ps1,*.command,*.cbl,*.cob,*.qs,*.wxs,*.ph,*.msc,*.glsl,*.hlsl,*.fx,*.vert,*.tesc,*.tese,*.geom,*.frag,*.comp,*.pssl,*.scons,</IncludeFilter>
		<ExcludeFilter></ExcludeFilter>
		<SyncFiles>false</SyncFiles>
		<Recursive>true</Recursive>
		<!-- ... -->
		<Children>
			<Folder>
				<Path>Ext1Files</Path>
				<IncludeFilter>*.ext1,</IncludeFilter>
				<ExcludeFilter></ExcludeFilter>
				<SyncFiles>true</SyncFiles>
				<Recursive>true</Recursive>
				<IsVirtual>false</IsVirtual>
				<Children></Children>
			</Folder>
			<Folder>
				<Path>Ext2Files/Folder2</Path>
				<IncludeFilter>*.ext2,</IncludeFilter>
				<ExcludeFilter></ExcludeFilter>
				<SyncFiles>true</SyncFiles>
				<Recursive>true</Recursive>
				<IsVirtual>false</IsVirtual>
				<Children></Children>
			</Folder>
		</Children>
	</Workspace>
</N10X>
```

**Comment by slynch8** [comment]
I was wrong about the IsVirtual flag, it is still used. But it doesn't do much other than show the simplified Virtual folder dialog in the UI and change 'Path' to 'Name' in the xml. I could probably remove it. A virtual folder just means that it doesn't correspond to a folder on disk, and it's not possible to enable syncing.

**Comment by slynch8** [comment]
btw, the `AutosaveWorkspace` setting is a general 10x setting stored in the .10x_settings file

**Comment by Roman-Skabin** [comment]
Idk what helped: additing `IsVirtual` or removing `AutosaveWorkspace` but now it works. The name of the folder is not that nice, but it works.
![image](https://user-images.githubusercontent.com/40520199/204301594-a15de625-df10-4298-bf2f-835aa5f93982.png)

**Comment by Roman-Skabin** [comment]
I've created with 10x UI and now it works.

**Comment by slynch8** [comment]
That's good. I've made some improvements to the UI recently, so it's probably best to stick with the UI now.

I will have a think about setting values on sync'd folders. It's a valid thing to want to do. But at the moment I can't think of a way of doing it that doesn't add even more complication. At the least I'll disable the settings UI for sync'd folders.
