### ISSUE TITLE
Incorrect highlighting for using functions

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#1279]
cmath:
![image](https://user-images.githubusercontent.com/40520199/204499710-a370ce03-a25e-4e36-a59a-f97c903fd438.png)

file.cpp:
![image](https://user-images.githubusercontent.com/40520199/204500044-b144e4da-966e-4e3d-a2a5-910fe3e8ffcc.png)

\
\--------------------
version: 0.35.49

**Comment by Roman-Skabin** [comment]
![image](https://user-images.githubusercontent.com/40520199/204500605-f0629716-584d-47af-a274-8d97a3cc85f4.png)

![image](https://user-images.githubusercontent.com/40520199/204500641-2e8df56a-29e0-49d0-aa66-a87209a78de6.png)

![image](https://user-images.githubusercontent.com/40520199/204500687-a8084e39-be85-4f66-94e3-a50987bb681a.png)

![image](https://user-images.githubusercontent.com/40520199/204500802-397586eb-d9c2-47f4-9d71-5851ff3e5eec.png)

It seems like `::` before `foo` confuses parser.

**Comment by slynch8** [comment]
thanks for the examples, this is fixed in latest
