### ISSUE TITLE
Vertical Mouse Scroll broken after long update

### ISSUE THREAD

**Issue by forrestsmithfb** [slynch8/10x#1293]
I tried 10x November 2021. It showed promise but had some blocking issues. I uninstalled the old version and installed latest. There was a weird crash on first launch. Re-launch it seemed fine, except vertical scroll with mouse wheel didn't work. Uninstall / reinstall and it still didn't work.

Then I uninstalled, deleted all 10x related folders under AppData, and re-installed. This fixed my mouse wheel scroll. 

I did at some point run a debug build you sent me a year ago to track down a crash. So there's no telling what kind of frankenstein state my local machine was in. 

My problem solved and I, unfortunately, don't have a repro.

**Comment by slynch8** [comment]
ok, thanks for letting me know. I'm not sure what would have caused that, I'll keep a lookout

**Comment by slynch8** [comment]
could you send me the crash dump for that crash?

**Comment by slynch8** [comment]
I've uploaded a fix for the crash. 

Let me know if you get any more blocking issues.
