### ISSUE TITLE
Added folder gets removed everytime I reopen the workspace

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#1296]
I'm trying to add the existing folder "../VS/Generated" to my .10_workspace. It works well except that when I close the editor and reopen it, the folder is gone in the workspace tree. Opening the workspace as text shows that the folder is indeed not listed in the <Children> list.

edit: I have the latest version.

**Comment by slynch8** [comment]
Did you definitely save the workspace after adding it?

**Comment by slynch8** [comment]
Although it should have prompted you when you closed if you hadn't

**Comment by bousquetm** [comment]
Yes, the workspace is saved, I can diff it and see that it's been modified on disk with the added folder. It's when I reopen the editor that the file gets reverted back.

**Comment by slynch8** [comment]
did you add it to a sync'd folder? Sync'd folders will re-sync on each open, removing anything you have added manually

**Comment by bousquetm** [comment]
Ah, you're right. The root of the workspace is sync'ed so yeah that makes sense. Thank you.

**Comment by slynch8** [comment]
although it shouldn't be possible to add a folder to a sync'd folder. How did you do it?

**Comment by bousquetm** [comment]
In the workspace tree, right click on the root of the project, then "Add existing folder...", select the folder and then "Ok".

**Comment by slynch8** [comment]
ok, I'll make sure that's disabled

**Comment by slynch8** [comment]
done (0.35.68)
