### ISSUE TITLE
Support for P4CONFIG

### ISSUE THREAD

**Issue by daveratti** [slynch8/10x#1297]
It appears I need to hardcode my perforce settings in LocalSettings.10x_settings. In practice I have several development streams that I work in each with their own P4 workspace. I use P4CONFIG to set these P4 environment variables "seamlessly" when using command line tools or Visual Studio. It would be nice if 10x would be compatible with this. I think if the Perforce* 10x settings were omitted from the P4 command when empty, then P4.exe would be able to figure them out on its own based on the working directory the command is ran from.

https://www.perforce.com/manuals/cmdref/Content/CmdRef/P4CONFIG.html

**Comment by slynch8** [comment]
10x does support P4CONFIG. Can you check your log an see if it shows
`[perforce] [p4config] Found P4CONFIG=`
Also, it will only check P4CONFIG if you have the `PerforceServerAddress` setting set

**Comment by daveratti** [comment]
Thank you, that does work. Having PerforceServerAddress set and then restarting 10x was the missing piece.
