### ISSUE TITLE
"Find File" should include "open in editor" files even if they aren't in the "solution"

### ISSUE THREAD

**Issue by forrestsmithfb** [slynch8/10x#1298]
I semi-regularly open files in-editor that are not actually part of my solution file. I frequently try to go back to these files by hitting my shortcut for "Find Files" and typing the file name. Unfortunately these "open in editor" files aren't in the "Find Files" list so I have to click around to find the tab.

An example of such a files would be log files, notes files, or headers that exist in some magical "include directories" search path that (perhaps incorrectly) not part of the solution.

**Comment by slynch8** [comment]
You can enter file paths in the Workspace Search if that helps. I guess I could add something similar to the Find File panel.

**Comment by forrestsmithfb** [comment]
Workspace Search helps, but Find File will still be helpful. It's often more natural to think "open file" rather than "search for content in file to open said file".

**Comment by slynch8** [comment]
I think I misunderstood your original bug, do you mean that already open files are not appearing in the Find File panel? If so that's a bug.

**Comment by slynch8** [comment]
fixed in (0.35.70)
