### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by forrestsmithfb** [slynch8/10x#1299]
It looks like 10x spins a thread. When I open task manager 10x has a "power usage" listed as "very high".

![image](https://user-images.githubusercontent.com/65318034/208174609-fbc2c475-344c-40e5-a3ca-df088b477e08.png)

This is on the latest version. This may not be enough for you to go from. I can't share this capture as it's on a work machine. I'll have to try and repro from my home machine. I'm not sure if this is an "always problem" or if it's something unique to my project / work environment.

Alternatively, if you can send me `10x.pdb` I can get you more info.

**Comment by slynch8** [comment]
That's concerning. Here's a release build with symbols.
https://e1.pcloud.link/publink/show?code=XZCadYZhcNTO8ny4Y5FA5OJiigcP7jzk8o7

Unzip and run the exe from the folder. You can create a mini-dump from the help menu.

**Comment by forrestsmithfb** [comment]
Ok now with symbols. 

![image](https://user-images.githubusercontent.com/65318034/208212886-532557b7-2cab-4812-9137-4468ae14c59d.png)

Looks like it's spending a lot of time in Windows' `NtlUserGetForegroundWindow`? This problem does not manifest itself right away. I currently have three copies of 10x open with three different projects. It was fine for awhile. I left my machine for half an hour. When I came back two of them are using most of a core. I'm on a 32-core threadripper.

All three windows were in the background. The problem _might_ go away if I focus the windows. But I'm not sure if that always works. I'll keep my eye on it.

Oh wait I think I just managed a partial repro! Put application in background. Lock the compute with Win + L. Unlock screen. Look at task manager, observe "very high" power usage and increased CPU time. Focus 10x windows and they're happy.

Curiously I am only currently observing the issue with 2 of my 3 open instances. So there's another piece to the puzzle.

Win 10 - 19044.2251
Nvidia RTX 3080 on 12/8 drivers

**Comment by slynch8** [comment]
Thanks for that. It looks like it's spinning trying to re-create the device (I'm using an old dx9 renderer). I've tried doing the same thing, but it isn't happening for me. Can you check your log file (%appdata%\10x\10x.log) and see if it shows these messages:
```
Attempting to reset lost device
Attempting to recreate lost device
Recreated lost device
```

**Comment by slynch8** [comment]
Also, it would be useful to be able to see the full callstack with line numbers. Could you force a crash dump from TaskManager and send me the callstack for the main thread?

**Comment by slynch8** [comment]
I managed to get it to happen by turning off `DisablePresentWhenIdle`. Can you check this setting, it should be `true`.

**Comment by slynch8** [comment]
I've fixed the spinning bug when `DisablePresentWhenIdle` is `false`. Let me know if you're still getting it.

**Comment by slynch8** [comment]
Ignore all that, I think I've found the real problem. I'll upload a new build tomorrow.

**Comment by slynch8** [comment]
I still wasn't able to get it to happen, but I've uploaded what I hope is a fix (0.35.71). Can you let me know if it fixes it.

**Comment by forrestsmithfb** [comment]
Used the new version all day yesterday and this morning and have not observed any issues. I think it's safe to call this issue fixed.

**Comment by slynch8** [comment]
that's good - closing
