### ISSUE TITLE
New Key Bindings Initialized Wrong

### ISSUE THREAD

**Issue by forrestsmithfb** [slynch8/10x#1302]
Most recent build included this in the change log:

> added `MoveToFileStart` and `MoveToFileEnd` commands (control+home/end keys)

Short cuts didn't work. I opened key bindings and they were set as:

`Control Home:MoveToFileStart`

This appears to be incorrect as it appears that you need to have a space after the colon. This issue was true for all the new commands.

**Comment by slynch8** [comment]
Thanks for letting me know. I think this is because it's trying to align to the previous setting value, which I'm guessing in your case is less than the name length? I thought I'd fixed this a few versions back, but obviously not. I'll upload  a fix.

**Comment by slynch8** [comment]
ok, thanks for confirming
