### ISSUE TITLE
`enum struct` is not parsed correctly

### ISSUE THREAD

**Issue by ghost** [slynch8/10x#1311]
`enum struct` is not parsed correctly. Highlighting and autocomplete do not work with it. Seems like it is interpreted as just `struct`.
It is expected to behave the same as `enum class` (which seems to work just fine).

```c++
enum QWE
{
    qwe,
};

enum struct ASD
{
    asd,
};

enum class ZXC
{
    zxc,
};

int main()
{
    QWE::qwe;
    ASD::asd;
    ZXC::zxc;
}
```

**Comment by slynch8** [comment]
done (0.35.77)
