### ISSUE TITLE
Highlighting not updated

### ISSUE THREAD

**Issue by StarlightDirective** [slynch8/10x#1313]
Highlighting gets stuck after updating an empty preprocessor macro.

Start with some dummy code:
```c++
struct ASD
{
    int asd;
};

int main()
{
    ASD x;
    x.asd;
}
```
then add before it:
```c++
#define ASD
```
[The highlighting now correctly identifies `ASD` as a macro.]
then change the `#define` to something else (the macro must expand to nothing when editing its name):
```c++
#define XXX
```
The highlighting of `ASD` is not updated, not even if the file is reopened. (It is fixed if the editor is restarted).

(Seems like a weird issue, but actually can happen while editing a `#define`.)

**Comment by slynch8** [comment]
fixed (0.35.77)
