### ISSUE TITLE
UI panel border bug

### ISSUE THREAD

**Issue by StarlightDirective** [slynch8/10x#1319]
`UI.Panels.Active Tab` has a sticky border on the left, right and bottom of the panel that does not get reset when switching the active tab.

Modifying the color scheme fixes it for a single redraw.

![Capture](https://user-images.githubusercontent.com/121533901/209803050-6bdc3f5d-1c7b-4662-a919-4e5c1b36900c.PNG)

Additionally, if no documents are open the border is not drawn at all. However if a document is closed the border will be drawn and retained (this time including the top border).

**Comment by slynch8** [comment]
how did I never notice that.

fixed (0.35.77)
