### ISSUE TITLE
Is*Open and Close* family functions

### ISSUE THREAD

**Issue by Sharlock93** [slynch8/10x#1324]
Currently we have access to a few functions around different panels being open, having more functions to detect these and being able to specifically close those panels would help in creating custom key bindings specifically in cases like Vim key bindings. One specific example would be IsFindFilePanelOpen and CloseFindFilePanel but making this more open ended might be a bit more beneficial in the future.

**Comment by slynch8** [comment]
done (0.35.77)

I've added these commands:
`CloseFindFilePanel`
`CloseCommandPanel`

and these to the python API:
`IsFindFilePanelOpen`
`IsCommandPanelOpen`

Let me know if you need more, they are very easy to add
