### ISSUE TITLE
Autocomplete with multiple cursors does not work

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#1344]
https://user-images.githubusercontent.com/40520199/210534589-7c0202cb-033a-4a46-8bbe-7db363ba5ab4.mp4

\
\---------------------
Version: 0.35.77

**Comment by Roman-Skabin** [comment]
The bug still exists.

https://user-images.githubusercontent.com/40520199/211873163-8a74ab84-8f02-4316-a758-eb7cf36ca048.mp4

\
\---------------------
Version: 0.35.78

**Comment by slynch8** [comment]
That looks like a bug with auto-fixing `.` to `->` ?

**Comment by Roman-Skabin** [comment]
Yes, but also it seems like autocomplete does not look into `VkAttachmentReference` structure. I have a path to `vulkan_core.h` in `AdditionalIncludePaths` (where this struct is defined) and I can go to definition of it pretty easy, so that means that 10x knows about this struct, but it does not want to suggest fields for autocompletion.

**Comment by slynch8** [comment]
think I've got it now
fixed (0.35.81)
