### ISSUE TITLE
extending SyntaxHighlighting for .asm support

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#1349]
Hi! More a question than a bug. I would like to use 10x & 10x workspace to edit .asm files and benefit from nice syntax coloring. So I copy/pasted cpp.10x_syntax into asm.10x_syntax and patched it a bit. But it doesn't really work, maybe it's expected. One annoying stuff is the "comment per line" I added this:

Extensions:					.asm
Language.Comment:
REGEX(;.*)

so anything after ";" should be a comment, but doesn't work. And I guess there is some hardcoded behavior for c++ when you type ";" on a line, the line is reformatted

Is there a way to disable all c++ specific re-shaping behavior when dealing with a non ".cpp" file?

thanks in advance!

**Comment by slynch8** [comment]
Hi, I think someone on the discord has already created an asm syntax highlighter. I'll see if they are happy to share it.
The ';' rule should work, there is no special C++ parsing going on, it's all just regex's. Is the ; at the start of the line, maybe you need .* before it?

**Comment by slynch8** [comment]
I just tried it and I see what you mean, `;.*` should work but it doesn't and `//` still seems to be recognised even though it's not in the rule set. It's as though it is hard coded. I'll take a look.

**Comment by slynch8** [comment]
I see what's happening, for some reason .asm is in the cpp.10x_syntax extension list. After removing it from there I tried the file below and `;.*` worked

asm.10x_syntax
```
# Format: <SettingName>: <Settingvalue>
# Setting name must appear at start of line and there must be whitespace after the colon.
# Multiple values can be comma separated or on subsequent lines.
#
# Valid settings for colour rules:
# REGEX()   A regular expression. Colours entire match or first group.
# WORD()	Matches a word (case sensitive)
# WORDI()   Matches a word (case insensitive)
# TEXT()	Match any text in the line (case sensitive)
# TEXTI()	Match any text in the line (case insensitive)

#----------------------------------------------
# settings

Extensions:					.asm

#----------------------------------------------
# colour rules

Language.Comment:
REGEX(;.*)
```

**Comment by arnaud-carre** [comment]
oh yeah it was in Settings.10x_settings! It works really nicely now, thanks!

**Comment by ggnkua** [comment]
Hey @arnaud-carre! I've made a 68k syntax highlight file for rmac here: http://rmac.is-slick.com/static/rmac.10x_syntax. You should be able to adapt it for other 68k assemblers easily, only the directives should need changing.
