### ISSUE TITLE
More UI border stuff

### ISSUE THREAD

**Issue by StarlightDirective** [slynch8/10x#1350]
Continuing #1319 

When 10x is launched or a window is docked (so presumably on full redraw):
![Launch](https://user-images.githubusercontent.com/121533901/211150741-8a63882c-35d7-463c-afa7-bb60adfda928.PNG)

When a subwindow is selected when it is not a tab (like `Workspace Tree` or `10x Output` here):
![NonTabFocus](https://user-images.githubusercontent.com/121533901/211150769-f553be76-cfa4-46ce-9955-449d1b79f885.PNG)

When moving a window from a tab to somewhere else (sticky!):
![1](https://user-images.githubusercontent.com/121533901/211150990-d7dd9312-f652-418a-b8dc-09dd49772500.PNG)
![2](https://user-images.githubusercontent.com/121533901/211150992-2f05c669-d1c2-4c0e-bf34-42b9d9dd5f97.PNG)

**Comment by slynch8** [comment]
fixed (0.35.80)
