### ISSUE TITLE
.cu files missing from solution

### ISSUE THREAD

**Issue by hstokholm** [slynch8/10x#1364]
I have an issue where a visual studio project with cuda files are not loaded correctly in 10x.
The headers (.h) are shown correctly in the workspace tree, but all .cu files are missing.
They are defined like this in the vcxproj:
```
<ItemGroup>
    <CudaCompile Include="path/to/test1.cu" />
    <CudaCompile Include="path/to/test2.cu" />
    ...

    <ClInclude Include="path/to/include1.h" />
    <ClInclude Include="path/to/include2.h" />
    ...
  </ItemGroup>
```

Is this a know limitation or is there something I can tweak?

**Comment by slynch8** [comment]
fixed (0.35.80)
