### ISSUE TITLE
Crash when using Alt-G (GotoSymbolDefinition) on a #include that's missing it's ending quote "

### ISSUE THREAD

**Issue by trigpointdave** [slynch8/10x#1372]
Happened in v0.35.79 and whatever version I was running just before I updated.

When using Alt-G to GotoSymbolDefinition on an include header file, if the header include is missing the closing quote ", 10x will crash.

In the below code example from an Unreal Engine 5 project, with the cursor on the #include "Kismet/KismetRenderingLibrary.h line that's missing the quote mark at the end, pressing Alt-G causes a 100% repro'able crash on my end.

**InkRemovalWidget.cpp**
```
#include "InkRemovalWidget.h"

#include "Engine/CanvasRenderTarget2D.h"
#include "Kismet/KismetMaterialLibrary.h"
#include "Kismet/KismetRenderingLibrary.h
```

Thanks,

Dave

**Comment by slynch8** [comment]
fixed (0.35.80)
