### ISSUE TITLE
$(SolutionDir) unspecified when using BuildCurrentFile

### ISSUE THREAD

**Issue by JeanGeffroy** [slynch8/10x#1374]
When using `BuildCurrentFile`, it appears that $(SolutionDir) is the same as $(ProjectDir), even if the solution lives in a different location. There's an argument to make that it kind of makes sense this way, since we're at this point outside of the context of a solution (compiling from project instead of solution), but it then doesn't match the VS behavior. This is a problem if you use $(SolutionDir) for a custom build command. It would be nice if the MSBuild command line could also set it with `/p:SolutionDir=.....`.

**Comment by slynch8** [comment]
is this for a 10x workspace or a VS solution?

**Comment by JeanGeffroy** [comment]
This is a VS Solution.

**Comment by slynch8** [comment]
I couldn't work out how to test it, but I've added `/p:SolutionDir=` to the build file command. Hope that works. Build (0.35.95)
