### ISSUE TITLE
Pressing ; pastes random line

### ISSUE THREAD

**Issue by castano** [slynch8/10x#1398]
Here you can see the problem in action:
![10x-bug-report-2023-01-30](https://user-images.githubusercontent.com/547891/215662104-3a0a2c20-af19-4d8c-90af-b1683803a6ac.gif)
I'm pressing ; followed by Ctrl+Z several times. The line being pasted is not in the clipboard, it seems to be coming from a different location in the same file. This only started occurring after a recent update. I've checked that the ; key is not associated to any command.

**Comment by castano** [comment]
The same problem occurs in other scenarios, for example, when closing braces all the lines between open brace and the cursor are replaced with seemingly random lines.

**Comment by slynch8** [comment]
This is very strange. Can you try doing a ReparseAll command and see if that fixes it.

**Comment by castano** [comment]
Sorry for the late response. Installing the update that was released after this bug report fixed the problem on my end, so I never had the chance to try the ReparseAll command. I've kept my eye open for this issue, but it has not occurred again, so I'm assuming it's been fixed. Thanks for the quick support!

**Comment by slynch8** [comment]
That's good. Hopefully it won't come back.
