### ISSUE TITLE
Add a small app icon (e.g. for the thin taskbar)

### ISSUE THREAD

**Issue by ands** [slynch8/10x#1411]
Hey, I end up looking for my 10x instance on the taskbar a lot.
I am using a small/thin Windows task bar and it seems this causes 10x to only be displayed with a default blank page icon, which is hard to recognize as a 10x instance:
![image](https://user-images.githubusercontent.com/151513/217091489-20919a86-f043-4a30-814a-13f146f548a0.png)

My guess is that it currently just is missing the smaller versions of the app icons within the executable resource table, but I haven't checked.

Cheers!

**Comment by slynch8** [comment]
weird. The icon contains a small 16x16 image. Can you tell which size it's using? Also try uninstalling and re-installing.

![image](https://user-images.githubusercontent.com/7141856/217092641-58e9cb47-98d1-49d2-8a1e-29389e6eb3c4.png)

**Comment by slynch8** [comment]
this is the ico file
[10XIcon.zip](https://github.com/slynch8/10x/files/10669368/10XIcon.zip)

**Comment by ands** [comment]
Thanks for the quick response! :)
I believe it is supposed to display the 24x24px version.
Looking at that version of the icon it seems to be a bit garbled at the end/bottom.
Maybe that has something to do with it?
I can open the file you posted fine in VS though.
I'll try reinstalling next.

**Comment by ands** [comment]
Reinstalling did not help. I just noticed though that 10x Notepad actually works fine:
![image](https://user-images.githubusercontent.com/151513/217097196-9eee119b-0830-4114-827d-5a3efdbe1b0f.png)

**Comment by ands** [comment]
Oh wow. Unpinning and repinning to the task bar did the trick. 🤦 
Thanks for your help! 😄

**Comment by slynch8** [comment]
I think this can happen after updating. Let me know if it happens again.

**Comment by ands** [comment]
Will do!
Cheers! :)
