### ISSUE TITLE
MSBuild processes are not killed when build has failed

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#1414]
If you look at the task manager, you'll see, that a lot of (all?) msbuild processes are still alive after unsuccessful build. When you try to build it once again the number of processes are being increased.
![image](https://user-images.githubusercontent.com/40520199/217293036-29232afc-6d18-4c04-ac94-2796ab4045d1.png)

\
\-------------------
Version: 0.35.88

**Comment by Roman-Skabin** [comment]
P.S. Haven't checked with successful builds.

**Comment by Roman-Skabin** [comment]
I killed some of them, but anyway, under the 10x process you can see them as well.
![image](https://user-images.githubusercontent.com/40520199/217293900-8298b155-f24a-4309-8446-57f4b1dc5f98.png)

But it's better to check it in "details" tab since they are remain being running even after closing 10x.

**Comment by slynch8** [comment]
How many are there? I think it's standard for msbuild to create an exe for each CPU and keep them around if you've building multi-threaded.

**Comment by Roman-Skabin** [comment]
> How many are there?

15, 20.

> I think it's standard for msbuild to create an exe for each CPU and keep them around if you're building multi-threaded

That's true, but when build ends I think they should be closed, right?

**Comment by slynch8** [comment]
no, I think they are kept around. I'm pretty sure I've also seen this with VS

**Comment by Roman-Skabin** [comment]
If msbuild itself does not clear its child processes then so shame on microsoft :)
