### ISSUE TITLE
GotoDefinition not working on pre-delcared struct

### ISSUE THREAD

**Issue by TurtleSimos** [slynch8/10x#1415]
Parser is failing to find the definition for FChartPacker.

Thankfully, easy repro. This is based on Unreal Engine 4.27.2 source.

File:
\Engine\Source\Runtime\MeshUtilitiesCommon\Private\LayoutUV.cpp

FInd FLayoutUV::FindBestPacking in the source. First line in the function is:
	FChartPacker Packer(MeshView, LayoutVersion, InTextureResolution);
	
FChartPacker is not understood.
It is pre-declared in the corresponding LayoutUV.h, but all the actual definition and implementation is in the same cpp file.

**Comment by slynch8** [comment]
I've added a simple repro bug #1424, closing this one
