### ISSUE TITLE
Visual glitches and flickers when editing code or sliding mouse up and down the lines.

### ISSUE THREAD

**Issue by JimmyDeemo** [slynch8/10x#1418]
![10x_screen_glitches](https://user-images.githubusercontent.com/4234718/217495411-8148f8cb-fe5c-4a6b-96da-519b08bf7024.gif)

You can see in the .gif that the preview in the top right flickers and the text also glitches whilst performing the action I am doing in the .gif. This is intermittent but happens all the time whilst I am coding, sometimes the glitch is the entire window. They are only for a fraction of a second but seem to occur when an actions causes an area of the screen to update, such as bringing up the auto complete dialogue.

Here is my device spec;

Device name	Dell_XPS_Laptop
Processor	11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz   2.50 GHz
Installed RAM	32.0 GB (31.7 GB usable)
System type	64-bit operating system, x64-based processor
Intel(R) UHD Graphics
NVIDIA GeForce RTX 3050 Ti

I am using a 2nd monitor connected via HDMI through a small USB-C adaptor that came with the laptop. Here are the monitor specs;

BenQ EL2870U
3840 x 2160, 60 Hz
8-bit depth
RGB, SDR

10x Version is 0.35.89.

**Comment by slynch8** [comment]
I've not seen this before. My initial thought is a driver bug.

Can you try setting `DisablePresentWhenIdle` to true
Try setting `VSync` to false
Try resetting everything back to defaults (close 10x and rename the %appdata%\10x folder)

Does it happen using the laptop screen or just on the second monitor?

**Comment by JimmyDeemo** [comment]
`DisablePresentWhenIdle` was already set to true.

Turning off `VSync` made the problem much more common, almost after every key press. I notices that the glitches affect more of the screen when the auto complete menu is up.

Setting `DisablePresentWhenIdle: false` and `VSync: true` caused an increase in the glitches but not as much as turninf off VSync altogether.

I reset everything back to defaults and observed the same thing.

Problem seems to be the same on either the laptop screen or second monitor. I would like to try and force 10x to run with integrated/dedicated graphics to see if this makes a difference but I'm not confident in those settings. Do you know of a way to do that and be sure the right graphics device is being used? (I had a VSync issue with a game recently... so maybe this *is* just a hardware/driver issue)

**Comment by slynch8** [comment]
Sorry, I'm not sure how to switch to integrated graphics, but if you can find out how it's definitely worth a try.

I do suspect a driver bug. The renderer is using dx9 so it wouldn't surprise me. I will be moving over to dx11 soon so that might fix the issue.

**Comment by JimmyDeemo** [comment]
I can confirm that if I use the NVIDIA Control Panel, go to 'Manage 3D settings' --> 'Program Settings' tab, then add 10x under '1.' and select 'Integrated graphics' for '2.' I no longer get any glitches or artifacts.

Ofc this means I won't get any hardware acceleration for the program itself but this is much less distracting! Is it worth keeping this ticket open for testing once DX11 is a thing?

**Comment by slynch8** [comment]
ok, that's interesting. Yes, let's leave this open until DX11 is done.

**Comment by slynch8** [comment]
dx11 renderer is done (0.36.2), can you check if it still happens

**Comment by JimmyDeemo** [comment]
The simple test I did showed that the glitching I had is gone, even after removing the entry from the NVIDA Control Panel. I think we can close this issue now and I'll reopen it if I see the problem again with extended testing.

Thanks for the notification and best of luck with 10x moving forward.
