### ISSUE TITLE
Bug using Find with highlighted text

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#1426]
I've seen this one quite a bit over the last few months.
I highlight some text, press Ctrl+F.
The Find window textbox shows the highlighted text correctly. However when I press F3 or the next arrow, it searches for something else (the last thing I used Find for)
Here you can see I'm trying to find "tlsf_malloc", but it repeatedly executes a find for the last used term "Fast". If I manually edit the search term in the text box, it works again

![FindBug2](https://user-images.githubusercontent.com/1583441/217651487-92861014-351a-4cac-8ddd-31a161c450ba.gif)

**Comment by slynch8** [comment]
fixed (0.35.92)
