### ISSUE TITLE
Crash on open: site module failure to load

### ISSUE THREAD

**Issue by rdunnington** [slynch8/10x#1444]
I wanted to try out the 10x trial version but running the exe did nothing. I attempted to run via VS to catch a crash on startup, but weirdly 10x started up just fine and I was able to use it. Running it standalone still resulted in what seemed like either an early exit or crash. Finally I used Windbg and caught the crash:

```
0:000> g
ModLoad: 00007ffb`ad830000 00007ffb`ad860000   C:\Windows\System32\IMM32.DLL
ModLoad: 00007ffb`94b30000 00007ffb`94bda000   C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
ModLoad: 00007ffb`ad880000 00007ffb`ad8d5000   C:\Windows\System32\SHLWAPI.dll
ModLoad: 00007ffb`ad780000 00007ffb`ad82d000   C:\Windows\System32\SHCORE.dll
<snip more module loads>
Fatal Python error: Failed to import the site module
(25c28.287c0): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
```

My project has some custom python sitecustomize stuff, so I'm guessing there is some incompatibility here. I'm not too familiar with it so I'm not sure how to disable it, but ideally 10x would at least display any errors related to this if it can't gracefully handle them.

**Comment by slynch8** [comment]
Thanks for tracking this down, I've not seen anything like this before. If you can find out what python setup causes this I'd be interested to try and repro. It looks like it's crashing initialising python but I'm not sure why my crash handling isn't catching it.

**Comment by rdunnington** [comment]
I've attached a dump if you want to take a look at the stack. I'll try to see what's going on.
[10x_python_crash.zip](https://github.com/slynch8/10x/files/10770848/10x_python_crash.zip)

**Comment by rdunnington** [comment]
I narrowed it down to these lines in our sitecustomize.py:

```
import art.lib.perforce as libP4
import art.lib.pip as libPip
```

`art` is a directory in the sitecustomize.py. I'm guessing the python instance inside 10x can't access them since it's in a totally different directory and it fails the initialization. Or maybe there is some incompatibility with the python in our libs with the version embedded in 10x.

**Comment by slynch8** [comment]
ok, I've looked it up. I never knew about site configuration. I've got it to crash now, investigating...

**Comment by slynch8** [comment]
here's a fix
https://e1.pcloud.link/publink/show?code=XZsJObZ8ahCMog7RTFvRed2YxxGSBBQ9iQX

**Comment by rdunnington** [comment]
Works perfectly! Thanks a ton, and I have to say I am incredibly impressed with the quick turnaround. Cheers :)

**Comment by slynch8** [comment]
No problem, glad it worked. I'll upload a new build in a couple of days
