### ISSUE TITLE
stop FindFile panel losing results when there is a space at the end of the search string

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#1455]

**Comment by charles-epic** [comment]
Or even a '.'

**Comment by slynch8** [comment]
'.' doesn't seem to be a problem for me, can you give an example?

**Comment by charles-epic** [comment]
Indeed, not sure if this was recently fixed, or if it was just the mixture space + . I can't reproduce that issue. It seems that the source of the issue is only the 'space'. Thanks for checking :)

**Comment by slynch8** [comment]
fixed (1.0.46)
