### ISSUE TITLE
The Beta product has expired: Cannot start 10x or 10x_notepad since 0.36

### ISSUE THREAD

**Issue by JeanGeffroy** [slynch8/10x#1464]
Since updating to 0.36, I'm unable to start 10x or 10x_notepad. I just get an error on startup asking me to download the latest version, but I'm already up to date (got the latest installer from the website just to be sure). Tried a repair and clean install, no luck either way.

**Comment by Muzza** [comment]
Same here

**Comment by ands** [comment]
Me too. Wether I've registered does not seem to make a difference.

**Comment by slynch8** [comment]
Really sorry about this, I'm uploading a new build...

**Comment by slynch8** [comment]
A new build has been uploaded. You'll have to download and install from the website
https://10xeditor.com/

**Comment by JeanGeffroy** [comment]
All good now, thanks!
