### ISSUE TITLE
Move between buttons in message box

### ISSUE THREAD

**Issue by benanil** [slynch8/10x#1486]
![image](https://user-images.githubusercontent.com/48527900/222705178-398f8974-0a60-4d48-9f07-d5044adcd633.png)
Moving in between them with arrow keys would be good.

**Comment by benanil** [comment]
and enter for select

**Comment by slynch8** [comment]
Arrow keys and enter work for me. Can you try this on a clean install - close 10x and rename your %appdata%\10x folder

**Comment by benanil** [comment]
still same, to produce change code a comment line maybe, dont save and hit alt, move to recent workspaces with arrow keys
and chose some other project then you are not going to able to move with arrow keys.

but if you click and drag one of the buttons we are able to move in between buttons

https://streamable.com/7qjmix

**Comment by slynch8** [comment]
fixed (0.36.11)
