### ISSUE TITLE
duplicate color schemes

### ISSUE THREAD

**Issue by d7samurai** [slynch8/10x#1500]
started 10x editor, was told it was a beta and that i had to download new version. uninstalled beta. downloaded and installed latest from website. now there's two of every color scheme. 

![Untitled](https://user-images.githubusercontent.com/5618797/223456669-48e2b193-0a11-4e5b-9808-a30fd89e70a7.jpg)

**Comment by d7samurai** [comment]
![image](https://user-images.githubusercontent.com/5618797/223494098-d3e25113-6f17-46a3-a217-7a8ce1caffe6.png)

**Comment by slynch8** [comment]
can you try closing 10x and deleting this file
`%appdata%\10x\cache\colour_scheme_manager.10x_cache`

**Comment by d7samurai** [comment]
that solved it. thanks!
