### ISSUE TITLE
Auto complete not working with cast

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#1502]
See example

```cpp
struct A
{
	static A* Get( void );
	int y;
};

struct B : public A
{
	void func();
	int x;
};

void MyFunc( A* a )
{
	B* b = (B*)a;
	int bx = b->x;	// auto complete works

	int ax = ((B*)A::Get())->x;	// auto complete empty
}
```

**Comment by Muzza** [comment]
On browsing my open issues I think this is the same as #1402

**Comment by Muzza** [comment]
Would you consider looking at this one (and #1402) soon-ish?
It stops quite a lot of code from being parsed correctly by 10x.

**Comment by Muzza** [comment]
Can I bump this again please? 
It doesn't seem complicated, but it stops autocomplete working on a lot of my code.

**Comment by slynch8** [comment]
Sure, I'll take a look at this next.

**Comment by slynch8** [comment]
I've added support for casting, early access build (1.0.209).

It only supports simple casts at the moment, but the example above now works. Hope this helps.

**Comment by slynch8** [comment]
done (1.0.218)
