### ISSUE TITLE
When doing a search (Control F), repressing Control F again should select the search text to ease replacing the search text

### ISSUE THREAD

**Issue by kiwaiii** [slynch8/10x#1518]
When doing a search within a file (Control F), it would be good to match VS behavior.

Details:
* Control+F it will pop the search entry. 
* Type the text you want, 
* Hit F3/Shift F3 to go from line to line. 
* Then if you want to change completely your search, you currently have to select the current text in the search box, and erase/replace it. In VS, on new  Control+F press, VS selects the current search, so that when you type your new search, it directly replaces the current text

**Comment by slynch8** [comment]
fixed (0.36.11)
