### ISSUE TITLE
parsing binary numbers with `

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#1522]
![formatting_issue_10x](https://user-images.githubusercontent.com/7141856/224530956-8beeed50-11d3-4527-b1d1-4995003e9453.gif)

**Comment by 989yty** [comment]
Hey, someone put like AI on my xbox and phone so there is recordings and shit of me implanted onto the news and into movies. Can someone help me

**Comment by slynch8** [comment]
fixed
