### ISSUE TITLE
Double clicking a file path in the build results doesn't open file

### ISSUE THREAD

**Issue by MarcAudy** [slynch8/10x#1525]
During our build process a pre-build step can output errors of the form G:/Builds/<path1>/<path2>/<file>.verse(6,9, 6,45): Verse compiler error ...

In MSVC if I double click this line it will take me to the file at line 6, however in 10x it treats it just as regular text and selects the word I double-clicked.

The files do exist in the workspace and can be opened using alt-shift-O. It is unclear to me whether it is the back slashes in the path or the unknown file type that is preventing 10x from recognizing it as a path and trying to navigate to the error, but it would be great if it could do so.

**Comment by slynch8** [comment]
fixed (0.36.15)
