### ISSUE TITLE
Down-arrow is broken in "Find Symbol"

### ISSUE THREAD

**Issue by forrestthewoods** [slynch8/10x#1528]
When doing "Find in Files" I can use up and down arrows to go through entries. In "Find Symbol" my "up arrow" works but "down arrow" doesn't. Very strange!

**Comment by forrestthewoods** [comment]
Upon further review this isn't always true. I somehow entered a buggy state where "Find Symbol" was not showing the "preview" at the bottom. That was broken, and down-arrow was broken. I'm not sure how I got into this bad state. Rebooting the editor fixed it.

**Comment by slynch8** [comment]
ok, I'll close this for now. Reopen if you get it again.
