### ISSUE TITLE
Should be able to run builds with new and unsaved files

### ISSUE THREAD

**Issue by forrestthewoods** [slynch8/10x#1531]
My workflow frequently involves text files. For example I might be debugging something and have 5 different new text files with copy/paste log output from different runs. 10x won't let me make a build if I have an unsaved file. If that file is in the project then sure I guess that makes sense. But I like to spam Ctrl-N to make new scratch files I intend to throw away. I should be able to make a build without being forced to save those scratch files.

**Comment by slynch8** [comment]
done (1.0.11)
