### ISSUE TITLE
Auto synchronize folder

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#1547]
Not sure if this a bug or not, but when I create a new file from the windows explorer in a folder that is synchronized, the workspace is not refreshed automatically, I have to manually click on 'Sync Folder' for it to work (or close and reopen 10x).

My project file is a .10x workspace, the root is a virtual folder ("Sync folder" is not ticked in the properties), and contains a few physical folders that are synced ("Sync folder" is ticked for all of those).

**Comment by bousquetm** [comment]
Hey, has there been any development on this by any chance? It's annoying to have to refresh the workspace every time I add a file or change a filename.

**Comment by slynch8** [comment]
I'll take a look soon

**Comment by bousquetm** [comment]
Thank you so much!
