### ISSUE TITLE
Running perforce commands from the current file's directory

### ISSUE THREAD

**Issue by Sharlock93** [slynch8/10x#1561]
One project at work has files from multiple workspaces which means setting the Client/Workspace setting to something fixed will only work in one workspace. I know 10x has support for P4CONFIG but its one p4config only.

When you do a p4 command in a folder, p4 will traverse the folders up until it finds a p4config file, that means you can have one p4config per workspace root folder and running p4 commands from the directory of the files means p4 can find the appropriate p4config. I have currently solved this with this:

```python
#------------------------------------------------------------------------
import N10X

import subprocess 
import os


def func(file):
    true_file_name = os.path.realpath(file)
    cur_dir = os.getcwd()
    file_base_dir = os.path.dirname(true_file_name)
    file_name = os.path.basename(true_file_name)

    os.chdir(file_base_dir)
    proc = subprocess.run(["p4", "edit", file_name], capture_output = True, shell = False)
    os.chdir(cur_dir)

N10X.Editor.AddPreFileSaveFunction(func)
```

while this works fine, it only works for checkout and not revert and other such commands.

**Comment by slynch8** [comment]
It should work as you describe. If you set P4CONFIG to a file name, it will look in the workspace folder and keep going up folders until it finds the file.

**Comment by Sharlock93** [comment]
> It should work as you describe. If you set P4CONFIG to a file name, it will look in the workspace folder and keep going up folders until it finds the file.

Its unfortunately not working like that, here is my setup:

```
C (root_drive)
|- FolderA (Perforce Workspace A)
|---- p4config <= (has P4CLIENT=Perforce Workspace A)
|
|- FolderB (Perforce Workspace B)
|---- p4config <= (has P4CLIENT=Perforce Workspace B)
|---- Solution.sln <= This has files from FolderA & FolderB
```
In this setup, I can checkout files in FolderB but fails for FolderA because the p4 command happens under the FolderB directory tree.

**Comment by Sharlock93** [comment]
Here is a better version of the script above, this assumes you haven't set any Perforce settings in 10x and have p4config file in one of the parents of the current opened file.
This checks only if the file is readonly then runs the command, also makes sure there is no 
pop-up window when running the `p4 edit` command.
I personally would consider the issue to be closable as I have a nice workaround but having this feature be built-in would be nice.

```python
#------------------------------------------------------------------------
import N10X

import subprocess 

import os
import stat


def func(file): 

    true_file_name = os.path.realpath(file)
    file_stat = os.stat(true_file_name)

    if (file_stat.st_file_attributes & stat.FILE_ATTRIBUTE_READONLY) == 0: return

    cur_dir = os.getcwd()
    file_base_dir = os.path.dirname(true_file_name)
    file_name = os.path.basename(true_file_name)

    os.chdir(file_base_dir)
    proc = subprocess.run(["p4", "edit", file_name],  capture_output = True, shell = False, creationflags = 0x00000008)
    os.chdir(cur_dir)
    output = proc.stdout.decode("utf-8")
    print(output )

N10X.Editor.AddPreFileSaveFunction(func)

```

**Comment by slynch8** [comment]
I recently made a change where it checks the p4config file for each file operations.
