### ISSUE TITLE
[feature Request] - *.10x_syntax files to support extension-less file names or wildcards

### ISSUE THREAD

**Issue by RetroZelda** [slynch8/10x#1563]
an example is when using waf, which uses python, relies on a `wscript` file.  This file is python syntax, so I would like the ability to be able to have the parser handle it like any other python file.  

Adding "wscript" to the "Extensions:" setting in `python.10x_syntax` currently doesnt accomplish this.

info on waf:
- https://waf.io/apidocs/tutorial.html

Not to be confused with Microsoft's wscript:
-  https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/wscript

**Comment by slynch8** [comment]
Done (1.0.117)
