### ISSUE TITLE
Cannoy copy search results from the search box

### ISSUE THREAD

**Issue by TurtleSimos** [slynch8/10x#1566]
You can highlight the results in the search box, but not copy them to the clipboard.

**Comment by MarcAudy** [comment]
Further to this, it would be very useful to have a way to export/copy all search results to the clipboard similar to Entrian (default bound to ctrl-alt-c and also available as a right click option which has formatting options, though that feels over kill)

![image](https://user-images.githubusercontent.com/6844694/227042227-98c61d82-cd59-4c02-bce4-8d303682b9ed.png)
![image](https://user-images.githubusercontent.com/6844694/227042306-6a9f591a-0bf4-41b0-95f3-267954be3f3c.png)

**Comment by slynch8** [comment]
done (1.0.45)
Control+C now copies the selected line, and Control+Alt+C copies all results. And I added a right click context menu.
