### ISSUE TITLE
Crash when merging a split floating window into the main window

### ISSUE THREAD

**Issue by RetroZelda** [slynch8/10x#1567]
I had a floating window with 2 panels: left side was a cpp and the right side was a header.

the main window is split, left side with a bunch of cpps, and right side with a bunch of headers.

I went to merge the floating window back in with the main window by dragging it to the left panel.  The process crashed upon releasing the mouse.  I have uploaded crash dump named `10x_crash_2023_3_21_20_50_44.dmp`

Probably not a helpful screenshot as I had to blur everything, but it shows the general state of what I was doing
![image](https://user-images.githubusercontent.com/4962388/226774592-1dd117f7-6a0c-4d01-a6b9-c6ee35f91f0a.png)

**Comment by slynch8** [comment]
fixed (0.36.17)
