### ISSUE TITLE
10x_notepad.exe cannot be used as P4EDITOR

### ISSUE THREAD

**Issue by MarcAudy** [slynch8/10x#1577]
When trying to set 10x_notepad.exe as the P4EDITOR the spec will open in the editor, however, 10x is not doing whatever perforce needs to be aware the file is still being edited and it immediately responds with an error. For example

-> p4 change
Error in change specification.
Error detected at line 32.
Change description missing.  You must enter one.
Hit return to continue...

According to https://www.perforce.com/manuals/cmdref/Content/CmdRef/P4EDITOR.html notepad++ requires additional command line parameters to have it hold the file? process? open in a way that the p4 command is aware of and does not try to read the results until the file/process is closed (in notepad++ it is the entire process).

**Comment by slynch8** [comment]
Fixed (1.0.4). I've added the `-NewInstance` command line arg
https://10xeditor.com/10xDocumentation/Perforce.htm
