### ISSUE TITLE
highlight find matches in map scroll bar

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#158]

**Comment by JeanGeffroy** [comment]
This is probably the feature that people are currently the most vocal about in our team. One of the main reason to still use VS+VAX at least occasionally :).

**Comment by aztekBP** [comment]
Also, and more important for me at least, is the ability to highlight the selected keyword in the map scrollbar similar to text markers in RockMargin.
![image](https://user-images.githubusercontent.com/99036728/169488279-5074e156-b1be-4d02-a609-ba8dadd4c2e0.png)

**Comment by slynch8** [comment]
This is done (0.33.12)

Highlighting the find text is on by default, but you'll need to turn on the highlight currently selected word. See the HighlightFindTextInScrollBar and HighlightSelectedWordInScrollBar  settings,
