### ISSUE TITLE
Console fails to show non-ASCII/ANSI characters when MSVC outputs non-English messages

### ISSUE THREAD

**Issue by alexGuntha** [slynch8/10x#1600]
Hi,

reproduced on10x version 1.0.8

My MSVC is set to output French (French Language Pack in the installer I assume), and a number of characters fail to be displayed correctly on the console:
![image](https://user-images.githubusercontent.com/39413331/230022631-39882a1c-4cce-4ce6-a8d9-78f1fe978416.png)

I can type the same characters with no visual issue in a text tab.

For reference, the expected result, here in Visual Studio 2022:
![image](https://user-images.githubusercontent.com/39413331/230022838-b9455a39-f5b7-4e68-ab8a-5bc71ef381a8.png)

**Comment by slynch8** [comment]
fixed (1.0.35)
