### ISSUE TITLE
confusing error reporting after a build

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#1602]
Hi! 
We're using a custom build system for large project. Everything is working fine when building from 10x editor except at the end, 10x often report positive number of errors despite the build is succeed, like: 

`===== Success : 10 errors, 301 warnings =====`

When inspecting the build log, my build is ok but I have 10 references to "error;" strings in the log, and 10x "think" it's real errors but they are not:

`\External\theora\lib\dec\idct.c(236): warning C4554: '>>': check operator precedence for possible error; use parentheses to clarify precedence`

So even if the build is ok, seeing "10 errors" at the end is quite confusing.

**Comment by slynch8** [comment]
I think I may have fixed this, is it still an issue?

**Comment by arnaudcarre** [comment]
I confirm the issue is still here in 1.0.81

**Comment by slynch8** [comment]
ok, I'll look at this next
