### ISSUE TITLE
Alt-shift click should block select

### ISSUE THREAD

**Issue by MarcAudy** [slynch8/10x#1616]
While you can alt-drag to make a block selection in 10x, other tools such as textpad, notepad++, and VSCode/VisualStudio allow alt-shift clicking to block select from the current cursor location to clicked location.

If you have multi-cursors in VSCode the block select appears to use the original/first cursor as the start point for the new block selection.

**Comment by ramenguy99** [comment]
Completely agree, personally I really like the notepad++ block select where hold alt and drag starts a new block, and alt+shift creates a block from current cursor position to mouse position

**Comment by slynch8** [comment]
done (1.0.11)
