### ISSUE TITLE
auto save when building regression

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#1621]
Hi!

I think there is a regression in very recent 1.0.11. I'm using a 10x workspace and when I "build active workspace", the modified files in editor aren't automatically saved right before launching the build command. ( they were properly saved in the previous version)

**Comment by slynch8** [comment]
Are these files in the workspace? I changed it to only save workspace files.

**Comment by slynch8** [comment]
ok, I've changed it in (1.0.12) so that it will also save non-workspace files, except for untitled files (which was the bug I was really trying to fix)
