### ISSUE TITLE
vim search behavior

### ISSUE THREAD

**Issue by Phildo** [slynch8/10x#1633]
when in vim mode (though I suppose this could be an option independent of vim mode, as `CloseFindPanelOnEnter` already is), search should:

1. on enter, _just_ close. it currently advances one additional search index, _then_ closes. if I initiate a search, type my search, and hit enter, it should be highlighting the first instance of the search after where I initiated the search, not the second.

2. place the cursor on the _first_ character of the found search term, not one past the last

**Comment by slynch8** [comment]
done (1.0.37)
