### ISSUE TITLE
UE5: #defines do not always match selected configuration (generated solution)

### ISSUE THREAD

**Issue by velaris1** [slynch8/10x#1643]
Switching configurations sometimes does not seem to re-parse correctly the defines. 

Taking Engine\Source\Runtime\Core\Private\ProfilingDebugging\CsvProfiler.cpp as an example, switching between Shipping and Development Client configurations doesn't refresh the CSV_PROFILER #define. 

For example, going from Shipping -> Development (or Dev. Client), anything declared within a CSV_PROFILER #define remains grayed out (after parsing), even though it should be defined under Development.

It seems to work as expected when switching between Shipping <--> Development Editor

**Comment by slynch8** [comment]
fixed (1.0.22)
