### ISSUE TITLE
Hang when entering a regular expression

### ISSUE THREAD

**Issue by Sneftel** [slynch8/10x#1647]
Entering a regular expression starting with "^" (which is generally where one would put it, I guess) causes 10x to hang, apparently indefinitely. This is version 1.0.14.

Steps:

1. Open a file
2. Activate the "find" tool (Ctrl-H). Ensure the pattern textbox is empty.
3. Enable regular expression searching (the "Reg" button).
4. Enter "^" into the pattern textbox.

Actual result: 10x hangs.
Expected result: Some essentially unhelpful highlighting.

**Comment by slynch8** [comment]
Is this still an issue? I think I might have fixed it a few builds back.

**Comment by slynch8** [comment]
can't repro, closing
