### ISSUE TITLE
Multiple Cursors in Workspace Settings

### ISSUE THREAD

**Issue by 3nigm4** [slynch8/10x#1653]
![grafik](https://user-images.githubusercontent.com/1385261/233789623-44693223-59d7-4457-b05b-14991eacf6f9.png)

Bug or feature? I can not move them together, they disappear once I click in one of the input fields, but only the cursor in which input field I just clicked.

This happens in a saved 10x workspace, with remedybg python script but no further modifications.

10x Version: 1.0.14

**Comment by slynch8** [comment]
this was fixed a few version back
