### ISSUE TITLE
Save Workspace dialog hang

### ISSUE THREAD

**Issue by onelivesleft** [slynch8/10x#1655]
I use Open Folder to open a Unity project; I have *not* added `.cs` to the parse files extension list.  It takes roughly 12 seconds to finish opening the workspace.  I then select "Save Workspace", and the application hangs.

![image](https://user-images.githubusercontent.com/17881109/234282931-fd49e349-fa9c-4157-b92d-bd6bb46f38ed.png)

**Comment by slynch8** [comment]
fixed (1.0.15)

**Comment by onelivesleft** [comment]
Have successfully opened the folder then saved a .10x workspace.  After closing-and-reopening 10x, I can open that workspace, but then when I either try to load it again, or save it, it hangs (when it hangs on save I think it's during the reload step).

However! I have since excluded the `Library` folder (which is autogenerated by Unity and a massive pile of data that the IDE should never look in), and things seem to be going OK.  So, probably not good that 10x is appearing to hang in these conditions, but they are extreme.
