### ISSUE TITLE
10x crashes for some fonts. Refuses to start up afterwards.

### ISSUE THREAD

**Issue by aelthalyste** [slynch8/10x#1662]
I have tried to change the editor font to `Inconsolata Bold` and it immediately crashed, before that I was using `Inconsolata SemiBold`. Both fonts exist in the system and I have been using them interchangeably for years in different editors. 
For the quickfix I'll be editing 10x settings via the notepad.

[10x_crash_2023_4_27_13_26_48.dmp.zip](https://github.com/slynch8/10x/files/11342393/10x_crash_2023_4_27_13_26_48.dmp.zip)

**Comment by slynch8** [comment]
Hi, where can I find the SemiBold font?

**Comment by slynch8** [comment]
ignore that, I've found it. It's not crashing for me. Can you try closing 10x and deleting the font cache file %appdata%\10x\cache\fonts.cache

**Comment by slynch8** [comment]
ok, I did try bold as well and that was fine. I guess something must have corrupted the font cache. Let me know if it happens again.
