### ISSUE TITLE
10x crashes when scrolling with the left control key pressed on.

### ISSUE THREAD

**Issue by aelthalyste** [slynch8/10x#1663]
I have reproduced the crash 5-6 times.
`left control` + `mouse scroll` crashes 10x. You need to try to scroll few times to get a crash, single roll on might not work but it always crashes after a second or so.

[10x_crash_2023_4_27_13_35_48.dmp.zip](https://github.com/slynch8/10x/files/11342474/10x_crash_2023_4_27_13_35_48.dmp.zip)

**Comment by slynch8** [comment]
Unfortunately the crash dumps you are sending me are corrupt. Could you send the original .dmp.gzip file.

I'm guessing this is related to the other font crash you are getting.

**Comment by aelthalyste** [comment]
Yeah after cleaning up the font cache it doesn't crash anymore. 
You can't upload files with .gzip extension so manually changed extension to .zip. For some reason I assumed you were using 7z which would open it anyways. It was a bad assumption sorry. 
I dont know how to link issues but you can link the other issue, solution is same.
