### ISSUE TITLE
Feature: option to strip whitespace from ends of lines on save

### ISSUE THREAD

**Issue by onelivesleft** [slynch8/10x#1674]
A handy feature to have is to remove all whitespace characters from line ends when the file is saved.  i.e. remove: (\s)+\n

**Comment by themole** [comment]
I use following python script to do that:
(Note that there already is a function in one of the predefined scripts that does the trimming)

```
import N10X
from Utils import TrimLines

def TrimLinesOnSave(filename):
	N10X.Editor.FocusFile(filename)
	TrimLines()

N10X.Editor.AddPreFileSaveFunction(TrimLinesOnSave)
```

**Comment by onelivesleft** [comment]
Thanks!  I hadn't spotted there were hooks.
