### ISSUE TITLE
Feature: Add support for multicursor to python API

### ISSUE THREAD

**Issue by onelivesleft** [slynch8/10x#1684]
i.e. `Editor.GetCursorCount()` & add a cursor index parameter to most Cursor functions.

**Comment by onelivesleft** [comment]
Alternatively, put the current Cursor methods inside a Cursor class, and expose a lit of all Cursors.

**Comment by onelivesleft** [comment]
N.B. The reason I was asking for this is, because of the way word jump works, it's not currently possible to do this in 10x:

https://www.youtube.com/watch?v=ZmJ0JOLk-Eg

I was about to ask for a setting to control the word jump, but then figured I'd write my own MoveCursorWordRight et al... to then discover this limitation.

**Comment by slynch8** [comment]
done (1.0.218)
