### ISSUE TITLE
Workspace tree collapses when moving a file

### ISSUE THREAD

**Issue by vulcan-dev** [slynch8/10x#1693]
https://github.com/slynch8/10x/assets/31520916/0dbff58c-da59-4bbc-801c-f57460706271

When moving a file in a 10x workspace, the file tree will collapse.

**Comment by vulcan-dev** [comment]
https://github.com/slynch8/10x/assets/31520916/fac2b0de-b109-40ad-8d8e-754ff90c2cb3

I just remembered this issue as well.
If you delete a file (via the context menu), it will do the same behavior as the issue.

**Comment by slynch8** [comment]
fixed (1.0.35)
