### ISSUE TITLE
Add a command to open the current solution in visual studio

### ISSUE THREAD

**Issue by moosichu** [slynch8/10x#1705]
The visual studio debugger syncing is really nice - but occasionally it would be useful to be able to quickly open the current solution in visual studio for other reasons, without triggering the debugger (and waiting for a compile to finish).

**Comment by moosichu** [comment]
sounds good!

**Comment by moosichu** [comment]
Re-opening this issue as it doesn't quite satisfy the needs of what I'm after in this case (and some googling hasn't helped unfortunately) -  ideally I would be able to either open the solution in a new VS window if one is not yet open *or* open the existing solution window if it already  exists. Unfortunately  VS  will just open  a new window anyway and then fall over itself :/ 

I've  also tried executing  the `File.OpenProject` command - but sadly that has the same behaviour.

**Comment by slynch8** [comment]
You could probably get python to enumerate the windows and check the windows names to see if the sln is already open. That's what I do in 10x. But if you want to wait I can implement this in 10x.

**Comment by slynch8** [comment]
done.
For 10x to VS: OpenCurrentFileInVS command (alt+X)
For VS to 10x install the 10xEditorLink extension (alt+X)

**Comment by moosichu** [comment]
Thank you! Been using it and it's been great!
