### ISSUE TITLE
__attribute__ compiler keyword (clang) doesn't seem to be supported

### ISSUE THREAD

**Issue by septag** [slynch8/10x#1718]
notice the function is highlighted incorrectly:
![image](https://github.com/slynch8/10x/assets/5081921/684ff92c-4113-4da7-b80c-395d5ae3d0a9)

deleting the NO_INLINE results in correct highlighting:
![image](https://github.com/slynch8/10x/assets/5081921/eea1d6db-8a5f-4285-8449-2836665f29e3)

**Comment by slynch8** [comment]
fixed (1.0.25)
