### ISSUE TITLE
10x crashes upon closure

### ISSUE THREAD

**Issue by twevs** [slynch8/10x#1722]
10x frequently crashes upon closure. I have just uploaded a batch of 15 crash dumps from the last week which should hopefully shed some light on the matter, from `10x_crash_2023_5_10_14_20_24.dmp.gzip` to `10x_crash_2023_5_16_1_4_0.dmp.gzip`; do feel free also to ping me on Discord (Thomas) if you have any questions about it.

**Comment by slynch8** [comment]
Looks like it's still logging output from an exe you've launched after closing 10x.

**Comment by twevs** [comment]
In all of these cases, I was running Unreal from 10x using Ctrl+F5. In the most recent crash dump, I distinctly recall that I had closed 10x for a while, but it was only when I closed the Unreal Editor itself that the crash message appeared.

**Comment by slynch8** [comment]
Yes, the 10x process will hang until Unreal Editor is closed, then will crash. I've made a fix where it stops the process, but would it be better if I leave it running and just detach 10x?

**Comment by slynch8** [comment]
although I'm not sure I can detach easily. It's blocking until the process finishes.

**Comment by twevs** [comment]
Thank you for looking into this. The latter option seems more intuitive to me — I tend to think of a process launched with Ctrl+F5 rather than F5 as being independent from the IDE, with the logging feature being quite incidental. If you go with the former, I do think it might be a good idea to display an "Are you sure you want to close the process?" dialog box when closing 10x in this situation.

**Comment by slynch8** [comment]
fixed (1.0.27)

10x will now detach itself from the process when it exits
