### ISSUE TITLE
Crash upon clicking on "Close All" in tab context menu

### ISSUE THREAD

**Issue by twevs** [slynch8/10x#1723]
I have only experienced this once and have not been able to reproduce it. Crash dump: `10x_crash_2023_5_16_12_39_42.dmp.gzip`.

**Comment by slynch8** [comment]
downgrading priority because it can't be reproduced. Let me know if you get this again.

**Comment by therathatter** [comment]
I have experienced this twice in the 10x notepad in the past few days. I've uploaded my crash log of it occurring.

File name: `10x_crash_2023_8_15_2_17_35.dmp.gzip`

**Comment by slynch8** [comment]
fixed (1.0.70)
