### ISSUE TITLE
Allow keybinds to non-US keyboard keys

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#1727]
Swedish keyboard here, with a few odd ones. VK_ codes below gathered using https://github.com/awakecoding/Win32Keyboard.git

§ = VK_OEM_5
å = VK_OEM_6 (this is where US have [ )
ö = VK_OEM_3
ä = VK_OEM_7
' = VK_OEM_2
< = VK_OEM_102

Maybe the KeyMappings.10x_settings should allow for VK_ codes. Might be useful for funny usb gizmo buttons you can buy too.

Help Menu -> Log Keys shows nothing:

`[10x] KEY: `

**Comment by slynch8** [comment]
done (1.0.156). VK_OEM_1 - VK_OEM_8 and VK_OEM_102 are now mappable.
