### ISSUE TITLE
Unexpected text drag on Ctrl+double click

### ISSUE THREAD

**Issue by dannye** [slynch8/10x#1728]
In version 1.0.30, with the new "TextDrag" setting set to true, holding Ctrl and double clicking on some text moves the next character *after* the current word (often bracket, quote, space, period, etc) into the middle of the current word at the current mouse position:

https://github.com/slynch8/10x/assets/5231310/7b98b026-17ed-42bf-8aed-c53e2d8d79a8

In the video, the only thing I'm doing is Ctrl+double click and then Ctrl+Z to undo.

As always, thanks for 10x :)

**Comment by slynch8** [comment]
fixed (1.0.31)
