### ISSUE TITLE
10x will always open a workspace or  solution in a new instance, even  if it's already open

### ISSUE THREAD

**Issue by moosichu** [slynch8/10x#1739]
This is tangentially related to #1721, where after additional testing, I realized that the base case of just giving a workspace as an argument would always open a new instance (tested with both 10x workspaces and visual studio solutions, both exhibited the same behavior). I'm splitting this out as a separate issue as  I presume it can be considered to be a  bug as[ the documentation](https://10xeditor.com/10xDocumentation/CommandLine.htm) states:

> If a file or **workspace** is specified and 10x or 10x_notepad is already open the the is opened in the existing process and is given focus. 

Another curious incidental thing is that if I invoke 10x.exe from the git bash terminal,  it will block the command line until the IDE is shut down, but I don't see the same behaviour from powershell or command prompt. This isn't really something that affects me in any meaningful way, but I thought  that I would mention it as I haven't seen this kind of behaviour from a program before and it stood out. I'm very happy to create a  separate issue for this if you think this is something worth addressing!

**Comment by slynch8** [comment]
fixed.

I'm not sure about the exe blocking the terminal. As far as I'm aware all exe's should do that. I'm not sure how I'd stop it other than spawning another process each time it starts.
