### ISSUE TITLE
Crash in Workspace Search when clicking erroneous rows

### ISSUE THREAD

**Issue by dannye** [slynch8/10x#1747]
![image](https://github.com/slynch8/10x/assets/5231310/9ee1857a-dcf7-42fe-a3b3-a2c791bb17a4)

After using Workspace Search to search for "aa", some .xpm files showed up in the results looking like a "filename match" rather than a "file content match" (no line number or line content shown in the search results) even though "aa" is only present in the file and not in the filename.

Then 10x crashed when I single-clicked on "res\app.xpm". I uploaded the crash dump to pCloud.

The crash consistently happened on a second attempt, but then I properly manually opened the .xpm files via the Workspace Tree and then the crash stopped occurring after that point.

**Comment by slynch8** [comment]
fixed (1.0.35)
