### ISSUE TITLE
[python] RuntimeError: Error calling GetSetting from thread, when using RemedyBG.py

### ISSUE THREAD

**Issue by hsjunnesson** [slynch8/10x#1752]
Just updated 10x to version 1.0.36. I also updated to the latest version of RemedyBG.py - 0.10.1 and I get this when I start the 10x:

```
[python] RuntimeError: Error calling GetSetting from thread
[python] 
The above exception was the direct cause of the following exception:

[python] Traceback (most recent call last):
[python]   File "C:/Users/Hans/AppData/Roaming/10x/PythonScripts/RemedyBG.py", line 785, in <module>
[python]     _rdbg_options:RDBG_Options = RDBG_Options()
[python]   File "C:/Users/Hans/AppData/Roaming/10x/PythonScripts/RemedyBG.py", line 116, in __init__
[python]     self.executable = Editor.GetSetting("RemedyBG.Path").strip()
[python] SystemError: <method 'GetSetting' of 'Editor' objects> returned a result with an exception set

```

**Comment by slynch8** [comment]
can you double check you have the latest script. It should have the InitialiseRemedy() function

![image](https://github.com/slynch8/10x/assets/7141856/07db2b67-4265-4c44-8c93-d4149f49758c)

**Comment by slynch8** [comment]
I didn't realise it had a version number, I'll update it. But the latest file is here:
https://github.com/slynch8/10x/blob/main/PythonScripts/RemedyBG/RemedyBG.py

**Comment by hsjunnesson** [comment]
Just update to version 0.10.2 of RemedyBG.py and that fixes it. Thanks!
