### ISSUE TITLE
Go to previous edit location

### ISSUE THREAD

**Issue by EpicDanSmith** [slynch8/10x#1758]
I would love a `PrevEditLocation` equivalent to the `PrevLocation` command that navigates to the last edited character across all files. `PrevEditLocationCurrentFile` would also be handy I suppose!

I find this super handy in other IDE's to go off spelunking in code (e.g: clicking through Super definitions), to find out how to do something, then snap back to where I was editing to get the job done!

**Comment by slynch8** [comment]
added (1.0.42)
