### ISSUE TITLE
[Title][List] Workspace did not aligned

### ISSUE THREAD

**Issue by Pickminer** [slynch8/10x#1760]
1) The selected workspace is "pickminer"
![workspace_1](https://github.com/slynch8/10x/assets/115069897/ab3bcc20-0a2f-43de-9ba8-e6a1c5adb398)

2) I select another workspace and the display is not done correctly.
![worksapce_2](https://github.com/slynch8/10x/assets/115069897/31e3cf0a-37b7-412e-9137-d1b22bece342)

3) I re-select "pickminer" and the word is not displayed.
![workspace_3](https://github.com/slynch8/10x/assets/115069897/e8ebdf0b-fff9-47fd-95a3-9cccdc426422)

**Comment by slynch8** [comment]
fixed (1.0.37)
