### ISSUE TITLE
Infinite loop when performing case-insensitive find & replace all in some circumstances

### ISSUE THREAD

**Issue by DJRBuckingham** [slynch8/10x#1791]
It is possible to cause an infinite loop when performing a "find & replace all" using case-insensitive selection, where the find/replace strings only differ by case. This is obviously incorrect usage, but is easy to accidentally do if you forget to enable the "Case" mode.

Repro:
1) Open a new document in 10x Editor
2) Type ABC aBc
3) Press Ctrl-H to open the find/replace widget
4) Put aBc in find and abc in replace
5) Ensure Case is not active
6) Press All
7) Observe 10x Editor get stuck in an infinite loop

The repro steps seem quite specific and/or unreliable. I seem to need to create a new document for it to repro reliably. If I use an existing document, or the recovered document on re-opening 10x, it doesn't always reproduce. Also, if I add newlines after typing ABC aBc, it doesn't repro.

In the wild I had this repro after implementing a ~150 line .cpp, and I had used "hwnd" and "hWnd" interchangeably in various functions. I went to rename all instances of hwnd with hWnd but hit the infinite loop, because I forgot to enable the Case option. This shows the issue can occur not just on a fresh file, but I wanted to provide the minimal repro above as best as I can.

Repro'ed on 10x Editor 1.0.41 and a few prior point releases.

**Comment by slynch8** [comment]
thanks for the repro. Fixed (1.0.42)
