### ISSUE TITLE
Add Perforce commands to file right click menu

### ISSUE THREAD

**Issue by kudaba** [slynch8/10x#1794]
Right now they are available on tab and tools, but just right clicking anywhere in a file to be able to have access would be nice.

**Comment by slynch8** [comment]
are there any specific commands that you want? Adding all of them makes the context menu very big. Although I guess I could add a sub-menu.

**Comment by slynch8** [comment]
done (1.0.45)
I've added Checkout, Diff, History and show in p4v. Let me know if you want other commands added.
