### ISSUE TITLE
[Request] Ctrl+F: Show number of matches in file

### ISSUE THREAD

**Issue by dannye** [slynch8/10x#1795]
It would be convenient if the Find box also showed the number of matches in the current file, perhaps here where I've circled:
![image](https://github.com/slynch8/10x/assets/5231310/a14daec9-99b5-4db2-aed5-b9eb9eb16dd2)

Additionally, it could also show which match number the current selection is at, although this isn't as important to me personally; I really just want to know -- at a glance -- how many matches there are in the current file.

**Comment by Wassimulator** [comment]
bump! would be great !

**Comment by vlucki** [comment]
@slynch8 isn't this done now, with the latest release (1.0.218)?

**Comment by slynch8** [comment]
Thanks, yes, enable with the `ShowFindTextMatchCount` setting
