### ISSUE TITLE
Parser with macros

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#18]
I know macros were not supported my the parser, but I think I read that recently you started adding support. Here is a common scenario I see in my code where the parser does not seem to understand it.

![10x_4](https://user-images.githubusercontent.com/1583441/102155800-5e3b5b00-3ed0-11eb-9b52-80092e8bd30f.png)

**Comment by slynch8** [comment]
it doesn't do any preprocessing yet, it's just indexing the macro so that goto-def works. Hopefully I'll get to the preprocessor soon, but that's going to be a big task.

**Comment by Muzza** [comment]
I'm confused as to why you have closed it?
IMHO the point of a public issue tracker is for users to be able to see what is already known and planned for, as opposed to it either being unknown, or something that is out of scope and unlikely to ever be looked at.
Also other users can give the issue thumbs up or add comments, so you can get an idea of how important it is.

Rather than close it, you could labels to mark it as 'Long term' or similar.

Personally, this is a big issue for me as I have quite a lot of code accessed via macros that currently don't give me any kind of auto-complete assistance.

**Comment by slynch8** [comment]
Sorry, I've only been using these issues for bugs so far, and it made it look like something wasn't working. But I take your point about using these issues for communicating new features as well, and I've created a new issue here for the preprocessor:
[https://github.com/slynch8/10x/issues/27](https://github.com/slynch8/10x/issues/27)

I'll also start labelling issues as 'bugs' or 'new feature' to make it clear.

It's useful to know that it's an important feature for you, I'll try and prioritise it.
