### ISSUE TITLE
Triple Click conflict with Double Click + Shift + Click 

### ISSUE THREAD

**Issue by ArnaudJamin** [slynch8/10x#1806]
Hello, 

On Visual Studio if you press shift after a double click, the next click will not be interpreted as a triple click. On 10x it will.

I usually use this to select a word and some text after. For example with the following text:

void MyClass::MyFunction(int arg1, int arg2)

- I want to select "MyClass::MyFunction" 
- My cursor is above "MyClass"
- I double click which select "MyClass"
- I move my cursor right after the word MyFunction
- I press Shit+Click 
- I expect the selection to be "MyClass::MyFunction" but on 10X the selection will be the full line because of a triple click

If I wait long enough after the double click and the next Shift+Click, it won't be interpreted as a triple click, and my selection will be what I expected.

Thanks!

**Comment by slynch8** [comment]
fixed (1.0.45)
