### ISSUE TITLE
[Request] Expose the build command functionality to the python api.

### ISSUE THREAD

**Issue by matiasjpedro** [slynch8/10x#1810]
This would basically provide unlimited options of build commands. 

![image](https://github.com/slynch8/10x/assets/7761322/15045004-8145-4b10-8295-9b4c27cb4196)

With something like that we can trigger the compilation of multiple stuff and get the results in the build output, like for example:

1. The engine code
2. The game code
3. Havok code
4. etc etc etc

**Comment by slynch8** [comment]
done (1.0.50)
