### ISSUE TITLE
Small update to FASTBuild .bff syntax highlighting rules

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#1818]
https://fastbuild.org/docs/syntaxguide.html#scoping defines that variables can start with a `^`, so the following rule can be added to section `variables` (`Language.Custom8`):

`REGEX((^|\W)\^[a-zA-Z_0-9]+\w\b)`

**Comment by slynch8** [comment]
thanks, but I don't seem to have a bff syntax highlighting file, could you send it please?

**Comment by ggnkua** [comment]
Oops! Here you go for what it's worth, it's not perfect and it has some stuff commented out
[fastbuild.zip](https://github.com/slynch8/10x/files/11866688/fastbuild.zip)

**Comment by slynch8** [comment]
Thanks. Ah, I did have it already, was looking for the wrong name. I'm sure people will find this useful.
