### ISSUE TITLE
Find Files can't resize filename / filepath columns.

### ISSUE THREAD

**Issue by forrestthewoods** [slynch8/10x#1821]
The pop-up for "Find Files" has two columns and it's not resizable. For projects with long file paths this is super annoying.

![image](https://github.com/slynch8/10x/assets/8474974/7b65f56f-c24b-4532-8e9b-02aea27825d3)

And I still think file paths should show the end of the path. If a path is too long to fit in a column I don't think I **ever** want to see the start of the path. I always prefer to see the end.

**Comment by slynch8** [comment]
column resizing fixed in (1.0.51)
