### ISSUE TITLE
Multi cursor and moving selection doesn't work together

### ISSUE THREAD

**Issue by uranium2818322192** [slynch8/10x#1823]
Triggering multi cursor and then moving the selection with control up & down doesn't seem to be working correctly, most of the time it will move the line last selected and sometimes it can do move multiple lines but even then not all the ones selected. It will work correctly if you select multiple lines by mouse input. I'm not sure what the correct behaviour would be exactly since user can select with multiple cursor partially (as in vertical slices).

**Comment by uranium2818322192** [comment]
In the case of partial selection, most editors seems to be moving the whole line which makes sense since moving the line is related to cursor's vertical position rather then selection.

**Comment by slynch8** [comment]
fixed (1.0.64)
