### ISSUE TITLE
look into using dx11 SetMaximumFrameLatency

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#1830]
might improve things on higher refresh rate monitors and reduce latency

from email:
"would be nice to have it added and be able to control. There's also Waitable swapchain and you should make sure that app is using modern flip model(Immediate). 

https://devblogs.microsoft.com/directx/dxgi-flip-model/
Decreasing latency using DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT. When in Independent Flip mode, you can get down to 1 frame of latency on recent versions of Windows, with graceful fallback to the minimum possible when composed.

DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING can enable even lower latency than the waitable object, even in a window on systems with multi-plane overlay support."

**Comment by schizobeyond-tech** [comment]
![image](https://github.com/slynch8/10x/assets/138343630/c431cb78-181f-446c-80d3-0cd1e54c4091)

CapFrameX, small .MD file(36 lines) opened in 10X, did few typing runs, deleting line, writing, hit enter, full screen(windowed), 5GHz CPU, C states disabled, 6900XT locked clocks, 360Hz monitor

![image](https://github.com/slynch8/10x/assets/138343630/e7da6b70-0741-4ffe-9aa5-abe4df314beb)
![image](https://github.com/slynch8/10x/assets/138343630/b09f5786-be27-415c-81c5-6354d7d37964)
last pic is zooming into the previous one to see 2.77ms frame time which is 1000/360Hz deadline

![image](https://github.com/slynch8/10x/assets/138343630/7d8aa620-5908-4a83-98b2-ea07adaf088d)

Note that this is just measuring using Present() timestamps and not GPU DX11 timestamping queries, also seems like scrolling even a small file causes massive spikes
![image](https://github.com/slynch8/10x/assets/138343630/fed9d2fa-a4ce-4d72-a2cf-313ba553e469)

below is with "Disable Fullscreen Optimizations enabled on 10x.exe"
![image](https://github.com/slynch8/10x/assets/138343630/0bc71ab7-f32d-4f78-b021-f545400dcfbc)

all tests are done with vsync off and DisablePresentWhenIdle set to false

![image](https://github.com/slynch8/10x/assets/138343630/a7d81c22-2ce0-42e4-84fe-0522775ca9eb)

^ this is with 200 LOC Minhook.h

below is a .txt file of 1.4million rows with ~30 ASCII chars per line, its very bad, frame time goes from ~1.5ms to constant 5ms
![image](https://github.com/slynch8/10x/assets/138343630/85a22411-b5fc-46f1-ba61-5de7378879d3)


I think pressing new-line/return causes a massive frame time spike

Also the app goes to sleep too aggresively and for too long if you are not constantly typing (and i mean smashing ASDASDASDASD over and over at constant high wpm rate)
For example here it is with some text inputs but with decent delay inbetween keystrokes(such as when thinking what code to write while programing)
![image](https://github.com/slynch8/10x/assets/138343630/ae3e071b-f2e6-47a4-9d07-25416e428721)
Thats 500ms per frame time, this is very noticeable when you hit the first keystroke after idling for a few 500ms-1000ms? moments

**Comment by schizobeyond-tech** [comment]
https://github.com/slynch8/10x/assets/138343630/c6b1b709-5f28-465d-b4dd-2aeba1d72aed

![1682698804010424](https://github.com/slynch8/10x/assets/138343630/501b2bf5-8284-4b08-9aa2-65774e9c3f00)

**Comment by schizobeyond-tech** [comment]
Maybe few settings to fine-tune depending on user machine type desktop/laptop/high-end desktop PC etc related to how often app sleeps and for how long, feels like first input after idle is always going to be from wake up state due to too aggresive sleeping and it can be felt on >60Hz displays. Maybe a raw input dedicated thread?(Busy polling one might be too much but worth it since there are some small % of users on Apex Pro TKL or 8kHz keyboards such as Razer Huntsman v3)

**Comment by schizobeyond-tech** [comment]
Any update on this? What about
`DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT`
or `DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING `
or `DXGI_USAGE_RENDER_TARGET_OUTPUT`
https://learn.microsoft.com/en-us/windows/uwp/gaming/reduce-latency-with-dxgi-1-3-swap-chains
`By default, the frame latency for waitable swap chains is set to 1, which results in the least possible latency`

**Comment by slynch8** [comment]
I tried changing to DXGI_SWAP_EFFECT_FLIP_DISCARD but not it only seems to be rendering the first frame and flickering between that and an empty back buffer each frame. Any ideas?

**Comment by slynch8** [comment]
I think I've found ka solution. Calling this after the present fixes it, although I'm not entirely sure why.
`gp_ImmediateContext->OMSetRenderTargets(1, &gp_RenderTargetView, nullptr);`

**Comment by schizobeyond-tech** [comment]
I think `DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT` is best bet with Present(SyncInterval:0), as for FLIP_DISCARD

> This flag is valid for a swap chain with more than one back buffer; although applications have read and write access only to buffer 0.
>specify that DXGI discard the contents of the back buffer after you call [IDXGISwapChain1::Present1](https://learn.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgiswapchain1-present1).

**Comment by schizobeyond-tech** [comment]
Also what about some settings to disable very aggressive sleeping on 10X? Such as, disableSleep,  maxSleepsPerSec etc? as https://github.com/slynch8/10x/issues/1830#issuecomment-1629862899 shows , i hooked Sleep() calls inside 10X editor and there is very aggressive sleeping when no input is being sent

**Comment by slynch8** [comment]
Hi. I've made some fixes. Can you give this build a try:
https://e.pcloud.link/publink/show?code=XZRmQDZ5XgW9vqWi18YuccJUpLl8VvIzaJk

- fixed bug with app going to sleep too soon, now sleeps after 5 seconds of idle
- reduced idle speed times to improve wake from sleep times on high refresh rate monitors
- fixed stalls updating map scroll bar
- removed 1 frame of latency by switching to waitable swap chains
- set MaximumFrameLatency to 1

The sleeping was just totally broken and was sleeping immediately. Now it waits 5 seconds before idling. So thanks for bringing that to my attention.

There was a huge stall adding a new line to a file because of updating the map scroll bar. This is fixed now.

When using waitable swap chains it seems you have to pass in 1 to the Present otherwise the wait doesn't work. But you can get it to pass in 0 by disabling vsync (which also disables the wait).

Let me know how you get on with this build. All going well I'll be releasing it sometime next week.

**Comment by slynch8** [comment]
Here's another build with window resizing fixed
https://e.pcloud.link/publink/show?code=XZySbDZsMPfxaUNFA4k7B50WOMR6Yrd760y

**Comment by slynch8** [comment]
another fix:
https://e.pcloud.link/publink/show?code=XZ2WbDZzKHoKyf0xg8ULqERh1xYuLlplk8k

**Comment by slynch8** [comment]
and another
https://e.pcloud.link/publink/show?code=XZ19bDZ9ICocgS599Y5E27UGGXRdQvfjIW7

**Comment by slynch8** [comment]
done (1.0.97)

Let me know how you get on.
