### ISSUE TITLE
Search doesn't update when you press the 'case' or 'word' buttons and instead you have to put the cursor inside the search bar and hit return again

### ISSUE THREAD

**Issue by Wassimulator** [slynch8/10x#1835]
expected behavior is updating search results if either of these buttons are pressed

**Comment by Wassimulator** [comment]
bump!

**Comment by slynch8** [comment]
Is this for Find text in file or Workspace Search? Although I can't get it to happen in either.

**Comment by Wassimulator** [comment]
Here's a simple demo, I think more specifically the VISUAL highlighting doesn't update.
https://github.com/user-attachments/assets/6601c1dc-a130-4c82-938a-755887488e4f

**Comment by slynch8** [comment]
fixed (1.0.218)
