### ISSUE TITLE
Request: a button to transition from the find UI to the find and replace UI instead of having to manually hit it again

### ISSUE THREAD

**Issue by Wassimulator** [slynch8/10x#1836]
![Code_inrOhmgjrT](https://github.com/slynch8/10x/assets/75145262/c8426075-8075-436a-afb3-8963b577e47b)

example for expected behavior, (from VSCode)

requested to change this panel:
![image](https://github.com/slynch8/10x/assets/75145262/bc164290-55c2-49c7-8461-e534fecf032e)

**Comment by slynch8** [comment]
You can switch it by hitting ctrl+H, or do you specifically want a button?

**Comment by Wassimulator** [comment]
true. I will admit I haven't realized that, likely because often when I am interacting with the find panel I'm more focused on mouse inputs.

**Comment by Wassimulator** [comment]
Apologies, this is not a thoughtful feature request, you can remove it.
