### ISSUE TITLE
10x holding onto shift key when launching external program (new in v1.0.47.0)

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#1848]
I have a python script that launches an external command line process if I press Ctrl+Shift+B in 10x
With v1.0.47.0, launching it causes the 10x editor screws up and acts as though I am still holding down Ctrl + Shift. I have to press and release them to be able to continue typing.
Rolling back to v1.0.45.0 fixed it.
The python script calls this (on a thread):
`Popen( [self.exe]+self.runParams, cwd=self.currentDir, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)`

**Comment by slynch8** [comment]
I can't get this to happen. Does the exe take focus away from 10x and does it stay running or terminate?

**Comment by slynch8** [comment]
ignore that, I've got it

**Comment by slynch8** [comment]
fixed (1.0.48)
