### ISSUE TITLE
make tab and backspace symmetrical. when tab inserts 4 spaces.

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#1858]
if i indent using 4 spaces when pressing tab, backspace should delete 4 spaces.
"should" or option.
i.e. backspace knows your indent mode is 4 spaces, so if it finds 4+ spaces to the left of the cursor, it deletes 4 spaces.

**Comment by slynch8** [comment]
done. Added `BackspaceDeletesTabs` setting (1.0.156)
