### ISSUE TITLE
Feature request: Let VisualStudioEnvBat: auto remain in settings file after restart

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#1868]
With a shared Settings-folder between computers, the VisualStudioEnvBat path needs to have different values, can be drives or professional/community.
If it could stay at auto and not rewrite the settings file, that would work.
Otherwise, some localsettings file either not synced between computers, or entries picked depending on say hostname would be a workaround if possible.

**Comment by slynch8** [comment]
You can move it to the local settings file `Settings Menu -> Local Settings`

**Comment by datgame** [comment]
Yes, but then I can't share the full Settings folder anymore, and have to make specific symlinks for each file and subfolder in it. 
So it's a nuisance.

**Comment by slynch8** [comment]
The way it's designed to work is you keep the local settings file local, and set the `SettingsPath` setting to point to your shared folder.
https://10xeditor.com/10xDocumentation/SettingsFiles.htm

**Comment by datgame** [comment]
Ok, cool :-) I expected the reverse (a LocalSettingsPath), but maybe this makes more sense.
I will try it out. If it works it solves the problem.
