### ISSUE TITLE
Texts are all buggy

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#1879]
![texts](https://github.com/slynch8/10x/assets/15263484/eb6299ab-f3c9-4af7-8272-1ab9bf95a15e)

Sometimes letters are buggy like in the picture, it can happen on everything in the editor. Note that for buttons, if I hover the mouse over it, the text is refreshed and it displayed normally.

This is an old bug, I've had it on my machine for at least a year.

**Comment by slynch8** [comment]
I've never seen that before. Can you try resetting everything to default. Close 10x and rename your %appdata%\10x folder.

**Comment by slynch8** [comment]
I think there was a bug a while back where the font cache could become corrupted, maybe it was that (`%appdata%\10x\cache\fonts.cache`)

**Comment by slynch8** [comment]
have you changed the UI font in the settings?

**Comment by bousquetm** [comment]
I haven't changed the settings (it's still "Segoe UI"). On both machines, I had installed 10x a long time ago and I've been updating it since then, so maybe I had the old bug you're talking about.

**Comment by bousquetm** [comment]
Could not reproduce the issue for a week after clearing the cache.

**Comment by slynch8** [comment]
ok, I'll close for now. Let me know if it happens again.
