### ISSUE TITLE
Feature Request: disable autocomplete arrow keys capture

### ISSUE THREAD

**Issue by odecaux** [slynch8/10x#1910]
I would like the autocomplete popup to show up but use a keybinding like ctrl+arrow to select results, or an option to show the suggestions at all time and hit the already defined ctrl+space to enable the capture.

**Comment by slynch8** [comment]
Autocomplete up/down and page up/down are now commands that can be re-mapped (1.0.68)
`AutocompletePrev`, `AutocompleteNext`, `AutocompletePageUp`, `AutocompletePagedown`
