### ISSUE TITLE
__restrict in fuctions declaration is not recognized anymore

### ISSUE THREAD

**Issue by Goryh** [slynch8/10x#1914]
This simple test can't resolve **test->a** anymore. It used to work according to closed issues.
```
struct TestStruct
{
	int a;
	int b;
}

void Test(const TestStruct* __restrict test)
{
	test->a = 0;
}```

**Comment by slynch8** [comment]
I see. It is parsing the test variable correctly, but it seems the -> resolving for has never worked for restrict variables. I'll get that fixed.

**Comment by slynch8** [comment]
fixed (1.0.58)

**Comment by slynch8** [comment]
I forgot to bump the parser cache version number, so you'll need to do a ReparseAll

**Comment by Goryh** [comment]
it works now, thanks a lot!!!
