### ISSUE TITLE
Bug: Randomly cannot change Settings of folder in 10x Workspace

### ISSUE THREAD

**Issue by MichaelCenger** [slynch8/10x#1917]
I have a pretty simple 10x workspace with 2 Subworkspaces. Since the latest update (Don't know if it was an issue before) I start to lose the functionality to change the Settings on any folders within the workspace after some time.

I managed to reproduce this 100%. It always happens once I right click a folder that is nested within another folder.
In the images below you will se my structure. Basically right-clicking any of the "Source" folders in either "Aeonis or "AeonisRuntime" works as expected. But as soon as I right click "Core" or "Application" the Settings option is greyed out. When I rightclick any of the "Source" folders after this happened the option will also be greyed out on them.

Freshly opened workspace. I can edit Settings of the "Source" folders when right clicking
![image](https://github.com/slynch8/10x/assets/49336079/98d6cd51-2172-4c96-95c5-53b96db58f3b)

After right clicking any of the folders that are nested deeper in "AeonRuntime" the Settings option is greyed out for all my folders.
![image](https://github.com/slynch8/10x/assets/49336079/2a14be86-c1f1-4c25-ba4e-256d0ba98d94)

**Comment by slynch8** [comment]
Are the folders sync'd? If so the settings should be greyed out on them. You can only change the settings on the root folder that is syncing, not the sync'd folders. But it does sound like a bug that it isn't updating the menu item properly though.

**Comment by slynch8** [comment]
ok, I've found the bug. When you click on the sync'd folder it is greyed out correctly, but then isn't getting reset when you click on something else. Will be fixed in the next build.

**Comment by slynch8** [comment]
fixed (1.0.60)
