### ISSUE TITLE
Formatting bug with multiline comments

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#1930]
Consider this block of code
![image](https://github.com/slynch8/10x/assets/5121492/def68387-d9bc-4966-ad7c-47ea2e42d9e2)
I would like to comment it out, so first I insert a `/*` at the top of the block
![image](https://github.com/slynch8/10x/assets/5121492/e57abb8e-cc07-4b8d-8677-7530c46f62f8)
This works fine, then I go to the last line of the block and press enter to insert a blank line.
![image](https://github.com/slynch8/10x/assets/5121492/8fa63972-8d70-4e56-a37b-79f6df523777)
A star character is inserted in the last line of code, as well as the next one. So then I have to manually delete that star character and complete the multiline comment by typing `/` at the last line.

**Comment by slynch8** [comment]
you need to set `AutoFormatBlockCommentsNewLines` to false

**Comment by ggnkua** [comment]
I see. Is this default behaviour? If yes, could I suggest turning this off by default, as it's probably not what most users that block comment a piece of code would likely want?

**Comment by slynch8** [comment]
yes, you're probably right. I'll disable it by default
