### ISSUE TITLE
"no autocomplete" not respected in keymappings file

### ISSUE THREAD

**Issue by Phildo** [slynch8/10x#1937]
I have
SubmitAutocompleteOnEnter: false 
in my Settings.10x_settings, but typing
Control G: Ru<enter>
autocompletes to "Run"

**Comment by slynch8** [comment]
do you have the `Autocomplete` setting set to false?

**Comment by Phildo** [comment]
yes, I have `Autocomplete:             false`

**Comment by slynch8** [comment]
fixed (1.0.65)
