### ISSUE TITLE
Comment indent with spaces is wrong

### ISSUE THREAD

**Issue by frederich** [slynch8/10x#1947]
I've to use spaces for indentation with size 2, company rules. 10x generates wrong indentation on comments. For instances:

```
{
  return false; // Very import comment;
               ^ just one blank here, should be two
}
```

**Comment by frederich** [comment]
In all companies I have worked in so far, no tabs but spaces are used, usually there were always two spaces and tabs were also set to two Spaces. When the tab key is pressed, it is not filled, but exactly the number of spaces is inserted that is set, so always two. No padding logic.

**Comment by slynch8** [comment]
I understand what you're saying, but I just tried it in Visual Studio and it does the same as 10x.

**Comment by frederich** [comment]
Okay
