### ISSUE TITLE
10x inserts 4 spaces even though I use tabs

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#1964]
I have "IndentMode" set to Tabs, "TabWidth" set to 4. When I type:
```
int foo(int toto,
```
and then hit enter, the cursor is placed on the new line vertically aligned with 'i' in int, which is perfect. However instead of 2 tabs, the editor gave me 8 spaces.

**Comment by slynch8** [comment]
This is by design because indenting using tabs won't be aligned properly for other people with different tab sizes. But I can add a setting to force it to use tabs.

**Comment by slynch8** [comment]
Yes, but then if someone else views the file with a different tab width it won't line up anymore

**Comment by slynch8** [comment]
I'll add a setting to make it always use tabs

**Comment by slynch8** [comment]
added new `UseSpacesAfterCurrentIndent` setting (defaults to false)
(1.0.146)
