### ISSUE TITLE
Enhancement request: In settings/keybindings file, highlight all lines which have clashing settings or syntax errors

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#1966]
Here is an example from focus editor:

![image](https://github.com/slynch8/10x/assets/5121492/6567fb53-8669-4540-b6f3-4dc4267a655b)

In the first line the bound function is invalid, while in the second the key binding is garbage.

**Comment by hsandt** [comment]
And I'd also suggest error logging somewhere (popup? some console? right now we see nothing at all) and auto-complete. For instance, I have an issue https://github.com/slynch8/10x/issues/2615 where I don't know if a binding exists or not. With syntax error highlighting + logging, I would be sure that a configuration is invalid, and with auto-complete, I would just type "Mouse" and see all mouse-related input names.

**Comment by ggnkua** [comment]
Closing this as it's a dupicate of #2452, but I made a note for Stewart to check this ticket as well.
