### ISSUE TITLE
Crash when modifying an opened file during build

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#1971]
I have a file that is being generated in the build command (win32_main.i). If I have the file opened in 10x, it crashes 100% of the time when compiling.

My command line is calling a .bat file that calls cl.exe to generatoe win32_main.i.

I have uploaded a crash dump.

edit: if I open win_main.i in 10x_notepad instead of 10x and compile my project, it also crashes 100% of the time.

**Comment by bousquetm** [comment]
It doesn't crash anymore but I have this error message (I think that was briefly shown before crashing in the main version):

"Error updating file: [path]/win32_main_i

Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processur." [The process cannot access this file because it is used in another process]

**Comment by slynch8** [comment]
Yes, that's expected. The process writing the file is holding a lock, so when 10x tries to update the file it can't and shows an error messages, then it retries a number of times.
