### ISSUE TITLE
Request: make SelectCurrentWord command update the F3 search

### ISSUE THREAD

**Issue by n00bmind** [slynch8/10x#1981]
Currently, when I do SelectCurrentWord, I need to do Ctrl+F3 to jump to the next ocurrence of that word, then I can use F3/Shift+F3 like for a normal search..
I think it'd make everything simpler if SelectCurrentWord already updated the search like FindInFileNextCurrentWord (Ctrl+F3) does, that way one could use F3/Shift+F3 for both a normal search and a current word search.

**Comment by slynch8** [comment]
done (1.0.70)
