### ISSUE TITLE
Click+drag to move highlighted text will over wright the clipboard

### ISSUE THREAD

**Issue by RetroZelda** [slynch8/10x#1986]
![clipboard](https://github.com/slynch8/10x/assets/4962388/f6500e73-c3ec-4e18-8da7-705b855cc8bd)

in this example I copy text and paste it, then I move text and then paste again but its not what I initially copied, but rather its the text that I just moved.  I would expect my "paste" would still have the text that i initially copied

**Comment by slynch8** [comment]
fixed (1.0.70)
