### ISSUE TITLE
[feature] setting for columns to auto-close when the last tab in that column is closed

### ISSUE THREAD

**Issue by Phildo** [slynch8/10x#1992]
this would be in service of replicating vim's "split" pane behaviors, which allows you to dynamically create and remove panes.

**Comment by slynch8** [comment]
you can do this with `View Menu -> Columns -> Auto`

**Comment by Phildo** [comment]
this does not work as described.

repro: 
- `View Menu -> Columns -> Auto`
- create a new column by dragging a tab on top of the column it's in (this is the only way I know to create a new column in `Auto` mode- "duplicate left" or "duplicate right" just _take over_ the column to the left or right rather than creating a new one)
- close the tab in the column you just created
- the column still exists, but is empty

**Comment by slynch8** [comment]
I see. With auto, it will only removes the last column if it's empty.

Ok, I'll add a setting to remove any column that is empty.

**Comment by slynch8** [comment]
done (1.0.189)

I didn't add a setting in the end, I just made auto always work this way (close any column that is empty)
