### ISSUE TITLE
Enable syntax highlighting when a new file is saved

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#2]
Create a new file, fill it with some code, then save it as a .c, .cpp or .h file.
Syntax highlighting does not work on this file until you restart 10x or reload the project file.
Related to this, on a new file the save dialog filters for *.txt files. I think it should filter on all common file types: cpp, c, h, hpp, etc.

**Comment by slynch8** [comment]
fixed in (0.17.16.0)
