### ISSUE TITLE
Debugger will not start because of false positive errors

### ISSUE THREAD

**Issue by urosidoki** [slynch8/10x#2007]
After building a VS solution, the output sometimes detects some errors that are actually just warnings. Causing the Debugger to not start after pressing F5

![imagen](https://github.com/slynch8/10x/assets/8173322/bc4c93f1-9a38-4d75-9202-7b64a3570f07)
![imagen](https://github.com/slynch8/10x/assets/8173322/b9597d28-cca9-4cd7-b247-4fa9bbe4611d)

**Comment by slynch8** [comment]
I've tried this but I can't get it to happen:
`test.lib(error.obj) : warning LNK4099: PDB something test.pdb was not found`

Could you give more of the line? You can change the name of the files.

**Comment by urosidoki** [comment]
Awesome.
Thanks for looking into it.

**Comment by slynch8** [comment]
fixed (1.0.74)
