### ISSUE TITLE
Crash when deleting files from 10x workspace

### ISSUE THREAD

**Issue by manicombinostics** [slynch8/10x#2016]
10x crashed when I deleted 2 files from my workspace.

Steps:
- Select 2 files from Workspace Tree
- Right-click and select Delete
- The files are deleted correctly (Windows notifications for file deletion popping up) but crash happens after the second file is deleted.

Deleting a single file doesn't cause a crash.

**Comment by slynch8** [comment]
fixed (1.0.74)
