### ISSUE TITLE
Parser fails on classes that implement pointer indirection in the base class

### ISSUE THREAD

**Issue by aemsle** [slynch8/10x#2017]
When trying to access the base type of a templated class that inherits from a templated pointer wrapper, the parser fails to recognize symbols from the base type.  

10x Behavior:
![msedge_ugchR1ZDjE](https://github.com/slynch8/10x/assets/44575716/08f7acf1-c989-47c1-b2a1-606be9437bf1)

VA+VAX Behavior: 
![devenv_FbJW9RI79r](https://github.com/slynch8/10x/assets/44575716/c74b3f6b-97a7-4073-b4a5-2d95407bfe59)

I've included an example solution if my explanation wasn't clear enough. 

[BugSLN.zip](https://github.com/slynch8/10x/files/12419913/BugSLN.zip)

**Comment by MohitSethi99** [comment]
It also happens with non-templated types as well.

**Comment by slynch8** [comment]
fixed (1.0.82)
