### ISSUE TITLE
Tracking Changes.

### ISSUE THREAD

**Issue by lineagedr** [slynch8/10x#2035]
Is tracking changes implemented? If so how can I enable it?

It's the green line that tracks the current changes you've made like in Visual Studio.
![image](https://github.com/slynch8/10x/assets/12139798/444b1dbe-2c77-4024-ab2e-224612e4dbc5)

**Comment by slynch8** [comment]
not yet, but there is already a feature request for it https://github.com/slynch8/10x/issues/365
