### ISSUE TITLE
slow python execution

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#2036]
simple script, locking up editor for 2 seconds or so upon save (triggering).

`def TrimLines(fn):
    N10X.Editor.PushUndoGroup()

    line_count = N10X.Editor.GetLineCount()

    for i in range(line_count):
        line = N10X.Editor.GetLine(i)
        line = line.rstrip()
        N10X.Editor.SetLine(i, line)

    N10X.Editor.PopUndoGroup()
N10X.Editor.AddPreFileSaveFunction(TrimLines)`

disabling the AddPreFileSaveFunction call "fixes" it.

**Comment by datgame** [comment]
maybe if there's an api to get the whole file in one call and write it back in 1 call, the FFI overhead could be overcome.
if at least for profiling.

**Comment by slynch8** [comment]
I've added `EndTextUpdate()` and `EndTextUpdate()`. If you wrap it like this it will fast
```python
def TrimLines(fn):
    N10X.Editor.PushUndoGroup()
    N10X.Editor.BeginTextUpdate()

    line_count = N10X.Editor.GetLineCount()

    for i in range(line_count):
        line = N10X.Editor.GetLine(i)
        line = line.rstrip()
        N10X.Editor.SetLine(i, line)

    N10X.Editor.EndTextUpdate()
    N10X.Editor.PopUndoGroup()
```

(1.0.74)

**Comment by slynch8** [comment]
I also made `SetLine()` do nothing if the line is the same
