### ISSUE TITLE
RemedyBG

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#2045]
This is more a feature request. 10xeditor is awesome and I'm using it half part time at work. Half time just because when I have to debug, I'm back to visual studio. I installed RemedyBG and it looks promising. 
I saw there is some .py script to use RemedyBG with 10x. It needs to install some other python component, follow some guidelines etc. My feature request: debugger is the only missing keyfeature for 10x. 
Is it possible to make RemedyBG integration a native thing? Like you have Perforce native support, it would be awesome to press F5 and boom, RemedyBG is launched, opening the right session with all openened files in 10x open in remedyBG, ready to debug.

Is that on the roadmap?
Thanks!

**Comment by slynch8** [comment]
I do want to look into a debugger at some point, and I might do what you say and integrate Remedy.

But to use the script all you have to do is add `RemedyBG.Hook: true` to your settings. You shouldn't have to install anything else. If you're having problems you can ask on the RemedyBG discord channel.

**Comment by arnaud-carre** [comment]
the webpage (https://github.com/slynch8/10x/tree/main/PythonScripts/RemedyBG) says I need to install both "requests" and "BeautifulSoup4" . then it talks about "Itch.io Login Cookie" that I don't even know what it means. 
I know you're looking at doing an integrated debugger (that is funny to code!) but having native RemedyBG integration without all these fancy python handmade instlal would be awesome!

**Comment by slynch8** [comment]
That's only for the updater. You don't need that.
