### ISSUE TITLE
UI bug - autocomplete window

### ISSUE THREAD

**Issue by krupitskas** [slynch8/10x#2070]
![image](https://github.com/slynch8/10x/assets/5683877/4a654577-bd14-40a9-bf16-61c3e13872f3)

Autocomplete window is very small and not allows me to traverse with arrows down and up
However I can grab mouse and scroll for more autocomplete suggestions

**Comment by slynch8** [comment]
can you check your `AutocompleteCount` setting

**Comment by krupitskas** [comment]
Oh yeah, it was completely missing. The problem is that I have a github to store my setting and I think its a new setting, which was overrided on my new machine after fetching github settings. Does it make sense to check if setting is not exist and add it automatically to the setting file?

**Comment by slynch8** [comment]
When you update to a new build it should add any new settings automatically.
