### ISSUE TITLE
Feature Request - GetVisibleText

### ISSUE THREAD

**Issue by krupitskas** [slynch8/10x#2086]
Hi!
Im currently starting to work on a plugin something similar to AceJump, where you can press a hotkey and start typing word, then cursor jumps to that position.
Problem that I cant distinguish visible text on a screen.
I've found only `GetVisibleLineCount` to work with something visible.
Basically I need at least a function to get first visible line in the opened editor, so I can get the first line and then search through `GetVisibleLineCount`

**Comment by slynch8** [comment]
I think `GetScrollLine()` should give you that
