### ISSUE TITLE
Crash on 10x_notepad at launch.

### ISSUE THREAD

**Issue by Jonazan2** [slynch8/10x#2112]
When openning 10x_notepad I get this crash. It is 100% repro, I can't no longer open 10x_notepad. I am on the latest version of 10x as of the writting of this bug.
[10x_crash_2023_9_19_11_26_27.dmp.zip](https://github.com/slynch8/10x/files/12658136/10x_crash_2023_9_19_11_26_27.dmp.zip)

**Comment by slynch8** [comment]
Could you send the original .gz file? Unfortunately unzipping with the wrong tool seems to corrupt the dmp file

**Comment by slynch8** [comment]
Also, to get around it, try closing 10x and renaming your %appdata%\10x folder. This will reset everything to default.

**Comment by Jonazan2** [comment]
Github isn't allowing me to submit directly the gzip file. So I zip it and also submitted here just in case: https://we.tl/t-stoBiKmKJn. Please let me know if I can help you in any way or form. Thanks!

[10x_crash_2023_9_20_11_28_42.dmp.gzip.zip](https://github.com/slynch8/10x/files/12726624/10x_crash_2023_9_20_11_28_42.dmp.gzip.zip)

**Comment by slynch8** [comment]
Thanks for the crash dump. Looks like it's related to restoring unsaved files. To get around it try renaming your `UnsavedFiles` directory in `%appdata%\10x\Workspaces\Default_notepad_f2419ad`

**Comment by slynch8** [comment]
fixed (1.0.81)
