### ISSUE TITLE
Add flag to hide Perforce in context menu

### ISSUE THREAD

**Issue by forrestthewoods** [slynch8/10x#2127]
I don't use Perforce and therefore don't want to see Perforce commands in context menus. It's pure noise.

A settings bool to hide them would be satisfactory. Bonus points if Perforce can be auto-detected.

**Comment by mauriziodepascale** [comment]
+1

**Comment by MohitSethi99** [comment]
It is already there:

Settings > Local Settings
`PerforceEnabled:          false`

It removes perforce options from context menu but not from Menu Bar > Tools and to be honest this one doesn't even bother me.

**Comment by forrestthewoods** [comment]
Feature wasn't there originally. Was added after request. Closing issue.
