### ISSUE TITLE
buffers with no backing file show up in ctrl-p but cant be selected

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#2134]
repro:
`ctrl+n`
and type:
```
apa
sdsd

```
`ctrl-p apa` and press enter
![image](https://github.com/slynch8/10x/assets/1130152/ae665f9e-57dc-46e1-b54d-71ae6a489bf7)

it's great that they show up. and i use the first line to suggest what filename i want when i'm about to save it.
(however, separate issue, it suggests a bad folder when saving, not the previous one i visited https://github.com/slynch8/10x/issues/1852 )

**Comment by slynch8** [comment]
what do you have ctrl-P mapped to?

**Comment by datgame** [comment]
Control P:            FindFile

**Comment by slynch8** [comment]
fixed (1.0.81)
