### ISSUE TITLE
feature request: right click taskbar icon -> "New empty workspace"

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#2140]
from discussion:

> is there a way to start a 2nd instance of 10x without opening the most recent workspace, and instead get an empty editor?
i'd like to rightclick the running 10x taskbar icon and do it. 

there's OpenLastWorkspaceOnStartup but sometimes i want to open a 2nd window. i'd have to edit the settings file i guess, then edit it back after i've opened the 2nd

example: Chrome's right click menu in the taskbar has an entry for "New Window" and "New Incognito Window".

**Comment by slynch8** [comment]
I've had a look but I can't find out how to add items to the task bar menu. If you can find out how I'd be happy to add it.

**Comment by datgame** [comment]
(i got some help)
[https://learn.microsoft.com/en-us/windows/win32/shell/taskbar-extensions#customizing-jump-lists](https://learn.microsoft.com/en-us/windows/win32/shell/taskbar-extensions#customizing-jump-lists)

> The last page is the one you want, it has an overview of all APIs you need, because of course it's split over half a dozen classes
> I.e. what you want is in ICustomDestinationList

also see [https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-addtab](https://learn.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-itaskbarlist-addtab)
