### ISSUE TITLE
Running application didn't work

### ISSUE THREAD

**Issue by askebv** [slynch8/10x#2154]
I had never used `Start Debugger (F5)` from 10x up until then (and I've neither tried it as of writing), only `Run (Ctrl+F5)`. I had not yet figured out that `Run Command` and `Debug Command` are what's linked to those aforementioned 10x commands. I had tried putting the executable into `Run Command` but it didn't launch - but I had never tried putting anything into `Debug Command`.
Then I tried putting the exe path into both `Debug Command` and `Run Command`, and then it launched when I hit `Run`. Removing `Debug Command` but keeping `Run Command` now had it working as intended.
I tried closing 10x and opening it again, to see if I could reproduce it, but I couldn't. Perhaps if you reinstalled it and did the same thing.
These were my settings at the time, if that helps.
[Settings.zip](https://github.com/slynch8/10x/files/12912587/Settings.zip)

Details of my confusing journey:
https://discord.com/channels/732150926810546186/1090588002058772540/1163109643741052968

**Comment by slynch8** [comment]
I've been unable to reproduce this. The Run and Debug command should be totally separate, you should only need to set the Run command and Run working directory settings (see discord discussion).
