### ISSUE TITLE
Changing UIFont changed the editor font

### ISSUE THREAD

**Issue by askebv** [slynch8/10x#2155]
In 10x, I changed the `UIFont` (I don't recall if I saved but I think so) and then it immediately changed both the font size and the editor font. It may have been related to me having both 10x and 10xNotepad open with different settings.
Changing the `EditorFontSize` refreshed the font and size for the editor back to be equal to `EditorFont`. I could not reproduce it, unfortunately. But another thing I'll add is that I had both `EditorFont` and `UIFont` as `Cascadia Code Roman` at the time. And 10xNotepad had `Segoe UI` in `UIFont` and `Cascadia Code Roman`.

**Comment by slynch8** [comment]
fixed (1.0.82)
