### ISSUE TITLE
Double-clicking text-pane divider could centre it

### ISSUE THREAD

**Issue by cdmaczane** [slynch8/10x#2167]
This is something I got used to with Sublime Text. Currently I have to change the column count to 1 through the menu and then change it back to 2 in order to put it back to the centre. I realise this is a minor issue, but I am a bit obsessive and it would be nice to have. Sorry if this has been asked already. I scanned most of the issues but may have missed it.

**Comment by cdmaczane** [comment]
Extra points for a keyboard shortcut.

**Comment by slynch8** [comment]
fixed
