### ISSUE TITLE
Ignore directories after converting file workspace to proper workspace

### ISSUE THREAD

**Issue by cdmaczane** [slynch8/10x#2171]
Is there a way to ingore .git directory? Many files within that directory are showing up in file searches and I haven't found a way to disable it.

**Comment by slynch8** [comment]
you can add an exclude filter in the workspace settings:
![image](https://github.com/slynch8/10x/assets/7141856/c3c6b48b-a319-4ca8-973c-04031472466c)

**Comment by cdmaczane** [comment]
Yep, that did it.
