### ISSUE TITLE
Moving focus to workspace tree to select a new file

### ISSUE THREAD

**Issue by cdmaczane** [slynch8/10x#2172]
When I use a keyboard shortcut to open the workspace panel I'd like to be able to use arrow keys to move up and down to select a new file and press enter to open the selected file. Right and left could open and close directories in the tree view. Please let me know if there is a way to do this already that I haven't found.

**Comment by slynch8** [comment]
fixed (1.0.89)

**Comment by cdmaczane** [comment]
Thanks for that. Would it be possible to put focus back on the pane that had focus before the workspace tree was opened?

**Comment by slynch8** [comment]
Is control+Tab ok, can I close this issue?

**Comment by cdmaczane** [comment]
I can live with it, but I think I would prefer the focus to return to where it was before the workspace tree was opened. Is there a downside to that behaviour?

**Comment by slynch8** [comment]
But I thought the original bug was that you wanted the workspace tree to get focus so that you could use the arrow keys to select files?

**Comment by cdmaczane** [comment]
Yes, sorry. That feature has been implemented. I'll submit another request for the extra functionality to put focus back to the pane that previously had focused when the workspace view is closed. Whether you decide to implement it or not is up to you. It isn't super-important.
