### ISSUE TITLE
no error reporting when compiling hlsl shader

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#2175]
I have a .sln project that contains both c++ files and hlsl shader files. I introduced an error in the shader hlsl file on purpose. I can spot the error when building under visual studio:

```
1>------ Build started: Project: abc2, Configuration: Release x64 ------
1>X:\leonard\Tools\abc2\SinglePalCompute.hlsl(69,2-4): error X3000: unrecognized identifier 'foo'
1>
1>compilation failed; no code produced
1>Done building project "abc2.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Now if I load this .sln in 10x and compile, it doesn't catch the error in the hlsl file. 10x output looks quite different from visual studio:

```
----- Building File SinglePalCompute.hlsl Release x64 -----
Executing build command:
msbuild /t:ClCompile /p:SelectedFiles="SinglePalCompute.hlsl" /p:Configuration="Release" /p:Platform="x64" /p:SolutionDir="X:/leonard/Tools/abc2/" /verbosity:minimal "X:/leonard/Tools/abc2/abc2.vcxproj"
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

===== Success : 0 errors, 0 warnings =====
```

Any idea?

**Comment by slynch8** [comment]
I think it's because it doesn't parse the 2-4 in the error line. There's already bug about that somewhere.

**Comment by arnaud-carre** [comment]
Probably it doesn't parse but it doesn't output the lines also

**Comment by slynch8** [comment]
It looks like you're doing a BuildFile? Maybe the syntax of the msbuild command is wrong, although it works for C++ files. If you can work out the correct msbuild command line I can change it in 10x. Or if you can create a test project that shows this I'll take a look.

**Comment by arnaud-carre** [comment]
good news: I just updated to 1.0.86 and the bug seems to be fixed! ( now it properly display hlsl compilation error in build window
