### ISSUE TITLE
"10x.exe filename.txt" doesn't open the file. 

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#2187]
however works with 10x_notepad.exe

**Comment by slynch8** [comment]
fixed (1.0.89)

**Comment by datgame** [comment]
It works with absolute paths, but not relative. i.e.
`D:\apps\10x\10x.exe CMakeLists.txt`  doesn't work., but 
`D:\apps\10x\10x.exe d:\dev\repo\CMakeLists.txt`  works

**Comment by slynch8** [comment]
fixed (1.0.97)
