### ISSUE TITLE
"New Instance" should do "New Empty Workspace", not open the previous one.

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#2188]
taskbar extension thingie. 
![image](https://github.com/slynch8/10x/assets/1130152/14261f36-c074-4194-b5d7-0fa9a4638828)

maybe rename it too, to be clear that it's an empty instance/workspace.

**Comment by datgame** [comment]
not fixed in 10.0.88

**Comment by slynch8** [comment]
fixed (1.0.89)
