### ISSUE TITLE
feature req: visual feedback when 10x is in a debug session

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#2199]
I'm using 10x with RemedyBG debugger, great combo! Often I have several 10x editors open. When in 10x, it's almost impossible to know if you're in a remedybg session or not. ( and even pressing shift-f5 doesn't give you any feedback ).

It would be great that let's say the first top 10x menu line could have like red background if you're attached to remedybg debugger.

thanks!

**Comment by vulcan-dev** [comment]
I think this is where it would be nice to expose some of the UI functionality to the Python API. Sure, he can do it in C++, but I don't see the point in that. We need some UI functions anyway, so might as well add that and then do this

**Comment by arnaud-carre** [comment]
> I think this is where it would be nice to expose some of the UI functionality to the Python API. Sure, he can do it in C++, but I don't see the point in that. We need some UI functions anyway, so might as well add that and then do this

Agree. But to me as far as 10x doesn't include a debugger, I would also prefer to have RemedyBG as first class citizen debugger. Like, 10x automatically detect RemedyBG somehow and natively support it. ( I don't like having to setup some python paths and vars in all my machines to support RemedyBG ). 
10x already natively support Perforce natively. I wish it also supports RemedyBG natively. But that's different topic from this ticket.

**Comment by slynch8** [comment]
The status bar now changes colour when the debugger is active
