### ISSUE TITLE
Launching an external process using a keyboard shortcut with Shift in it

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#22]
I launch external processes using keyboard shortcuts like Ctrl + Shift + B
The process takes a few seconds, but when focus returns to 10x, if I click anywhere on the file, it acts as though Shift is held down and selects everything. I have to alt-tab away and back again to fix it. I run these external processes a lot so this is a big irritation for me.

Whilst trying to make a repro case, I've found that it does not happen if I use a keyboard shortcut that does not have shift in it. So it seems like a case of 10x storing the shift down, but not registering the shift up as the shortcut executes.

Here is a way to reproduce. Save this code to test.bat:
```
echo Building
ping www.google.com
echo Done
```

Then create a python script:
```python
def Test():
	N10X.Editor.SaveAll()
	N10X.Editor.ClearBuildOutput()
	N10X.Editor.ShowBuildOutput()
	result = run(["C:\\test.bat"], stdout=PIPE, stderr=PIPE, universal_newlines=True, shell=False)
	N10X.Editor.LogToBuildOutput( result.stdout );
	N10X.Editor.LogToBuildOutput( result.stderr );
```

Assign Test() to Control Shift T.

In an open file, position your cursor in some text, then do Ctrl+Shift+T. When the process completes click anywhere else in the file. The region will be selected and will continue to select everything until you either alt-tab or (I just discovered) press and release shift.

**Comment by slynch8** [comment]
Thanks for the repro. Fixed in (0.20.2.0). For some reason when a sub-process is started like that I don't get a WM_KILLFOCUS message. I've worked around it by resetting the shift flag when it re-gains focus.
