### ISSUE TITLE
[Feature Request] Go to file at line number

### ISSUE THREAD

**Issue by NicoM1** [slynch8/10x#2201]
Hello,

In VS Code I often use the go-to-file dialog to go to a file at a specific location.

Pasting in either of these:

Test.cpp(102) 
Test.cpp:102

Will open the file Test.cpp at line 102, which is really handy for copy-pasting out of external error messages.

I'd love if the "Find File" dialog in 10x could support this same syntax.

Thanks!
Nico.

**Comment by slynch8** [comment]
Hello,

Are you referring to the FindFile panel? separating with : does work

![image](https://github.com/slynch8/10x/assets/7141856/3f1fd180-16cb-435f-ae8e-db7a85cd632f)

**Comment by slynch8** [comment]
oh I see, it doesn't work for full paths

**Comment by NicoM1** [comment]
Ah, separating with ":" is nice, but yeah full paths would be an improvement.

Also in the build system I use, the error paths often use File.cpp(102), which VS Code supports, would be handy if 10x could support that as well. Otherwise manually editing the paths isn't any faster than just ctrl-p followed by ctrl-g to go direct to the line.

Thanks for the quick response!
Nico.

**Comment by slynch8** [comment]
done (1.0.89)

**Comment by NicoM1** [comment]
I'm getting a weird issue now where using either the () or : syntax is trying to load files from the PureDev path instead of the local folder path:

Here I typed "test.cpp:108"

![image](https://github.com/slynch8/10x/assets/6273562/4e795bb7-9006-4f50-859b-85ce8e251ffd)

**Comment by slynch8** [comment]
Is test.cpp in your workspace?

**Comment by NicoM1** [comment]
Yes, and the path is shown correctly before I press Enter:

![image](https://github.com/slynch8/10x/assets/6273562/e92c91c2-2b92-4ce5-96fe-eff4b4c0ccc9)

**Comment by slynch8** [comment]
I see. Only seems to happen for sln workspaces. I'll get this fixed in the next build.

**Comment by NicoM1** [comment]
Interesting, I'm not in a sln workspace (though there's probably a .sln file somewhere in my workspace, but I haven't opened it).

**Comment by slynch8** [comment]
Weird, now I can't get it at all. Seems random for me.

**Comment by slynch8** [comment]
Ignore that, I've got it

**Comment by slynch8** [comment]
fixed (1.0.97)

**Comment by NicoM1** [comment]
Thanks! Working for me :)
