### ISSUE TITLE
can't see constant value in tooltip

### ISSUE THREAD

**Issue by arnaud-carre** [slynch8/10x#2202]
I'm used to declare all constants in my code like this:

static	const	int		HOBS_COUNT = 2;

In 10x when I move the mouse over one constant use like

`	if (i >= HOBS_COUNT)			// don't render HOBS (coming first)
`
tooltip is only showing:

`static	const	int		HOBS_COUNT`

Like it displays everything except the important numerical value

**Comment by arnaud-carre** [comment]
any update on this one? ( working on a big c++ project plenty of that kind of static const int )

**Comment by slynch8** [comment]
ok, I'll look at this next

**Comment by slynch8** [comment]
fixed (1.0.177)

**Comment by arnaud-carre** [comment]
that's great, however it's only fixed for integer values, but not for strings :( Like:

static const char*	kWndSongInfo = "Song Info";

just display 

static const char*	kWndSongInfo = "

**Comment by slynch8** [comment]
fixed (1.0.189)
