### ISSUE TITLE
show breakpoints in map scroll bar

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#221]

**Comment by JeanGeffroy** [comment]
I'm bumping this one since this is actually one of the things that our team is missing the most with 10x compared to VS. Having breakpoints (and even more importantly, bookmarks) showing up in the scroll bar would really be invaluable when working on large files. I thought we had already created a ticket for this a while ago but couldn't find it, and I just discovered this one today.

**Comment by slynch8** [comment]
Does anyone know how the changes marker should work? Is it the changes since the file was opened, or changes from the checked in file or something else? I just tried it in VS but it doesn't seem to be working.

**Comment by id-bogdan-coroi** [comment]
VS 2022 (without VAX) tracks changes since the file was opened. I think this should be enough, no need to track source control changes or anything of that nature.

**Comment by slynch8** [comment]
This is in early access build (1.0.238)

**Comment by JeanGeffroy** [comment]
This is amazing, thanks a lot! I noticed a tiny bit of glitching when initially turning on the setting on either of the three new properties (the scrollbar shrunk to a few pixels) but turning it off and on again solved it and it's now working great.

**Comment by id-bogdan-coroi** [comment]
Loving it, thank you! Confirming also the glitch Jean is seeing.

**Comment by slynch8** [comment]
I can't get the glitch to happen. Is this with the Standard or Map scroll bar?

**Comment by JeanGeffroy** [comment]
That was with the Map mode. Upon a bit more testing, it looks like specifically changing ShowUpdatedLinesInScrollBar the scrollbar width will often shrink. This can happpen when changing the value to true or false. Updating any other property in the settings file after that (even completely unrelated properties, such as ColumnGap) will restore it to the correct size.

**Comment by slynch8** [comment]
The scroll bar will increase the width when the setting is disabled, which causes it to re-render. Is this what you're seeing?

![glitch](https://github.com/user-attachments/assets/4b7aff7a-96c7-4ccb-b665-e4b5214680f9)

**Comment by JeanGeffroy** [comment]
No, I am seeing the following sequence of operations. When changing the setting from true to False, the map width shrinks. When changing it back to true, it increases very slightly. When changing any other setting (like this unrelated ColumnGap property), it goes back to the standard size defined by MapScrollBarWidth.
![image](https://github.com/user-attachments/assets/a5f7cde0-80e2-4d51-83e8-aff2f20c7c93)
![image](https://github.com/user-attachments/assets/47281271-1f41-4276-a350-e5947202a462)
![image](https://github.com/user-attachments/assets/135fdb63-dcb0-48e2-ab9e-b1ebca0ce6de)
![image](https://github.com/user-attachments/assets/6f8d9e5f-c658-4163-86d4-43089cfdc9c0)

**Comment by slynch8** [comment]
I still can't get it, can you send me your settings file

**Comment by JeanGeffroy** [comment]
Sure thing, here's my settings file.
[Settings.zip](https://github.com/user-attachments/files/17817023/Settings.zip)

**Comment by JeanGeffroy** [comment]
The new build appears to fix the issue indeed. Thanks!

**Comment by slynch8** [comment]
dpone (1.0.249)

**Comment by id-bogdan-coroi** [comment]
I noticed this a while ago, but it looks like 'ShowUpdatedLinesInScrollBar' is not working as intended. It never retains the change in the scrollbar. Is there a new setting that I need to turn on alongside it?
