### ISSUE TITLE
Bug : [Escape] key needs to be pressed twice in vim mode

### ISSUE THREAD

**Issue by JPBarrick** [slynch8/10x#2211]
If a popup, such as auto-complete is visible, hitting [Escape] will cancel the popup, but the editor remains in Insert mode.

I see that this was potentially fixed in 1.0.0.64: https://discord.com/channels/732150926810546186/1092852325154050130/1138054338879701094

If it was the same issue, then it persists in 1.0.88.

**Comment by SimpsonGSD** [comment]
Should be fixed in 1.0.203, consider closing.

**Comment by slynch8** [comment]
fixed (1.0.203)
