### ISSUE TITLE
10X Crash After Launching into UE Solution After Updating to 10.0.91

### ISSUE THREAD

**Issue by emanuelpm** [slynch8/10x#2238]
Hello!

I updated this morning to 10.0.91 and then launched 10X right into my Unreal project.  10X then crashed within a few seconds of load.  When it relaunched, it started parsing the whole solution again, but was able to complete without issue and is now running fine.

I uploaded the dump in case it proves useful.  Other than the minor annoyance of having to re-parse the massive solution, it didn't cause any issues.

Thanks!

**Comment by slynch8** [comment]
Hello,
That's good to know that it came back after restarting. I have a feeling that it was bad data left over from the previous build.
And thanks for the note.

**Comment by slynch8** [comment]
hopefully fixed now
