### ISSUE TITLE
preserve symbol references panel dimensions

### ISSUE THREAD

**Issue by paul2t** [slynch8/10x#2247]
Each time I open the symbol references, the dimensions are reset to the default ones.
Is it possible to preserve the dimensions and position of this panel ?
It is only restore correctly if it is docked. Then I can close it and it will open at the same position the next time.

**Comment by slynch8** [comment]
This isn't happening for me. Is it the dimensions or the position? It will center it when it opens.

**Comment by paul2t** [comment]
Ok I understand that the panel is centered, that's ok.
But I do have the issue for the dimensions of the panel.
It doesn't do it for the Workspace Search panel, for which, the dimensions are preserved.
Only the Find File and Symbol References panels are reset to the default dimensions.

**Comment by slynch8** [comment]
I still can't get it. 

Just to check we're talking about the same thing, is this what you're doing?
![findrefssize](https://github.com/slynch8/10x/assets/7141856/4a1eff43-db62-4b03-b12f-fe821a846139)

**Comment by paul2t** [comment]
Yes, this is the same panel. If I do the same actions as you, the size of the panel is not preserved.

**Comment by slynch8** [comment]
Are you on the latest build?

**Comment by slynch8** [comment]
I've got it. It works if you click the X button, but not if you use the open or cancel buttons.

**Comment by slynch8** [comment]
fixed (1.0.110)
