### ISSUE TITLE
10x crashes after adding new files to a solution (using VS 2022)

### ISSUE THREAD

**Issue by velaris1** [slynch8/10x#2261]
Hi,

I'm encountering the following issue:

1) Have 10x and VS 2022 open, both with the same solution loaded.
2) In VS 2022, right click on an existing filter in the solution explorer. Select "add -> Existing Item..." to add code files.
3) In VS 2022, save the solution.
4) 10x reloads automatically the workspace.
5) In 10x, try to open open any of the new files.
6) Crash.

Thanks

**Comment by slynch8** [comment]
fixed (1.0.96)
