### ISSUE TITLE
Open folder opens the directory above the one requested

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#23]
I have a folder layout:
![2021-01-07 13_27_17-Window](https://user-images.githubusercontent.com/1583441/103843554-26e55600-50ec-11eb-86cf-9ecfb29af5e7.png)

When I use Open Folder to open 10xTests/5, the workspace always shows everything from the folder above:
![2021-01-07 13_27_39-Window](https://user-images.githubusercontent.com/1583441/103843594-3a90bc80-50ec-11eb-908a-b31318391c56.png)

**Comment by slynch8** [comment]
fixed in (0.20.1.0)
