### ISSUE TITLE
Incorrect preprocessor parsing

### ISSUE THREAD

**Issue by cdmaczane** [slynch8/10x#2310]
This code is dimmed even though the code should be active. Checked that it should work using Clang on Godbolt.

![image](https://github.com/slynch8/10x/assets/26070711/7058928b-7b34-4d3f-ae96-a68f5c8f795b)

**Comment by askebv** [comment]
![image](https://github.com/slynch8/10x/assets/4981659/2ffe249d-7b09-4d2f-b873-88644d016c04)

Seems to happen a lot with starting `if`-statements at the start of `#if` blocks, from my experience

**Comment by slynch8** [comment]
@askebv is this still happening for you? I can't get it with the example above.

**Comment by slynch8** [comment]
Got it - thanks.

**Comment by slynch8** [comment]
Fixed (1.0.117)
