### ISSUE TITLE
Support Import in VS project files

### ISSUE THREAD

**Issue by kingofthebongo2008** [slynch8/10x#2312]
Hello,
Searching in files which are not in the .vcxproj file does not work.

I have cpp files which are separated in the vcxproj like this.
separate_files.msbuild

<?xml version="1.0" encoding="utf-8"?> 
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"> 

  <ItemGroup>
    <ClCompile Include="MyCpp.cpp" />
  </ItemGroup>
</Project>

and in the .vcxproj file I have
  <Import Project="separate_files.msbuild" />

This way configurations are separated and handled nicely, helps with merge requests, because these msbuild files may be generated and makes merging around easier.

This is a significant issue, i need to open every file manually

**Comment by slynch8** [comment]
Hi,
I think your report is missing some text, what do you have in the proj file?

Also, are you referring to workspace search? If so you can add folders that are not in the project in the settings:
![image](https://github.com/slynch8/10x/assets/7141856/f3569cee-aea7-4bea-b5dc-aa9df0c7f913)

**Comment by kingofthebongo2008** [comment]
<Project DefaultTargets="Build" ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"> 
  <ItemGroup>
    <ClCompile Include="pch.cpp">
      <PrecompiledHeader>Create</PrecompiledHeader>
    </ClCompile>
    <ClCompile Include="file.cpp" />
   <ItemGroup>

**Comment by kingofthebongo2008** [comment]
github removes them

**Comment by kingofthebongo2008** [comment]
<img width="648" alt="image" src="https://github.com/slynch8/10x/assets/1145201/5732c0c1-fdd0-4cb1-a754-64e60ebd044d">

**Comment by kingofthebongo2008** [comment]
<img width="593" alt="image" src="https://github.com/slynch8/10x/assets/1145201/45853b36-b253-4f00-8f2b-b2d20ed4f96f">

**Comment by kingofthebongo2008** [comment]
The idea is that the .vcxproj only holds the project options,
all files are then spread out in separate msbuild files, which are imported

**Comment by kingofthebongo2008** [comment]
This is very convenient practice by the way, one can generate separate files with a tool so if one works in a repository, there is no merge conflicts on them

**Comment by slynch8** [comment]
I see, so the problem is that Import in VS project files isn't supported.

**Comment by slynch8** [comment]
Done (1.0.117)

**Comment by kingofthebongo2008** [comment]
thank you, works
