### ISSUE TITLE
Setting breakpoint is prioritized over resizing files panel even when cursor is changed from pointer to resizer

### ISSUE THREAD

**Issue by tomaszte** [slynch8/10x#2318]
Something I noticed again today.
In video, I clicked 3 times in total.
1st and 3rd click showed resize cursor, but after click and hold breakpoint was set instead.
When file panel is focused, it works correctly (second click).

https://github.com/slynch8/10x/assets/1183196/f724d1ba-4bf4-44b5-b6cc-f6e63dbeb057

I'm dziablo on 10x discord in case of questions

**Comment by slynch8** [comment]
Is this still an issue? I can't get it.

**Comment by slynch8** [comment]
Ignore that, I've got it now

**Comment by slynch8** [comment]
fixed (1.0.115)

**Comment by slynch8** [comment]
still seems to be an issue in some cases

**Comment by slynch8** [comment]
fixed (1.0.203)
