### ISSUE TITLE
Bug: Workspace Tree auto-scrolls on mouse click after relaunch

### ISSUE THREAD

**Issue by dannye** [slynch8/10x#2325]
Mouse clicking into the Workspace Tree panel sometimes causes it to instantly scroll to the top, changing what filename is under the mouse cursor. So if I quickly double-click then I end up opening the wrong file. This appears to happen consistently when relaunching 10x if it was previously closed with the Workspace scrolled down to the bottom.

https://github.com/slynch8/10x/assets/5231310/86b01e85-b1a0-4eb4-b5f5-10e891a64243

**Comment by slynch8** [comment]
fixed (1.0.115)
