### ISSUE TITLE
10x not finding MSVC STL symbols due to incorrect _STL_LANG

### ISSUE THREAD

**Issue by aemsle** [slynch8/10x#2327]
I was using std::string_view when I noticed 10x wasn't finding the symbol. After poking around in the headers, the _STL_LANG macro is defined to 199711L due to 10x not being able to find the define for _MSVC_LANG which should override the value to 202002L for c++20. 

vcruntime.h:
    - VS:
![image](https://github.com/slynch8/10x/assets/44575716/a300af2a-68d3-4d78-bc55-32a13be04176)
    - 10x:
![image](https://github.com/slynch8/10x/assets/44575716/70cc92cd-3352-47fa-b954-f9e8e232ad5f)

this happens when using a .sln file that was generated from premake script

**Comment by slynch8** [comment]
I'll add this as a default, but for now you get get around this by adding a define in the project settings

![image](https://github.com/slynch8/10x/assets/7141856/9eec3190-0ddb-4a33-933f-f23d8e62e916)

**Comment by slynch8** [comment]
done (1.0.115)

For now I've hard coded _MSVC_LANG to 201703 until I work out how to get the value from the project

**Comment by aemsle** [comment]
<LanguageStandard>stdcpp17</LanguageStandard>

**Comment by aemsle** [comment]
From generating a basic new project from Visual studio it seems like in the vcxproj files the ```<LanguageStandard>``` tag isnt there so it defaults to c++14. But if you change the language standard to anything else the tag will appear within the ```<ClCompile>``` section e.g. ```<LanguageStandard>stdcpp17</LanguageStandard>```. That _should_ map nicely to the potential values of _MSVC_LANG/_STL_LANG

**Comment by slynch8** [comment]
Great, thanks. I'll add a new Issue.
