### ISSUE TITLE
"Force Includes" parsing breaks when switching configuration

### ISSUE THREAD

**Issue by jcl1234** [slynch8/10x#2328]
#### Steps to reproduce:
1. Create a header file and add it to the "Force Includes" section of workspace settings for all configuration & platform combinations
2. Define a symbol in this file
3. Reference this symbol in another file, notice parsing is working.
4. Switch configurations or platform. Notice parsing stops recognizing the symbol.
5. Edit "Force Includes" section (example add a gibberish entry) and hit "OK". Notice parsing works again until configuration is switched.

https://github.com/slynch8/10x/assets/21160174/8f477ce6-0abe-4d62-b645-e84c3a3412b9

**Comment by slynch8** [comment]
You need to set the value for each config/platform.

Although it's a bit weird that adding gibberish for it working. That sounds like a bug.

**Comment by slynch8** [comment]
ok, I've found a bug with this. Will be fixed in the next build. But you do still have to set it per config.

**Comment by jcl1234** [comment]
@slynch8 Got it, thanks. Just to clarify, Step 1 in the repro steps includes adding the header per-config/platform, this step just isn't shown in the attached mp4 (pch.h is already added for each config). The specific bug is that even when added per-config, the force-included file will stop parsing when **switching** to another configuration that was previously parsing the force-included file correctly, and to resolve this the `"Force includes"` setting must be modified in some way (e.g. adding a random force include and hitting OK).

**Comment by slynch8** [comment]
I see. But I still can't get it. If I add the pch to both configs switching configs works.

Maybe I've misunderstood. Here's what I'm doing:

![pch_bug](https://github.com/slynch8/10x/assets/7141856/3476cad2-5fc4-42aa-8750-e92d5a014a14)

**Comment by slynch8** [comment]
fixed(?) (1.0.115)

I've fixed _an_ issue with this, although I'm not sure if's the same as the bug you report. I wasn't able to reproduce the problem as you describe it (see gif above). Feel free to re-open if you're still getting it.

**Comment by jcl1234** [comment]
@slynch8 Hmm still seeing this issue after the latest update. I've attached a zip of the workspace I'm using to reproduce the issue (from my mp4) in case it can help, sent via the crashdump uploader on the site.

**Comment by slynch8** [comment]
Thanks for the workspace, I can repro it now.

I've got a fix, can you try this build:
https://e.pcloud.link/publink/show?code=XZC9ReZU1FRbiDKbwfgcVfj9dDugRFYt0jk

**Comment by jcl1234** [comment]
@slynch8 Using that build things look to be working correctly now!
