### ISSUE TITLE
Add an ability to get the name of the class which is in the current scope.

### ISSUE THREAD

**Issue by megamika** [slynch8/10x#2336]
Perhaps it could be done in this way as an example (pseudocode).

string ScopeName = N10X.Editor.CppParser.GetCurrentScopeName()

and depending on if you are inside of a struct or a class it would return the name, if you are outside of any scope it wouldn't return anything.

**Comment by slynch8** [comment]
done (1.0.115)

`N10X.Editor.GetCurrentScopeName()`
