### ISSUE TITLE
Hitting Enter in multiline comment deletes text and sometimes inserts something weird

### ISSUE THREAD

**Issue by askebv** [slynch8/10x#2342]
(The phantom lines are from copying the multiline comment)
![image](https://github.com/slynch8/10x/assets/4981659/01be9e22-5f9e-48e5-9462-c20dc2e09d7e)

Hitting Enter will sometimes result in this (i.e. third line is gone and replaced with differently indented line):
![image](https://github.com/slynch8/10x/assets/4981659/72d19f1e-594f-4e4c-95ea-b6194acae8ec)
Other times it has inserted parts of the clipboard and made it look weird.
And I believe it sometimes automatically changed `*/` to `* /`, although I can't reproduce it atm.

I can also get it to happen without a malformed and bracket:
![image](https://github.com/slynch8/10x/assets/4981659/b280709f-a432-481b-b5c4-97c5ba1404e3)
![image](https://github.com/slynch8/10x/assets/4981659/bc8bb4fe-5b19-4273-9913-cb4b882c59b2)
[Settings.zip](https://github.com/slynch8/10x/files/13866375/Settings.zip)
I also created a dump file right after pressing enter and the bug occurring.

**Comment by slynch8** [comment]
fixed (1.0.115)

I've fixed the issue with pressing enter with a selection running over the end of the line. Maybe that was what was causing the problems.

Feel free to re-open the issue if it's still happening.
