### ISSUE TITLE
The GotoSymbolDefinition command used to pick the symbol under the mouse cursor but not anymore

### ISSUE THREAD

**Issue by Goryh** [slynch8/10x#2344]
The GotoSymbolDefinition command could be assigned to a mouse button and it's used to open a symbol under the cursor.
This behavior is broken atm (since around 1.0.114) and opens the symbol under the current cursor position.
There is no way around to emulate the same functionality with existing commands/py-api set (almost no commands interacting with the mouse, N10X.Editor.SendKey('MouseLeftButton') doesn't work either).

**Comment by slynch8** [comment]
fixed (1.0.115)

**Comment by slynch8** [comment]
The middle mouse button should now be mapped to `GotoSymbolDefinitionUnderMouse`
