### ISSUE TITLE
[Feature Requests] Python bindings for OnWorkspaceCreated and SetWorkspaceVariable(s) GetWorkspaceVariable(s) 

### ISSUE THREAD

**Issue by Andersama** [slynch8/10x#2356]
`OnWorkspaceCreated` a binding for when a workspace is initially created, similar to and processed before `OnWorkspaceOpened`, This is potentially for future integrations which would like to modify a workspace when one is "initially" opened, but only once when the file is first created.

`SetWorkspaceVariable` and `GetWorkspaceVariable` there are a number of bindings for variables that are missing to modify workspace settings for build and debugging commands, make all of them accessible so that scripts can both read and write them.

**Comment by slynch8** [comment]
done (1.0.117)
