### ISSUE TITLE
Add debug line indicator with Title bar color change for better debugging xp

### ISSUE THREAD

**Issue by septag** [slynch8/10x#2361]
- Changing title bar color (with scripting) to orange or red,  would better indicate that we are in debugging mode
- Having an arrow or line in between the lines or next to the line number that is also scriptable would help a lot with current debugging position

**Comment by slynch8** [comment]
done (1.0.120)

**Comment by slynch8** [comment]
```
N10X.Editor.SetStatusBarColour((255,0,0))
N10X.Eeitor.ClearStatusBarColour()
N10X.Editor.SetDebuggerStepLine(filename, line_index)
```
