### ISSUE TITLE
Doesn't detect Visual Studio 2022 Preview

### ISSUE THREAD

**Issue by kjk** [slynch8/10x#2362]
I only have Visual Studio 2022 17.9.0  Preview 3.0 installed and 10x (1.0.18) doesn't detect it.

I got compilation working by setting:
```
VisualStudioEnvBat:                    "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\Tools\VsDevCmd.bat"
```
(vsars64.bat is `"C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build\vcvars64.bat"`)

Debugging doesn't work: after F5, the log says:
```
[vs-debugger] Launching Visual Studio...
[vs-debugger] "Common7/IDE/devenv.exe" "C:/Users/kjk/src/sumatrapdf/vs2022/SumatraPDF.sln"
[vs-debugger] attempting to connect to Visual Studio...
...
[vs-debugger] Error: timed out connecting to Visual Studio

```
but it fails to connect / launch.

devenv.exe is `"C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\devenv.exe"`

**Comment by slynch8** [comment]
fixed (1.0.124)
