### ISSUE TITLE
[Feature Request] Python bindings for Add/RemoveBuildConfiguration(), Add/RemovePlatform()

### ISSUE THREAD

**Issue by Andersama** [slynch8/10x#2364]
Forgot to add to #2356, should have bindings for modifying the list of builds and platforms without necessarily changing the current setting.

A bit of a design choice, if the current build or platform is being removed do you allow the removal? Does it force a change in the current selection? Might be a parameter in the call.

**Comment by slynch8** [comment]
I added it to the Get/SetWorkspaceSetting API. Pass in "Configurations" or "Platforms" and the value is a comma separated list.
In build (1.0.124)
