### ISSUE TITLE
[Bug] Debug event appears to only run build script?

### ISSUE THREAD

**Issue by Andersama** [slynch8/10x#2381]
Currently there appears to be a problem where my cmake integration script and remedybg's script only executes the build stage from the cmake integration script. However remedybg successfully runs and is able to launch the debugger from the command window. It's not clear what the issue is because past the cmake build steps running there isn't any further feedback, no apparent errors, so it's impossible to tell if there's some problem that makes it so just the build step executes, or if there's some other problem preventing further execution of the remedybg's debugger callback.

**Comment by slynch8** [comment]
If `BuildBeforeStartDebugging` is set and the build command is overridden from python the debug command doesn't get called.

**Comment by Andersama** [comment]
Ahh...well that pretty much explains it to a T.

**Comment by slynch8** [comment]
You need to let 10x know the build has finished by calling OnBuildFinished(), then the debugger will start.
Added in build (1.0.124)

**Comment by Andersama** [comment]
Alright, will update script.
