### ISSUE TITLE
Build configuration and platform cleared upon build completion

### ISSUE THREAD

**Issue by JeanGeffroy** [slynch8/10x#2392]
Since version 1.0.120, upon completion of a build, the build comfiguration and platform are cleared and have to be manually reselected in order to start another build or a debug session.

**Comment by slynch8** [comment]
It must be due to the new config/platform syncing from Visual Studio. 

I think I've got a fix, can you try this build:
https://e.pcloud.link/publink/show?code=XZ54qeZ3QcvJQ45ALkfQvu9iE8xapP8Q71V

**Comment by JeanGeffroy** [comment]
That build appears to fix it indeed, thanks for the fast turnaround!

**Comment by slynch8** [comment]
Great, I'll get a new build out. This might be affecting others as well.

**Comment by slynch8** [comment]
fixed (1.0.121)
