### ISSUE TITLE
Failed to get config and platform: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by detritivore** [slynch8/10x#2402]
10x's output log prints these messaged repeatedly.

this is with a .sln (unreal) with vs2022. 10x 1.0.123 and EditorLink 1.2

`[10xEditorLink] Connected
[vs-debugger] Error: The message filter indicated that the application is busy. (Exception from HRESULT: 0x8001010A (RPC_E_SERVERCALL_RETRYLATER))
[vs-debugger] Connected
[vs-debugger] debugger started
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] debugger stopped
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.
[vs-debugger] Failed to get config and platform: Object reference not set to an instance of an object.`

**Comment by slynch8** [comment]
fixed (1.0.124)
