### ISSUE TITLE
[Request] Add setting so that Ctrl+Shift+Right doesn't select trailing whitespace

### ISSUE THREAD

**Issue by dannye** [slynch8/10x#2407]
When the cursor is at the left edge of a word (or in the middle of the word) and I press Ctrl+Shift+Right, it selects the rest of the word plus any trailing whitespace. It would be nice if this worked more like double mouse click and only selected the rest of the word. A setting to change this behavior would be great.

**Comment by slynch8** [comment]
done (1.0.125)

**Comment by slynch8** [comment]
I made it the default way it works, so I haven't added a setting.
