### ISSUE TITLE
force included header is incorrect defined out

### ISSUE THREAD

**Issue by peewee26** [slynch8/10x#2408]
hi, i have a parser bug where a force included pch is getting defined out because 10x thinks it is being included multiple times already
(MSVC Solution Settings -> C/C++ -> Advanced -> Force Included File)
![image](https://github.com/slynch8/10x/assets/158231842/1cd8966c-3d3f-4ada-9026-5665deb3c746)

**Comment by slynch8** [comment]
Can you provide a project that shows this? I can't get it to happen.

**Comment by slynch8** [comment]
fixed (1.0.128)
