### ISSUE TITLE
preallocate space in margins for line numbers up to 9999

### ISSUE THREAD

**Issue by peewee26** [slynch8/10x#2409]
it would be nice if 10x preallocated enough space in the margins for line nums up to 9999 to prevent the issue in the gif, and also prevent having the code windows misaligned (e.g if you switch from a code panel with 99 lines to one with 100 lines, you can also see this issue, which can be annoying)

obviously, we lose some space in the code editor if we do this, but I would like it to  at least be an option since it can be quite annoying for me, but others may not mind as much and actually would love to keep the extra space
![10x_HbnNV0VSqa](https://github.com/slynch8/10x/assets/158231842/f7a82440-eca9-42c9-8562-105c7de1b1ad)

**Comment by slynch8** [comment]
done (1.0.125)

I've added a new setting `MinLineNumberWidth` which you can set to 4 (defaults to 3)
