### ISSUE TITLE
Include files without extension in search

### ISSUE THREAD

**Issue by NicoM1** [slynch8/10x#2416]
Hello,

Our build system uses "dir/sources" files, which do not have an extension but contain important text. Is there a way to make 10x include these, or other no-extension files in the default (or custom) search filter?

Thanks!
Nico.

**Comment by NicoM1** [comment]
Follow up, just noticed these files don't seem to even show in the workspace tree, is there some option that's hiding no-extension files?

**Comment by slynch8** [comment]
That's a good point. The include filter takes wildcards, and there is no way of specifying a file without an extension with a wildcard. I guess I'll have to add a checkbox for it.

**Comment by slynch8** [comment]
Are the files always named the same? If so you could just add the file name

![image](https://github.com/slynch8/10x/assets/7141856/a95eda47-3499-4f88-9464-b25305532fc4)

**Comment by NicoM1** [comment]
Hmm. This doesn't appear to be working, and I'm still not seeing the no-extension files in the workspace tree either. Maybe some setting is blocking them completely?

**Comment by slynch8** [comment]
I've added a checkbox for this in the workspace settings
fixed (1.0.128)

**Comment by NicoM1** [comment]
Thanks @slynch8, unfortunately this seems to only be working for files in the root directory, I'm not seeing no-extension files in subdirs, but I can confirm they exist.

**Comment by NicoM1** [comment]
Changing this from "*.*" to "*" does work for the workspace (I misread you previous image as being the search filter settings).

![image](https://github.com/slynch8/10x/assets/6273562/152049c2-2b1a-4c15-94d5-5a87b6692402)

But I still am not able to search-in-files across the no-extension files. And "*" doesn't seem to work there.
