### ISSUE TITLE
[BUG] Autocomplete is filled with partial identifiers

### ISSUE THREAD

**Issue by Botondar** [slynch8/10x#2419]
Here's an image showing it in action:
![image](https://github.com/slynch8/10x/assets/16489781/3950f3f5-1903-41e2-8545-5d10a6a24321)

- Reparse all (but not reparse file) fixes the issue.
- I've only noticed this with `#define`s, not sure if it affects other things as well

I don't know how to reliably trigger this behavior, but once it happens with a particular define, editing that define name further causes every (partial) variation of it to appear in the autocomplete.

Version is 1.0.124

**Comment by slynch8** [comment]
I've just tried it but I can't get it to happen. Let me know if you notice what triggers it. It's odd, this was a bug a while back, but I thought I'd fixed it.

**Comment by Botondar** [comment]
I think I've found a repro, have a file like this:
```
#define First
#define Second First
```
Editing `Second` at this point makes all variations of it appear in autocomplete.

**Comment by slynch8** [comment]
fixed (1.0.128)
