### ISSUE TITLE
[Feature Request] Auto add space between brackets.

### ISSUE THREAD

**Issue by Catddly** [slynch8/10x#2425]
It is cool to have auto space adding between brackets.

Example:
From this:
if (CanBeDamaged(giant))
{
}
To this:
if ( CanBeDamaged( giant ) )
{
}

Some kind of functionality like Visual Studio Tools->Options->Code Style->Formatting->Spacing.

It should be really helpful!

**Comment by slynch8** [comment]
I've added a new setting `SpaceBrackets` (1.0.136)
