### ISSUE TITLE
highlighted line doesn't follow goto definition

### ISSUE THREAD

**Issue by detritivore** [slynch8/10x#2434]
https://github.com/slynch8/10x/assets/15983555/5acb9400-1441-4db1-9023-9133f4b1b11b

video shows, goto-def. hightlight not following,
then normal panel switching with highlight working,
then I can't type, but eventually show got-def. not highlighting again :-D 

when goto-def. the line of the def. is not highlighted with the 'highlight line' colour.
the previously highlighted line is correctly dimmed.

maybe a conflict with the word highlighting?

**Comment by slynch8** [comment]
fixed (1.0.128)
