### ISSUE TITLE
Left-arrow incorrect behavior with selection when the cursor is at the beginning of a line

### ISSUE THREAD

**Issue by EeroMutka** [slynch8/10x#2440]
### Case 1
In the following case
![image](https://github.com/slynch8/10x/assets/16746615/052afcee-aba5-4076-a099-29087e3749bc)
, pressing left arrow brings the cursor to the previous line:
![image](https://github.com/slynch8/10x/assets/16746615/88c26992-7d76-4ee9-90ca-2349f27ecbaa)
The cursor should instead go to the beginning of the selection (beginning of line 2) like in other text editors.

### Case 2
In the following case
![image](https://github.com/slynch8/10x/assets/16746615/386fd59c-f06a-4750-afc1-9bdd159dfbaa)
, pressing left arrow does not do anything. It should go to the beginning of the line.

### Case 3
In the following case
![image](https://github.com/slynch8/10x/assets/16746615/79fac4d4-a2b6-4a9e-b7d4-d09bd7747664)
, pressing left arrow brings the cursor to the end of line 1. It should go to the beginning of line 1.
![image](https://github.com/slynch8/10x/assets/16746615/841c3d93-fe62-4e83-bf56-270a94a1f11d)

Overall, when there is a selection, left arrow should bring the cursor to the beginning of the selection, and right arrow to the end of the selection. Right now it seems like when the cursor is at the beginning of a line, then pressing left moves the cursor one step backwards and ignores the selection instead of going to the beginning of the selection.

**Comment by slynch8** [comment]
fixed (1.0.128)
