### ISSUE TITLE
Duplicates in "Find References" result window

### ISSUE THREAD

**Issue by Scr3amer** [slynch8/10x#2443]
Greetings !

Me again with a new weird bug.
I was looking for references in the source code of a UE5 project and I noticed that the results in the .cpp files were duplicates.
I tried reparsing the file and the whole project (which is a classic VS .sln as you probably know) and it didn't fix it.

I checked already existing issues and didn't find anyone mentioning it so here I am.

I am using the trial version of the latest version of the editor (1.0.126) but I saw it also in 1.0.118

Here is a screenshot of the bug:

![image](https://github.com/slynch8/10x/assets/9144188/b7a4bdb7-3e1e-46bf-84c2-55ae5f8862a1)

Cheers,
Scr3am

**Comment by Scr3amer** [comment]
Good call Sir !

I had for some reason a copy of that file elsewhere in my drive and it was present in the workspace.
But I don't understand why because the .sln (specifically the .vcxproj) contains that file only once.

**Comment by slynch8** [comment]
I think if you open a file that's not in the workspace it gets added to the parser database. Try closing the file and doing a ReparseAll.
