### ISSUE TITLE
Search is modifying Find/Replace text

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#2448]
If I do a search for "xxx", then double click a search result and open find/replace, the FIND entry is being set to "xxx" rather than retaining my last search.
This is particularly a problem if I search for "xxx IN MyProject", then open find/replace to wants to do a find for "xxx IN MyProject"

**Comment by slynch8** [comment]
Fixed (1.0.128)

I changed it so that if the search text contains keywords it won't set the find text.

I also added a `Search.SetFindText` setting so you can turn it off completely.
