### ISSUE TITLE
Option to prevent read-only files from being edited

### ISSUE THREAD

**Issue by Strewya** [slynch8/10x#2451]
When using perforce, files are usually marked as read-only unless checked out. Some (most? idk) editors prevent read-only files from being edited at all, even in memory, and i relied on this behaviour to alert me that the file i'm looking at isn't checked out, as i like to explicitly do that because it makes me more conscious of what files i'm touching.

It would be nice if there was an option in 10X that allowed for this behaviour, if possible.

**Comment by slynch8** [comment]
done (1.0.131)
