### ISSUE TITLE
[Feature Request] Highlight all capture groups

### ISSUE THREAD

**Issue by Andersama** [slynch8/10x#2469]
It appears currently that the highlighting engine uses the last capture group to highlight.

EG:
```
Language.Class:
REGEX((\[)(?:[^\]\\]+|(?:\\.)+)+(\]))
```

produces:
![image](https://github.com/slynch8/10x/assets/25020235/80eb38b2-8a42-4b71-a9db-f6f9a174f11f)

Where one might expect that both `[` and `]` would get syntax highlighting.

**Comment by Andersama** [comment]
Here's what I've appended to `10x_settings.10x_syntax` as a quick example:
```txt
Regex.Quantifier: 
REGEX(*[\*\?\+])
REGEX(+[\*\?\+])
REGEX(?[\*\?\+])
REGEX(\{[0-9]+,[0-9]*\}[*?+]?)
REGEX(\{[0-9]*\}[*?+]?)
TEXT(*)
TEXT(+)
TEXT(?)

Regex.Range:
REGEX((?:(?:\\x[0-9a-fA-F]{2})|(?:\\u[0-9a-fA-F]{4})|(?:\\u\{[0-9a-fA-F]{4}\})|(?:\\c[A-Z])|(?:\\[0-7]{0,3})|(?:\\[^\n\rb])|.)-(?:(?:\\x[0-9a-fA-F]{2})|(?:\\u[0-9a-fA-F]{4})|(?:\\u\{[0-9a-fA-F]{4}\})|(?:\\c[A-Z])|(?:\\[0-7]{0,3})|(?:\\[^\n\rb])|.))

Regex.Escape:
REGEX(\\x[0-9a-fA-F][0-9a-fA-F])
REGEX(\\u[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F])
REGEX(\\u\{[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]\})
REGEX(\\c[A-Z])
REGEX(\\[0-7][0-7][0-7])

Regex.NegatedClass:
REGEX((\[^)(?:[^\]\\]+|(?:\\.)+)*(\]))

Regex.Class:
REGEX((\[)(?:[^\]\\]+|(?:\\.)+)+(\]))
REGEX(\\[wWsSdD])

Regex.Anchor:
REGEX(\\b)

Regex.Escape:
REGEX(\\.)

Regex.NonCaptureGroup:
REGEX((\(\?:)(?:[^\)\\]+|(?:\\.)+)*(\)))

Regex.CaptureGroup:
REGEX((\()(?:[^\)\\]+|(?:\\.)+)*(\)))

Regex.Anchor:
REGEX([$^])
```
Then in `Sunset.10x_settings`:
```txt
# Regex expressions
Regex.Quantifier:                                 114, 216, 220

Regex.NonCaptureGroup:                            172, 211, 95

Regex.NamedCaptureGroup:                          172, 211, 95

Regex.CaptureGroup:                               111, 216, 91

Regex.NegatedClass:                               214, 97, 216

Regex.Class:                                      255, 140, 0 

Regex.Anchor:                                     172, 211, 95

Regex.Range:                                      154, 197, 209

Regex.Escape:                                     255, 211, 112

Regex.Expression:                                 default

Regex.Character:                                  default
```
The colors are from the `Language.Custom` set of colors.

**Comment by slynch8** [comment]
I've just tried this and it's not highlighting anything in the REGEX(). Although it works if I remove the REGEX(. Is this working for you?
![image](https://github.com/slynch8/10x/assets/7141856/ceb6ba38-07af-444d-8d70-4535e6a2a3bc)

**Comment by slynch8** [comment]
I think misunderstood want you're asking, I thought you meant support for multiple capture groups in a single regex, but you want the results for both REGEX statements?

I managed to add support for multiple capture groups per regex, but I'm not sure if that is useful now.

Adding groups both REGEX statements is tricky because I don't current store that grouping anywhere. I just have a list of all rules and their colour mapping.

I wonder if it could be done using multiple capture groups in a single regex.

**Comment by slynch8** [comment]
Ok, so removing the Language.String entry for REGEX makes it parse the regex's as regex

![image](https://github.com/slynch8/10x/assets/7141856/bf293d4d-fb59-4d65-a67c-cb79b63d2b2c)

I think it might almost be working, I'm not sure, maybe you can work it out?

<img width="482" alt="image" src="https://github.com/slynch8/10x/assets/7141856/4288d48a-10b7-4bda-8613-d908cc2d27ef">

I'm not sure parsing regex's with regex's is ever going to work properly though? I thought this would be a simple fix but it's blowing my mind  🤯 😂

**Comment by slynch8** [comment]
ok, reading back through this bug, it does appear that you were asking for multiple capture groups per single regex after all (sorry, your changes to 10x_settings.10x_syntax confused me). The original example you gave does now work (sort of, apart from the escaped `\[`).

![image](https://github.com/slynch8/10x/assets/7141856/e79ff672-96ba-4db9-8c27-d6c7c6f736d3)

**Comment by slynch8** [comment]
It now highlights all capture groups (1.0.146)

**Comment by Andersama** [comment]
Sorry I've been distracted with other things, let me check.
