### ISSUE TITLE
'symbol search' makes up filenames (alternating cases)

### ISSUE THREAD

**Issue by detritivore** [slynch8/10x#2485]
when using symbol search, results shown have filenames that sometimes use all lowercase, sometimes the (correct) mixed case of the files on disk.

![2024-03-01_10-34-47_10x](https://github.com/slynch8/10x/assets/15983555/5fa3b85d-f300-4d18-b5b5-66001d692085)

**Comment by slynch8** [comment]
fixed (1.0.136)
