### ISSUE TITLE
Can't find the symbol references if it was defined by macro

### ISSUE THREAD

**Issue by dawnarc** [slynch8/10x#2495]
10x editor can't find function `CalculateRigLogic` references in Unreal Engine 5 source code.

![2024 03 05_王爱国 11d82db29026f1763cad09ce79e7137d](https://github.com/slynch8/10x/assets/3351764/216db1dd-87bf-46a9-8b4e-cef7a33b8838)

But Visual Studio works right:

![2024 03 05_王爱国 b8ce9144590a326f4f4b3d590e5f8a09](https://github.com/slynch8/10x/assets/3351764/b6584a13-6f73-43e3-a0bf-de60d39a6f3f)
![2024 03 05_王爱国 332f374776f2333635ef81de19541bcf](https://github.com/slynch8/10x/assets/3351764/09f1933e-c988-43e3-adc2-1481a38b0b35)
![image](https://github.com/slynch8/10x/assets/3351764/e2cb37b3-b047-46d5-b1ea-5b3ea7715d06)

I guess that because the reference was in the function that was defined using macro: `FRigUnit_RigLogic_Execute()`

**Comment by slynch8** [comment]
It seems to be because FRigUnit_RigLogic_Execute isn't defined. I can't find it anywhere in the codebase, where should it be?

![image](https://github.com/slynch8/10x/assets/7141856/7c97bc7a-70cd-4f39-8205-3de1156f4a08)

**Comment by dawnarc** [comment]
![image](https://github.com/slynch8/10x/assets/3351764/cd0e0d77-9ede-49d0-aea8-87b2e7c8eefb)

![image](https://github.com/slynch8/10x/assets/3351764/465db43e-9bc5-426f-b04e-2e968d3d5797)

@slynch8 `FRigUnit_RigLogic_Execute`  is in the generated source file, loc:    
Engine\Plugins\Animation\RigLogic\Intermediate\Build\Win64\UnrealEditor\Inc\RigLogicModule\UHT\RigUnit_RigLogic.generated.h

**Comment by dawnarc** [comment]
I also wonder why Visual Studio can find references that are so deeply hidden, I guess that because I installed the Visual Studio plugin for Unreal Engine.

![2024 03 07_王爱国 551509a699024e9d071f87bbdda8df77](https://github.com/slynch8/10x/assets/3351764/aeb25741-279d-4f01-b09c-b409cb1814ec)
It's a open source: https://github.com/microsoft/vc-ue-extensions

**Comment by slynch8** [comment]
fixed (1.0.136)
