### ISSUE TITLE
[Feature Request] Make [] and () work the same as {} with FormatBracesOnEnterSplit

### ISSUE THREAD

**Issue by DennyLindberg** [slynch8/10x#2498]
When using 10x with `FormatBracesOnEnterSplit true` and `OpenBraceOnNewLine false` you get the following behavior with {}. Doing this with [] or () does not. I would like to request that {}, [] and () has the same behavior as other IDEs like Visual Studio or VS Code.

```c
// The cursor is at the |
void Foo() {|}

void Foo() 
{|}
```

```c
// What is expected
void Foo() {
  |
}

void Foo() 
{
  |
}
```

**Comment by slynch8** [comment]
done (1.0.136)
