### ISSUE TITLE
Code navigation has issues when using type auto&

### ISSUE THREAD

**Issue by kingofthebongo2008** [slynch8/10x#2512]
Hello,
There are issues with code navigation, if the type is not explicitly stated
std::vector<A*>	m_objects;

//this code does not find foo upon pressing ALT + G
for (auto& m : m_objects)
    m->Foo();

//this code finds foo upon pressing ALT + G
for (A* m : m_objects)
   m->Foo();

**Comment by slynch8** [comment]
fixed (1.0.138)
