### ISSUE TITLE
crash when file deleted outside editor

### ISSUE THREAD

**Issue by neeraj9** [slynch8/10x#2516]
I noticed two crash dumps for 10xeditor during my evaluation before subscribing.

1. If a file open in 10x, but removed outside the editor via file manager or other means then the editor crashed.
2. 10x crashed for another ~~unknown reason which is harder for me to remember~~. I could repro the issue and noticed that when a new file is generated in the folder which 10x is monitoring (workspace) via build or other means and I quickly use the workspace tree to expand the folder which stores the new file then 10x crashes.

I have crash dump for both scenarios. Let me know where I should be uploading those crash dump files.

**Comment by slynch8** [comment]
Thanks, I'll take a look. You can upload the crash dumps here: https://10xeditor.com/upload_crash.htm

**Comment by slynch8** [comment]
I had a go but couldn't get it to crash with either case. Does it still happen on the latest build?

**Comment by neeraj9** [comment]
I am using version1.0.134
Uploaded 3 crash dumps.

**Comment by slynch8** [comment]
Thanks. I've got the crash dumps.

Are you able to re-create this in a simple test project?

**Comment by neeraj9** [comment]
I have not tried again. Updated to latest version 1.0.136 now. Will let you know if I get crashes again.

**Comment by slynch8** [comment]
Closing for now, re-open if you get it again.
