### ISSUE TITLE
Auto upload crash dumps

### ISSUE THREAD

**Issue by frederich** [slynch8/10x#2517]
I'm behind a corporate proxy wall, we can't upload crash dumps via the website. An automatic upload of crash dumps via https rest requests would be reasonable.

**Comment by aemsle** [comment]
An automatic upload wouldn't be the best idea. The company I work for has extremely tight security on their source code and an automatic upload would kill any potential for 10x to be used as it would be a leak risk. This _could_ be a opt-in feature however, even the potential for the crash dumps to be sent off would set alarm bells off for our security team. Obviously I dont know your specific circumstances so I could be way off here but this feels like an issue that your companies internal security should handle by adding an exception.

**Comment by Matthew-Rennie** [comment]
Have to agree with @aemsle here, auto upload of crash dumps would completely kill the ability to use the editor, since any crash dump would necessarily have to include the contents of currently open files.
