### ISSUE TITLE
10x crashed when closing a huge project 

### ISSUE THREAD

**Issue by neeraj9** [slynch8/10x#2521]
**10x Version:** 1.0.136

> I have 128GB RAM and there was enough left, so memory was not an issue.

**What was I doing when it crashed?**: I was working on a huge codebase, with a lot of C, C++ source and header files along with many other files from different programming languages and formats. 10x was taking around 50GB of memory  (which is fine since I have plenty more). When I closed the editor then it crashed.
 
I have uploaded the crash logs to https://10xeditor.com/upload_crash.htm

## Project Stats

| Type     | Value |
| -------- | ----------- |
| Parsed files | 300196    |
| C source lines | 8025105 | 
| C++ source lines | 34326677 |
| C header lines | 14844360 |
| C++ header lines | 252409 |
| | |
| Overall folder files | 525266 |

Total Memory: 49.46 GB (as per 10x output)

**Comment by slynch8** [comment]
Thanks for the crash dump. That certainly is a big project! Does it happen every time you shut down?

**Comment by slynch8** [comment]
I think it might be hitting the shutdown timeout. If it doesn't shut down in 3 minutes it triggers a crash dump so that I can see what's going on. That's a lot of memory to free up so maybe it's taking > 3 mins?

**Comment by neeraj9** [comment]
Typically applications dont cleanup (memory free, etc) because any modern operating system would do that. You could choose to do the same and let operating system worry about it, in case you are trying to free up memory with delete / free calls.

**Comment by slynch8** [comment]
I've confirmed from the crash dump, it was just a timeout shutting down, so nothing to worry about. But I will see what I can do to make shutting down quicker.

**Comment by slynch8** [comment]
I've improved the shutdown time so it shouldn't hit the timeout crash anymore (1.0.146)
