### ISSUE TITLE
Incorrect rendering in a dialog

### ISSUE THREAD

**Issue by kingofthebongo2008** [slynch8/10x#2527]
There is incorrect rendering which looks like this:
Probably because my display settings are on 200% on 4k desktop

![image](https://github.com/slynch8/10x/assets/1145201/40a106fa-a157-4329-8e9f-da7d27fffe38)

**Comment by slynch8** [comment]
Looks like it's caused by doing a multi-line search (which isn't supported yet)

**Comment by slynch8** [comment]
fixed (1.0.146)
