### ISSUE TITLE
[Search Panel] The size of input layout becomes unreadable

### ISSUE THREAD

**Issue by mchornyi** [slynch8/10x#2541]
At startup it looks fine but after a while > 1 hour the size of bottom layout strangely decrease
![image](https://github.com/slynch8/10x/assets/30892477/fca0e16e-d547-4101-b2ef-b0322d290c1e)

**Comment by slynch8** [comment]
What do you have your UIScale setting set to?

**Comment by mchornyi** [comment]
> What do you have your UIScale setting set to?

UIScale: auto

Below is my PC settings
![image](https://github.com/slynch8/10x/assets/30892477/00e09fcd-283f-4497-988e-0b07f0806db8)
![image](https://github.com/slynch8/10x/assets/30892477/8fa341f4-8246-4b19-b54a-acd3813bee57)
![image](https://github.com/slynch8/10x/assets/30892477/07e7b169-445a-4620-adbb-4d68da8a4e5e)

**Comment by slynch8** [comment]
It seems to only happen when the UIScale setting is 1.25 (or auto with the OS scale set to 125%), if you set it to 1.5 it stops happening. I'm looking into it.

**Comment by slynch8** [comment]
Yes, that's a known issue with setting a larger UI font size, the UI won't automatically scale up (that's what UIScale is for). 

I think I've got a fix now though. Can you give this build a try:
www.10xeditor.com/upload/10xUIScaleBugFix.zip

**Comment by mchornyi** [comment]
https://github.com/slynch8/10x/assets/30892477/8378463b-8b50-4ac2-b117-d25f8decc2df

**Comment by mchornyi** [comment]
It is better. But we may still notice how labels overlap checkboxes.

https://github.com/slynch8/10x/assets/30892477/cfaa04cb-032e-48c2-8685-a3c0ff909c25

**Comment by mchornyi** [comment]
I set the fonts back to default value and it looks great.
![image](https://github.com/slynch8/10x/assets/30892477/a2a099e5-8c3c-4540-be7d-c3c0a3defe5c)

**Comment by mchornyi** [comment]
But what should I do if I need to make font bigger and do not cause the issue again?
![image](https://github.com/slynch8/10x/assets/30892477/7ef03dc5-318f-42dd-aed9-679152663ff6)

**Comment by slynch8** [comment]
It might also be that the font you are using is bigger by default, so you can set the UIScale higher and the UIFontSize lower to make it fit.
