### ISSUE TITLE
build command fails with workspace created over menu

### ISSUE THREAD

**Issue by blups0r** [slynch8/10x#2555]
When i create a workspace over File->Create Workspace and fill out all required fields and try to execute my build command i get below error.

Create Workspace 1
![grafik](https://github.com/slynch8/10x/assets/166128659/2abd361e-7ea6-4599-afa5-b53e4f101e93)

Create Workspace 2
![grafik](https://github.com/slynch8/10x/assets/166128659/62969284-1f61-4110-8951-a15053ba2b1d)

Error during build
![grafik](https://github.com/slynch8/10x/assets/166128659/ad5dfb15-e896-4cda-ba6f-56a9cc917a52)

The messsage says "The directory name is invalid"

The interesting thing is when i copy an old workspace file and change the name and open it it just works fine. The only difference between those 2 files is the ConfigProperties and IncludeFilesWithoutExt tag. The created one has no ConfigProperties and the old copied one has entries.

What i saw is that the new created one loads stuff in different order than the old one. See below.

Error 10x output
![grafik](https://github.com/slynch8/10x/assets/166128659/4fc7af6a-757e-4542-b27d-5660ea9b61bf)

Working 10x output
![grafik](https://github.com/slynch8/10x/assets/166128659/d0445f2c-1b8a-40e0-a98a-12089ee95a41)

I also attached the simple project were it did not work. It contains both workspaces. Named accordingly
[10x_error.zip](https://github.com/slynch8/10x/files/14885123/10x_error.zip)

Another thing is when i edit to not working file to match the working one it still does not work. But when i copy over the whole content from the working to the not working one it works just fine.

Feel Free to ask for more information. It is a really strange issue. I love your work. Keep it up

**Comment by slynch8** [comment]
I haven't had a chance to investigate this yet, but I notice that your working directory is set to build.bat. It should be set to the working directory for the build script, or leave it blank to use the workspace root directory.

**Comment by blups0r** [comment]
leaving the working directory blank solved the issue. Thank you for your help and great editor.
