### ISSUE TITLE
Feature: File > Reload Workspace option along with keyboard shortcut for python script dev

### ISSUE THREAD

**Issue by neeraj9** [slynch8/10x#2562]
A new "File > Reload Workspace" should be made available, such that python script development is much faster.
At present I have to save the script and then either open a new instance of 10xeditor or close and then open again.

**Comment by neeraj9** [comment]
This will be fixed once #2568 is resolved.

**Comment by slynch8** [comment]
closing as no repro. Let me know if it's still a problem.
