### ISSUE TITLE
Crash of 10xeditor when tabswitch and trying to paste copied text

### ISSUE THREAD

**Issue by neeraj9** [slynch8/10x#2578]
**Version:** 1.0.144
**OS:** Win11, 23H2 (OS Build 22631.13296)

**Note:** The crash happened once and could not repro it.
**Note:** I have uploaded dump to the 10xeditor upload site.

**Steps:**
- Open a workspace and open a file
- Switch tab to another application and copy text
- Switch back and use CTRL+V

**Comment by slynch8** [comment]
It's crashed trying to open the file in Visual Studio. Could you have pressed alt+X by mistake? Anyway, I'll get it fixed in the next build.

**Comment by slynch8** [comment]
fixed alt+X crashing (1.0.146)
