### ISSUE TITLE
Small formatting bug with `&`

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#2580]
When I add a close bracket to the following:

```
            int variable1 = 0;
            int variable2 = 0;
            if (variable1&variable2)
            {
```

then `variable1&variable2` doesn't have spaces added between the `&`. If I change the `&` to other unary symbols like `|` or `+` then the spaces are added when closing the bracket.

(small update)

`extern byte icons[9*8*4+8*16*7];`

formats to

`extern byte icons[9 * 8*4 + 8*16 * 7];`

**Comment by slynch8** [comment]
fixed (1.0.147)
