### ISSUE TITLE
[Feature] Popup for showing project files

### ISSUE THREAD

**Issue by vulcan-dev** [slynch8/10x#2587]
In Focus, Visual Studio Code, and maybe some other editors, you can press CTRL+P to get a menu like this:
![image](https://github.com/slynch8/10x/assets/31520916/9cb0f3a9-98b5-4863-85d5-f1850f372b56)

And when you open a file, it will change the order, so the file you've just opened will now be at the top. This is quite important to have, because say you eventually got rid of tabs and want to go to your previous file, you would just press: CTRL+P, Down, Return. And then the order will of course change.

**Comment by slynch8** [comment]
Note to self: can make the FindFile panel do this if the filter is empty

**Comment by slynch8** [comment]
If all you want is to open a recently opened file you can use control+Tab

**Comment by slynch8** [comment]
FindFile panel (alt+shift+O) now shows recent files when the filter is empty
