### ISSUE TITLE
Cursor goes to wrong position when navigating with arrows keys if TabWidth is 2

### ISSUE THREAD

**Issue by Strewya** [slynch8/10x#2589]
It only happens when the value is 2, at 3+ the behavior is correct. Haven't tested value of 1.
IndentMode doesn't matter whether it's spaces or tabs, it's the same with both.

https://github.com/slynch8/10x/assets/3354058/e92b9cea-545d-487c-bac2-f011a3d40d8d

**Comment by slynch8** [comment]
fixed (1.0.218)
