### ISSUE TITLE
pressing esc does not exit sub-sub-menu

### ISSUE THREAD

**Issue by pixelmager** [slynch8/10x#26]
Pressing esc does not exit the sub-menu ("move"), like it does the direct menus ("view").
![image](https://user-images.githubusercontent.com/3230052/104030563-e3621900-51cb-11eb-8782-96a5a197b89d.png)

Expected: Would exit sub-sub-menu, like it does the view-menu / menu.

**Comment by slynch8** [comment]
fixed (0.20.8.0)
