### ISSUE TITLE
[Feature Request] Add a way to manually override path to devenv.exe when debugging begins

### ISSUE THREAD

**Issue by aemsle** [slynch8/10x#2625]
This is to allow for multiple installations of visual studio on the same machine. The main issue im hitting is that 10x defaults to the newest version of devenv regardless of the `VisualStudioEnvBat` setting. On my machine, vs2022 doesnt have certain extensions that are required for running the program so I would need some way to force it to boot into vs2019.

**Comment by slynch8** [comment]
This is done. Build (1.0.168). It will now use the same Visual Studio install as is set in VisualStudioEnvBat. And you can also override it with the VisualStudioInstallPath setting.
