### ISSUE TITLE
Goto definition and toggle between header/cpp displays in random view

### ISSUE THREAD

**Issue by stevenhaggerty** [slynch8/10x#2638]
Whenever I use Go To Definition <alt-g> or <alt-o> to swap between header/cpp files, rather than 
using the view I'm currently using, the goto/toggle will occur in an apparently random view.

I could understand this if the file was already present in one of the views, but it isnt.

The goto/toggle should only affect the currently active view.

Thanks.

**Comment by slynch8** [comment]
You need to set UseColumnPresets to false and OpenFileInActivePanel to true.

**Comment by stevenhaggerty** [comment]
Excellent. Many thanks.
