### ISSUE TITLE
Macros/Prepreossor Directives for selected config not getting pulled into 10x syntax highlighting. 

### ISSUE THREAD

**Issue by CodyOlivierRSGNWE** [slynch8/10x#2642]
I have a bunch of disjoint macros defined on each config on the project/slns in Visual Studio (Properties Page -> C/C++ -> General -> Preprocessor Directive field). These don't seem to be either pulled into to 10x or aren't getting updated when I change config/platform in 10x.

**Comment by slynch8** [comment]
I'll take a look. For now you can add them manually in the workspace settings

**Comment by slynch8** [comment]
I've just checked this and it does seem to be working. Make sure you wait for the parse to finish after switching configs, it can take a while the first time.

**Comment by slynch8** [comment]
Is this still an issue? It's working in my test project.

**Comment by CodyOlivierRSGNWE** [comment]
Hey Stewart, yes this issue does seem to be working. I was waiting until I got an opportunity to test out the new forceinclude changes in case that fixed my issues with macros and it does indeed seem to be the case.
