### ISSUE TITLE
Consistent crash opening seemingly innocuous file.

### ISSUE THREAD

**Issue by TheSandvichMaker** [slynch8/10x#2644]
I was working on my codegen script and when I forgot to write a newline I managed to produce a file that crashed 10x every single time when I open it, or even just when I open a workspace in which it is contained.

So far as I can tell, there are no weird bytes in it or anything, it's just ascii text with crlf line endings.

The exact file [can be found here](https://github.com/TheSandvichMaker/retro-fps/blob/75129141a02e2e71eb959005211a535b395734e7/src/game/render/shaders/gen/shaders.c)

10x stops crashing when I add the missing newline, so when I go from
```
// Generated by metagen.luadf_shader_info_t df_shaders[DfShader_COUNT] = {
```
to
```
// Generated by metagen.lua
df_shader_info_t df_shaders[DfShader_COUNT] = {
```

I also uploaded a crash dump under the name "The Sandvich Maker".

10x version: 1.0.168

**Comment by slynch8** [comment]
fixed (1.0.177)
