### ISSUE TITLE
Renaming file in workspace with F2 doesn't work, but workspace tree visually thinks so

### ISSUE THREAD

**Issue by askebv** [slynch8/10x#2660]
Renamed the file from `types.h` to `ash_types.h`:

![image](https://github.com/slynch8/10x/assets/4981659/25f53874-9317-4992-bbcf-941770e34d40)

**Comment by slynch8** [comment]
I didn't mean to enable renaming, renaming files isn't supported yet.

**Comment by slynch8** [comment]
fixed (1.0.189) removed renaming in workspace tree
