### ISSUE TITLE
Hover box comment bugs

### ISSUE THREAD

**Issue by MohitSethi99** [slynch8/10x#2671]
- hover box has some additional content
- comment on the side is not shown for function definitions at all
- comment is not shown if variable is initialised with {}

![image](https://github.com/slynch8/10x/assets/29519295/0f92fdf2-1c6a-46f0-ae48-b2eee4f945c5)
![image](https://github.com/slynch8/10x/assets/29519295/b0ceb5b2-dbed-4047-8f3c-64a57093fa1a)
![image](https://github.com/slynch8/10x/assets/29519295/228494f0-5c33-456b-9ffc-8d9131035006)

Code:
```cpp
#define BEGIN_INCLUDES __pragma(warning(push))
#define END_INCLUDES __pragma(warning(pop))

BEGIN_INCLUDES
#include<Windows.h>
END_INCLUDES

// Test Top Comment
void TEST1();    // Test 1
void TEST2();    // Test 2
int a{0};            // a
int b = 0;         // b

int WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nShowCmd)
{

}
```

**Comment by slynch8** [comment]
fixed (1.0.189)
