### ISSUE TITLE
Crash when reopening existing workspace (msvc vs solution).

### ISSUE THREAD

**Issue by Krpa** [slynch8/10x#2673]
[10x_crash_2024_6_28_12_13_47.dmp](https://github.com/user-attachments/files/16027948/10x_crash_2024_6_28_12_13_47.dmp)

The editor crashes each time I try to open the VS solution with an existing workspace (either as a solution or as a recent workspace). This is a cmake project with a generated solution for MSVC. The same project opens multiple time just fine if the VS solution is generated for clang. 
When I delete the workspace in %APPDATA%\Roaming\10x\Workspaces, I can open the solution and it works, but it crashes again the next time I try to (re)open it.

**Comment by slynch8** [comment]
Hi. Unfortunately the dmp file is corrupt and can't be opened. Would you be able to share your project?

**Comment by Krpa** [comment]
[10x_crash_2024_6_28_15_41_46.dmp](https://github.com/user-attachments/files/16030601/10x_crash_2024_6_28_15_41_46.dmp)

That's unfortunate, it's a 100% repro. Here's the latest one, but I'm guessing it will also be corrupt. I can't share the project, but I can try and see if I can repro it with a dummy project over the weekend. I'll let you know.

**Comment by slynch8** [comment]
Same. Can you send the original .dmp.gzip file?

**Comment by Krpa** [comment]
Github doesn't allow it, so here they are on gdrive: https://drive.google.com/drive/u/0/folders/1lzfp5qGdikvEXsqj6CvAMvvJ5DlmFM6K

**Comment by slynch8** [comment]
Got them, thanks.

It's crashing in the map scroll bar renderer, although I can't see why. Maybe something has corrupted it. If you can get it in a test project that would be really helpful.

**Comment by Krpa** [comment]
I think you're right, my MapScrollBarWidth was set to 0. When I set it to 1, it doesn't crash. Thanks!

**Comment by slynch8** [comment]
turned out to be caused by MapScrollBarWidth set to 0

**Comment by slynch8** [comment]
fixed (1.0.189)
