### ISSUE TITLE
Multi-cursor toggle comment line

### ISSUE THREAD

**Issue by randrew** [slynch8/10x#2677]
If I have have multi-cursors on two lines and then try to toggle comments, only one of the lines is toggled. Works fine if it's a full line selection instead of just multi cursors with no selection area, but I would have expected the behavior to have been as if I had done a toggle on each of the lines with a cursor on them.
![qhNfxmNj1T](https://github.com/slynch8/10x/assets/26056/b34411df-c5ad-48cf-b7c5-2383470b4dfa)

**Comment by vulcan-dev** [comment]
Agreed, this would be nice to have

**Comment by slynch8** [comment]
fixed (1.0.203)
