### ISSUE TITLE
Hover box fails to resolve return type with certain function signatures

### ISSUE THREAD

**Issue by uranium2818322192** [slynch8/10x#2679]
Tends to happen with functions that has multiple qualifiers. [StrChrIW](https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strchriw) seems to be one of them.

**Comment by slynch8** [comment]
Do you have _WIN32 defined? It's not working for me because of the __export directive that gets added for non-Windows platforms.

**Comment by slynch8** [comment]
anyway, I'll make it support __export

**Comment by uranium2818322192** [comment]
> Do you have _WIN32 defined? It's not working for me because of the __export directive that gets added for non-Windows platforms.

Indeed I was missing that define for the editor.

**Comment by slynch8** [comment]
fixed (1.0.189)
