### ISSUE TITLE
[Feature request] Have a command to close all the tabs of a specific column.

### ISSUE THREAD

**Issue by matiasjpedro** [slynch8/10x#2688]
The need of that kind of commands is that I was trying out the QuickPane plugin:

[QuickPane](https://github.com/slynch8/10x/blob/main/PythonScripts/QuickPane/QuickPane.py)

But the script only works if you only work with 1 tab open at a time, because otherwise it will close all the other tabs that you had open on your main column. With `CloseAllTabsOnColumn` I could specify to close all the tabs from the secondary column without affecting the ones that are open in the main.

**Comment by slynch8** [comment]
done (1.0.189)

`N10X.Editor.CloseAllPanelsInColumn(n)`
