### ISSUE TITLE
Full re-parse hanging

### ISSUE THREAD

**Issue by aemsle** [slynch8/10x#2691]
Initially when opening the vs solution it manages to parse fine if the parser cache is cleared, however, during the build process we generate some code files from data which are then included in the build. These files appear to hang the parser which in turn breaks auto completion/syntax highlighting for other files if they get edited. 

CppParser.LogParseStatus
``` 
[parser] ----- Parse Status -----
[parser] Parse Time: 6539 sec  (108:59)
[parser] State: FullParse
[parser] Pending Read File Count: 0
[parser] Pending Preprocess Count: 0
[parser] Pending Parse Count: 0
[parser] Pending Parse Defs Count: 461
[parser] 
[parser] currently parsing 12 files:
```

Upon seeing this I triggered a full re-parse but it doesn't seem to help much other than giving very basic syntax highlighting from the `cpp.10x_syntax` file

```
[parser] ----- Parse Status -----
[parser] Parse Time: 1436812 sec  (23946:52)
[parser] State: FullParse
[parser] Pending Read File Count: 0
[parser] Pending Preprocess Count: 0
[parser] Pending Parse Count: 0
[parser] Pending Parse Defs Count: 0
[parser] 
[parser] currently parsing 0 files:
[parser] ------------------------
```
(I could be wrong but I do not believe I've been in the office for 16 days)
 
Unfortunately i'm unable to reproduce this in a test solution and I'm unable to share any code from the current project.

My best guess is that it might have something to do with the recent force include changes? 

This seems to be a regression that occurs in 1.0.183 (early access) 
previous: 1.0.179

**Comment by slynch8** [comment]
fixed (1.0.189)
