### ISSUE TITLE
Ignore blank lines between comments and classes/struct/functions/etc when showing hover box

### ISSUE THREAD

**Issue by vlucki** [slynch8/10x#2693]
Unreal Engine projects rely on macros like `UFUNCTION` or `UPROPERTY` to setup the reflection system. This, however interferes with the info displayed when hovering functions, variables, etc... because those tend to be preceded by said macros, which end up pushing any comments with documentation one line up, making them ignored by 10x.

For example, the following snippet
```
// Calculates damage based on the attributes of the attacker and defender. Ignored if defender is invincible.
UFUNCTION(BlueprintCallable)
void DealDamage(const FAttackData& AtkData);
```

Will not have any comment displayed when the function is hovered.

On custom code, it may be possible to move the macros above the comments, but any Engine-side code will suffer from this issue.

Since those macros evaluate to nothing (the unreal header tool just leverages them to generate stuff on other files), it may be possible to ignore the empty lines and still get the comments showing.

**Comment by slynch8** [comment]
fixed (1.0.189)
