### ISSUE TITLE
Feature: Skipping indents while navigating with arrow keys

### ISSUE THREAD

**Issue by GloriousPtr** [slynch8/10x#2694]
I was trying out 4coder and Instantly found this particular behaviour really helpful. It skips indents when you navigate through arrow keys which saves me a few redundant clicks.

**Comment by slynch8** [comment]
Someone just created this script which does what you want: https://github.com/slynch8/10x/blob/main/PythonScripts/SmartSpace/SmartSpace.py

**Comment by GloriousPtr** [comment]
It works really well, thanks :)
