### ISSUE TITLE
Implement Parser Preprocessor

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#27]
The parser currently doesn't have a preprocessor.

This task is to add support for:
- macros
- ifdef'd out regions

**Comment by slynch8** [comment]
created in response to [https://github.com/slynch8/10x/issues/18](https://github.com/slynch8/10x/issues/18)

**Comment by Muzza** [comment]
As a temporary measure before the preprocessor is implemented, is there any chance of getting the parser to ignore unknown tokens in struct/class definitions?
e.g.
`struct __ALIGN(16) MyStruct`

I have a lot of classes and structs that have no syntax highlighting and no intellisense, down to this one macro usage.

**Comment by slynch8** [comment]
done. I've added support for __ALIGN (0.24.6)

Let me know if there are any more temporary things like this that would help, they are easy to add.

**Comment by Muzza** [comment]
Thanks, another use of it would be:
`Type __ALIGN(16) varName;`

**Comment by slynch8** [comment]
that's in (0.24.8)

**Comment by slynch8** [comment]
I've moved this to the [roadmap](https://www.10xeditor.com/roadmap.htm)

**Comment by slynch8** [comment]
changed my mind, I'll keep it open

**Comment by muzzi11** [comment]
Not sure if this belongs here, but can we get a setting for macro text colour? I like having different colours for preprocessor keywords and macros.

**Comment by slynch8** [comment]
done
