### ISSUE TITLE
Debug Command Arguments Per Project Configuration

### ISSUE THREAD

**Issue by rvc86** [slynch8/10x#2705]
I'm working on a multiplayer UE5 game, and would love to have something like what the [Smart Command Line Arguments](https://marketplace.visualstudio.com/items?itemName=MBulli.SmartCommandlineArguments) plugin in Visual Studio provides, so I could launch editor, server and client with different arguments.

**Comment by slynch8** [comment]
I added this recently: View Menu -> Command Line Arg Selector
