### ISSUE TITLE
Inconsistent behavior opening the command panel from Vim's normal mode

### ISSUE THREAD

**Issue by javiersalcedopuyo** [slynch8/10x#2719]
Hello!
I noticed that opening the command bar from normal mode with `:` behaves slightly inconsistently.

It always opens prepopulated with `:` but sometimes it'll be selected, meaning if you start typing immediately it'll replace it, forcing you to retype the `:`. This seems to be the default behavior as it is what happens if you open a new 10x instance?
However, after typing something in the command bar and closing it (either by cancelling or executing the command), the next time you open it, the cursor will be after the `:`, rather than selecting it.

It's not a major issue, but it is a bit frustrating at times when I'm firing multiple commands through muscle memory and I mix vim and 10x commands.

Personally, I'd prefer the bar to not be prepopulated at all, because typing `:` twice when I need a vim command is faster than `:` and then return for every other command.
Locally I have disabled that so I can submit a PR if you agree.

Best regards.

**Comment by SimpsonGSD** [comment]
I've never seen this issue of the text highlighted when it's open, so that feels like a bug to me. I'm not a fan of having to double type `:`.

**Comment by SimpsonGSD** [comment]
Just to update, if you now set `VimEnableCommandlineMode: true` in settings, commands will now appear in the status bar which may help with this issue.
