### ISSUE TITLE
[Bug] Wrong character being selected

### ISSUE THREAD

**Issue by lucrool** [slynch8/10x#2720]
https://github.com/user-attachments/assets/4eef7e92-7a41-422a-86a2-0bb5726671a4

https://github.com/user-attachments/assets/14c7bbbd-0dde-4fa3-8614-0ca3f15e4b6d

Selecting things can feel janky because of this

**Comment by slynch8** [comment]
I'm not seeing that here. What font and font size are you using? And what UIScale?

**Comment by lucrool** [comment]
![image](https://github.com/user-attachments/assets/9221f7ec-e57f-4c58-9c6e-494227a36576)
![image](https://github.com/user-attachments/assets/d57c9a52-09c0-4d63-824e-0ede4882045b)
![image](https://github.com/user-attachments/assets/7280375c-fcc2-43b7-95eb-e6413a593773)
![image](https://github.com/user-attachments/assets/3bfded56-a6ab-4828-91b7-784b49f5d7df)
![image](https://github.com/user-attachments/assets/2527197e-45b1-490e-824e-80736ecc6681)

All my UI settings are default (I think), though I Control + Mouse Wheel scroll in and out whenever I need to. 
For some reason I can't reproduce this bug, it doesn't seem to happen after a restart, it works perfectly now (for now).

**Comment by slynch8** [comment]
ok, let me know if you see it again.
