### ISSUE TITLE
Slight bugs in find and replace within selection

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#2738]
1. When I make a selection and hit `ctrl-h` to replace a string with another inside the selection, everything works fine. Then, if I make a second selection that has the same string to be replaced and try to hit `alt-r` to start replacing, then no strings are found. If I do something like deleting the last character in the `find` box and type it again then it starts matching strings again
2. If I replace a string with another inside a selection, and the replaced string is smaller, then the editor is highlighting some extra spaces at the end of the line of each replace, the size of what the old string used to be

**Comment by slynch8** [comment]
fixed (1.0.218)
