### ISSUE TITLE
Command Request: SetFindText

### ISSUE THREAD

**Issue by SimpsonGSD** [slynch8/10x#2756]
A command we can call from python to set the find text, so the FindNextInFile, etc commands work,

**Comment by SimpsonGSD** [comment]
Would really appreciate a command for being able to set match by whole word only so we can fix the Vim `*` script command.

**Comment by SimpsonGSD** [comment]
Different request but related/requested for the same purpose. 
There's currently no way to trigger a replace with a 10x command or python function.

Example usage of how substitute works in vim to understand usage.

Find and replace all in file.

![02_basic_find_replace](https://github.com/user-attachments/assets/f85718f8-f752-4192-a360-b2244c43feec)

Find and replace next in file.

![03_with_confirmation](https://github.com/user-attachments/assets/bf83aed2-8c75-44fc-97b8-c0a0342b104f)

Vim also allows you to replace in a custom range, so being able to SetSelection and run replace commands on that.

**Comment by slynch8** [comment]
I'm implementing the other functions at the moment. But there are the ReplaceAllInFile and ReplaceNextInFile commands for replacing text in the current file.

**Comment by slynch8** [comment]
done (early access build (1.0.211)

**Comment by slynch8** [comment]
- added SetFindText and SetReplaceText to python API
- added SetFindByWord to python API

**Comment by SimpsonGSD** [comment]
@slynch8 Can we also have GetFindByWord so we can restore the previous setting?
