### ISSUE TITLE
Autocomplete page up/down keybindings still map to Page up/down

### ISSUE THREAD

**Issue by Strewya** [slynch8/10x#2773]
If you change the keybindings in the KeyMappings file for AutocompletePageUp/Down to anything else other than Page Up/Down keys
and open the autocomplete box, using PageUp and PageDown keys still invokes AutocompletePageUp/Down respectively, as if these bindings are hardcoded. The new bindings also work, but the expectation would be that PageUp/Down keys no longer do.

**Comment by slynch8** [comment]
fixed (1.0.218)
