### ISSUE TITLE
Code file sometimes opens in workspace tab

### ISSUE THREAD

**Issue by Meetem** [slynch8/10x#2783]
Version: 1.0.206 
Worth mentioning I have put tabs layout like that:
![image](https://github.com/user-attachments/assets/f48eac08-e76e-4f92-b751-b81fc5be44ee)
e.g. Worktree is not extended to the bottom, but instead resides on the same height as file editing.

https://github.com/user-attachments/assets/369fef9c-919b-488d-a38b-99b9b10ac7c8

**Comment by slynch8** [comment]
It looks like you've docked the workspace tree in column 0, which is where code files open by default. You can either dock it to the side or change the Column0Presets setting.

**Comment by slynch8** [comment]
Closing for now. Let me know if it's still an issue.
