### ISSUE TITLE
Start Debugger Launches Visual Studio Even Though It Is Not Specified

### ISSUE THREAD

**Issue by trustednstaller** [slynch8/10x#2787]
I want to have the `Debug Command` and `Debug Command Arguments` work without resorting to invoking Visual Studio. For instance, I use WinDbg as my debugger, and have a script set up to invoke through PowerShell that puts me in the debugging experience that I want to be in after I build. I want to set up the `Debug Command` and arguments and hit F5 to reflect this.  Doing this in Visual Studio (when setting up `Debug Command` and `Debug Command Arguments`) works perfectly but 10x launches VS every time even though there is nothing related to VS.

![image](https://github.com/user-attachments/assets/6a110fa5-bc93-4ca0-a855-ddc035e1c7aa)

This same setup, when applied in the `Debugging` settings for Visual Studio works as expected.

**Comment by slynch8** [comment]
You need to turn off the VisualStudioSync setting
