### ISSUE TITLE
Question: Opening New File in Existing Visual Studio Solution

### ISSUE THREAD

**Issue by trustednstaller** [slynch8/10x#2789]
This may seem like a very stupid question but I do not see how I can create new files that are part of an existing Visual Studio project? Right-clicking the Workspace Tree provides no option. I do see the creating "text files" option but is it not possible to simply take an existing VS project and work completely out of 10x with it i.e., adding new source files, rename existing files part of the project, additional options, etc.

**Comment by slynch8** [comment]
It's not possible yet, but there is a feature request if you want to up-vote it. https://github.com/slynch8/10x/issues/268
