### ISSUE TITLE
Feature request:  highlight current tab in [...] dropdown

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#2790]
in the ... dropdown next to the tabs.  can i suggest to highlight the current tab in that dropdown?
typically i use it to see if there are any tabs hiding between the pinned ones and the leftmost visible right of the pinned ones,
as that's not obvious unless clicking ... or doing ctrl+pgup and finding one.
a small divider between the pinned and non-pinned and indicator of more tabs are hiding to between them would probably clear it up too.

**Comment by slynch8** [comment]
done (early access build (1.0.211)

**Comment by slynch8** [comment]
done (1.0.218)
