### ISSUE TITLE
Comma seperated member variables not parsed when empty constructor exists

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#2791]
Bit of an odd one. See the below code.
a.j.y is not parsed properly (and shows in white)
But if I comment out the constructor to AAA or change it to be external, it fixes it. Note that you have to do a ReparseFile after making the change.

```cpp
struct Vec2i
{
	int x,y;
};

struct AAA
{
	AAA() {}	// comment this out, or change to AAA(); to fix it
	Vec2i i,j;
};

void Func( void )
{
	AAA a;
	a.i.x;
	a.j.y;	// j.y is not parsed, unless you comment out the constructor to AAA()
}
```

**Comment by slynch8** [comment]
Fixed (1.0.218)
