### ISSUE TITLE
Paste shortcut doesn't work on edit boxes

### ISSUE THREAD

**Issue by castano** [slynch8/10x#2804]
I have these options in my key mappings:

```
# Paste from clipboard
Control V:              Paste

# Paste from clipboard
Shift Insert:           Paste
```

but it seems these only work on the main editor. When editing text on edit boxes, for example, in the debug argument box, or in the new command line arg selector, the only shortcut that works is Control+V.

I haven't confirmed this, but I suspect the shortcuts in the edit boxes are hard coded. If so, it would be good to match the standard Windows behavior, where both shortcuts work, or ideally respect the user keyboard mapping.

**Comment by slynch8** [comment]
done (1.0.218). All UI elements now use the key mapped clipboard commands
