### ISSUE TITLE
Allow global syntax highlighting files

### ISSUE THREAD

**Issue by detritivore** [slynch8/10x#2806]
```
Having a global syntax highlighting file seems like a good idea.
I think you could create one and put *.* into the Extension setting at the top. Not sure how it will work with multiple matching files, but it's worth a try. 
```

sadly, that didn't 'just work', so support for it should be added.
this would allow users to specify custom 'syntax colouring rules' for keywords such as NOTE: TODO: etc.

sidenote: supporting full/partial/multilines for such a feature would be a bonus :-)

**Comment by slynch8** [comment]
done (1.0.218)
