### ISSUE TITLE
Feature Request: Optionally have no editor tabs

### ISSUE THREAD

**Issue by rbento** [slynch8/10x#2822]
### Optionally have no editor tabs
- Have a single 'no tab' editor, or
- Have a double 'no tab' editor for corresponding header/cpp files.
- The recent files on `CTRL+TAB` should still show a max number of recently opened files.

**Comment by andreyfmc** [comment]
maybe this will help

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by rbento** [comment]
@slynch8 I reported the comment above as phishing and they responded saying that the admin of a repository can disable ghost accounts.

> The ghost username is in place to designate accounts that have been deleted by their owners, but that still have content that is visible across the GitHub platform. If you have write permissions to a repository, you can hide, edit, or delete comments from ghost users with the tools described here:
 
Managing disruptive comments: [https://docs.github.com/en/github/building-a-strong-community/managing-disruptive-comments](https://docs.github.com/en/github/building-a-strong-community/managing-disruptive-comments)

Regards.

**Comment by slynch8** [comment]
Thanks @rbento, I've deleted the comment.

**Comment by slynch8** [comment]
Closing as duplicate https://github.com/slynch8/10x/issues/1891
