### ISSUE TITLE
Feature Request: Disable formatting for # of spaces between commas or equal signs

### ISSUE THREAD

**Issue by alexgwalley** [slynch8/10x#2824]
An option to allow formatting like below would be wonderful. I like to line up my equal signs for similar variables, currently the formatter would remove those extra spaces.

```c
// github code view isn't aligning these, but they should be :)
int a                    = 0;
int longer_name = 1;

// similarly for initializer lists:
{A,       10,      another_thing},
{B,      123,      b_thing}
```

**Comment by slynch8** [comment]
done (1.0.249)
added FormatEquals and FormatCommas settings to turn off formatting for these chars.
