### ISSUE TITLE
BUG! vertical file-tab bar scrolls when not needed

### ISSUE THREAD

**Issue by datgame** [slynch8/10x#2831]
made a new instance, set tab bar to the right, opened quake3 source 🙂  and opened some 20 files by clicking the workspace explorer, then closing it again
as you can see, extremely confusing behaviour

stewart: "I see. I think it's trying to scroll the currently selected file into view when it doesn't need to "

https://github.com/user-attachments/assets/ceebe6d8-9d29-4160-a6f1-d77f50855467

**Comment by slynch8** [comment]
I think I fixed this but forgot to close it. Is it still n issue?

**Comment by datgame** [comment]
Still happens in version 235

**Comment by slynch8** [comment]
fixed (1.0.249)
