### ISSUE TITLE
Crash bug: saving new text file

### ISSUE THREAD

**Issue by JonnyKelso** [slynch8/10x#2844]
Hi, this is pretty repeatable for me:
`10x version: 1.0.218`

1. Create a new file with File -> New Text File
2. Type in some text, just a few chars - 'hello'
3. Save As using File -> Save As
4. Enter a filename 'hello.txt' but don't set filetype
5. Click Save
6. Will either crash immediately, or save the file and pop up a second Save As dialogue with no filename set, crashes on clicking save

Have sometimes seen multiple save dialogues popup and I just try and cancel them all away (the file is actually saved) and can also get crashes here too.

**Comment by slynch8** [comment]
caused by the SaveAllOnLoseFocus setting

**Comment by slynch8** [comment]
fixed (1.0.222)

**Comment by slynch8** [comment]
fixed (1.0.230)
