### ISSUE TITLE
Feature: Set StatusBar font, size and color

### ISSUE THREAD

**Issue by SimpsonGSD** [slynch8/10x#2847]
We use the status bar for vim status and commands and right now it is very small with no ability to use monospace fonts without changing the editor size and font.

It would be very useful if these were different sizes. 

Also being able to change color in color scheme would be great too.

**Comment by slynch8** [comment]
You can override the status bar colour with SetStatusBarColour() if that helps

**Comment by SimpsonGSD** [comment]
That is good to know, but font color too would be great :)

**Comment by slynch8** [comment]
on it

**Comment by slynch8** [comment]
done (1.0.222)

**Comment by SimpsonGSD** [comment]
Increasing font size, say to 20, doesn't increase status bar height so the text is clipped

**Comment by slynch8** [comment]
fixed (1.0.249)
