### ISSUE TITLE
10x per solution preferences

### ISSUE THREAD

**Issue by santagada** [slynch8/10x#2854]
For using 10x with a big solution on a multi user company, would be interesting to be able to define settings on a solution, like which extensions are cpp and header files, which extensions to search on, etc. Is this being worked on?

**Comment by slynch8** [comment]
You can create a workspace settings file by creating a .10x_settings file in your workspace folder. This will override normal settings. See here: <https://10xeditor.com/10xDocumentation/SettingsFiles.htm>

**Comment by santagada** [comment]
Would then having a button for creating/opening this file be a very nice to have?

**Comment by slynch8** [comment]
added feature request https://github.com/slynch8/10x/issues/2858
