### ISSUE TITLE
add dropdown for active project

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#292]

**Comment by slynch8** [comment]
also, add a way to set the debug args

**Comment by charles-epic** [comment]
Adding extra image for context.
![image](https://user-images.githubusercontent.com/51400986/222700673-968e6ea8-961d-4877-b01f-7849d0f486dd.png)

**Comment by slynch8** [comment]
done (1.0.32)

![ActiveWorkspaceToolbar2](https://github.com/slynch8/10x/assets/7141856/02e712d6-0dbd-4f22-9bcc-500b1cc7d0a4)
