### ISSUE TITLE
PythonAPI: SetFindText Case and Regex functions

### ISSUE THREAD

**Issue by SimpsonGSD** [slynch8/10x#2936]
As per title, same as setting find by word

**Comment by slynch8** [comment]
Do you want separate functions or args added to SetFindText? Args might be easier.

**Comment by SimpsonGSD** [comment]
If it args can it the args also have the whole word so it matches all the options in the find panel?

**Comment by slynch8** [comment]
This is in early access build (1.0.234)

**Comment by SimpsonGSD** [comment]
I still need functions to be able to set these options without it updating the find as well. E.g. SetFindByWord worked perfectly here but I need to set case and Regex without it re-searching.

**Comment by SimpsonGSD** [comment]
Could I also have a function to specify search direction. So when calling SetFindText it can search backwards or forwards on update

**Comment by slynch8** [comment]
Direction isn't currently supported by the find panel. Can you do it in the script with a FindPrev call?

**Comment by SimpsonGSD** [comment]
Not really when searching while typing. We already do it for jumping to prev match. It can wait until/if the find panel code can support it then. I assume that is a prequisite.

**Comment by slynch8** [comment]
How do you want reverse finding to work, a Get/SetFindReverse() function or an arg to SetFindText?

**Comment by SimpsonGSD** [comment]
An argument would work fine :)

**Comment by SimpsonGSD** [comment]
Actually it might be good to have both so it can be reset. I'm concerned about these settings persisting as for vim we don't want to affect the original find panel really as the user might want to use both.

**Comment by slynch8** [comment]
I've just noticed that the first call to SetFindText selects the next occurrence, but then calling it again doesn't do anything. Is this how you want it to work?

**Comment by slynch8** [comment]
When you get a chance could you give this build a try and let me know if it's working as expected
https://www.10xeditor.com/upload/10xSetFindTextChanges.zip

I've added:
```python
GetFindByCase()
SetFindByCase()
GetFindByRegex()
SetFindByRegex()
GetReverseFind()
SetReverseFind()
and added a reverse arg to the end of SetFindText()
```

**Comment by SimpsonGSD** [comment]
Will try that build

> I've just noticed that the first call to SetFindText selects the next occurrence, but then calling it again doesn't do anything. Is this how you want it to work?

Interesting.. this might be something I noticed.. I want it to just how to typing in the find panel does. 
Every time a char typed I add it to the search string and call SetFindText, which is supposed to replicate typing letters in the find panel.

**Comment by SimpsonGSD** [comment]
so that build is almost perfect.

The reverse search when passing as an arg is odd.

When searching the following paragraph, with the cursor at position |. 
Typing `t` correctly jumps to the end of the second to last line, then typing `e` correctly jumps to the start of that line.
However, when typing `s` instead of staying on this line it jumps the previous line. I guess this is because technically it's searching before the cursor but when it's hit a match it needs to stay on that line, if you understand me?

```test
test
Test
test
test
Test
|test

**Comment by slynch8** [comment]
Yes, that's the thing I noticed where I thought searching forwards might be wrong, but it's actually the find reverse that wrong. I think it's searching from the start of the selection instead of the end. I'll get that fixed.

**Comment by slynch8** [comment]
Actually, the reverse search problem is a bit more complex. It searches backwards from the current cursor position, but because the cursor position moves on each call it ends up travelling backwards. The way the find panel does it is to set a search start position when it's opened, then each time the text is changed it searches from the same position. I think the only way to get this to work properly is to ass a start position to the SetFindText call, what do you think?

**Comment by slynch8** [comment]
give this a try:
https://www.10xeditor.com/upload/10xSetFindTextChanges2.zip
I've added startpos as an optional last arg. You can just omit it or pass in (-1, -1) fur the current cursor pos (couldn't get none to work)

**Comment by SimpsonGSD** [comment]
Works a treat!

**Comment by slynch8** [comment]
done (1.0.249)
