### ISSUE TITLE
10x can't run executables from workspaces with spaces in its path

### ISSUE THREAD

**Issue by lucrool** [slynch8/10x#2940]
![image](https://github.com/user-attachments/assets/93226603-2d6b-4fc6-800a-b2c151c95af3)
![image](https://github.com/user-attachments/assets/efe3241c-4325-4a46-a447-33d44dc57f28)

**Comment by slynch8** [comment]
I can't reproduce this. What do you have your Executable setting set to?
![image](https://github.com/user-attachments/assets/2d66d960-d4da-4191-92b1-28cdd7d493f5)

**Comment by slynch8** [comment]
Thanks, got it now.

**Comment by slynch8** [comment]
fixed (1.0.249)
