### ISSUE TITLE
Syntax highlighter breaks with commenting

### ISSUE THREAD

**Issue by septag** [slynch8/10x#2943]
when commenting out some code, highlighter breaks and some variables are wrongly highlighted.
Happens with `ColourUndefinedKeywords: true` setting

To reproduce this, open this file: 
https://github.com/septag/Junkyard/blob/AssetTest/code/Tests/TestAsset.cpp
go to 550 and comment the pushConstant definition

![CommentBug](https://github.com/user-attachments/assets/088ae0c5-a064-40de-b5a5-2e6d424d6685)

Reopening the file fixes it.

Like Stewart mentioned in discord (https://discord.com/channels/732150926810546186/1305225794188214322)
"Unresolved symbols are not getting refreshed after they are commented out with the first /* before the */ is added"

**Comment by slynch8** [comment]
fixed (1.0.249)
