### ISSUE TITLE
Toggle comment non-standard behavior

### ISSUE THREAD

**Issue by castano** [slynch8/10x#2955]
The toggle comment function in 10x is different to VS Code, Sublime Text and Visual Studio. These three editors implement this function in similar ways, although Visual Studio has some differences.

However, 10x implements this function in a significantly different way, this causes some confusion and introduces friction when switching between editors.

In the first place, 10x inserts comments at the beginning of the line when the cursor is in the first column:

![10x-block-comment-2](https://github.com/user-attachments/assets/78b38485-a407-444b-9fa8-cf094449d646)

but skips the indentation if it's at a different column:

![10x-block-comment-1](https://github.com/user-attachments/assets/683eacf1-649e-4d6a-92f3-1246c739caf0)

In some lines it introduces a space and in others it does not.

Sublime and VS Code insert the comment at the lowest indentation level of the lines in the selection range. The exact position of the cursor does not matter:

![subl-block-comment-1](https://github.com/user-attachments/assets/c61b642c-e0a1-4e04-bf91-e858ed7eca59)

Another important difference is that 10x decides to comment or uncomment depending on the contents of the first line. If the first line is a comment, then it uncomments all the line comments, including the ones that are not at the beginning of the line:

![10x-block-comment](https://github.com/user-attachments/assets/6b041a7a-64db-4dd4-b56c-ee769e12c1be)

Compare this to Sublime:

![sublime-block-comment](https://github.com/user-attachments/assets/0d81e4a7-384c-4472-9b76-29bc78ab7032)

Visual Studio comments full lines at the lowest indentation level when the entire line is selected:

![vs-block-comment-1](https://github.com/user-attachments/assets/ebff4a78-2a82-4579-b1bd-bc81b0fccca7)

 but uses /**/ comments when partial lines are selected. It would be good to have this option also for Visual Studio users that are used to that behavior.

![vs-block-comment-2](https://github.com/user-attachments/assets/95869914-c05b-4161-8a96-a94cd7ab6ef2)

Note that 10x does better than this, as it allows toggling the comments back and forth. However, it does not realize that /**/ comments cannot be inserted within existing line comments:

![10x-block-comment-3](https://github.com/user-attachments/assets/e037d393-59f0-4a3f-b82e-62898a092c47)

In general it feels like this feature needs more polish and it would be nice to offer additional settings to mimic the behavior of popular editors.

**Comment by slynch8** [comment]
Thanks for the detailed explanations. I agree with all points.

**Comment by slynch8** [comment]
fixed (1.0.249)

**Comment by castano** [comment]
This is so much better, thanks!
