### ISSUE TITLE
Option for FindFunction panel so it ignores structs defined inside functions

### ISSUE THREAD

**Issue by AxelCaroPiraknights** [slynch8/10x#2962]
Initial context:

On version 1.0.234, in an unreal project, the FindFunction panel displays a lot of functions all labeled Impl::
This is because all calls to the unreal "check" macro expand to locally defined structs with member functions.
Although this is correct, these pollute the FindFunction panel with essentially 99% noise, depending on how many checks (asserts) are in the file.

![FindFunction_clutter_01](https://github.com/user-attachments/assets/bbaa95b1-b60e-4a2a-bb4c-640569ec3078)
![FindFunction_clutter_02](https://github.com/user-attachments/assets/e0fb4f83-5654-47b7-aa4e-a2e19f4a0090)

**Comment by slynch8** [comment]
fixed (1.0.249)
