### ISSUE TITLE
New error, breaks all python scripts (Version (1.0.247) ): Cannot import name 'UserHandledResult' from 'Vim'

### ISSUE THREAD

**Issue by moosichu** [slynch8/10x#2976]
Updated 10x this morning, now on opening 10x I get this in the build log:

```bash
Error getting compiled script for Utils.cpython-310
Error getting compiled script for Vim.cpython-310
[python] Traceback (most recent call last):
[python]   File "<PATH-TO-10x>/10x/PythonScripts/VimUser.py", line 2, in <module>
[python]     from Vim import UserHandledResult, Key
[python] ImportError: cannot import name 'UserHandledResult' from 'Vim' (<PATH-TO-10x>\10x\PythonScripts\Vim.py)
```

Will keep investigating... but due to this all my personal python scripts never seem to get loaded/work either (I think?).

**Comment by moosichu** [comment]
Removing that file (`VimUser.py`), the error there goes away. But I still get these:
```
Error getting compiled script for Utils.cpython-310
Error getting compiled script for Vim.cpython-310
```

and my custom commands still seem to be AWOL, will try re-installing now.

**Comment by moosichu** [comment]
Repairing the install didn't fix it... going to try full uninstall and re-install

**Comment by slynch8** [comment]
I think the latest vim script needs the latest early access build

**Comment by moosichu** [comment]
hmm I updated to the latest early access build

**Comment by moosichu** [comment]
10x was telling me that I was on the latest version

**Comment by moosichu** [comment]
Otherwise why would it be on the latest Vim script?

**Comment by slynch8** [comment]
ok, make sure you have the latest vim.py from here https://github.com/slynch8/10x/tree/main/PythonScripts/Vim

**Comment by moosichu** [comment]
A full re-install of the latest early access build of 10x has not fixed the issue for reference. Will try that now.

**Comment by slynch8** [comment]
If you delete (or rename) your appdata PythonScripts folder 10x will re-create it with the default scripts when you next open it

**Comment by moosichu** [comment]
> latest early access version is (1.0.247)
What is the most reliable way to get the current version? I was just grabbing the latest version number from the changelogs on the website which is probably why it's incorrect

**Comment by moosichu** [comment]
I've deleted the AppData PythonScripts folder and I get these errors now:
```
Error getting compiled script for Utils.cpython-310
Error getting compiled script for Vim.cpython-310
Error getting compiled script for VimUser.cpython-310
```

**Comment by moosichu** [comment]
![image](https://github.com/user-attachments/assets/be6e7c07-3601-4694-8084-413b464021f3)
it has made them nice and fresh can confirm that at least.

**Comment by slynch8** [comment]
The changelogs page should show it, although you may need to refresh the page.
This page will always give the latest version, it's what 10x uses https://10xeditor.com/update.php

That error seems normal, I'm getting it as well. Not sure what it means, I'll investigate.

**Comment by moosichu** [comment]
yeah, I've managed to fix the issue with my python scripts now, the step I had locally to copy my scripts folder to roaming was setup incorrectly so when I deleted it my local scripts weren't getting copied over! That's all resolved now thank you!
