### ISSUE TITLE
Feature request: Shortcut to autoalign multicursors

### ISSUE THREAD

**Issue by Wassimulator** [slynch8/10x#2977]
https://github.com/user-attachments/assets/c25ff674-5af7-438a-a576-2263b936ba48

Sublime text has this in its Alignment add on. adds spaces to all the cursors left of the most-right one.

**Comment by slynch8** [comment]
done. Early access build (1.0.248)

**Comment by slynch8** [comment]
Done. Added AlignMultiCursor command (alt+A) (1.0.249)
