### ISSUE TITLE
Add breakpoints to external debugger

### ISSUE THREAD

**Issue by mathias234** [slynch8/10x#3]
Hey, I'd like to see a feature where you can add a breakpoint to an external debugger.

Some standalone debuggers have some way to add a breakpoint through command line arguments. 

Example for remedybg:
`remedybg.exe add-breakpoint-at-file filename line-number`
`remedybg.exe remove-breakpoint-at-file filename line-number`
This will add a breakpoint to the already running process of remedy.

I imagine some system like the one we have for Run, Debug, Build etc.. except it also contains variables for file and line nr

**Comment by Muzza** [comment]
I did this in a python plugin. Below is the code I've used (part of a larger file so there may be some unnecessary imports)

```python
import N10X
import sys,os,subprocess,glob,re,time
import threading
from subprocess import Popen
from subprocess import PIPE, run
from subprocess import check_output

def process_exists(process_name):
    call = 'TASKLIST', '/FI', 'imagename eq %s' % process_name
    # use buildin check_output right away
    output = subprocess.check_output(call).decode()
    # check in last line for process name
    last_line = output.strip().split('\r\n')[-1]
    # because Fail message could be translated
    return last_line.lower().startswith(process_name.lower())

def IsRemedyBGRunning():
	return process_exists( "RemedyBG.exe" )

def SetBreakpoint():
	if IsRemedyBGRunning()==True:
		(x, y) = N10X.Editor.GetCursorPos()
		p = Popen(["C:/Apps/Dev/remedybg/remedybg.exe","add-breakpoint-at-file",N10X.Editor.GetCurrentFilename(),str(y+1)], shell=False,stdin=None,stdout=None,stderr=None,close_fds=True,creationflags=DETACHED_PROCESS)
```

Then in KeyMappings I have `F9: SetBreakpoint()`

You don't get to see the breakpoint in 10x, and you can't currently toggle breakpoints (as 10x does not know where the existing breakpoints are - although I could extend the python code to handle that). If we had a way to display custom markers in the 10x margin, similar to bookmarks, then I think you could get the full experience using a python plugin.
We could also lobby the remedybg guy for an interface to retrieve existing breakpoints.

**Comment by mathias234** [comment]
> I did this in a python plugin. Below is the code I've used (part of a larger file so there may be some unnecessary imports)
> 
> ```python
> import N10X
> import sys,os,subprocess,glob,re,time
> import threading
> from subprocess import Popen
> from subprocess import PIPE, run
> from subprocess import check_output
> 
> def process_exists(process_name):
>     call = 'TASKLIST', '/FI', 'imagename eq %s' % process_name
>     # use buildin check_output right away
>     output = subprocess.check_output(call).decode()
>     # check in last line for process name
>     last_line = output.strip().split('\r\n')[-1]
>     # because Fail message could be translated
>     return last_line.lower().startswith(process_name.lower())
> 
> def IsRemedyBGRunning():
> 	return process_exists( "RemedyBG.exe" )
> 
> def SetBreakpoint():
> 	if IsRemedyBGRunning()==True:
> 		(x, y) = N10X.Editor.GetCursorPos()
> 		p = Popen(["C:/Apps/Dev/remedybg/remedybg.exe","add-breakpoint-at-file",N10X.Editor.GetCurrentFilename(),str(y+1)], shell=False,stdin=None,stdout=None,stderr=None,close_fds=True,creationflags=DETACHED_PROCESS)
> ```
> 
> Then in KeyMappings I have `F9: SetBreakpoint()`
> 
> You don't get to see the breakpoint in 10x, and you can't currently toggle breakpoints (as 10x does not know where the existing breakpoints are - although I could extend the python code to handle that). If we had a way to display custom markers in the 10x margin, similar to bookmarks, then I think you could get the full experience using a python plugin.
> We could also lobby the remedybg guy for an interface to retrieve existing breakpoints.

This is def a cool way todo this for now. But talking with Stewart it sounds like he is willing to implement a proper system for calling the remedy cmdline args

**Comment by slynch8** [comment]
nice script! I'll add support for showing breakpoints soon. That's a good point about getting breakpoints back from remedybg, really need that.

I'm having a think about a general debugger interface so that implementations can be added for different debuggers.

**Comment by Muzza** [comment]
Having it built in would obviously be very nice. The limiting factor may well be remedybg rather than 10x though - so I suspect we'd need help on the remedybg side. For example, changing your start-up project in 10x introduces difficulties. Currently my python script has to kill the remedybg process, and restart it. Preserving breakpoints or open files becomes difficult or impossible. (if anyone else is doing this I'd love to hear how?)

All the same it is a very worthy goal, as having 10x and RemedyBG working nicely together is the ultimate in a full ultra-fast Visual Studio replacement!

**Comment by slynch8** [comment]
Can you store a global list of breakpoints and then re-apply them after restarting remedybg? 

It sounds like people are very close to getting this working with scripts. I could easily add a SetBreakpoint to the python interface so you can see the breakpoints in 10x. I will also work on a built-in solution though.

**Comment by mathias234** [comment]
Remedy has the session file which contains all the information like breakpoints, not sure about the format though

**Comment by Muzza** [comment]
> 
> 
> Can you store a global list of breakpoints and then re-apply them after restarting remedybg?
> 
> It sounds like people are very close to getting this working with scripts. I could easily add a SetBreakpoint to the python interface so you can see the breakpoints in 10x. I will also work on a built-in solution though.

You could re-apply them yes, but it would be a one-way street. When debugging on RemedyBG any breakpoint changes you make there would not be returned to 10x, so the two would be out of sync.

I've been getting by using the script solution, but its not perfect. If you added a way to visually display breakpoints, and if we can get RemedyBG to add some more functionality I think we could have the whole thing working in a python script. 

One other feature that would help would be a script method to retrieve the exe and working directory settings from the Visual Studio project settings. Currently I use GetActiveProject and have some code to map that to an exe that I pass to RemedyBG, but that is specific to my project.

**Comment by slynch8** [comment]
10x knows the exe path, I can expose that to python.

**Comment by slynch8** [comment]
I've just uploaded a build with support for Breakpoints (0.17.4.0)
- added ToggleBreakpoint command (F9)
- added AddBreakpoint and RemoveBreakpoint python functions
- added AddBreakpointAddedFunction and AddBreakpointRemovedFunction python functions
- added RemoveAllBreakpoints python function

I've also added a new Help menu with a List Commands to help you with your scripts.

**Comment by slynch8** [comment]
I've added a new python function: GetWorkspaceExePath()
This works for sln workspaces as well as 10x workspaces

**Comment by Muzza** [comment]
AddBreakpointAddedFunction / AddBreakpointRemovedFunction  are working well for me.
Its nice to have the breakpoint indicator in 10x, but can you change the shape or size of it so both bookmarks and breakpoints can be visible when on the same line?

**Comment by slynch8** [comment]
fixed in (0.17.14.0), now shows both breakpoints and bookmarks

**Comment by slynch8** [comment]
Can I close this now? At some point I want to add built in support for external debuggers, but that's a bigger task

**Comment by mathias234** [comment]
Yeahtthe issue can be closed now
