### ISSUE TITLE
New Workspace dialog crashes 10x when "Close All" is chosen on '...' menu

### ISSUE THREAD

**Issue by IRooc** [slynch8/10x#307]
When you open Create Workspace dialog, and click the '...' button on the top right and select 'Close All'. All tabs go away, no idea if this is expected but ok. If you then want to close the dialog it crashes.

[10x_crash_2021_7_23_8_31_50.dmp.gzip.zip](https://github.com/slynch8/10x/files/6866926/10x_crash_2021_7_23_8_31_50.dmp.gzip.zip)

NOTE (added .zip suffix to the crashdump so github would take it...)

**Comment by slynch8** [comment]
removed the ... button. Fixed (0.27.8)
