### ISSUE TITLE
A definitions panel

### ISSUE THREAD

**Issue by Ziv-spec** [slynch8/10x#310]
## A panel to view all of the definitions inside your project. 
This should (they way I see it) be a global definitions panel where you are able to search for function names, structs, enums and so on.. just by typing the name for said function struct and so on..
For people like me prefer to write or just know the name of the definition and want to jump to it, this would be an awesome feature

**Comment by slynch8** [comment]
See the Find-Symbol panel. Parser Menu -> Find Symbol... You can dock the panel if you want.

**Comment by Ziv-spec** [comment]
OK great, I did not notice it.
