### ISSUE TITLE
Artifacts on checkbox text

### ISSUE THREAD

**Issue by rishineedscookies** [slynch8/10x#312]
There is a strange graphical artifact for checkbox text (haven't noticed it anywhere else).

You can see a strange bordering effect around the text here:
![image](https://user-images.githubusercontent.com/7583396/126912813-e82d8cb1-1af6-439c-8db3-92daa488e36c.png)

It isn't present in other text:
![image](https://user-images.githubusercontent.com/7583396/126912834-99075490-0649-4a60-ae09-7166eaf47f5f.png)

**Comment by slynch8** [comment]
Well spotted.
Fixed (0.27.9)
