### ISSUE TITLE
[BUG] second all black workspace panel opens

### ISSUE THREAD

**Issue by JacobTDev** [slynch8/10x#313]
Repro steps: 
1. File -> Open Folder
2. Close 10x
3. Open Again
4. File -> Recent Workspaces -> Some folder you were working on before

 What happens: 
 Everything works as expected, but two workspace panels open, one of which is all black (and removable).

 **NOTE:** You need to have a workspace panel open by default when you start the program, else it won't happen.

Attached image for more details:
![workspacebug](https://user-images.githubusercontent.com/45700744/126914426-871d2321-1095-49ee-9949-7379b8958463.png)

**Comment by slynch8** [comment]
Awesome! This is the bug I've been looking for that been causing most of the crashes - thank you!
Fixed (0.27.9)
