### ISSUE TITLE
Build command input does not take scrolled width into account when setting the cursor with mouseclick

### ISSUE THREAD

**Issue by IRooc** [slynch8/10x#314]
When the build command is larger than the width of the input and you scroll to the right, the mouse click does not put the cursor at the correct position.
![Animation](https://user-images.githubusercontent.com/5981147/126953813-92589d3e-b4bd-42c8-850e-08226d07acbc.gif)

The cursor is put at the position without the scrolled part...

Nice editor!

**Comment by slynch8** [comment]
Thanks! :-) 
Fixed in (0.27.9)
