### ISSUE TITLE
Make N10X.Editor.SaveAll() return success

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#315]
I have some scripts that do a N10X.Editor.SaveAll() call before then processing the files.
Sometimes SaveAll fails because my backup system has momentarily locked the file. When this happens my script runs anyway, delays 10x for a few seconds, and only then do I get the pop-up message that a file did not save.
If SaveAll() could return success, I could detect this, cancel the script early and not have to suffer through the delay each time.

**Comment by slynch8** [comment]
SaveAll now returns a bool. And I've increased the save retry count so hopefully it won't fail so much.
