### ISSUE TITLE
Allow custom build commands without visual studio projects file

### ISSUE THREAD

**Issue by TaffyQuinzel** [slynch8/10x#316]
For most of my projects I don't use the visual studio projects file and have a simple batch script to build.
To work around this I created a dummy visual studio project executing my build command.

A custom build command option could be added to the editor settings and would be nice for a cleaner setup. However I don't know if that is withing the spirit of the project and something you want to add or not. Especially because it can be easily implemented via the visual studio projects file.

**Comment by slynch8** [comment]
You can achieve this with a 10x Workspace. File Menu -> Create Workspace. You can add folders to the workspace by right clicking on the workspace tree node. And you can set the build command by right clicking on the workspace node and selecting Properties.

**Comment by TaffyQuinzel** [comment]
Awesome! I'll start using the workspaces.
