### ISSUE TITLE
ALT codes focus and accented characters with CTRL left/right

### ISSUE THREAD

**Issue by Alouett-e** [slynch8/10x#317]
- Entering a character via ALT codes (example ALT+145) will move the focus to the title bar, need to repress ALT to go back to the text. Some languages like French sadly require alt codes to write common words like "eggs" or every words in capital.

- Can't use the CTRL + left/right shortcut with non ASCII characters (example éaèaçaœaàaæaùaïaëa ), it will stop the cursor at each accented character.

**Comment by slynch8** [comment]
fixed (0.27.16)
