### ISSUE TITLE
Show whitespace issues

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#32]
From this screenshot, the tabs start at the vertical lines, but each tab is shown further to the right than the previous one.
This continues throughout the line, and so later tabs are significantly offset from their real positions.

![2021-02-08 07_52_24-Window](https://user-images.githubusercontent.com/1583441/107159199-a6638f00-69e2-11eb-9cab-573bac793f6a.png)

Also, some lines end in a dot, some end in two dots, and some end with no dots. I'm not sure what that is about. Often the dots are several spaces to the right of where the line actually ends. I would expect no dots. Maybe its related to the tabs showing wrong?

![2021-02-08 07_54_06-Window](https://user-images.githubusercontent.com/1583441/107159234-dad74b00-69e2-11eb-867d-a1a37b0a8157.png)

(I turned down the colour of the whitespace as the default was a bit too intrusive, so you may have to look carefully on the second screenshot to see the dots at the right side)

**Comment by slynch8** [comment]
have you changed the tab width? (Editor.Tab Width)

**Comment by Muzza** [comment]
Its 4 which I think is the default.

**Comment by slynch8** [comment]
I see the problem, the -> character is too wide, what font are you using, is it fixed-width?

**Comment by Muzza** [comment]
You're right, its the font. I'm using JetBrainsMono-Medium from https://www.jetbrains.com/lp/mono/
I just checked and they had a newer version of the font, which does seem to fix the problem for me.

**Comment by slynch8** [comment]
that's good, I will fix this anyway

**Comment by Muzza** [comment]
Actually there are still issues. 
I still get occasional dots at the end of lines, and sometimes the tabs are placed on the character before the real tab.

![2021-02-08 08_32_27-Window](https://user-images.githubusercontent.com/1583441/107160091-3f48d900-69e8-11eb-8c71-ed395f939779.png)

The tab after _NotOK* is a space too early. And also has a dot at the end. There is also no space marker in the brackets for B( )

**Comment by slynch8** [comment]
could you paste that line for me?

**Comment by slynch8** [comment]
don't worry, I've got it now

**Comment by Muzza** [comment]
ok good. FYI with the latest version of that font I'm using JetBrainsMonoNL-Medium.ttf

**Comment by slynch8** [comment]
fixed (0.21.32.0)
