### ISSUE TITLE
Build commands fails with "CreateProcess error: Invalid Handle"

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#321]
Every time I try to run a build/rebuild/clean/run/debug command, it fails with the error "CreateProcess error: Descripteur non valide" (my windows is in French), even if it's as simple as just `echo Foo`. I've tried running the editor as an administrator just in case and doesn't change anything. Note that the only command that I found to be working is `cmd`.

I have version 0.27.12.0 with Windows 10 Entreprise.

**Comment by slynch8** [comment]
From my tests it looks like the commands such as 'echo Foo' are succeeding, it is output in the Build output panel. The error can be ignored for now. The error goes away if you use a batch file instead of a command. But I will fix the error message in the next build.

**Comment by bousquetm** [comment]
Thanks, tell me if you need anything for me to test.

**Comment by slynch8** [comment]
Ignore my previous comment, you are right, it not executing anything. To execute a bat file use cmd /c test.bat. 

I'll automatically prefix it with cmd or cmd /c in the next build.

**Comment by slynch8** [comment]
This should be fixed in (0.27.17)

**Comment by bousquetm** [comment]
I confirm that this is indeed fixed with 0.27.17 !
