### ISSUE TITLE
Windows environment variables are not parsed

### ISSUE THREAD

**Issue by LordSk** [slynch8/10x#324]
When opening a solution, if a path contains an environment variable it is discarded.

Example:
`<AdditionalIncludeDirectories>%TM_SDK_DIR%\headers;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>`

Manually replacing the variable by the corresponding value fixes the issue.

**Comment by LordSk** [comment]
Update, this is not *always* the case apparently.

This one works fine:
[test1.zip](https://github.com/slynch8/10x/files/6911189/test1.zip)

This one does not:
[gameplay_sample_interaction_system.zip](https://github.com/slynch8/10x/files/6911190/gameplay_sample_interaction_system.zip)

**Comment by slynch8** [comment]
The project that doesn't work is using % environment variables (instead of $() visual studio variables). I've added support for this in (0.27.20)
