### ISSUE TITLE
It seems that creating workspace doesn't change working directory

### ISSUE THREAD

**Issue by maxphilippov** [slynch8/10x#325]
I'm on latest Win10 x64. 10x version is 0.27.18.0
When I create workspace inside a folder of my existing project 10x doesn't add any files to the project.
When I tried to change build command to my build.bat it can't find the file unless I specify absolute path. If I specify absolute path it doesn't find any source files since they're specified relatively to the build script.
When I try to do Workspace Search (ctrl+shift+s) it shows my `SettingsPath` at the bottom. And looks like it searches there.

I don't know what should I provide. Am I missing something here? This is the log output inside the editor:

> [10x] Opening workspace C:/dev/work/catelda/testing2.10x_workspace
[10x] Read workspace time: 3 ms
[10x] Read workspace time: 28 ms (async)
[10x] ReadSolutionFinalizer time: 27.71 ms
[parser] waiting for process cache lock...
[parser] obtained process cache lock...
[parser] Reading workspace...
[parser] Reading workspace cache...
[parser] Parsing files (32)...
[parser] Read cache complete
[parser] Read cache time: 17 ms
[parser] Finished reading workspace files
[parser] Finished parsing
[parser] Updating syntax highlighting...
[parser] Writing cache...
[parser] waiting for process cache lock...
[parser] obtained process cache lock...
[parser] Waiting for parser to stop...
[parser] Write started...
[parser] Finished writing cache
[parser] Write cache time: 9 ms
[parser] Finished updating syntax highlighting
[parser] Parse complete
[parser] total parse time: 43 ms
[parser] Parse complete

**Comment by slynch8** [comment]
When creating a workspace make sure that Sync Files checkbox is checked. Or you can right click on a workspace and select properties and set Sync Files there. It will then automatically add the files in the folder.

The build command relative path is a bug, I'll get that fixed.

Workspace search will find all files in the workspace and a few other files such as the python scripts and settings files. If you don't have any files in the workspace then it will only show those.

**Comment by slynch8** [comment]
The build command now sets the working directory to be the workspace folder. Build (0.27.19).

Let me know if you're still having problems.
