### ISSUE TITLE
Opening command prompts continuously

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#33]
The update after the whitespace fix seems to be running command prompts constantly.
Its hard to kill the process as it pops up so many. They say something like TASKLIST on the top of them... ?

**Comment by slynch8** [comment]
I can't reproduce this, would it be possible to grab a screenshot?

**Comment by slynch8** [comment]
could it be one of your python scripts?

**Comment by Muzza** [comment]
I can try disabling my script tomorrow. It was happening after a minute or less of normal editing and I wasn’t activating any script key shortcuts. It also happened after every restart of 10x and locked up the system so much I had trouble killing the process. 
Still it’s not impossible that something very odd was happening in my script so I will investigate further.

**Comment by slynch8** [comment]
it's worth having a look at the log file, that might give a clue  (%appdata%\10x\*.log)

**Comment by slynch8** [comment]
I have a theory: if 10x is connected to a VS instance, when it loses focus it will sync the breakpoints. If you have a script that runs when breakpoints are changes and it brings up a command prompt it will lose focus again. I'll put in a guard to catch this.

**Comment by slynch8** [comment]
(0.21.33.0) has a guard against infinite recursion in syncing breakpoints in case that's it.

**Comment by Muzza** [comment]
I had actually opened VS just before this problem appeared so it could be that (I don't usually have VS open).
It has not happened so far this morning with the new version. I've got VS open to test that, so I'll see what happens throughout the day.

**Comment by Muzza** [comment]
I've had no problems since the update.

**Comment by Muzza** [comment]
I started seeing this again today. It happens when I have the same project open in Visual Studio as the one in 10x.
I'm not using VS for debugging, its just open for editing purposes.
Every time I alt-tab into 10x, it freezes for 3 or 4 seconds and I can see a series of command prompts being spawned and immediately disappearing.

**Comment by slynch8** [comment]
Can you send me your log file please?

**Comment by slynch8** [comment]
I'm guessing this is still the breakpoint syncing. In the latest build I've added a VisualStudioSync setting so that you can turn it off.

**Comment by Muzza** [comment]
Turning that option off fixes it, thanks.
