### ISSUE TITLE
Whitespace oddly coloured

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#34]
Some of my whitespace shows normal, and others show with the text selection colour behind it.
Selecting and unselect does nothing, but if I scroll away and return to the text then it goes away.

This screen is dark but two of the tabs have the blue selection colour in their background. Occasionally it ends up littered across all of the whitespace which looks very messy.
![2021-02-12 08_03_19-Window](https://user-images.githubusercontent.com/1583441/107698561-d5db0a00-6d08-11eb-8ccd-f276c7d51957.png)

**Comment by slynch8** [comment]
fixed (0.21.37.0)
