### ISSUE TITLE
Setting to align new lines to the open bracket

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#349]
add setting to align new lines to the open bracket (for function calls over multiple lines)

```
Function(arg1,
         arg2,
         arg3);
```

**Comment by stan680** [comment]
Looking forward to this one as it's a common style in projects I work on :)

Would this feature extend to support for things like:
```
// Aligning to other open brackets - e.g. an if
if(something &&
   something_else)

// Aligning to brackets, nested
if(function(a_parameter,
            another_parameter) &&
   another_thing)
{
}

// This one might be a stretch but feels conceptually similar?
// I'd certainly appreciate the option
bool value = something &&
             something_else;
```

I'd also be rooting for tabs for indentation and spaces for this bracket alignment (so devs can change tab-width without breaking all the aliignment).

**Comment by slynch8** [comment]
done (0.33.6).

Also includes requests from @stan680 although the conditional and equals ones need to be turned on in the settings. I've also added an AlignUsesSpaces setting to make them use spaces instead of tabs.
