### ISSUE TITLE
Too easy to remove read-only

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#35]
I find I accidentally click on the little lock icon, especially if I'm closing a bunch of tabs with the middle mouse button (because the lock icons position moves depending on the length of the filename).
When it happens I have to open explorer and restore it. If I don't notice doing it, then it has big implications for source control.
I feel this option should be in the right click menu, or have some kind of confirmation pop up. Anything to make it less likely to be accidentally activated.

**Comment by slynch8** [comment]
Agreed. I've moved the Read Only to the drop down menu. 
Fixed (0.21.38.0)
