### ISSUE TITLE
Incorrect automatic spacing in literal suffixes

### ISSUE THREAD

**Issue by Botondar** [slynch8/10x#366]
When writing integer literals with the `ll`  or `ull` suffixes, or writing scientific float literals (such as `1e6f`)  the editor will incorrectly insert a space after typing the semicolon. For example `1000ll;` becomes `1000l l;`.

EDIT: Version is 0.28.4

**Comment by slynch8** [comment]
If you want you can turn off formatting until I get this fixed (Parser.AutoFormat setting)

**Comment by slynch8** [comment]
fixed (0.28.5)

**Comment by Botondar** [comment]
Thought I'd try examples from the cppreference website ([integer](https://en.cppreference.com/w/cpp/language/integer_literal) and [float](https://en.cppreference.com/w/c/language/floating_constant))
Found more cases (IMO apart from the first two they're non-issues):
- Hex literals (the behavior is the same as with dec literals before the patch)
- `lu` and `llu` suffix
- Binary literals (I see that this has its own issue)
- There are also a ton of weird cases with floats, but those are much rarer so I'd imagine they'd be a lower priority.
- The syntax highlighting is also wrong when using the `'` separator, but that's a separate thing.
