### ISSUE TITLE
Bookmarks at top of documents

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#37]
A lot of my files have bookmarks at line 0 or line -1, both of which are impossible to remove without manually editing the 10x workspace_settings file.
I don't know exactly how it happens, I can't reproduce it, but it seems to inevitably happen on every file I use bookmarks in.

**Comment by Muzza** [comment]
I just tried to delete all bookmarks and 10x hung on me.
After looking at the workspace, I have 27000 bookmarks and 20000 breakpoints. Most of them on invalid lines. In reality I had maybe 20 bookmarks and no breakpoints, so something bad is happening there.
Also, can we get an option and keyboard shortcut for 'Remove all breakpoints from current file' please? (Ctrl Shift F2 is what Visual Studio used to use)

**Comment by slynch8** [comment]
That does sound very broken. I'll look at this next. And I'll add a 'Remove all breakpoints' command.

**Comment by slynch8** [comment]
fixed (0.21.48.0)

It was losing the line indices when a file was modified outside of 10x, and a few other bugs as well. I've reset all breakpoints and bookmarks to clear out any bad data. And I've added RemoveBookmarksFromFile and RemoveBreakpointsFromFile commands.
