### ISSUE TITLE
Under certain conditions, trying to remove a file from a 10x workspace results in it being added to the exclude filter

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#370]
To repro this:

1. Create a workspace, uncheck "recursive" and "sync"
2. Add a few files to the workspace
3. Right click on a file and click "remove"
4. Instead of the file disappearing from the workspace view, it gets added to the "exclude" field of the workspace settings.

Tested in version 0.28.9. Obviously very minor priority, worst case one can simply edit the workspace file themselves and remove the file.

**Comment by slynch8** [comment]
fixed
