### ISSUE TITLE
Support for C99 designated initializers

### ISSUE THREAD

**Issue by kaervin** [slynch8/10x#371]
Hello,
I would be really glad if the auto-completion/formatting could properly support C99 designated initializers.

thank you.

**Comment by septag** [comment]
Just wanted to add that this is not just C99 specific anymore, C++20 also has designated initializers.

**Comment by slynch8** [comment]
example:
```c++
struct Test_Thingy {
  float some_field              = 0;
  const char* some_text_field = nullptr;
};

int main(void) {
  Test_Thingy t1 = {
      .some_field      = 1,
      .some_text_field = "hi",
  };
  return 0;
}
```

**Comment by slynch8** [comment]
done (1.0.74)
