### ISSUE TITLE
Cannot debug solution with space in its name

### ISSUE THREAD

**Issue by uucidl** [slynch8/10x#373]
I have a solution for Visual Studio 2019 with a space in its target and names. In 10x when trying to Debug the executable msbuild barfs up an error:

```
msbuild /t:"First%20Second" /p:Configuration="Debug" /p:Platform="x64" /verbosity:minimal "First Second.sln" /m

MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.NullReferenceException: Object reference not set to an instance of an object.
```

I figured maybe this had to do with the URL Encoded "First%20Second" so I ran it from the command line instead with:

```
msbuild /t:"First Second" /p:Configuration="Debug" /p:Platform="x64" /verbosity:minimal "First Second.sln" /m
```
And the build was successful

**Comment by slynch8** [comment]
fixed (0.28.11)
