### ISSUE TITLE
Search with Ctrl-F does not work after interacting with the Scroll Map

### ISSUE THREAD

**Issue by uucidl** [slynch8/10x#383]
After interacting with the Scroll Map it is not possible to use the Ctrl-F shortcut without first clicking once more in the text pane.

A sequence that I find common is that I first search spatially with the map, fail to find what I want, then type Ctrl-F "My Text String"

For some reason until I click again in the text pane the Ctrl-F shortcut does not operate. However "My Text String" often ends up in the text at the point I was at.

**Comment by slynch8** [comment]
fixed (0.28.16)
