### ISSUE TITLE
Goto Definition does not work with extern functions

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#385]
See comments in code. Basically Alt-G is working when a declaration is void X() but not when a declaration is extern void X()

```cpp
// file1.cpp
void DoesNotWork( void )
{
}

void DoesWork( void )
{
}
```

```cpp
extern void DoesNotWork( void );	// Alt-G on me does nothing !!
void DoesWork( void );	// Alt-G on me will goto definition in other c file

void main()
{
	DoesNotWork();	// Alt-G on me will goto declaration ok
	DoesWork();		// Alt-G on me will goto declaration ok
}
```

**Comment by slynch8** [comment]
The extern DoesNotWork function does work now. I think I fixed this a few builds back. I'm not sure it covers every case, so let me know if you're still having problems with this.

**Comment by slynch8** [comment]
Clean re-parse fixed it for Zenity. Please re-open if it's still an issue.
