### ISSUE TITLE
crash adding workspace to itself

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#391]

**Comment by dangmoody** [comment]
So I've noticed that adding a workspace to _any_ existing workspace via 10x will cause it to crash.  However, if I take the example .10x_workspace file from your blog post where you talk about workspaces and load _that_ via 10x then it seems to work fine.

**Comment by slynch8** [comment]
I couldn't get the crash but I fixed another issue that might be related. Let me know if you're still getting it in (0.30.22)

**Comment by dangmoody** [comment]
Fixed! Thanks.  =)

**Comment by slynch8** [comment]
\O/
