### ISSUE TITLE
Better one-by-one Find/Replace keyboard navigation

### ISSUE THREAD

**Issue by litterattus** [slynch8/10x#396]
The default behavior of Enter keypress in Find/Replace is to replace all occurrences (the behavior of the "All" button), and the only keyboard-only way of using one-by-one replace (the behavior of the "Replace" button) is rather cumbersome, i..e, you have use arrow keys or (shift+)tab to select the appropriate button and then press enter.

There should be a quicker keyboard-only way to achieve this (e.g., shift+enter for replace all; enter for one-by-one replace) as well as quickly being able to skip individual occurences.

**Comment by slynch8** [comment]
fixed (0.28.20)
