### ISSUE TITLE
Strange ToggleComment behavior for single-line comments

### ISSUE THREAD

**Issue by litterattus** [slynch8/10x#401]
Consecutive uses of ToggleComment result in inconsistent formatting: if the cursor is somewhere in the non-whitespace part of 2nd line and ToggleComment is used at least twice in a row, after the first time cursor jumps to the beginning of next line, ignoring the position (column) in the previous line.
```
void foo() {
    a();
    b();
    c();
}
```
This leads to the following:
```
void foo() {
    //a();
//    b();
    c();
}
```
Furthermore, if the cursor is in the whitespace before text (indentation using spaces), the `//` is inserted right at that position, instead of beginning of the line or a position that matches the indentation. E.g. if you ToggleComment while the cursor is line 2, col 3 of the first code fragment, you get the following:
```
void foo() {
  //  a();
    b();
    c();
}
```

**Comment by slynch8** [comment]
fixed (0.28.21)
