### ISSUE TITLE
Freezes and large memory usage

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#41]
For the first time ever I noticed 10x was doing a Visual Studio and pausing whenever autocomplete needed to pop up.
Sometimes for a split second, sometimes for a number of seconds.
Task manager reported 10x was using 22GB of 32GB system, which seemed to be the cause. Closing 10x took a long time with the memory usage slowly decreasing.
Restarting 10x it goes back to using about 4GB.

**Comment by Muzza** [comment]
Its quickly gone up to 18GB again

**Comment by slynch8** [comment]
wow, major leak. On it.

**Comment by slynch8** [comment]
I've fixed some leaks in (0.22.11.0), but wasn't able to reproduce any leaks on this scale, so not sure if I've fixed it or not.

I suspect it's caused by changing files outside of 10x and 10x reparsing files on startup. Let me know if you see it again.

**Comment by Muzza** [comment]
I have a script that runs on a keyboard shortcut to rebuild my visual studio projects (when I add or remove a file) and then reload the workspace.
Every time I run it (with the latest build) the memory usage is going up several GBs. Looks like I can reproduce it by just the File menu then Recent Workspaces and reopening the workspace I already have open.

This can't have been the same as the problem I encountered originally because I wasn't reloading the workspace, but it may be a related issue.

**Comment by slynch8** [comment]
I've fixed the workspace closing not releasing memory (0.22.13)

**Comment by slynch8** [comment]
(0.22.14) has another leak fix, think this might be the one.

**Comment by Muzza** [comment]
I've had no further problems with this, thanks.
