### ISSUE TITLE
Visual bug occurring when searching

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#417]
The repro of this takes a bit of a setup, but here goes:

1. Open a file and duplicate it in 2 panes
2. On one pane, search for something that has at least one result, so that the editor highlights it
3. Go to the other pane (don't deselect the search result) using ctrl-tab
4. Move the cursor at least one line above the search result of the first pane
5. Insert or delete a line

The result is that the selection turns into garbled characters

**Comment by slynch8** [comment]
fixed (0.28.28)
