### ISSUE TITLE
Triple clicking is not very reliable

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#422]
To explain myself better: I expect that when I double click a word it gets selected, and when I triple click the whole line gets selected. This works, but not all the times. Some times I end up clicking many times until this catches on.

Also, triple clicking outside the end of the line is also pretty erratic, eventually the line will be selected but it is unclear how many clicks it takes each time.

**Comment by slynch8** [comment]
let me know if this is still a problem in (0.28.44)

**Comment by ggnkua** [comment]
That is spot on now! Closing this.
