### ISSUE TITLE
cursor blinking behaviour customisation

### ISSUE THREAD

**Issue by khvorov45** [slynch8/10x#430]
It'd be great to have the option to stop the cursor from blinking. Also, 10x doesn't seem to follow window's ["cursor blink rate"](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getcaretblinktime) (control panel -> keyboard) which I guess wouldn't matter so much with internal customisation options.

**Comment by slynch8** [comment]
done (0.30.37)
