### ISSUE TITLE
Add command to force-reconstruct all parsed information

### ISSUE THREAD

**Issue by kaervin** [slynch8/10x#431]
Hello,

Currently 10x has some bugs where outdated symbols and autocomplete-suggestions from files which I have deleted are still present.
Other symbols of the very same files are not retained any longer.

Additionally, the type-information of some structs seem to not be recognized, although they have been in the past, and very similar structs from the same file are recognized without problems.

There doesn't seem to be much of a pattern to this, so I don't really know how I can help you to track down the bugs with the information I have.

What I would personally wish for is a command which reparses all the information for the active workspace.
This way, the symptoms can at least be cured in a way.

Thank you.

**Comment by slynch8** [comment]
Yes, I'm aware of some bugs with things not always updating, hopefully I'll be able to track these down. And I'm going to be working on a Reparse command next. For now you can do it manually by closing 10x and deleting the this folder: %appdata%\10x\cache\parser\<workspace>

**Comment by kaervin** [comment]
Thank you, deleting the folder did the trick!

**Comment by slynch8** [comment]
You can now reparse from the menu. Although hopefully you shouldn't ever have to.
