### ISSUE TITLE
Editor randomly freezes

### ISSUE THREAD

**Issue by bousquetm** [slynch8/10x#432]
It's hard to reproduce but sometimes when I use 10x it just freezes for a long time (I measured it once and it lasted about 3mn). There's no obvious pattern: sometimes it happens when I click around, sometimes it's when I open the 'Find File' dialog, sometimes it happens when I open another menu. 

Note that the editor is usually very fast and my workspace is huge (millions of lines of code across tens of thousand files).

If you need me to do some tests just tell me as I guess that's not going to be easy to fix ;)

**Comment by slynch8** [comment]
Could it be paging memory? At the moment 10x does use up a lot of memory for large workspaces.

If it isn't memory, next time it happens could you force a crash dump? You can use ProcDump to generate a minidump.
[https://docs.microsoft.com/en-us/sysinternals/downloads/procdump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump)

Thanks.

**Comment by bousquetm** [comment]
I haven't looked at the memory usage during a freeze but I doubt that's the problem since I have 64GB or RAM. Next time it freezes, I'll upload a dump!

**Comment by bousquetm** [comment]
Wait I just got confirmation that I don't have the authorization to upload dumps like that, the information is too sensible for my company... I'm sorry :(

**Comment by slynch8** [comment]
That's a shame, but I understand. Maybe I could give you my symbols and you could look at the dump yourself? I just need to know  the callstack of the main thread. Are you on the latest build?

**Comment by bousquetm** [comment]
That's an excellent idea. I'm on version 0.27.19.0.

**Comment by slynch8** [comment]
It's tricky to find the symbols for that build, they are buried somewhere in my symbol server and I don't know how to find them. Could you update to the latest?

**Comment by bousquetm** [comment]
Mmmh that's strange, when I click on 'Check For Updates', it takes a few minutes (the editor doesn't freeze) and then says I'm already on the latest one. Guess I'll download it directly from the website.

**Comment by slynch8** [comment]
That's weird. It checks this page for the current version, what does it show for you?
[https://www.10xeditor.com/update.php](https://www.10xeditor.com/update.php)

**Comment by bousquetm** [comment]
It says "php_output:0.28.31.0"

**Comment by bousquetm** [comment]
After upgrading from 0.27.19.0 to 0.28.31.0 I haven't had any freeze in one week so I guess that's solved issue. I'll keep the symbols you sent me for a little while so if I experience freezes again I'll try to debug it.
