### ISSUE TITLE
Crash when toggling the status bar menu option

### ISSUE THREAD

**Issue by philoez98** [slynch8/10x#437]
Toggling the "status bar" menu option causes the application to crash. In my case it happens 100% of the time, with no special configuration. 
I already uploaded a crash dump, but if needed, I can provide more details / additional dumps.
I'm on the latest version (0.28.42) but it happens also on the previous ones (I tested up to version 0.28.40).

Phil

**Comment by slynch8** [comment]
fixed (0.28.43)
