### ISSUE TITLE
Go to Next Error goes to next line of the same error

### ISSUE THREAD

**Issue by nem0** [slynch8/10x#45]
Steps to reproduce:
1. build any source code with errors, getting output like this:
![image](https://user-images.githubusercontent.com/153526/111987552-a8575c80-8b0f-11eb-912b-50f54be4b205.png)
2. press F8 - `Go to Next Error`, it jumps to first error
3. press F8 again
4. observe that it does not jump to next error, just highlights next line of the same error in output

Note: pressing F8 several times jumps to next error, this is especially annoying for template errors, which can span **a lot** of lines

**Comment by slynch8** [comment]
fixed (0.22.26)

**Comment by nem0** [comment]
Works great. VS is fixing this for months, you did it in 5 hours 👍
