### ISSUE TITLE
Docked output is not always restored in correct place

### ISSUE THREAD

**Issue by nem0** [slynch8/10x#46]
Steps to reproduce:
1. dock windows like this:
![image](https://user-images.githubusercontent.com/153526/111999086-ee66ed00-8b1c-11eb-9ac1-023b2a8238d9.png)
2. close the output window
3. build project
4. observe that output window pops up as undocked
![image](https://user-images.githubusercontent.com/153526/111999308-22daa900-8b1d-11eb-8640-0bf5e5537405.png)

Expected result: after closing output window and building project, the window should be restored in the same place as before closing.
Note: it's restored correctly if docked in some other places

**Comment by slynch8** [comment]
fixed (0.22.26)
