### ISSUE TITLE
Running remedybg hangs the build command

### ISSUE THREAD

**Issue by maxphilippov** [slynch8/10x#463]
Win 10 x64, Version 0.28.48

I got this line set as debug command in workspace settings:
`remedybg.exe start-debugging`

When I press F5 it runs compilation and runs remedybg but debug doesn't start. If I press F5 again it runs compilation and 10x hangs on what seems to be linker stage (or it's just a console output lag), cause it fails to print the usual "status line" ```===== Fail : 2 errors, 12 warnings =====``` after all the warnings.

I tried to wait couple of minutes and it doesn't seem to help. It seem to happen mostly when remedybg wasn't running before I run debug, but I believe I saw couple of cases when it didn't matter. If I restart 10x while remedybg is still running it doesn't seem to hang anymore.

It's a very weird issue, so I was hesitant to post it early, but it's there since I started using 10x (around 0.28.20).

If seems to me that remedybg takes some time to return some value from the command, but maybe it's 10x handling the result incorrectly. I'm perfectly fine to go to remedybg forums and try to solve it with the author.

**Comment by slynch8** [comment]
I'll take a look, but to get around it for now try binding F5 to a python function and start the process from python using subprocess.run.

**Comment by slynch8** [comment]
It sounds like the build command hasn't finished. I wonder if it's because remedybg is holding a lock to the pdb file? Does the build command also hang if you run it from the command line?

**Comment by slynch8** [comment]
actually, it may be the same as this bug I'm looking at https://github.com/slynch8/10x/issues/418

**Comment by maxphilippov** [comment]
> It sounds like the build command hasn't finished. I wonder if it's because remedybg is holding a lock to the pdb file? Does the build command also hang if you run it from the command line?

I haven't check that, but if I remember correctly when RemedyBG was holding a lock of exe (I forgot to stop debugging) the build failed correctly and nothing hanged.

**Comment by maxphilippov** [comment]
0.31.2 can't reproduce
