### ISSUE TITLE
Edit menu doesn't respond to mouse clicks

### ISSUE THREAD

**Issue by maxphilippov** [slynch8/10x#469]
Win 10 x64, Version 0.28.48 (broke 4-5 versions before)

When you click with mouse on items in Edit menu (top bar) nothing happens, when you call those by hotkeys -- options work fine.
Some items in file menu don't respond too (Save file, Close file).

**Comment by slynch8** [comment]
wow, thanks for letting me know. Looks like I broke it with the UI focusing change. Fixed now.
