### ISSUE TITLE
Close brackets at wrong tab position

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#47]
If I type the following whilst indented by a tab or two:
if( x )
{
}

10x will often put the closing curly bracket inset by one tab. It seems to be related to how fast I type (I can't repro when doing it slowly). It is not easy to reproduce at will, but it has happened dozens of times today. I hadn't noticed it last week.

**Comment by slynch8** [comment]
I'm currently re-writing the indenting, so hopefully this will be fixed. Should have it in a new build in the next day or two.

**Comment by slynch8** [comment]
Let me know if this still happens in (0.24.3)

**Comment by slynch8** [comment]
I found this in the end, fixed in (0.24.4)
