### ISSUE TITLE
Blurry editor

### ISSUE THREAD

**Issue by DerickThePoney** [slynch8/10x#470]
Hi, 

Everything in the editor is quite blurry when my mouse is not over it. I have tried quite a few things such as disabling vsync, disabling PreventPresentWhenIdle, UI scaling, I touched the VSync parameters in the nvidia panel and nothing seems to make a difference... I did not disable gsync cause I don't seem to have it (maybe it's a monitor thingy ?). I have attached pictures of what I see... The things when the editor goes in the background (ie when I Alt-Tab), everything look normal again...

![2021-10-02_21h09_17](https://user-images.githubusercontent.com/7872231/135729432-0c33dfe2-89f7-4d7a-a52f-40abaf1cbdfc.png)
![2021-10-02_21h17_29](https://user-images.githubusercontent.com/7872231/135729433-8215ad77-a052-4c96-9be2-59874e8a359c.png)

I have installed 10x on my work computer, which I use with the same monitor and it does not have the problem.

Here are my specs:
W10
i9-9900K 3.6GHz
2080 SUPER
32 Go RAM

My work PC has an i7 on windows 7 with a GTX 970 and 32 GB of Ram.

My monitor is an MSI Optix, 2560*1440 @ 144Hz.

Thanks in advance !

**Comment by slynch8** [comment]
That's the strangest bug I've seen in a while.

Looks like it might be caused by FXAA see: https://www.nvidia.com/en-us/geforce/forums/geforce-experience/14/268336/blurred-text-until-i-hover-over-them/

**Comment by DerickThePoney** [comment]
Lol... Anyway it works thanks so much !
