### ISSUE TITLE
Autocomplete within comments

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#48]
Currently autocomplete tries to fill in keywords even after typing // or /* resulting in it changing an english word to a c++ keyword.

**Comment by slynch8** [comment]
fixed (0.24.0)

**Comment by Muzza** [comment]
This is happening again, only with // comments

**Comment by slynch8** [comment]
fixed (0.32.84)

**Comment by slynch8** [comment]
some people like this, so I've decided to add a setting Parser.AutocompleteInComments
