### ISSUE TITLE
Parser loses symbols when editing headers

### ISSUE THREAD

**Issue by septag** [slynch8/10x#483]
After editing some widely used headers, some symbols are lost:

![image](https://user-images.githubusercontent.com/5081921/136549019-5f0a3981-bb82-4979-8633-97a771507ee1.png)

After deleting and restarting:

![image](https://user-images.githubusercontent.com/5081921/136549039-5f0227fe-82ce-468b-9469-e5d2f52af169.png)

**Comment by slynch8** [comment]
Let me know if you find a good repro for this, I haven't been able to get it. Also, does it happen in the normal (non-PP) build?

**Comment by septag** [comment]
Nope, I encountered this in PP build. ok, I will try to replicate this and get back to you

**Comment by septag** [comment]
I still have to reparse every once in a while. but I will close this since it's not reproducible
