### ISSUE TITLE
Multi-line move is not working

### ISSUE THREAD

**Issue by septag** [slynch8/10x#487]
When I select multiple lines and try to move them up and down with shortcut keys, it only moves the line I'm in, I think it should work for all selected lines:
![Animation3](https://user-images.githubusercontent.com/5081921/136551287-77107750-0c46-49bd-9c47-eecde3f8f0b3.gif)

**Comment by maxphilippov** [comment]
I'll reference this one here  #462 since it's probably related, maybe some other editing features don't work as expected with multicursor.

**Comment by slynch8** [comment]
fixed
