### ISSUE TITLE
Parser gets confused with nested unnamed structs and unions

### ISSUE THREAD

**Issue by septag** [slynch8/10x#492]
When unnamed structs and unions are used, parser can only partially parse member variables. 

For example, in here, parser only detects `x` and `y`.
```c
struct some_type
{
    union {
        int x;
        int y;
    };

    float a;
    float b;
};
```

In this one, parser only detects `f`:
```c
union some_vector
{
    struct {
        float x;
        float y;
    };

    float f[2];
};
```

**Comment by maxphilippov** [comment]
Have an issue on structs #471

**Comment by septag** [comment]
Seems to be fixed now. thanks
