### ISSUE TITLE
Cant move window when it is narrow

### ISSUE THREAD

**Issue by StoneMonkeyMark** [slynch8/10x#497]
When the window is narrow the menu takes up all the top area so there is no place to click and drag the window about.
More of an issue with 10x notepad than when coding.
The 10x corner does not seem to do anything so that could still be used as an active area to grab and move the windows.

**Comment by StoneMonkeyMark** [comment]
Oh and note the line number are clipped. 
Oh and why are the minimise and fullsize icons now selected? They are not when the app runs.
Sorry those should be in separate issues.
PS using 10x as it is the only thing that can handle a 1.46GB text file. (sweet). Note it was seconds of unresponsive program when loading. and searching backwards also caused an unresponsive app for a number of seconds too.

**Comment by slynch8** [comment]
fixed (0.31.0)

Menu now automatically hides when windows becomes too narrow. You can also do a long click anywhere at the top to drag the window. Borders around min/max buttons should also be fixed now. I've added another bug for the clipped line numbers https://github.com/slynch8/10x/issues/748
