### ISSUE TITLE
Multicursor inserts duplicate characters

### ISSUE THREAD

**Issue by track-5** [slynch8/10x#498]
10x version: 0.28.58

## What happens

Pressing CTRL+D on a selected word more times than the word is present in the file causes 10x to insert duplicate characters.
This only happens when there's **more** than one instance of the word in the file.

## Steps to reproduce

Create a new file (or use an existing one) and select a word that appears more than one time in the file.

Sample file content:

```
foo
bar
foo
```` 

Select the word `foo` and press `CTRL+D` 3 times.
Press any input character key (e.g., `b`).
The character `b` gets inserted twice after the first cursor.

If you reset the file and press `CTRL+D` 4 times, it both cursors get duplicated characters.

**Comment by slynch8** [comment]
fixed
