### ISSUE TITLE
Parser.AutoFixIndirection should correct on backspace

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#51]
When Parser.AutoFixIndirection is enabled, it incorrectly changes -> to . when dealing with shared_ptr (and in some other cases too).
When it does this, it becomes difficult to fix, as the editor changes it every time.

Visual Assist has a feature where if you press backspace after it has made a change to -> or . it will undo it. I think this would be a good addition to 10x.

**Comment by slynch8** [comment]
Done (0.24.13). Although hopefully you won't need it as I've now added support for shared_ptr.
