### ISSUE TITLE
Large parts of code lose syntax colouring

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#52]
I'm regularly getting large parts of a file having all the text change to white.
It seems to happen when I edit something, and then scroll upwards, everything above the top of the screen has lost syntax highlighting. If I edit a line, or insert a new line, the colours come back (but only on or below the point I edited).
I deleted all 10x cache files, but it didn't fix it.

**Comment by Muzza** [comment]
Also, it doesn't seem to pick up newly added symbols from header files.
I added two values to an enum in a header file. When using the new values in a cpp file they showed up white, and intellisense would not work on them. Eventually one of the two enums started showing coloured again, but not the other one.
It is very inconsistent, so I don't know if I could reliably reproduce it.

**Comment by Muzza** [comment]
Another example, I have about six classes in a single header. They all show with syntax highlighting in the header file, but when they are used in a cpp file, the last class always shows up white as though it is unknown. All the others are fine.

**Comment by Muzza** [comment]
Possibly its just doing the parsing in the background and taking a long time?
I added a new (fairly small) header file. Normally when I save it the syntax highlighting appears instantly, but in this cases it was all white for about 30 seconds, then the colours all just appeared.

**Comment by slynch8** [comment]
I'm struggling to reproduce this. It could be that it is taking a long time, although nothing should take that long, maybe there is some specific code that it doesn't like. Would you be able to provide a file that has the problem?

**Comment by Muzza** [comment]
I don't really know how to do that without sharing the entire project.
I took one example where it fails to parse a single class in a file that has multiple classes in it. (The class is coloured in the header file, but remains white in all cpp files and is never in the autocomplete suggestion list)
I copied and pasted the cpp and h file into an empty project without changes, and it recognised the class correctly. So it does not seem to be something particular to the code.

As for the problem I described in the top of this issue, I don't have any way to make it consistently happen.

**Comment by Muzza** [comment]
hmm, I've done another delete of the 10x cache files, including those inside the Workspaces folder and now that same class is working.
I'll have to see whether it has also affected the problem a the top of this issue.

**Comment by slynch8** [comment]
Are you editing files outside of 10x? Someone reported something similar when doing that.

Also, would you be prepared to share a cpp file that has the problem of losing the syntax highlighting after an edit? I could run some tests on it with the parser and try and re-create the problem. It may be a particular bit of code that is breaking the parser.

**Comment by slynch8** [comment]
Actually, I think I may just have found it, it maybe happening when a file is saved

**Comment by slynch8** [comment]
I've narrowed this down, it happens if you save a file while it's still reading in the parser cache.

**Comment by slynch8** [comment]
This is fixed now (0.24.4). It also happened if you modified files externally.
