### ISSUE TITLE
Symbol References critical bug

### ISSUE THREAD

**Issue by all500234765** [slynch8/10x#522]
If you try to search any symbol with Symbol References by using your fingers and keyboard, then it won't show you anything. Even if you press hotkey on a symbol and then add and remove space at the end

PP2 0.28.61

**Comment by all500234765** [comment]
I think #522 needs more attention since it prevents you from searching anything with Symbol References, besides using hotkey on a symbol

**Comment by slynch8** [comment]
Sure, I'll take a look today

**Comment by slynch8** [comment]
Do you mean using Alt+Shift+F to open the FindReferences panel from the code? I've just tried it and it is working for me. It shows the symbol and the references to it.

**Comment by slynch8** [comment]
oh, I see, you mean actually typing it and selecting from the dropdown. I'll get that fixed

**Comment by slynch8** [comment]
fixed (0.29.14)

**Comment by all500234765** [comment]
Sorry to bother @slynch8 but you mistook FindSymbolReferences with FindSymbol :)
Which is Alt+Shift+S and not Alt+Shift+S

But as of FindSymbolReferences it now works properly

**Comment by all500234765** [comment]
Reopen

**Comment by slynch8** [comment]
I've checked the Find Symbol panel and it seems to be working as expected. Could you provide a gif showing what you mean?
![findsymbol](https://user-images.githubusercontent.com/7141856/140031784-438b784c-6c76-455f-987a-c4289cd70793.gif)

**Comment by slynch8** [comment]
closing due to no repro. Please reopen if it's still an issue with more info.

**Comment by all500234765** [comment]
you mistook FindSymbolReferences with FindSymbol
![FindReferences](https://user-images.githubusercontent.com/8898684/152123788-d9127e9f-160a-402c-bd19-2fa25d01c663.gif)

**Comment by slynch8** [comment]
fixed (0.31.0)
