### ISSUE TITLE
Syntax highlighting, goto Definition, do not work in greyed out areas

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#569]
Is it possible that rather than greying out code due to the pre-processor, you just dull the normal syntax highlighting?
And similarly, can we still use functions like Goto Definition within those areas?
Large amounts of my code show in grey. Mostly this is because 10x does not handle defines from other header files (so anything inside a .inl or .h file does not show correctly). There also appears to be some bugs still where files go grey incorrectly. 
Whilst these problems are still being worked out, having the pre-processor is making it a poor editing experience. A 'disable pre-processor' option both for individual files and as a global setting would be good to have.

**Comment by slynch8** [comment]
(0.29.12) enabled syntax highlighting and goto-def in defined out code
I'd rather not disable the preprocessor unless I really have to.
