### ISSUE TITLE
Rename issues

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#57]
I just tried the 'Rename' option on a symbol again, but it is really not working at all.
It missed a second instance of the symbol in the file I started in, and only changed one other file out of the 30 odd it should have changed.
When I was done, I tried to rename back as an experiment, but it won't even start the rename process on this changed symbol. All the symbols were appearing in a normal search.
Does it try and use the parser for the rename or is it a search and replace for any instance of the word?
If it is the later than I would have expected it to work. If it is not the later, then we really need a Find & Replace across files.

**Comment by Muzza** [comment]
ok, if it is using the parser that explains it. It was a macro I was renaming.

**Comment by Muzza** [comment]
It doesn't work if I do Find References on __ALIGN, it doesn't report any results.

```
#define	__ALIGN(n)		__declspec( align(n) )

struct __ALIGN(16) A
{
};
```

**Comment by slynch8** [comment]
oh yes, __ALIGN is a special case that I hacked in until I get the preprocessor in, it won't work on that one.

**Comment by Muzza** [comment]
If I try and rename the first 'AAA' here to 'BBB'

```
struct AAA
{
	AAA();
	~AAA();
};

AAA::AAA() {}
AAA::~AAA() {}
```

I get:

```
struct BBB
{
	AAA();
	~AAA();
};

BBB::AAA() {}
BBB::~BBB() {}
```

**Comment by Muzza** [comment]
Also, doing a rename on a class like that seems to leave the parser in a state where it doesn't recognise anything. Most of my file has gone white.

**Comment by slynch8** [comment]
I've fixed the rename not updating the constructors and destructors (0.24.18).

But I couldn't get the "everything going white" after a rename. Does it happen for you in a simple test?

**Comment by slynch8** [comment]
closing for now, reopen if you see this again
