### ISSUE TITLE
Syntax highligher / comment bug

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#570]
See example
```cpp
void func( void )
{
	if( 1 )	// put a /* before the if( 1 )
	{
		x = (x&1)? 0:1; // and the code will only go green until this point
		x++;
	}
}
```

**Comment by Muzza** [comment]
I feel this issue should get some attention because all comment syntax highlighting using /* */ has been totally broken in my code for a few weeks now.

**Comment by Muzza** [comment]
This is doing some strange things.
Try commenting out the function below by inserting /* and */ on the blank lines. It just doesn't work at all.

```cpp
#define xxx true

bool func( void )
{
	return xxx;
}

```

In other code I get block comments showing green for every line apart from the those that have macros in them, which show with normal syntax highlighting.

**Comment by slynch8** [comment]
seems to work for me, does it happen for you if that is the only thing in a file? 
![comment2](https://user-images.githubusercontent.com/7141856/143215226-f956548c-9b6f-4f01-9f86-5ab94aacf614.gif)
?

**Comment by slynch8** [comment]
the macro one sounds strange, can you give an example? This simple case seems to be working. Again I wonder if it's due to what else is in the file.

![macrocomment](https://user-images.githubusercontent.com/7141856/143215840-b518ee44-db09-4590-a579-e19b926222d3.gif)

**Comment by slynch8** [comment]
might also be worth trying a clean reparse

**Comment by Muzza** [comment]
Its the only thing in the file. I've deleted parser and workspace caches.
![2021-11-25 08_04_49-Window](https://user-images.githubusercontent.com/1583441/143312689-eda89266-b807-4ff6-b786-bec6a3529b40.png)

**Comment by slynch8** [comment]
got it now

**Comment by Muzza** [comment]
Here's an example of the macro issue. ZMove and THETOOL are both macros.
This is also after deleting the parser cache.

![2021-11-25 08_08_41-Window](https://user-images.githubusercontent.com/1583441/143312980-a51f6846-9807-4ab3-b5ef-4a0c9472f749.png)

Removing the comment then left the bottom two lines green.

**Comment by slynch8** [comment]
I've fixed these two issues.

10x (0.29.32)
- fixed comment blocks sometimes not updating
- fixed lines with macros not being commented out in comment blocks

I suspect there may still be some interaction issues between comment blocks and the preprocessor but hopefully this is better. I need to take a look at this again when I have more time.

**Comment by Muzza** [comment]
Seems fixed
