### ISSUE TITLE
Find File does not always refresh display

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#576]
I've seen this happen a lot. I search for a file, type a few letters, 10x display the files.
Then I push the down arrow key, and 10x changes all the files after the first one. Often I press return just before noticing and open the wrong file.

Also I found that if I don't press the down arrow key, but instead run the mouse across all the rows, it changes them. So I assume its not always refreshing the display completely.

The difference between these two screenshots was just that I ran my mouse over the options.
![2021-11-12 15_13_08-AllProjects_win sln - 10x](https://user-images.githubusercontent.com/1583441/141408263-7f93efee-166c-4cac-a31f-896c9cfa5732.png)

![2021-11-12 15_13_37-AllProjects_win sln - 10x](https://user-images.githubusercontent.com/1583441/141408500-7888d5fd-a266-4c15-a54a-fce9c8244e26.png)

**Comment by slynch8** [comment]
I'm not seeing this. Do you have the window docked or floating? and does it happen if you use the default settings (rename your %appdata%\10x folder to test)

**Comment by Muzza** [comment]
The window is floating, and yes, it still happens if I rename the 10x folder and use default settings.

**Comment by slynch8** [comment]
Could you show what happens in a gif?On 13 Nov 2021 02:40, Alastair Murray ***@***.***> wrote:
The window is floating, and yes, it still happens if I rename the 10x folder and use default settings.

**Comment by slynch8** [comment]
I wonder if something is causing a slowdown for you, is it running low on memory?

**Comment by Muzza** [comment]
![FindFile](https://user-images.githubusercontent.com/1583441/141660524-efde99a5-cae4-4385-a8ba-b8143b3f7502.gif)

I'm using less than 45% of 32GB on my system. Everything is 100% responsive. I pause a bit in the gif to show that it does not refresh the display until moving my mouse over the rows.

**Comment by slynch8** [comment]
Thanks, that's really helpful. It's definitely a rendering issue then. I have an idea what it might be, but I'm still wondering why I'm not getting it. Are you on a high refresh rate display?

**Comment by Muzza** [comment]
Yes, Gsync display at 120hz, but I just turned it off and ran at 60hz and it behaves the same.

**Comment by slynch8** [comment]
I think it is a timing thing that just works for me by chance. I've got a potential fix, can you give this a try:
[https://e.pcloud.link/publink/show?code=XZzabJZORnJ0LJu58SJTxzLe3Pf6H8WLyR7](https://e.pcloud.link/publink/show?code=XZzabJZORnJ0LJu58SJTxzLe3Pf6H8WLyR7)

**Comment by Muzza** [comment]
Sorry, still happening.

**Comment by slynch8** [comment]
I thin I've got it. If two searches return exactly the same number of results it won't update.
[https://e.pcloud.link/publink/show?code=XZz3bJZCVx1HXuo8DL4uzNYVn2fE7eOdVOy](https://e.pcloud.link/publink/show?code=XZz3bJZCVx1HXuo8DL4uzNYVn2fE7eOdVOy)

**Comment by Muzza** [comment]
Fixed!

**Comment by slynch8** [comment]
Great! :-)

I'll get that into the next build
