### ISSUE TITLE
Feature request: Borderless fullscreen mode on F11

### ISSUE THREAD

**Issue by all500234765** [slynch8/10x#577]

**Comment by yesitsfebreeze** [comment]
bump 👍

**Comment by slynch8** [comment]
Is it literally just changing the window size so that it covers the Windows task bar, or is there more to it?

**Comment by slynch8** [comment]
Done (1.0.117)

added ToggleFullscreen command (alt+Enter)
added ToggleFocusMode command (alt+control+Enter)
added ToggleFullScreenFocusMode command (alt+shift+Enter)
