### ISSUE TITLE
Add support for defined(X)

### ISSUE THREAD

**Issue by all500234765** [slynch8/10x#581]
![{7F88856B-E306-43AB-ACF5-C33894AFA6F3}](https://user-images.githubusercontent.com/8898684/141656297-cfe79934-3d25-4952-b712-d2d0eaab8d45.png)

![image](https://user-images.githubusercontent.com/8898684/141656320-c84cea7b-e886-4d19-abe4-9381a0bb1877.png)

**Comment by slynch8** [comment]
I'm not sure what you are showing here. Defined(X) does work, maybe NO_DIRECT3D_12 isn't defined?

**Comment by slynch8** [comment]
Closing for now, but please re-open if it's still an issue.
