### ISSUE TITLE
Require selection of autocomplete

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#59]
I'm not sure if something has changed here or not, but every time I type say, struct Identifier<return>, the autocomplete starts up as I'm typing identifier. Usually there is no way the autocomplete can be correct as I'm entering a brand new name. But as soon as I press return it changes what I typed, and I have to undo it.
Or I have to press escape to cancel the autocomplete - something I usually miss if I'm typing fast.

I just checked out how Visual Studio/Assist does it and I feel a small change to be like VAX would be an improvement.
In VAX, as you type the autocomplete box pops up, but no entry is selected until you press the down arrow key to choose an option. So you can safely type and press return without autocomplete changing anything, but if you see the entry you want in the autocomplete box, you press Down-Arrow followed by Return to have it replace your text with the suggestion.

**Comment by slynch8** [comment]
I've been thinking about changing it as you say. But a lot of the time I really like the auto-selection of the first item. I will probably put it on a switch as you suggest. But I might try something else first, simply not allowing autocomplete when writing a struct or class name, it should be fairly easy to detect.

**Comment by Muzza** [comment]
Not sure that would be enough tbh. It’s the same with variables, enums, functions.
Also there are times you do want autocomplete after struct. In C for example using a non-typedef’d requires writing struct first or when doing forward declarations in c++.

**Comment by slynch8** [comment]
Yeah, maybe you're right. Although it's only the ones where you would press Enter after that matter I think? Typing a variable or function you just continue typing and it disappears.

Also, you can always manually bring it up with ctrl+space.

**Comment by slynch8** [comment]
I made it work as you suggest in the end. Let me know how you get on.

10x (0.24.15)
- made autocomplete not select any items for non-indirection autocompletes
- stopped enter from submitting autocomplete if no item selected
- only allow ( to submit autocomplete if item is selected and it is a function
- don't auto-add function brackets on autocomplete submit if user submitted with a (

**Comment by Muzza** [comment]
First thing I've found is that if there is only one entry in the autocomplete list, you can't push down to select it.
Also, I've realised that I have the same problem pressing tab that I did when pressing return. If I'm typing fast, tab will change the word to the first autocomplete option when I didn't want it to.

**Comment by Muzza** [comment]
I've also found it accepts the first result on pressing (
So for example, type 
`void MyClass::NewFunctionName(`
And NewFunctionName always gets replaced by the top suggestion.

**Comment by slynch8** [comment]
these should be fixed now (0.24.16)
- stopped ( from submitting autocomplete when there is no selection
- fixed up/down keys dismissing autocomplete when there is no selection and only one item in the list
- added SubmitFirstAutocomplete setting to disable tab submitting first autocomplete item when there is no selection
- added SubmitAutocompleteOnOpenBracket setting to enable/disable the submitting of autocomplete on (

I decided to keep Tab submitting even if no item is selected, but you can turn it off with the SubmitFirstAutocomplete setting.

The submit happening on ( is by default but will not only happen if you have an item selected. But if you don't want it you can turn it off with the SubmitAutocompleteOnOpenBracket setting.

**Comment by Muzza** [comment]
This is minor, but if the autocomplete opens with only one suggestion but selects the first entry itself, pressing down arrow will still cancel it. If it opens with more than one entry, no amount of up/down arrows will cancel it.
It had me a bit confused for a while as to whether this was the previous issue re-appearing, but I can see this is just different behaviour of the autocomplete depending on whether I just typed struct or not...

**Comment by slynch8** [comment]
fixed (0.25.4)
