### ISSUE TITLE
Multiselect issue with repeated selection

### ISSUE THREAD

**Issue by septag** [slynch8/10x#597]
There is a strange bug in multi-select, if I continue pressing CTRL+D and do a second pass over the selections, everything I type is repeated over, demonstrated here, I pressed CTRL+D 6 times and when tried to edit, each word repeated twice:

![multiselect_bug](https://user-images.githubusercontent.com/5081921/143622090-a6a3a061-450a-41d3-b7c0-5963c5fa6bf1.gif)

**Comment by slynch8** [comment]
yes, at the moment the search wraps around and adds the selection multiple times, and each selection adds a new cursor.

**Comment by slynch8** [comment]
fixed (0.30.2)
