### ISSUE TITLE
Function description disallows up/down arrow keys

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#60]
Type the following. There is a pop up window with a description of the function parameters, but it seems to lock the arrow keys so I cannot move up/down in the code, even though there are no options to select. I have to press escape to get out of it.
It doesn't feel right that the function description (which is merely for reference and has no options) should stop me from navigating up/down the code. Instead it should disappear as I move away.

```
void MyFunc( int, int )
{
}

MyFunc(  // try and use the up/down arrow keys here
```

**Comment by slynch8** [comment]
fixed (0.25.7)

I've also changed the way the function list works so that when you start typing the args it will only show the selected function. Go back to the function start to show all options again.
