### ISSUE TITLE
Relative Line Numbering [Feature Request]

### ISSUE THREAD

**Issue by behreajj** [slynch8/10x#600]
Hello,

This is a feature request for relative line numbering. For example, if the cursor was on line 67, the display in the lefthand gutter would look like this:

```
3 
2
1
67 foo();
1
2
3
```

Maybe a settings option would allow a choice between absolute (default) and relative.

Thank you for considering!
Best,
Jeremy

**Comment by matiasjpedro** [comment]
This would be awesome for VIM verical movement/command 🙏

**Comment by slynch8** [comment]
done (1.0.177)
