### ISSUE TITLE
(Low priority) Map scrollbar visually wraps file preview texture for short files

### ISSUE THREAD

**Issue by pmttavara** [slynch8/10x#607]
10x Version 0.29.37
Windows 10 Home x64, Version 1511 (OS Build 10586.1176)
Graphics: Nvidia GeForce 920M, driver version 388.57, D3D12, feature level 11_0

It appears that the Map Scroll Bar can show an infinitely wrapping looped view of the map preview.
I don't think the `MapScrollBarWidth` setting affects it.
It seems that the wrapping only appears on short files that are smaller than the height of the map.
It's possible that this is a feature not a bug, in which case my apologies in advance.

Apologies if there isn't enough information here - i'm perfectly willing to answer any questions!

Settings file: 
[Settings.10x_settings.txt](https://github.com/slynch8/10x/files/7655093/Settings.10x_settings.txt)

Very short file with clear wrapping:
![image](https://user-images.githubusercontent.com/34119228/144729456-05670f81-21a2-44e0-8790-8a4ae32fb2ed.png)
Crop of the same view:
![image](https://user-images.githubusercontent.com/34119228/144729457-1280177e-1682-4858-ae3b-9e0c0c3bca6b.png)
Much wider scrollbar setting (600)
![image](https://user-images.githubusercontent.com/34119228/144729491-d4747d7c-9069-45a4-8bb0-9a41b1c31713.png)
Long file that doesn't exhibit the wrapping problem:
![image](https://user-images.githubusercontent.com/34119228/144730967-d5b11b43-75c6-4606-ad4a-4d4428df0d6e.png)

**Comment by slynch8** [comment]
Thanks for letting me know about this, it's definitely not a feature and not something I've seen myself. I'll take a look at the code and see if I can spot anything that might cause it.

**Comment by slynch8** [comment]
Can you try closing 10x and renaming the %appdata%\10x folder and see if you still get it

**Comment by SimpsonGSD** [comment]
I am seeing this on files that have small amount of text.
If I make the window smaller the it does stop wrapping vertically or if I add more lines it stops.
This is on a 3 day old install.

**Comment by slynch8** [comment]
are you using Remote Desktop?

**Comment by SimpsonGSD** [comment]
No this is local.

**Comment by slynch8** [comment]
definitely fixed now (0.34.25)
