### ISSUE TITLE
Memory footprint grows wildly while open an Unreal C++ project

### ISSUE THREAD

**Issue by dawnarc** [slynch8/10x#613]
![image](https://user-images.githubusercontent.com/3351764/146708089-d3b9764e-63db-4230-9754-2be00a9cbe4e.png)
Steps to reproduce this case:
1. New a C++ project using Unreal Engine 4.
2. Open this project in 10x Editor.
3. Wait a moment, memory would increase insanely.

**Comment by slynch8** [comment]
This is expected at the moment, the parser is taking a lot of memory. I'm currently working on a fix for that, I hope to have a new build out in a week or so.

Most of the memory isn't touched after startup so the OS should page most of it out.

**Comment by slynch8** [comment]
Here's the new build, it should use a lot less memory
https://e1.pcloud.link/publink/show?code=XZIKzFZqoUbS7Y3QuVXRW1SFwS0kjPUNrby
Let me know how you get on.

**Comment by dawnarc** [comment]
@slynch8 Great! memory dropped a lot. 👍

![Taskmgr_iVTvWbppFL](https://user-images.githubusercontent.com/3351764/146957779-998314ee-4524-4562-931e-95c6ac6c7c3e.png)

**Comment by slynch8** [comment]
That's good. Here's a new build with some fixes:
https://e1.pcloud.link/publink/show?code=XZk4RFZRd2I4TUThEzgnOdP1tQ4hFz6vLWy
