### ISSUE TITLE
"Failed to open file" trying to open file with warning from Output

### ISSUE THREAD

**Issue by all500234765** [slynch8/10x#614]
Double clicking on warning or error in Output window shows an error that previously wasn't there.
I am totally sure that file is real and it works if I try to open this file via Search window.

![image](https://user-images.githubusercontent.com/8898684/146730311-ad76a67a-0b5d-4523-9204-e6af818f2e5e.png)

Project type: VS 17 .sln
Worked before 0.29.41

**Comment by slynch8** [comment]
could you post the build output line that is failing

**Comment by slynch8** [comment]
I think I fixed this, let me know if it's still an issue
