### ISSUE TITLE
Really high CPU usage when sitting idle

### ISSUE THREAD

**Issue by RetroZelda** [slynch8/10x#615]
I opened a very large *.sln for a project(AAA game; proprietary engine) to try out the editor and I noticed that while sitting idle without any files opened the CPU usage is very high.  

![image](https://user-images.githubusercontent.com/4962388/146795031-0ac80fec-11b0-4f25-9420-1cea410b49d5.png)

I closed and re-opened the editor and now it appears that whatever task it was doing previously is still running as well as a duplicate of that task is created when re-opening because now I have 2 10x.exes appears in the process manager

![image](https://user-images.githubusercontent.com/4962388/146794051-ba28077b-0578-4168-84b5-6cdf1d445799.png)
![image](https://user-images.githubusercontent.com/4962388/146794136-2c6eb5eb-473e-4b64-b965-6699fd82b093.png)

within the editor I noticed that the progress bar for "Parser" seems to be stuck(or its moving extremely slowly.  I just cant tell), but I assume performance will return if it completes.
![image](https://user-images.githubusercontent.com/4962388/146795273-c1a4ff6a-6f26-485f-b2a7-70912581af70.png)
I waited about 30 minutes on my first opening and then 10 minutes after re-opening

my 10x log output is this upon the reopening:

> [10x] Initialising Visual Studio build environment...
> [10x] Opening workspace 
> [10x] N10XMain::InitialiseApp time: 2872.38 ms
> [python] Executing script ClangFormat 0ms
> [python] Executing script Example 0ms
> [python] Executing script FormatFile 0ms
> [python] Executing script KeyMappingExample 0ms
> [python] Executing script Snippets 2ms
> [10x] Initialising Visual Studio build environment complete.
> [10x] Opening workspace D:/path/to/solution.sln
> [10x] Read workspace time: 63 ms
> [vs-debugger] Connected
> [parser] waiting for process cache lock...
> [parser] obtained process cache lock...
> [parser] Reading workspace...
> [parser] Reading workspace cache...
> [10x] Read workspace time: 6916 ms (async)
> [10x] ReadSolutionFinalizer time: 1701.57 ms
> [parser] Parsing files (50966)...
> [parser] Read cache complete
> [parser] Read cache time: 2872 ms
> [parser] Finished reading workspace files

**Comment by RetroZelda** [comment]
update: The original 10.exe eventually crashed.  Unfortunately I dont think i'll be able to share the crash report based on the nature of the *.sln I was using

**Comment by slynch8** [comment]
Parsing files will only happen the first time you open the sln. After that it will read from the cache. Parsing a sln of that size (50966) files should only take 2-3 mins, so it does sound like something has got stuck. Does it only happen on this sln? Maybe there is a particular project that it doesn't like.

**Comment by slynch8** [comment]
Because it currently uses up so much memory it can take a while to shut down (this will be fixed soon). Try killing the other process and see if finishes parsing.

**Comment by RetroZelda** [comment]
I tried a different solution(53087 files) and the parser's progress gets to this point fairly quickly and then seems to stop. 
![image](https://user-images.githubusercontent.com/4962388/146797822-ec136bfe-1610-44e1-a315-8bcaf9463e1d.png)

although right after I captured that screenshot it seemed to move a little bit(or my eyes are lying to me), but it still seems to be "stuck".  ill let it sit for about an hour and see if it changes

**Comment by RetroZelda** [comment]
![image](https://user-images.githubusercontent.com/4962388/146798568-8f62c022-7f47-4617-a9f3-2ec8c55335bf.png)

**Comment by slynch8** [comment]
It shouldn't take more than a few minutes on even the largest sln. Could you take a crash dump when it's been stuck for a while?
You can trigger a mini-dump from the Help menu.

**Comment by slynch8** [comment]
That is an interesting pattern though, where cores 16-32 are all over the place. You could try changing MaxCoreCount in the 10x settings to be 16.

**Comment by RetroZelda** [comment]
Just uploaded the dump on the site.  10x_crash_2021_12_20_11_20_8.dmp.gzip from  RetroZelda should appear

**Comment by slynch8** [comment]
got it - thanks

**Comment by RetroZelda** [comment]
setting MaxCoreCount to 16 didnt change much, but settings to 8 does give a slightly different appearance
![image](https://user-images.githubusercontent.com/4962388/146800375-4c84f19f-bcc9-4167-8759-c34c26c90abd.png)

**Comment by RetroZelda** [comment]
but it still doesnt complete

**Comment by slynch8** [comment]
I've had a look and I can't see anything unusual, just all the usual parsing stuff. I can't think why it is taking so long for you. Is this an Unreal project?

**Comment by RetroZelda** [comment]
this is a proprietary engine to my company.  We use python/WAF to generate our solutions.  This one is a vs2019 solution

**Comment by slynch8** [comment]
I see. It's weird, in the dump it almost looks like optimisations are off, although I don't see how that is possible.

Could you try this build:
https://e1.pcloud.link/publink/show?code=XZeOHFZ9V1I0SA1hPHgXfC3vAUzw7Sz9kdy
This is the very latest build that I'm working on right now. It will be interesting to see if it performs better.

You can just extract it and run it from there - thanks.

**Comment by slynch8** [comment]
Looking at the crash dump a bit more, all threads are in the preprocessor. Maybe your code uses the preprocessor in a way that the parser doesn't like. Unfortunately I can't tell which files it is stuck on because it's only a minidump.

**Comment by RetroZelda** [comment]
it seems to get to the same place a little quicker, but then proceeds to hang.  Core utilization seems to be less aggressive but still fairly active.  It is still set to have 8 set for MaxCoreCount  
![image](https://user-images.githubusercontent.com/4962388/146802347-82c1484d-1d74-44c5-a9be-9ad7e1f1d714.png)

**Comment by RetroZelda** [comment]
can I enable more verbose logging for the parser's activity?

**Comment by slynch8** [comment]
I was just going to suggest that :-)

try setting Parser.VerboseLogging to 1

**Comment by RetroZelda** [comment]
closing the release build you sent at least wont leave a hanging process :) 
![image](https://user-images.githubusercontent.com/4962388/146802972-d892b5e6-fe6a-4f4c-88a2-4daf8f807dcc.png)

**Comment by slynch8** [comment]
hmm, that wasn't the plan :-)

The verbose logging will slow down the parse quite a bit, but you should see if it's stuck on a particular file. The parse times for each file are logged to the 10x output window.

**Comment by RetroZelda** [comment]
it looks to be struggling with *curse words* boost

[parser] ParseLines: 9743.97 ms c:/needy/cache/3rdparty/boost/boost-1.67.0.1.3.2.2032812/include/boost/hana/detail/struct_macros.hpp

**Comment by slynch8** [comment]
ah ha! Yes, you'll need to exclude that. I draw the line at trying to parse the boost code. In the workspace settings you can add exclude filters. Right click on the sln node in the workspace tree and select Settings. You'll then need to restart 10x.

**Comment by RetroZelda** [comment]
its always boost... haha

that seems to have done the trick tho!  Thanks!

**Comment by slynch8** [comment]
great! It might be best to go back to the main build, the build I sent you is still fairly experimental, but up to you. It will use up a lot less memory. I think I'll hard code the boost exclusion :-)

**Comment by slynch8** [comment]
10x (0.29.42)
- exclude boost from parser because it takes too long to parse
