### ISSUE TITLE
can't set custom build settings in workspace?

### ISSUE THREAD

**Issue by mattiasljungstrom** [slynch8/10x#616]
I'm trying to setup custom build settings in a workspace that is just a folder of files with a custom build script. Whatever I type into the build settings is gone after I close and open the window again. Am I missing something completely obvious that needs to be setup first or is this a bug?

1. Open folder with project files
2. Settings -> "Workspace Settings" -> Build -> Build Command
3. Enter anything, close window
4. Open window again, settings are gone.

I've also tried saving the workspace but it doesn't seem to make a difference.

(Btw, the window title is incorrect "Worksapce Settings")

**Comment by slynch8** [comment]
It sounds like a bug, I'll take a look. Did you use Create Workspace or open a folder?

**Comment by slynch8** [comment]
oh sorry, you said you opened a folder. That should work, but for now try doing Create Workspace from the file menu.

**Comment by mattiasljungstrom** [comment]
Ok, it works if I use "create workspace" instead. Thanks!

**Comment by slynch8** [comment]
That's good. I've uploaded a fix for saving folder workspaces.

10x (0.29.43)
- fixed folder workspace settings not being remembered
- fixed saving folder workspace as workspace
