### ISSUE TITLE
Support .otf fonts

### ISSUE THREAD

**Issue by tksuoran** [slynch8/10x#620]
I'd like to use Source Code pro font. I have it as .otf.
Would it be possible to support .otf fonts?

`Font Error: Unable to find font SourceCodePro-Semibold.ttf. Using consolas instead.`

**Comment by slynch8** [comment]
I think it should be possible to support .otf files, I'll take a look next week. But it looks like you can get it in ttf here: https://www.1001freefonts.com/source-code-pro.font

**Comment by slynch8** [comment]
oh, sorry, just re-read the error, you're already using .ttf. Try removing the .ttf extension.

**Comment by slynch8** [comment]
please re-open if it's still an issue.
