### ISSUE TITLE
Unable setup Build.VisualStudioEnvBat for VS 2022

### ISSUE THREAD

**Issue by tksuoran** [slynch8/10x#621]
Somehow, I cannot configure `Build.VisualStudioEnvBat`. I have Visual Studio 2022 and it provides this:

```
Directory of C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build

09/11/2021  10.04                39 vcvars64.bat
```

I have tried several different ways to spell this path in settings, restarting 10x after (before) every attempt, including these:
```
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\Build\vcvars64.bat
C:\\Program\ Files\Microsoft\ Visual\ Studio\\2022\\Preview\\VC\\Auxiliary\\Build\\vcvars64.bat
C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Auxiliary/Build/vcvars64.bat
C:/Program\ Files/Microsoft\ Visual\ Studio/2022/Preview/VC/Auxiliary/Build/vcvars64.bat
"C:/Program Files/Microsoft Visual Studio/2022/Preview/VC/Auxiliary/Build/vcvars64.bat"
"C:\\Program\ Files\Microsoft\ Visual\ Studio\\2022\\Preview\\VC\\Auxiliary\\Build\\vcvars64.bat"
```

Sometimes I get this error:
```
----- Building All erhe Debug x64 -----
Executing build command:
msbuild /p:Configuration="Debug" /p:Platform="x64" /verbosity:minimal "C:/git/tksuoran/erhe/build/erhe.sln" /m
CreateProcess error: The system cannot find the file specified.
===== Fail : 0 errors, 0 warnings =====
```
And sometimes I get
`Build failed. VSEnvBat not setup. Check your 'Build.VisualStudioEnvBat' setting`

Please advice what is the correct format and how to diagnose this further. Thanks!

**Comment by slynch8** [comment]
I think the correct path will be:
C:/Program Files (x86)/Microsoft Visual Studio/2022/Community/Common7/Tools/VsDevCmd.bat
(forward slashes, no quotes)

But the main problem is your other bug where 10XLogEnv.exe is being quarantined. It uses this to grab the environment variables from VsDevCmd.bat

**Comment by tksuoran** [comment]
I got this working after excluding the helper exe in FSecure.
