### ISSUE TITLE
Duplicate new.txt files in my solution and crash when closing them

### ISSUE THREAD

**Issue by tksuoran** [slynch8/10x#622]
When I open my solution, it opens with many `new.txt` tabs. When I try to close these, 10x crashes.

I have uploaded several crashdumps, latest one being `10x_crash_2021_12_22_17_22_55.dmp.gzip`.

Can I somehow remove these new.txt from the solution/workspace?

**Comment by slynch8** [comment]
I've not seen that before, I'd be interested to know what causes it to get into this situation. For now you can delete your workspace files %appdata%\10x\Workspaces

**Comment by slynch8** [comment]
I think this was fixed a while back. Let me know if you get it again.
