### ISSUE TITLE
FSecure flags 10XLogEnv.exe as harmful

### ISSUE THREAD

**Issue by tksuoran** [slynch8/10x#623]
FSecure considers 10XLogEnv.exe harmful, pointing to https://www.f-secure.com/v-descs/heuristic.shtml, and quarantines it.

I'm not sure if this may be related to the crashes I get.

**Comment by slynch8** [comment]
Hi,
This will be related to your VisualStudioEnvBat problem. Would it be possible to exclude it from the security software? I think the reason it's being flagged is that it logs out all environment variables.

**Comment by slynch8** [comment]
I've signed the exe, hopefully that stops it being flagged
