### ISSUE TITLE
Indent lines not working when using Editor.Tab Mode: Spaces

### ISSUE THREAD

**Issue by rojuu** [slynch8/10x#627]
With `Editor.Tab Mode: Tabs` the indent lines or "guides" are working proprely as follows:
![tabs](https://user-images.githubusercontent.com/15312785/147653687-beecbd0d-497a-4fe4-a316-3f6cb2e765cd.PNG)

But with `Editor.Tab Mode: Spaces` the indent lines are not working anymore:
![spaces](https://user-images.githubusercontent.com/15312785/147653717-fa2cde2b-fca8-4a61-ac31-901608d78994.PNG)

**Comment by rojuu** [comment]
To note, the file is indented with 4 spaces, but the actual indentation character being tabs or spaces in the file has no effect. Only toggling the setting `Editor.Tab` Mode matters.

**Comment by slynch8** [comment]
fixed (0.30.23)
