### ISSUE TITLE
Windows 11 borders

### ISSUE THREAD

**Issue by s9chroma** [slynch8/10x#632]
Are these borders transparent intentional?
![image](https://user-images.githubusercontent.com/35374338/147852115-82227672-1575-417e-9029-9e937190ee22.png)

**Comment by slynch8** [comment]
no, looks like something has gone wrong with the non-client area rendering. Maybe a Win11 thing, although no-one else has reported it yet.

**Comment by slynch8** [comment]
does it go away if you maximise?

**Comment by s9chroma** [comment]
No it's there on maximise as well 
![image](https://user-images.githubusercontent.com/35374338/147852747-20e35758-1da7-4eb4-a451-49d571c70306.png)

**Comment by slynch8** [comment]
Unfortunately my PC doesn't support Win11 so I can't try it, but here's a possible fix:
https://e1.pcloud.link/publink/show?code=XZI0uFZ7T64uf8xso0JnY828msDmQAOvOSy
(just unzip it and run it from there)

**Comment by s9chroma** [comment]
Thank you that worked.

**Comment by slynch8** [comment]
wow, that's great. To be honest I wasn't really expecting it to work :-) I'll upload a new build.
