### ISSUE TITLE
Go to definition bugs

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#64]
'Go to definition' does not work for overriden functions. Also if do goto definition on the usage of a function, it often goes to the implementation rather than the definition.
Try the code below in a header and cpp file and read the inlined comments.

```
// header.h
struct A
{
	virtual void Func();
};
struct B : public A
{
	void Func() override;	// 'go to definition' on Func goes to A::Func
};
```

```
// source.cpp
void main()
{
	B b;
	// goto definition in Func here, 
	// will go to implementation of A::Func,
	// should go to the header file of B::Func
	b.Func();
}

void A::Func()
{
}

void B::Func()
{
}
```

**Comment by slynch8** [comment]
both fixed (0.25.10)

Thanks for these simple repro's btw, very helpful.

**Comment by Muzza** [comment]
The first part of this seems to be fixed, but not the second. If I do goto definition on b.Func() (within the main function) it still goes to the implementation.

**Comment by slynch8** [comment]
That's as design, when you goto-def on a function call it will go to the function definition. As long as it's going to the B definition now, not the A one.

**Comment by Muzza** [comment]
But it’s going to the implementation not the definition.

**Comment by slynch8** [comment]
you mean the declaration? It is going to the definition for me. I'll check again.

**Comment by slynch8** [comment]
It's definitely working for me. I didn't bump the cache version number, try deleting your cache. Although I don't think this change should need the cache cleared, but it's worth a try.

**Comment by slynch8** [comment]
I see, yes, I often have the same problem. Although I do think I want the definition more often than the declaration. But as you say, two goto-defs allow this. I might consider changing my workflow :-)

I made it go to the definition by default because that was a default for VS, but I can definitely add an option for this so that it works as you expect.

One thing I use is (ctrl+minus) to go to the prev location to get me back to where I was.

**Comment by slynch8** [comment]
10x (0.25.14)
- added Parser.GotoFunctionImplementation setting. Makes goto-def on a function call go to the implementation instead of the declaration. Defaults to true.

Set it to false and it should work as you expect.

**Comment by Muzza** [comment]
This is working very nicely now, thanks.

**Comment by Muzza** [comment]
There seems to be a bug related to the GotoFunctionImplementation setting.
Every time I start 10x it acts as though Parser.GotoFunctionImplementation is set to true when I press Alt+G. I have to go to the settings file, change it to true, save it, change it back to false, save it again, and then it starts working correctly.
When I close and reopen 10x, it goes back to acting as though the setting is true.

**Comment by slynch8** [comment]
fixed GotoFunctionImplementation not being set when a workspace is opened (0.25.15)
