### ISSUE TITLE
Very small update to the firefly colour scheme

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#643]
Changed ```UI.Panels.Inactive Tab``` and ```C++.DefinedOut``` for slightly more consistency.

**Comment by slynch8** [comment]
Thanks, what did you change them to? :-)

**Comment by ggnkua** [comment]
Oh dear, brain was not working when I opened the issue apparently! Here's the changed file:

[firefly.zip](https://github.com/slynch8/10x/files/7846907/firefly.zip)

**Comment by slynch8** [comment]
Thanks
10x (0.30.13)
