### ISSUE TITLE
Find in Files should opens files in different window

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#646]
If I have the new "Find in Files Results" window docked in a pane, any files that are opened from double clicking on a result are opened on the same pane as the results window, rather than on the pane I have all my source code in.
This used to be a problem with the search window too, but you fixed it there.

**Comment by slynch8** [comment]
I can't remember what I did, but I'll take a look.

Another way of fixing this would be to add the code extensions to column 0 in the settings

```
# File wildcards for files that should automatically open in column 0. Separated by commas.
UI.Column0Files:                                  *.c,*.cc,*.cpp,*.c++,*.cp,*.cxx,*.h,*.hh,*.hpp,*.h++,*.hp,*.hxx,*.inl,*.txt

# File wildcards for files that should automatically open in column 1. Separated by commas.
UI.Column1Files:                                  

# File wildcards for files that should automatically open in column 2. Separated by commas.
UI.Column2Files:                                  

```

**Comment by Muzza** [comment]
You fixed it in 0.28.18
I have all my column settings as blank as I don't really divide columns by file type. I use the columns in different ways depending on what I'm doing.

**Comment by slynch8** [comment]
ah yes I remember now. It's using the current panel in that case. I'll get a fix in tomorrow.

**Comment by slynch8** [comment]
fixed (0.30.12)

**Comment by Muzza** [comment]
This has returned in a slightly different form. In the search window, if I double click on a header file, it correctly opens it in the window I have all my code in. If I double cluck on a C file, it opens it over the top of the search results.

**Comment by slynch8** [comment]
sorry, I deleted some code that I thought wasn't needed anymore. I'll get this fixed in the next build.

**Comment by Muzza** [comment]
Haven't had any recent problems with this
