### ISSUE TITLE
Parser has issues in evaluating some expressions in #define statements

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#648]
In the following snippet 10x will not evaluate the #if clause correctly:

```#define a (1)

#if (a==1)
#define b
#endif```

However, removing the parentheses makes the parser work correctly:

```#define a 1

#if (a==1)
#define b
#endif```

**Comment by ggnkua** [comment]
As an addendum, this also won't evaluate correctly:

```
#define a 1

#if (a+1>0)
#define c
#endif```

**Comment by slynch8** [comment]
also:
#define TEST (1 == (1 ? 1 : 0))
#if TEST

**Comment by slynch8** [comment]
also
#define TEST (0)
#if !TEST

**Comment by septag** [comment]
Here's one occasion:
![image](https://user-images.githubusercontent.com/5081921/154471213-3664d66f-f725-4c40-bded-070f47fd81a2.png)

`MR_ENABLE_DEBUG_NAMES` should be enabled:
```cpp
#define IS_RETAIL_BUILD 0
#define IS_LINUXSERVERS_PLATFORM (0)
```

if I removed the paranthesis from `IS_LINUXSERVERS_PLATFORM` then it will get parsed correctly

**Comment by slynch8** [comment]
(0) should work now

**Comment by slynch8** [comment]
done. All of the above should work in (0.31.6)
