### ISSUE TITLE
"cour" font looks too thin using a white theme

### ISSUE THREAD

**Issue by kaervin** [slynch8/10x#652]
Hello,
using the "cour" font with a light theme, at standard gamma of 1.8, the font looks overly thin.
Compare this to the default theme in notepad++, and one can see a stark difference.
To have a similar look in 10x I have to set the gamma to 0.75, which works alright for me, but I'd suspect things shouldn't stay like this.

thanks,
km.

**Comment by slynch8** [comment]
Could you give a link to the font, having trouble finding it
