### ISSUE TITLE
Build commands set to run a .bat file will fail linking in 10x, but succeed in command line

### ISSUE THREAD

**Issue by dangmoody** [slynch8/10x#659]
If I have a `build.bat` which builds my binary and I set the build command in 10x to run that `build.bat` then it will fail at the linking stage, but if I run that same build script in the command line then it will work fine.

Is the expectation that I need to do additional setup/configuration of the editor in this case (setup additional environment variables or something)? Or should it just work out of the box?

I've attached a repro project for you:
[10x_bug_build_script_fail.zip](https://github.com/slynch8/10x/files/7909226/10x_bug_build_script_fail.zip)

**Comment by slynch8** [comment]
Thanks for the repro project, taking a look...

**Comment by slynch8** [comment]
I'm not familiar with building with clang. If I build from the command line it complains about not finding stdio.h. I'm not actually sure where it is finding clang.exe, i don't remember installing it

```
main.c:1:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.

```

I also tried building from the VS2019 command prompt but then I get 

```
main-bd0e10.o : error LNK2019: unresolved external symbol __acrt_iob_func referenced in function printf
main-bd0e10.o : error LNK2019: unresolved external symbol __stdio_common_vsprintf referenced in function _vsnprintf_l
main-bd0e10.o : error LNK2019: unresolved external symbol __stdio_common_vfprintf referenced in function _vfprintf_l
LINK : error LNK2001: unresolved external symbol mainCRTStartup
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x86\libcmt.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
test.exe : fatal error LNK1120: 4 unresolved externals
clang: error: linker command failed with exit code 1120 (use -v to see invocation)
```

**Comment by dangmoody** [comment]
Ah, forgot to mention that Clang was installed and in my path etc. Apologies for that!  I've not tested other compilers (I can if you want?).

So this bug is assuming that I have Clang installed and Clang is added to my PATH in environment variables in Windows.  You could also just point to clang via the absolute path as well I suppose.

The error you get in VS2019 is what I see from 10x.

**Comment by slynch8** [comment]
I see. I have another bug where if 10x is started from the installer or updater it isn't getting path env vars for some reason, maybe it's that?

**Comment by slynch8** [comment]
To stop 10x using the VS command prompt to build try clearing the Build.VisualStudioEnvBat setting (keep the setting there just set it to nothing)

**Comment by dangmoody** [comment]
Yeah now it works fine.  Thanks! =)

In which case, would it be possible to have the option for using the VS command prompt/env vars configurable via platform/config?  That way if I want to compile something on MSVC over, say, clang I can just change the config.

**Comment by slynch8** [comment]
Yes, I'll try and come up with a better way of doing this

**Comment by dangmoody** [comment]
Awesome, thanks.  =)

**Comment by slynch8** [comment]
I've added a new bug for this https://github.com/slynch8/10x/issues/663
