### ISSUE TITLE
Function pop up with multiple options disappears after space

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#66]
```cpp
struct MyStruct
{
	void Func( int );
	void Func( int, float );
};

void main()
{
	MyStruct a;
	a.Func( 
}
```

Start to type a.Func( at the bottom of the example so that it pops up the window with the function declarations. At first it correctly shows both options.
![2021-05-27 08_42_35-Window](https://user-images.githubusercontent.com/1583441/119740731-bf2b7e00-bec7-11eb-9b2c-4d76154eabc6.png)

Then as you type the first space, it removes the first option.
![2021-05-27 08_42_47-Window](https://user-images.githubusercontent.com/1583441/119740740-c18dd800-bec7-11eb-9b73-71a487044418.png)

**Comment by slynch8** [comment]
This is an experimental feature, it will only show the selected function once you start typing the args. I've made it ignore whitespace now. Let me know if it's annoying and I'll add a setting to disable it.
