### ISSUE TITLE
Using cursor keys in Find/Replace box

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#67]
You can use the left/right arrow keys to move through the menu options in the Find & Replace boxes.
I find this to get in the way of editing the actual find/replace text. I would expect only Tab and Shift+Tab to move between Find/Replace boxes and the various options.

Here is a common scenario for me. I perform a Find & Replace. Then press Ctrl+H to do a follow up Find & Replace. I want to append something to the Find term, but it is highlighted so I need to clear the highlight before typing. Normally I would do this by pressing the right arrow key (to take me to the end of the selected term, as it works in the main text editor), but doing this here will move the cursor to the Replace box.

Similarly if I want to edit the start of the Find text, I would expect pressing the Left arrow key would take me to the start (again as it works in the normal text editor). But instead it takes me to one character in from the right hand side. It feels like the rules for the Find/Replace editing are different from the text editor.

Also whilst I'm here... there is a drop down list of recent Find terms, but none for Replace. Can we have both?

**Comment by slynch8** [comment]
I've stopped it moving focus if the text box has selected text which should get around the case you describe.
I've also added a new setting FindPanelCursorKeys so you can turn it off if it's still annoying. 
And I've added the dropdown (0.25.15)
