### ISSUE TITLE
10x likes to create whitespace on it's own

### ISSUE THREAD

**Issue by dangmoody** [slynch8/10x#682]
If I have a function:

```c
// if you copy and paste this function (or any function with whitespace line gaps in it)
// then 10x will make whitespace between the printf statement and the exit code
int main( int argc, char** argv ) {
	printf( "Yeah this is my awesome project with my awesome code in it or whatever.\n" );

	return 0;
}
```

Or really any function, and I copy/cut and paste it, then 10x will create a tab character between the `printf` call and the `return 0;` (in this instance).

I've only tested this using tabs and when inside a 10x workspace and it only seems to happen inside files that are marked by 10x as a source file (.c, .cpp, etc.).  I've also only tested with auto-formatting off.

I know this is only a minor thing, but now that I've noticed it I can't _not_ notice it and it's quite annoying.  😅

**Comment by slynch8** [comment]
fixed (0.30.30)
