### ISSUE TITLE
10x locks up on exit

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#689]
[Opening this specific file](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/byte-oriented-aes/aestable.c) into 10x and then exiting, the editor seems to hang, maxing a CPU core.

**Comment by slynch8** [comment]
it doesn't happen for me, if you can get it again can you force a crash dump?

**Comment by ggnkua** [comment]
When this happens, the 10x window is gone, but the process exists in the task manager. So I can't create a crash dump from the 10x menu. But I can "create dump file" from the task manager. This produces a 500Mb file which compresses down to 50Mb with 7zip. Does this help you?

**Comment by slynch8** [comment]
yes please

**Comment by ggnkua** [comment]
Good, uploaded!

**Comment by ggnkua** [comment]
So, to recap: I open this file into 10x, then exit 10x. The window closes but the task still appears on task manager, and the laptop fans are going nuts. I have to terminate 10 manually.

**Comment by ggnkua** [comment]
Update: I found out that the very high CPU usage happens even when 10x is running (i.e. I don't have to close it). So I was able to generate a crash dump from the editor - which I uploaded too.

**Comment by slynch8** [comment]
fixed (0.30.31)
