### ISSUE TITLE
Find box keeps focus

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#69]
Press Ctrl+F to start a search. Enter the search term and press Return or F3 to execute.
The search box keeps the cursor focus, so you can't edit anything in the text editor without pressing escape to close it.

**Comment by slynch8** [comment]
Unfortunately my PC has died so I'm going to be out of action for a few days. I'll get to this as soon as I can.

**Comment by slynch8** [comment]
(0.25.17) I've added a setting CloseFindPanelOnEnter which will close the find panel on Enter or F3. It's off by default, although I'm tempted to default it to on, I can't see any downsides. Let me know how you get on.
