### ISSUE TITLE
binding SaveAll to ctrl+shift+S not working

### ISSUE THREAD

**Issue by slynch8** [slynch8/10x#691]

**Comment by slynch8** [comment]
seems to be working for me, can you send your key mappings file?

![image](https://user-images.githubusercontent.com/7141856/151712228-88c681f7-9b0d-4eac-a91e-2792a46c4299.png)

**Comment by SimpsonGSD** [comment]
[KeyMappings.txt](https://github.com/slynch8/10x/files/7969620/KeyMappings.txt)

Running SaveAll command works but the key binding doesn't.

**Comment by slynch8** [comment]
did you rename the file? It should be KeyMappings.10x_settings. After renaming it works for me.

**Comment by SimpsonGSD** [comment]
I renamed it so github didn't complain. 
Other bindings work.
The issue for me is with the binding Control Shift S. 
Other bindings I try are fine.

**Comment by slynch8** [comment]
can you bind Control Shift S to anything else?

**Comment by SimpsonGSD** [comment]
No

**Comment by slynch8** [comment]
and can you find Control Shift <some other key> to SaveAll?

**Comment by SimpsonGSD** [comment]
Just Control Shift? No
Control Shift K works for example though.

**Comment by slynch8** [comment]
yes, that's what I meant, github mangled my message. This is really odd, I can't think why just that key binding wouldn't be working.

**Comment by slynch8** [comment]
can you try resetting all other settings by renaming your %appdata%\10x folder

**Comment by SimpsonGSD** [comment]
Apologies - the issue is on my end. 
For some reason Contol Shift S does not work using Remote Desktop!

**Comment by slynch8** [comment]
ok, glad you sorted it. That's useful to know.
