### ISSUE TITLE
Build output / filenames error

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#7]
Build output error message:
`c:\program files (x86)\windows kits\10\include\10.0.17134.0\ucrt\stdlib.h(289): error C2059: syntax error: etc`

When double clicking on the error message, 10x pops up an error box with: 
`Failed to open file: C:/Program Files - File does not exist.`

I'm guessing the parsing of the line sees the (x86) brackets in the filename and assumes it is the line number.

**Comment by slynch8** [comment]
fixed in (0.17.17.0)
