### ISSUE TITLE
Pressing tab erases part of line

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#70]
type this and then press tab after the final character. It removes the last four characters.
```cpp
#define SOMETHING
```
The autocomplete shoes SOMET for some reason. So I guess it is related to that. It works with any word, and there is nothing declared as SOMET or SOMETHING anywhere else.

![2021-06-08 12_51_26-Window](https://user-images.githubusercontent.com/1583441/121115332-509bd800-c858-11eb-9a03-5ac02ad83b07.png)

**Comment by slynch8** [comment]
That's a tricky one, there are times when you do want it to autocomplete to something shorter, for example if you've typed an incorrect character. Maybe I could put a limit on the length that is deleted, it's obviously wrong in this case.

If you want to find out where SOMET comes from you can try goto-def on it.

**Comment by Muzza** [comment]
This isn't the autocomplete replacing the word with a known shorter word.
It does it in a completely empty workspace, with any word of similar length. SOMET is not defined anywhere and alt-g does nothing.

**Comment by slynch8** [comment]
That's odd. I can't think where that is coming from. I'll have a look and see if I get the same thing when I have a PC again.

**Comment by slynch8** [comment]
fixed (0.26.14). I found out what was happening, it was showing the current symbol you were typing in the list. Happened on every letter if you typed slowly enough. Only showed up on defines because they don't need a ; to complete the symbol.
