### ISSUE TITLE
Namespace Aliases support

### ISSUE THREAD

**Issue by all500234765** [slynch8/10x#703]
```cpp
namespace VeryLongName1 {
	namespace VeryLongName2 {
		typedef unsigned int SomeTypeA;
	}
}

namespace Namespace2 {
	namespace ShortName = VeryLongName1::VeryLongName2;

	ShortName::SomeTypeA function(ShortName::SomeTypeA T);
}
```
![{0AC5F0F3-DEEE-4C42-9B90-9B634A482339}](https://user-images.githubusercontent.com/8898684/152124726-c0b3247e-002e-4c87-8c1b-0d18d7479100.png)

https://docs.microsoft.com/en-us/cpp/cpp/namespaces-cpp?view=msvc-170#namespace_aliases

**Comment by slynch8** [comment]
done (0.32.90)
