### ISSUE TITLE
Tab still shows new.txt when hovered after doing save as

### ISSUE THREAD

**Issue by SimpsonGSD** [slynch8/10x#707]
Repro:
File -> New Text File
File -> Save As -> workspace/Entity.h
Hover over Entity.h tab
10x shows new.txt instead of correct filepath.

![image](https://user-images.githubusercontent.com/11320611/152154349-93662f65-45f9-4530-be00-1f2051754699.png)

**Comment by slynch8** [comment]
fixed (0.31.15)
