### ISSUE TITLE
What's the intended workflow for new files when using solutions?

### ISSUE THREAD

**Issue by SimpsonGSD** [slynch8/10x#708]
Hi, what is the intended workflow to add new files to a project when using a .sln ?
Do we need to add them via Visual Studio, then reload the solution?

Thanks.

**Comment by slynch8** [comment]
At the moment yes. Eventually I'll support adding of files in 10x, see this bugs:
https://github.com/slynch8/10x/issues/268
https://github.com/slynch8/10x/issues/226
