### ISSUE TITLE
Parser acting odd

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#71]
I have a file where the parser is acting up. It recognises some member variables but not others. Attempting to reproduce it in a single file has proven to be difficult, but I've found a semi-reliable way to make it happen - although it is still unpredictable.

Create a new workspace with two files:
header.h
```cpp
namespace NS
{

namespace NS2
{
	struct S2
	{
		int x,y;
	};
};

class MyClass
{
	MyClass();
	template<typename T> T*  Make() { return nullptr; }

protected:
	NS2::S2 mData[3];
};

};
```

source.cpp
```cpp
namespace NS
{

using namespace NS2;

MyClass::MyClass()
{
	S2 s2; // watch me
}

};
```

The 's2' in the constructor of MyClass is the line acting up.
When I delete the parser cache and open the folder from new, s2 has syntax highlighting and everything looks fine.
If I then edit the header file, (add a new member variable etc.) then save it, sometimes the s2 in the cpp file will go white. Sometimes it happens immediately, sometimes it takes several edits, but I've had it happen four or five times in a row.

This may not even be the same problem I'm experiencing in my code base as that one doesn't require any editing to go wrong - the member variable mData just doesn't work even from a clean parser cache. But this is the closest I got to reproducing something similar. Sorry for the messy bug report...

**Comment by slynch8** [comment]
perfect repro, got it 100%. Working on a fix - thanks.

**Comment by slynch8** [comment]
The repro is fixed, and will hopefully fix your other issues as well. There was a bug reparsing 'using namespace' statements, and another bug introduced with the file watcher where the file would be reparsed when saving.
