### ISSUE TITLE
Various small UI bugs

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#718]
All tested in v0.30.37:

- Clicking on the configuration boxes arrow icons a couple of times consecutively will make their boxes selectable permanently. 
- Mouse over a function name or define etc pops up a box that describes the item. Using the mouse wheel to scroll up or down keeps the pop up open, so it looks like it's open in the air without context.
- Same thing as the previous item, some times (cannot reproduce it reliably) moving the mouse wheel to scroll will not scroll the window at all.

**Comment by ggnkua** [comment]
Another small thing:

- Clicking to open a configuration/platform and clicking on the same location again to close it doesn't do that. For example, clicking on "Debug" will open the "Debug/Relase" pop-up, but clicking on "Debug" again will not close the pop-up.

**Comment by slynch8** [comment]
-- Clicking on the configuration boxes arrow icons a couple of times consecutively will make their boxes selectable permanently.
Fixed

-- Clicking to open a configuration/platform and clicking on the same location again to close it doesn't do that.
Fixed

**Comment by slynch8** [comment]
all of these should be fixed now
