### ISSUE TITLE
crash after closing a file

### ISSUE THREAD

**Issue by Alouett-e** [slynch8/10x#727]
With a clean 10x install (deleted 10x in APPDATA) :
- Open a file
- Select 1 word then another
- close the document
- 10x crash

https://user-images.githubusercontent.com/88099147/152650619-a6680a96-1745-4a93-82d8-44a833cfac54.mp4

Also minor visual bug :
- pressing WIN + Right then WIN + Left
- you can see a window below the main window on the edges

https://user-images.githubusercontent.com/88099147/152650679-51ad4593-6a6e-4002-a16f-f51058b22356.mp4

**Comment by slynch8** [comment]
Thanks for the videos.
I've split the second bug out to make it easier to track https://github.com/slynch8/10x/issues/new

**Comment by slynch8** [comment]
crash fixed in (0.30.41)
