### ISSUE TITLE
GotoSymbolDefinition goes to forward declaration

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#74]
I have this setup:
```cpp
// header file 1
typedef struct Thing Thing;

// header file 2
typedef struct Thing
{
 int data;
} Thing;

// source file
void Func()
{
 Thing* thing = GetThing();
}
```

If I use GotoSymbolDefinition on 'Thing' within Func() then it takes me to header file 1, when really it should be header file 2.
This doesn't happen when I tried to reproduce an example in a single file.

**Comment by slynch8** [comment]
Fixed (0.26.6)
