### ISSUE TITLE
usage time

### ISSUE THREAD

**Issue by benanil** [slynch8/10x#742]
hello Stewart I hope you are doing well, AFAIK you have usage time data, can we see it.

**Comment by slynch8** [comment]
Hi benanil. Not easily, the data is stored in the 10x.telemetry file which is just 4 ints; day, month, year, usage time. Every day it gets sent anonymously to the server and reset back to zero. I could maybe add a feature that tracks your usage if you'd find that useful?

**Comment by benanil** [comment]
its not prior task but it could be useful
