### ISSUE TITLE
Mouse cursor does not change correctly when entering scrollbar / minimap slowly from the right

### ISSUE THREAD

**Issue by Rattenhirn** [slynch8/10x#750]
1. Have a view on the right edge of the windows with a vertical scroll bar or minimap (i.e. output view)
2. Slowly move mouse cursor over the right edge of the window onto the window
3. Observe that it changes to the horizontal resize shape
4. Keep moving to left
5. Observe the the cursor stays in the horizontal resize shape until the scroll bar or minimap has been cleared and a text view is reached, where it changes to the text entry cursor

This also happens when moving the cursor of the right edge at normal speed, but this is less reliably reproducible.

**Comment by slynch8** [comment]
fixed (0.31.6)
