### ISSUE TITLE
Operator [ ] and arrays

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#76]
This one has been bugging me for ages, and I've finally found how to reproduce it.
If a class has an operator [] in it, then declaring an array of that class results in the 10x parsing not handling it correctly.

```cpp
struct MyStruct
{
	int x,y;
	int Something( const MyStruct& v );
	inline int&	operator[]( int i );
};

void Func()
{
	MyStruct a;
	a.x = 0;	// <-- OK

	MyStruct b[3];
	b[1].x = 0;	// <-- no autocomplete + x shows in white
}
```

**Comment by slynch8** [comment]
Good find - thanks for the repro. I wasn't treating array variables as pointers, and I've now disabled the [] operator on pointers. Fixed (0.26.8)
