### ISSUE TITLE
C++.DefinedOut doesn't seem to be updating

### ISSUE THREAD

**Issue by ForestCSharp** [slynch8/10x#767]
I was trying to prevent my DefinedOut code from being darker. Maybe this isn't the correct way, but setting C++.DefinedOut to white doesn't seem to be working
 
C++.DefinedOut:                                   255, 255, 255

Result:
![image](https://user-images.githubusercontent.com/7401287/154309496-e379472d-2be6-44cf-944a-76b6f3b137e7.png)

**Comment by slynch8** [comment]
I've removed that colour setting and instead added a new setting called Parser.DefinedOutBrightness. Build (0.31.6)

**Comment by ForestCSharp** [comment]
Awesome I'll check that out. Thanks!
