### ISSUE TITLE
Keep unsaved files

### ISSUE THREAD

**Issue by WessamUnity** [slynch8/10x#77]
Currently 10x doesn't keep unsaved files after restart (like what other text editors do e.g.: Sublime Text, Notepad++).

While 10x presents a warning if the user attempts to close 10x manually, no warning is presented if the user chooses to install an update which automatically restarts 10x. This results in all data in that file being lost forever.

**Comment by slynch8** [comment]
Sorry about that, hope you didn't lose anything. Fixed in (0.26.11). It will now prompt to save changes.
