### ISSUE TITLE
Selection is not reset without pressing escape

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#772]
* select a text
* do **not** press ESC and move cursor to another place
* start selecting a text
* your selection extends. <- BUG
if you select text from another line, then your selection becomes multiline

**Comment by slynch8** [comment]
I can't get this, could you provide a gif/video?

**Comment by Roman-Skabin** [comment]
Hmm, I've just updated editor to the version 0.31.6 and it seems like it goes away. If I'll see this bug again, I'll send you a video.

**Comment by slynch8** [comment]
closing for now, re-open if it happens again
