### ISSUE TITLE
Text is added instead of being replaced

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#773]
* Copy text
* Select another text you want to replace with the copied one
* Press Paste
* Selected text is not replaced, copied text just appends to selected one

**Comment by slynch8** [comment]
I can't get this to happen, could you provide a gif/video. Are you using ctrl+C, ctrl+V?

**Comment by Roman-Skabin** [comment]
Hmm, I've just updated editor to the version 0.31.6 and it seems like it goes away. If I'll see this bug again, I'll send you a video.

**Comment by slynch8** [comment]
closing for now, re-open if it happens again
