### ISSUE TITLE
Run seems to Build instead of running..?

### ISSUE THREAD

**Issue by TrianglesPCT** [slynch8/10x#776]
When I go to Debug->Run or hit ctrl F5 it doesn't run my game, instead it prints out some info that show it attempting to build.  

Here is the exact text that shows up in the Build output when I hit Run

----- Building Project Cloud Release Win64_AVX2 -----
Executing build command:
msbuild /t:"0_ Core\Cloud" /p:Configuration="Release" /p:Platform="Win64_AVX2" /verbosity:minimal "C:/depo/common/build_premake17/Cloud.sln" /m

  Cloud.vcxproj -> C:\depo\common\build_premake17\bin\Win64_AVX2\Release\Cloud.exe
===== Success : 0 errors, 0 warnings =====

 When I hit debug it does open VS and launch the game though.

**Comment by slynch8** [comment]
You can stop it building before run with the BuildBeforeRun setting.

Can you look in the log file %appdata%\10x\10x.log and see if it has the right path for the exe, should look somehting like this
`22/02/2022 20:12:37: [10x] Running: D:\temp_projects\testcpp\x64\Debug\testcpp.exe `

**Comment by TrianglesPCT** [comment]
I figured out what was wrong, it doesn't seem to know about the working directory being different from the directory the .exe is located at.
 My working directory was set to: ..\..\..\..\app\makemake\bin
(This is relative to the .exe location)

This data seems to be stored in a file with .vcxproj.user extension along side the .vcxproj file

And looks like this:

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release Win64_AVX2|x64'">
    <LocalDebuggerWorkingDirectory>..\..\..\..\app\makemake\bin</LocalDebuggerWorkingDirectory>
    <DebuggerFlavor>WindowsLocalDebugger</DebuggerFlavor>
  </PropertyGroup>

I found that you could right click on projects in 10x and set working directory, so got it working.

**Comment by slynch8** [comment]
Glad you got it working. I'll take a look though, it should be pulling across the debug settings from the .user file

**Comment by slynch8** [comment]
I've added a separate bug for this
https://github.com/slynch8/10x/issues/779
