### ISSUE TITLE
Maybe add .fx to Parser.Extensions?

### ISSUE THREAD

**Issue by TrianglesPCT** [slynch8/10x#777]
I use .fx for many shader files, not sure how common this is, but I think it as the default extension for much older DX stuff. 

I added it to my local file, but maybe add it to the default parser?

**Comment by slynch8** [comment]
good idea, thanks for letting me know. Added in (0.31.8)

**Comment by zauberfuchs** [comment]
If it is possible .fxh would also be a great addition
