### ISSUE TITLE
After 0.31.6, closing and then reopening the workspace tree or build output, opens them as floating windows even if I redock them.

### ISSUE THREAD

**Issue by kondamask** [slynch8/10x#778]

**Comment by kondamask** [comment]
It looks like this only happens only when they are the only tab in their panel. For example if the Build Output and Workspace tree are "bundled" on the same panel you can close and open the and they will be correctly placed on their panel. But if the Build Output for example is the only tab on its own panel at the bottom, closing it and reopening it will open it as a floating window.

**Comment by slynch8** [comment]
I can't get this, how are you closing the workspace, from the file menu?

**Comment by slynch8** [comment]
also, try closing 10x and deleting/renaming your workspace_settings file in %appdata%\10x\Workspaces

**Comment by kondamask** [comment]
Deleting the workspace_setting folders did not fix the issue.
Here is a gif: https://imgur.com/a/B22CiSl
Also, if only one of these is open they stay docked. But if I toggle the workspace tree for example while the build output is open, it will open as a floating window. You can see this in the second gif.

**Comment by slynch8** [comment]
got it - thanks! I think I've got a fix...

**Comment by slynch8** [comment]
I've uploaded a new build, let me know if that fixes it

**Comment by kondamask** [comment]
yea all good. thanks!
