### ISSUE TITLE
Format file gives incorrect indentations when args are on a separate line

### ISSUE THREAD

**Issue by ssylvan** [slynch8/10x#78]
Example:

```
int test(
  int x ) {
  return 0;
}

int test2() {
  return 0;
}
```

If you format this code, the test2 function will end up getting indented an extra tab width (tested with tabs as spaces  and 2 spaces per tab). Each function with the args on a separate line will cause one more tab indentation on subsequent code, causing the file to walk off to the right.

This matters because when you have many args with long types, it's often necessary to put (some of) the args on a separate line if you want to keep the max width something reasonable.

**Comment by slynch8** [comment]
Fixed (0.26.13). Most of my testing has been with the brace on a new line, so I missed this case. Let me know if you find any more.
