### ISSUE TITLE
Menu vs. shortcuts conflict

### ISSUE THREAD

**Issue by Rattenhirn** [slynch8/10x#781]
Hey,
I usually map my Perforce shortcuts to Alt+P, followed by another key.
In 10x Alt+P always opens the "Parser" window menu, thus blocking Alt+P (as well as some other combinations from being useful).
Personally, I have never used Alt+Key to access the window menu and could do without that completely and wouldn't mind to see it gone / disable-able. But I guess there is also a more canonical to this conflict. :)

**Comment by slynch8** [comment]
fixed (0.31.13)
