### ISSUE TITLE
Syntax highlighting is not working properly in some cases

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#785]
1. **Moo::Handle**
I can go to definition, but it highlights type as a plain text.
Definition is
```C++
namespace Moo
{
    // ...
    typedef int Handle;
    // ...
}
```
2. **distance**
There is a method in a class and there is an input argument in a function named identically. Syntax highlighting highlights the argument as a function.

**Screenshot:**
![image](https://user-images.githubusercontent.com/40520199/155998196-deaa8d90-792c-4420-ab8c-6a3b5b84d11b.png)

**Comment by slynch8** [comment]
typedef problem is fixed. I think the 'distance' problem is fixed a well. Let me know if it's still a problem
fixed in build (0.31.13)
