### ISSUE TITLE
Add scrollbar to the workspace settings window.

### ISSUE THREAD

**Issue by kondamask** [slynch8/10x#789]
This may only be a problem on smaller res screens (hd ready on my case) but the window can barely fit all the options on the build and parser tabs. This is what it looks like with the maximum possible height.
https://imgur.com/uwbYmol

**Comment by slynch8** [comment]
fixed (0.31.15)

**Comment by kondamask** [comment]
The "Additional Include Paths" is now pretty much broken. Can't really explain it. Hope this helps: https://i.imgur.com/Iegd5ib.gif

**Comment by slynch8** [comment]
fixed (0.31.18)
