### ISSUE TITLE
Error opening file %s

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#79]
I've been getting this a fair bit recently. Its also gone hand in hand with crashes.
I delete a file, close the file in 10x. Later 10x crashes, when it restarts I get this.

![2021-07-12 07_55_50-Window](https://user-images.githubusercontent.com/1583441/125211019-a398fd00-e2e6-11eb-9abc-ed48394c6e99.png)

**Comment by slynch8** [comment]
fixed (0.26.13)
