### ISSUE TITLE
10x does not reposition search results that are 'underneath' the search bar

### ISSUE THREAD

**Issue by dangmoody** [slynch8/10x#792]
When searching in a file if I get a match that just so happens to be positioned underneath the search bar, 10x will not re-position it to be in the screen.  I'm guessing this is due to the fact that 10x considers it technically inside the editor screen bounds?

This can cause confusion because I won't see any search results on the screen but then if I press Enter again it will take me further down the file.  The expected behaviour (to me, at least) is to treat that search result as if it's outside of editor screen bounds (like any other search result further down/up in the file, for instance).

**Comment by slynch8** [comment]
fixed (0.31.18)
