### ISSUE TITLE
Find/Replace Selection no longer auto-enabled

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#793]
If a block of text is selected and I press Ctrl+H for Find/Replace, the 'Sel' option used to be automatically selected, it no longer is.

**Comment by slynch8** [comment]
fixed (0.31.18)

**Comment by slynch8** [comment]
How about only enabling Sel for multi-line selections, would that help?

**Comment by slynch8** [comment]
I've disabled Sel for the Find panel, as you say this isn't that useful. I've left it enabled for replace but I only set it if the selection is multi-line.

I've also fixed the scroll bug.

Let me know if it's still not working as expected.

build (0.31.19)
