### ISSUE TITLE
Add indent left and indent right key shortcuts

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#794]
VS Code analogue:
![image](https://user-images.githubusercontent.com/40520199/157328875-4c313613-66b3-4cae-ace9-22d31afd18c2.png)

**Comment by slynch8** [comment]
If you make a selection Tab and Shift Tab do that. But I'll also add it as a command.

**Comment by Roman-Skabin** [comment]
Oh, thanks, didn't know about shift-tab

**Comment by slynch8** [comment]
I've added IndentLine and UnindentLine commands (control+], control+[)
(0.31.20)
