### ISSUE TITLE
Search window - Whole Word sometimes hidden

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#8]
I've had this happen a few times where the File Types dropdown covers up the tickbox for 'Whole Word'.
If I close and restart 10x, it fixes itself.

![2020-12-03 15_55_46-Window](https://user-images.githubusercontent.com/1583441/100966080-323ee200-3580-11eb-8765-855d4197b330.png)

I've not touched the File Types itself. Not sure of the cause.

**Comment by slynch8** [comment]
fixed in (0.18.0.0)
