### ISSUE TITLE
Multiple copy/pastes stopped working

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#805]
Ctrl + Shift + V to do a paste from previously copied text seems to be broken.
A menu pops up and is populated correctly, but there are a number of problems with it:
1. Sometimes up/down arrow keys do not function. (seems to be every other time I bring it up)
2. Pressing return to select the item closes the box but pastes nothing.
3. Clicking on the item I want always pastes the first item in the list.

**Comment by slynch8** [comment]
fixed (0.31.34)
