### ISSUE TITLE
Multi line comments are not auto indented when using Format File

### ISSUE THREAD

**Issue by kondamask** [slynch8/10x#806]
https://imgur.com/a/myWQkIu

**Comment by slynch8** [comment]
I can't seem to get this, could you share the before/after file?

**Comment by kondamask** [comment]
Maybe this helps: https://imgur.com/tkELgBF

**Comment by slynch8** [comment]
I see - thanks. I'll get this fixed in the next build

**Comment by slynch8** [comment]
fixed (0.31.36)
