### ISSUE TITLE
Preprocessor bug

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#810]
Copy the code below, hover your mouse over the line struct APPEND_TYPEID(Data)
It will correctly say 'preprocessed line: struct Data99'
Now uncomment the bottom line that redefines Data. Hover the mouse over the line again
It will incorrectly say 'preprocessed line: struct APPEND_TYPEID(Data)99

The main reason this is a problem is that 'Data' is then not understood by the parser anywhere further down the file, such as its usage in Func()

```cpp
#define MACRO_CONCAT2x(x,y) x ## y
#define MACRO_CONCAT(x,y)  MACRO_CONCAT2x(x,y)

#define TYPEID 99

#define APPEND_TYPEID( x ) MACRO_CONCAT( x, TYPEID )

struct APPEND_TYPEID(Data) // <-- hover mouse over here
{
 int x;
};

//#define Data APPEND_TYPEID(Data)

void Func( void )
{
	Data myData;
	myData.x = 0;
}
```

**Comment by slynch8** [comment]
fixed (0.31.38)
