### ISSUE TITLE
[WEBSITE] Minor visual issue on the home page

### ISSUE THREAD

**Issue by chooie** [slynch8/10x#824]
Just FYI, the lovely green download button's vertical text alignment is 'off' at https://10xeditor.com/index.htm.

![Screen Shot 2022-03-27 at 10 00 17 PM](https://user-images.githubusercontent.com/5822082/160300844-1e0c8a74-69d3-4f56-9b0d-e60e255fa960.jpg)

It can be fixed with:

```css
display: grid;
place-content: center;
```

...in the `.MainDownloadButton` block.

![Screen Shot 2022-03-27 at 9 51 38 PM](https://user-images.githubusercontent.com/5822082/160300848-ca8a3ba3-0af4-4753-a0a3-1884b23a01b6.jpg)

**Comment by slynch8** [comment]
Thanks very much. I've made the fix. Although it looks like it's because it's using the wrong font, it should be using 'Segoe UI', do you not have that installed?

**Comment by chooie** [comment]
On my Mac, it seems that that font isn't installed by default (no Segoe UI in the font book). It defaults to "Times":

![Screen Shot 2022-03-27 at 11 02 16 PM](https://user-images.githubusercontent.com/5822082/160302884-91921a88-d5aa-4b5c-823b-221248d9362b.jpg)

**Comment by slynch8** [comment]
I was just wondering if you could check the site again and see if it's now using the correct "Segue UI" font? I've now installed the font on my website.

**Comment by chooie** [comment]
Hi Stewart, 

I can confirm that I'm now seeing the Segue UI rendered (after a hard refresh). LGTM!

**Comment by slynch8** [comment]
great - thanks!
