### ISSUE TITLE
Goto symbol definition bug

### ISSUE THREAD

**Issue by Muzza** [slynch8/10x#83]
```cpp
// header file
struct MyThing
{
	void Works(void);
	void Works(int);

	void DoesNotWork(void);
	void DoesNotWork(int) { DoesNotWork(); }
};
```

```cpp
// cpp file
void MyThing::Works()
{
}

void MyThing::Works(int x)
{
}

void MyThing::DoesNotWork()
{
}

void main()
{
	MyThing a;
	a.Works(1);
	a.DoesNotWork(1);
}
```

Alt-G on a.Works(1) will take you to the declaration in the header (although the wrong version), and a second Alt-G will take you to the definition in the source file.
Alt-G on a.DoesNotWork(1) will take you to the declaration in the header (the right version), but subsequent Alt-Gs will just alternate between the two declarations, never taking you to the source file definitions.

**Comment by slynch8** [comment]
The parser doesn't support function overloading yet, so it's random which one it will choose. It's on the list.

**Comment by slynch8** [comment]
Closing. Tracked by https://github.com/slynch8/10x/issues/259.
