### ISSUE TITLE
UI improvement: add support for ctrl/left+right in text/edit boxes.

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#833]
Shift+left/right appears to work fine, but ctrl+left/right or shift+ctrl+left/right won't jump to the next/previous word. Would be nice to have that.

v0.31.51

**Comment by ggnkua** [comment]
I didn't feel like opening a new issue for this, but: While we're at it, could we also have pressing Return to activate the OK button?

**Comment by ggnkua** [comment]
Just noticed: Ctrl+Left/Right (shifted or not) also does not work in find/replace pop-up boxes. Would be nice to have for quickly selecting words.

**Comment by ForestCSharp** [comment]
+1 to this request

**Comment by slynch8** [comment]
ctrl+left/right is fixed in latest.

@ggnkua can you let me know which OK button doesn't accept Enter.

**Comment by ggnkua** [comment]
Thanks @slynch8!

The Ok button in `Workspace settings` for example.

Also, a minor thing I noticed in latest: go to the start of the line, hold shift+control and press right. Eventually the whole line will be selected... and then it will be deselected. Personally I'd expect the selection to not disappear due to repeated shift+ctrl+right.

**Comment by slynch8** [comment]
Closing this bug and added two new bugs:
https://github.com/slynch8/10x/issues/1059
https://github.com/slynch8/10x/issues/1060
