### ISSUE TITLE
Weird behaviour when jumping to errors from the "build" window

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#838]
My case is the following:

- I have split the screen in 2 panes
- The build window is in the right pane
- I have one file open in both panes

I observed that when I wanted to jump to some warnings from the build window on the editor, the editor prefers to open the file on the right pane, even if I have the file open in the left pane and is on top.

My suggestion would be that the editor would try to open and give focus to the copy of the file that isn't on the same pane as the build window. That way one is able to read both the warning/error and the code at the same time.

(v0.31.54)

**Comment by bbroscoe** [comment]
Would also like to see an option for GotoSymbolDefinition and similar functions to open on a pane that isn't the current one, so the original code and results can be viewed side by side. This should also happen regardless of if and where a file is already open.

**Comment by slynch8** [comment]
Done. If you remove the ColumnNFiles settings GotoNextBuildError will always open in column 0 if the build panel is in column 1.

And I've added a new setting GotoDefColumn. Again, remove the ColumnNFiles settings and set GotoDefColumn to "other". Goto-def will then open the file in a column other than the current one.
