### ISSUE TITLE
Small formatting bug (*)

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#839]
```C
r=(19595*r)>>16;
```

gets formatted to

```C
r = (19595*r)>> 16;
```

i.e. no spaces around the multiplication. The shifting has been mentioned in #837

(v0.31.54)

**Comment by slynch8** [comment]
fixed (1.0.125)

**Comment by slynch8** [comment]
I've had to roll back the fix, it was breakpoint pointer asterisk formatting.

**Comment by slynch8** [comment]
fixed again (1.0.128)
