### ISSUE TITLE
Menus painfully slow to appear

### ISSUE THREAD

**Issue by dbechrd** [slynch8/10x#848]
I just installed 10x out of curiosity, used it for less than 10 seconds, and am already annoyed with how slow it feels. For something that's claiming to make everything instant, why does it take 10x longer for menus to appear when you hover your mouse than any other program on Windows? This hover delay is infuriating. Please make it instant and live up to the claims on the website.
#FreeTheMenus

**Comment by dbechrd** [comment]
Also, the menu disappear is extremely annoying. It adds and extra click to every single operation. Sure, once people get used to the program maybe they'll use hotkeys, but again, if your goal is to make the program fast, don't do clever things like hide the main menu because you think it looks cleaner without thinking about the fact that now every common operation is significantly slower and more frustrating.

**Comment by dbechrd** [comment]
There's also a weird rendering order bug if you click the "File" menu then move your mouse to hover the tab of the first open file (which is easy to do accidentally since they're so close together, I wasn't actually trying to do anything with the file while the menu is open of course).

![image](https://user-images.githubusercontent.com/707367/161363422-1e2a02cb-b69b-4dd0-9b4e-d2c97ac6addc.png)

**Comment by dbechrd** [comment]
Seems like a cool project so far. I clicked "Build" and nothing happened. It would be helpful if it printed something to the build window like "This feature is not yet implemented" (I'm assuming it's not since it doesn't do anything?)

**Comment by slynch8** [comment]
Hi dbechrd, sorry you had a bad first experience of 10x. I've not seen menus being slow to appear before. If UI.HideMenu is true the menu should appear as soon as the mouse moved over the title bar. It's a fair point about UI.HideMenu defaulting to false though.

Build should be working. Are you opening a 10x workspace or a Visual Studio sln? If it's a sln it will call msbuild to build the sln, if it's a 10x workspace you'll need to setup the build command yourself. Right click on the workspace node in the workspace tree view and select settings.

I'm happy to help you with these issues if you want to contact me directly.
https://10xeditor.com/contact.htm

This is what the menu should be like:

![menu](https://user-images.githubusercontent.com/7141856/161372543-ed3dffe7-b52b-4df6-bb32-1302491f183e.gif)

**Comment by dbechrd** [comment]
Morning Stewart, thanks for the very fast and friendly response to my complaints. Super appreciate it. Let me provide a more scientific analysis of my emotional "slow" response.

I meant the hover speed of a submenu appearing when you hover, not the main menu itself. I have nothing to compare that to since other applications don't do that, but it feels "instant" IMO.

I recorded submenus appearing in other programs I use and, to my surprise, VS 2022 is actually slower, so I'm not sure why 10x felt so slow. Maybe my expectations were confused by expecting to be fast an overanalyzing? In any case, Blender is quite a bit faster. It would be cool to have this be configurable by milliseconds in the settings. I'm curious what 1 frame would feel like.

Here's a comparison video I recorded:
https://www.youtube.com/watch?v=Zf-a6WM6brw

You can use the < and > keys on YouTube to step frame-by-frame. There's a frame counter in the lower left. The timings for each app I tested are at roughly these timestamps (I tried to slow it down in post but I have a busy day and couldn't figure it out in time):

0:01 - 10x Editor
Frame 3: Hover highlight appears
Frame 22: Menu appears

0:14 - Visual Studio 2022
Frame 3: Hover highlight appears
Frame 28: Menu appears

0:22 - Blender 3.0
Frame 4: Hover highlight appears
Frame 16: Menu appears

Anyways it seems like you're faster than Visual Studio from my measurements, so I guess I was just paying too much attention to something. It turns out most software is slow if you pay attention it seems, so kudos to you for trying to fix that.

I'm running 64-bit standalone alpha, so it seems I just didn't know I had to configure "Build". I suspect as much, but since the program did literally nothing when I clicked it I just assumed it wasn't implemented yet. I do think it should say e.g. "Configure build settings in XYZ menu" or automatically pop-up the settings if you have no config the first time you try to build so that users aren't totally left in the dark.

**Comment by slynch8** [comment]
Hi dbechrd, thanks for clarifying. There is a delay on the submenu appearing of 350ms. This is to stop sub menus appearing as you move the cursor down the menu, so they only appear when you pause the mouse. It's not something I've given much thought to to be honest, I was just copying what other software does. But you're right, it doesn't need to be that long. I'll try experimenting with a lower value.

Good idea, I'll add a message if the build command isn't set.

**Comment by slynch8** [comment]
here's what it's like with no delay, I don't think it's such a nice user experience

![menu2](https://user-images.githubusercontent.com/7141856/161545406-ecdc4f81-2371-47d0-aeeb-87104b0f4140.gif)

**Comment by slynch8** [comment]
100ms seems like a good compromise. I'll expose a setting for it in the next build.

**Comment by dbechrd** [comment]
Awesome. The title of this should probably have been "slower than some things, faster than others" in hindsight, but now it's "as fast as you want it" which is perfect. Closing. :)
