### ISSUE TITLE
UI bug on mouseover

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#853]
- Open a file and duplicate it in 2 panes
- Scroll to roughly the same spot
- With one pane active, mouse over the inactive pane for some line that the preprocessor can display info. The popup box with the info will open on top of the active pane.

Not sure if it's a bug or not but it's annoying :). Personally I'd prefer if the popup box opens on top of the line the mouse cursor is on, or not at all.

(v0.31.54)

**Comment by slynch8** [comment]
fixed (0.32.3)
