### ISSUE TITLE
Colons are not handled correctly in local Settings.10x_settings file

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#857]
Local Settings.10x_settings file:

![image](https://user-images.githubusercontent.com/40520199/162162011-7db91755-f04c-4b30-9ebe-3d4da2595555.png)

10x logs:

![image](https://user-images.githubusercontent.com/40520199/162161793-86727cf8-cba5-4744-9c46-186940e124e5.png)

It thinks that "C" is a setting's name instead of the value. It seems like it happens when value is on a new line.
\
\
\------------------------
version: 0.31.54

**Comment by slynch8** [comment]
yes, sorry. At the moment you have to put them all on the same line

**Comment by slynch8** [comment]
I've added a new issue for this
https://github.com/slynch8/10x/issues/869
