### ISSUE TITLE
Submenu item rendering issue

### ISSUE THREAD

**Issue by kondamask** [slynch8/10x#865]
The background doesn't get properly filled when the cursor is on it.

![](https://i.imgur.com/52vuVTF.png)

**Comment by ppetrov** [comment]
The same is true for any item that has submenu items

![2](https://user-images.githubusercontent.com/84007/182392968-1d0cac51-05fa-4baa-a3cc-d6db4ca3a2b1.png)

![1](https://user-images.githubusercontent.com/84007/182392955-5935ff46-b647-44e8-bcdf-3504d9237bbc.png)

**Comment by slynch8** [comment]
looks like you also have the transparent border bug as well? https://github.com/slynch8/10x/issues/907

**Comment by ppetrov** [comment]
> 

Yes, I have it.

![image](https://user-images.githubusercontent.com/84007/182541241-b709c464-e438-43cc-9c86-e1b9e536c320.png)
 
#907 is still open, so it's somewhat expected to still happen.

**Comment by slynch8** [comment]
fixed (0.33.6)
