### ISSUE TITLE
UI bug with 10x workspaces

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#878]
With a 10x workspace (workspace is actually saved) try the following:

- Add an existing folder
- Decide you made a mistake, so you want to remove that folder
- First try: revert the workspace by selecting it from file->recent workspaces. You are then prompted to save the workspace. You don't want that, so you click "No". You then get a quite large (infinite?) amount of prompts to save the workspace file. Only "Cancel" and "Yes" can get you out of this.
- Second try: close the workspace. You again get the prompt to save the workspace. You have to click "No" twice for the workspace to close without saving.
- Third try: You try to go to the workspace tree, right click and select "Remove". This apparently does nothing; the folder is still there.

Notice that I didn't save the workspace after adding the folder, because I just wanted to undo my error.

v0.31.62

**Comment by slynch8** [comment]
all these have been fixed in (0.32.3)
