### ISSUE TITLE
Opening a second solution after having previously loaded another will show search results from both sln.

### ISSUE THREAD

**Issue by detritivore** [slynch8/10x#884]
"load a.sln, and then load b.sln without closing 10x -> it's still showing stuff from a.sln

Note, I've only tested this with 'loading previous sln/workspace on start', not with manually loading two consecutive workspaces/sln.
also, only tested with actual sln. not 10x workspaces

**Comment by slynch8** [comment]
fixed in (0.31.67)
The problem was that it was including the recently opened files list in the files to open/search
