### ISSUE TITLE
Perf issue with find/replace (ctrl-h) and large lines

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#896]
To repro, in any c/c++ source paste the following line (not sure if only applicable to those extensions, but it's what I did here):

`int a[900]  = { 4 d 5 a 90 00 03 00 00 00 04 00 00 00 ff ff 00 00 b8 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 28 01 00 00 0e 1f ba 0e 00 b4 09 cd 21 b8 01 4 c cd 21 54 68 69 73 20 70 72 6f 67 72 61 6 d 20 63 61 6e 6e 6f 74 20 62 65 20 72 75 6e 20 69 6e 20 44 4f 53 20 6 d 6f 64 65 2e 0 d 0 d 0 a 24 00 00 00 00 00 00 00 09 6 d e8 31 4 d 0 c 86 62 4 d 0 c 86 62 4 d 0 c 86 62 16 64 85 63 6f 0 c 86 62 d3 ac 41 62 55 0 c 86 62 f3 7 d 82 63 58 0 c 86 62 f3 7 d 85 63 41 0 c 86 62 f3 7 d 83 63 d4 0 c 86 62 16 64 82 63 66 0 c 86 62 da 7e 82 63 c1 0 c 86 62 16 64 80 63 4 c 0 c 86 62 16 64 83 63 bb 0 c 86 62 16 64 87 63 52 0 c 86 62 4 d 0 c 87 62 0 d 0e 86 62 da 7e 8f 63 ab 0 d 86 62 da 7e 86 63 4 c 0 c 86 62 da 7e 79 62 4 c 0 c 86 62 4 d 0 c 11 62 4 c 0 c 86 62 da 7e 84 63 4 c 0 c 86 62 52 69 63 68 4 d 0 c 86 62 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 45 00 00 64 86 08 00 78 3 a 6f 62 00 00 00 00 00 00 00 00 f0 00 32 00 0b 02 0e 1 c 00 80 ad 00 00 0 a a5 04 00 00 00 00 ec c1 9 a 00 00 10 00 00 00 00 00 40 01 00 00 00 00 10 00 00 00 02 00 00 05 00 01 00 00 00 00 00 05 00 01 00 00 00 00 00 00 e0 52 05 00 04 00 00 00 00 00 00 02 00 60 81 00 00 10 00 00 00 00 00 00 10 00 00 00 00 00 00 00 00 10 00 00 00 00 00 00 10 00 00 00 00 00 00 00 00 00 00 10 00 00 00 00 95 16 01 c8 2 a 00 00 c8 bf 16 01 40 01 00 00 00 a0 51 05 b8 82 00 00 00 30 4 b 05 b0 43 06 00 00 00 00 00 00 00 00 00 00 30 52 05 3 c ab 00 00 40 94 06 01 70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 10 96 06 01 28 00 00 00 b0 94 06 01 38 01 00 00 00 00 00 00 00 00 00 00 00 90 ad 00 78 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 2e 74 65 78 74 00 00 00 57 7e ad 00 00 10 00 00 00 80 ad 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 20 00 00 60 2e 72 64 61 74 61 00 00 4 c 6 b 69 00 00 90 ad 00 00 6 c 69 00 00 84 ad 00 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 40 2e 64 61 74 61 00 00 00 20 24 34 04 00 00 17 01 00 d6 0 d 00 00 f0 16 01 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 c0 2e 70 64 61 74 61 00 00 b0 43 06 00 00 30 4 b 05 00 44 06 00 00 c6 24 01 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 40 2e 6 d 73 76 63 6 a 6 d 63 26 00 00 00 00 80 51 05 00 02 00 00 00 0 a 2 b 01 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 c0 5f 52 44 41 54 41 00 00 94 00 00 00 00 90 51 05 00 02 00 00 00 0 c 2 b 01 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 40 2e 72 73 72 63 00 00 00 b8 82 00 00 00 a0 51 05 00 84 00 00 00 0e 2 b 01 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 40 2e 72 65 6 c 6f 63 00 00 3 c ab 00 00 00 30 52 05 00 ac 00 00 00 92 2 b 01 00 00 00 00 00 00 00 00 00 00 00 00 40 00 00 42 }`

Then, select the contents between the brackets and press ctrl-h. Type a space in "find" and ", 0x" in "replace". Notice the speed of execution. Also, if you bring up task manager you will notice that one CPU core is maxed out on 10x. Undoing this also takes quite some time. Now, try exiting 10x. You will notice in the task manager that the CPU usage is still quite high. Sometimes I have to kill the 10x process, sometimes it manages to exit on its own.

**Comment by slynch8** [comment]
fixed (0.35.78)

**Comment by ggnkua** [comment]
Not sure if I should reopen this or open a new ticket but... I tried this in 0.35.79:

Paste the above line, do the find/replace (happens in a reasonable time), then hit ctrl-z twice so I undo the find/replace and the line paste (i.e. I wanted to get the file to its initial state). Then within 1-2 seconds I exited 10x completely. 2 out of 3 times I tried this, the 10x window became unresponsive and had to kill the process (laptop fans started spinning really fast too).

**Comment by slynch8** [comment]
I've stopped it hanging on shutdown, but it's still going to max out the cpu for a while while it handles all the updates. Ultimately I need to change the way I do the find/replace so that it only updates the line once, but that's a bigger and change that is too risky now.

**Comment by slynch8** [comment]
I've added a new task
https://github.com/slynch8/10x/issues/1373
