### ISSUE TITLE
MoveCursor key bind name inconsistencices

### ISSUE THREAD

**Issue by TurtleSimos** [slynch8/10x#897]
Sorting my key binds after losing settings, I found:

MoveCursorPrevWord / MoveCursorNextWord

But then for the versions which also extend the selection it is:

MoveCursorNextWordSelect - which is moving the previous word, equivalent to MoveCursorPrevWord 
MoveCursorNextNextSelect - which is moving to the next word, equivalent to MoveCursorNextWord

Changing the naming of the select versions to extend the base versions would be more intuitive.

**Comment by slynch8** [comment]
also check https://github.com/slynch8/10x/issues/887
