### ISSUE TITLE
Parser inconsistent when #undef a macro used to declare some symbols

### ISSUE THREAD

**Issue by JeanGeffroy** [slynch8/10x#899]
Example code:

```c++
#define MY_PREFIX( x ) int prefix_##x;
MY_PREFIX( some_def )
//#undef MY_PREFIX
prefix_some_def;
//#undef MY_PREFIX
```

The parser will correctly process the MY_PREFIX( some_def ) line as well as the prefix_some_def line, and all the goodies (find references, go to definition, etc.) work as expected. However, uncommenting either one of the #undef statements will break it. We use variations of this pattern in a few places in our codebase, resulting in 10x not parsing all the symbols correctly.

**Comment by JeanGeffroy** [comment]
This appear to now be working as expected in 0.32.34. Tested in the simple case I pasted in that earlier message, but also in more complex cases from our codebase, it's consistent everywhere. Thanks!

**Comment by slynch8** [comment]
great! :-)
