### ISSUE TITLE
After last Update(0.32.44), can no longer launch 10x nor repair it

### ISSUE THREAD

**Issue by kayakakan** [slynch8/10x#916]
Here is the log file for the repair attempt [log.txt](https://github.com/slynch8/10x/files/8819139/log.txt). I'm on Windows 7.

**Comment by slynch8** [comment]
What happens when you launch it, does it create a crash dump? see %appdata%\10x\CrashDumps

Also, instead of repairing try uninstalling and then reinstalling.

**Comment by kayakakan** [comment]
The crash seems to be a generic Windows crash ; it opens a dialog box saying that the application didn't launch correctly and has this error code in parenthesis: 0xC000007B.
Sadly, I coudn't find a crash dump related to that issue, it's like 10x doesn't get far enough in launching to allow that. Uninstalling and reinstalling was already tried, and led to the same situation.

**Comment by slynch8** [comment]
I can't think of anything that has changed that might cause this.

Can you try going back to the previous version and see if that still works. you'll need to uninstall first before installing an older version.
https://10xeditor.com/prev_versions.htm

**Comment by kayakakan** [comment]
Just installed version 0.32.43, and it worked right the first time. I don't know how to use Windows Event Viewer nor where to find it. There is definetely a bug lurking somewhere and it's a strange one, but if it doesn't happen to anyone else, I'm fine using a previous version.

**Comment by slynch8** [comment]
type "Event Viewer" into Windows and go to Windows Logs -> Application and see if you can find any errors.

I suspect it may be due to a .NET change. Maybe you need to install a more recent .NET.

![image](https://user-images.githubusercontent.com/7141856/171631097-607c5ba7-f368-4431-b7a9-7c5958b993ba.png)

**Comment by kayakakan** [comment]
I installed the .NET SDK version 6.0.300, and the .NET Runtime version 6.0.5 for both Desktop Apps and Console, but I was already on the latest .NET Framework which is 4.8. This did not resolve the issue, and it's the exact same dialog box from Windows and no crash dump.

**Comment by slynch8** [comment]
can you try starting it from within Visual Studio. Open the exe as a sln file from VS and then Start Debugging. See if there is a particular dll that it fails on.

**Comment by kayakakan** [comment]
This is what appears in the debugger output:
'10x.exe' (Win32) : Loaded 'W:\Programmes\PureDevSoftware\10x\10x.exe'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\ntdll.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\kernel32.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\KernelBase.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\msimg32.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\gdi32.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\user32.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\lpk.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\usp10.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\msvcrt.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\dwmapi.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\advapi32.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\sechost.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'10x.exe' (Win32) : Loaded 'W:\Programmes\PureDevSoftware\10x\PerforceAPI.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\mscoree.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\imm32.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\msctf.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\vcruntime140.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-crt-runtime-l1-1-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-core-timezone-l1-1-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-core-file-l2-1-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-core-localization-l1-2-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-core-synch-l1-2-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-core-processthreads-l1-1-1.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-core-file-l1-2-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-crt-heap-l1-1-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-crt-string-l1-1-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-crt-stdio-l1-1-0.dll'. 
'10x.exe' (Win32) : Loaded 'C:\Windows\System32\api-ms-win-crt-convert-l1-1-0.dll'. 
'10x.exe' (Win32) : Loaded 'W:\Programmes\PureDevSoftware\10x\VisualStudioLink.dll'. 
'10x.exe' (Win32) : Loaded 'W:\Programmes\PureDevSoftware\10x\MSBuildVarsNative.dll'. 
'10x.exe' (Win32) : Unloaded 'W:\Programmes\PureDevSoftware\10x\MSBuildVarsNative.dll'

**Comment by slynch8** [comment]
thanks, looks like it's MSBuildVarsNative.dll which is what I suspected. I'll send you a build to try later today.

**Comment by slynch8** [comment]
can you give this build a try. Extract and run the exe from that folder.
https://e1.pcloud.link/publink/show?code=XZd4uRZMCRAQ0yuY7JCIgQqVsrErykhuLBX

**Comment by kayakakan** [comment]
Thank you. It Worked!

**Comment by kayakakan** [comment]
Yes, this one works too!
I'll use a previous version and wait for the update. Thank you again.

**Comment by slynch8** [comment]
fixed (0.32.45)

**Comment by kayakakan** [comment]
Can confirm that the update resolved the issue.
