### ISSUE TITLE
Issue when using yank or delete line in combination with Vim visual modes

### ISSUE THREAD

**Issue by begla** [slynch8/10x#921]
When using yank with a selection made in visual line or character mode, it currently copies the line the cursor ends up in after the yank (and thus exiting the visual mode).

Removing this line fixed the issue for me:

https://github.com/slynch8/10x/blob/701a480a3784287304f0f6f0ce3cb180b212a232/PythonScripts/Vim/Vim.py#L250

Something similar happens when trying to delete a visual mode selection via "d". Removing the following line also fixes the issue for me:

https://github.com/slynch8/10x/blob/701a480a3784287304f0f6f0ce3cb180b212a232/PythonScripts/Vim/Vim.py#L223

**Comment by SimpsonGSD** [comment]
PR #1362 should fix these issues.

**Comment by slynch8** [comment]
nice, thanks Scott
