### ISSUE TITLE
Support for more complex keybindings?

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#924]
Still in the series of adding Emacs support to 10x.

Emacs defines `kill rectangle: C-x r k`. We added `Control x, r, k:        DeleteCharacters` to 10x but it seems to stop after the first control-x and insert an in the open tab.

**Comment by 42Bastian** [comment]
Just fetched the latest build and noticed double keys do no longer work.
Example:
Control x, Control s : SaveFile

Noting happens when pressed.

**Comment by 42Bastian** [comment]
Just checked, in .45 it works, in .46 not.

**Comment by slynch8** [comment]
fixed (0.32.46)
