### ISSUE TITLE
Some key bindings are working

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#926]
These key bindings are not working after recent updates.
These commands were bound control-alt-numpad4, numpad6, numpad8, numpad2 before.

![image](https://user-images.githubusercontent.com/40520199/172560696-7393b8a9-7577-477d-b53f-65ee2a521b84.png)

And also a request: can you please return numpad# keys in key bindings?
There is no way to bind 2 different commands to numpad and default numbers now.
\
\
\--------------------
version: 0.32.53

**Comment by slynch8** [comment]
can you try in the build I've just uploaded (0.32.53). Control Alt 4 works for me.

You can still use NumPad#. I think I made a mistake when I tried to fix up the old Num# bindings.

**Comment by Roman-Skabin** [comment]
Oh, yeah, Numpad# works fine. I've just read changelog and think you replaced numpad# to just #. So never mind, it works fine.

**Comment by Roman-Skabin** [comment]
Hmm, if control-alt-numpad# works fine, control-numpad# does not work for me.

**Comment by slynch8** [comment]
fixed (0.32.55)
