### ISSUE TITLE
Issue with multiple cursors + goto line

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#931]
- Start a multiline cursor
- Press ctrl-G to go to a line outside the cursor range
- Only one cursor moves, the others stay in their original place. Perhaps the multiline should be cancelled at that point? Probably not a common case to want to take the multiline cursors with you on goto

**Comment by stan680** [comment]
Oops, I just created and closed #1084 after realising it was a dupe of this issue but it does additionally point out that this is also true of GotoNextBuildError which is what caught me out so thought that was worth mentioning.

**Comment by ggnkua** [comment]
This seems to be fixed in v1.0.34. Closing.
