### ISSUE TITLE
Parser crash while parsing quite awkward macros

### ISSUE THREAD

**Issue by ggnkua** [slynch8/10x#934]
[10xplayground.zip](https://github.com/slynch8/10x/files/8907851/10xplayground.zip)

I've managed to find a small repro case for this, although it's quite hard to describe. Basically if you try to "Reparse all" 10x crashes here.

But that's not all. If you move the macros from `play.h` to `play.c` then if you hover over variable `x` inside `int a()` then you can see that 10x somehow identified `x` to the macro parameter (?) because `x` is not defined inside the function scope.

There is an even weirder implication of this, although I can't repro it in this test case: If you try to rename `x` into something else then 10x also crashes. This happens when the defines are in another file and not the same. Sadly I cannot share that repro case.

**Comment by ggnkua** [comment]
Further investigation shows that this is more severe than expected.

The original code in `play.h` was not like that. Instead it looked like this

`#define yyyy(x) ((U4)(((U4)result&0x1f)<<(result>>5)))`

What happened is that the first time I tried to do a rename ("x" to "result"), it started replacing `x` in a lot of macros inside the codebase with `result` and in all macros that have `x` as a parameter it also put a `result` at the start of the line.

**Comment by ggnkua** [comment]
Attached an updated workspace
[10xplayground.zip](https://github.com/slynch8/10x/files/8916670/10xplayground.zip)

Multiple weird things noticed with this one. I haven't deduced the results exactly but here is an approximation:

- "Go to definition" might take the cursor to `LOL_DEFINE(X1, even_more_macro_craziness(X4 x))` in `play2.c` or to `LOL_DECLARE(X1, even_more_macro_craziness(X4 x))` in `play.h`. It's not consistent. Looks like the renames might affect the result (see below)
- Try to rename the first instance of `x` in `play.c`. `LOL_DEFINE(X1, even_more_macro_craziness(X4 x))` in `play2.c` might get renamed. Undo.
- Try to rename the second of `x` in `play.c`. `#define SOME_KIND_OF_HELPER(x) MOAR_MACRO(x, MAGIC_VALUE)` and `LOL_DECLARE(X1, even_more_macro_craziness(X4 x))` might get renamed instead. The rename string might get prefixed in the first define.

**Comment by slynch8** [comment]
not sure how that got fixed :-) but good that it is.
