### ISSUE TITLE
Parser fails on Unreal FColor pre-inited colors

### ISSUE THREAD

**Issue by TurtleSimos** [slynch8/10x#937]
UE4 (and 5) has pre-inited colors as part of Color.h

For example: 
FColor::Blue

It's defined inside the Color.h header, as part of struct FColor
	static CORE_API const FColor Blue;
	
CORE_API is highlighting as something unparsed, as is Blue.

Note: the _API defines control whether dll linkage is specified. They are per module, but could be ignored.

**Comment by slynch8** [comment]
It should be fine if CORE_API is defined to a declspec, so I guess the problem is that the PCH defines header isn't being found for this file?

Also, in the build I'm about to upload I fixed a problem parsing static variables, so maybe it's that.

**Comment by TurtleSimos** [comment]
Just checked and it's now found the CORE_API which is a declspec, but the colors aren't recognised still. So likely static related. It's a quick/easy one to check at least.
