### ISSUE TITLE
10x can't repair itself

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#941]
I tried to update 10x, it took too long (about 5 minutes, while it takes about a minute usually), I aborted it thinking something goes wrong. Then I ran repair in 10xInstaller.exe hoping it will repair incomplete installation, but it failed with the output above.

One of failures in the log output of 10xInstaller.exe:

[1E38:6F44][2022-06-20T10:21:11]e000: Error 0x80070002: Failed attempt to download URL: 'http://go.microsoft.com/fwlink/?LinkId=560369' to: 'C:\Windows\Temp\{7F1208B5-26FA-40EB-A50A-9E61CB7CB500}\NetFx46Redist'

This is ERROR_FILE_NOT_FOUND error.

Log file: [log.txt](https://github.com/slynch8/10x/files/8938409/log.txt)
\
\
\--------------------
version: 0.32.76

**Comment by Roman-Skabin** [comment]
I tried to update 10x, it took too long (about 5 minutes, while it takes about a minute usually), I aborted it thinking something goes wrong. Then I ran repair in 10xInstaller.exe hoping it will repair incomplete installation, but it failed with the output above.

**Comment by slynch8** [comment]
Did it take 5 minutes to download (the green progress bar) or to actually install?

For now instead of repairing, use uninstall and then install again.

**Comment by slynch8** [comment]
sometimes you need to reboot if you have a windows update pending

**Comment by Roman-Skabin** [comment]
I have none

**Comment by slynch8** [comment]
ok, let me know if it happens again. Might have just been a temporary slowdown with my hosting.

I'll get the repair fixed.

**Comment by slynch8** [comment]
I can't find out how to fix the Repair. It seems to be a bug in Wix. So for now I've disabled it and created a new bug: https://github.com/slynch8/10x/issues/942

For now uninstall and then reinstall.

**Comment by slynch8** [comment]
ignore that, I managed to fix it
