### ISSUE TITLE
workspace tree scrollbar overlaps bottom docked window when resizing

### ISSUE THREAD

**Issue by RobertLemmens** [slynch8/10x#947]
Not a huge problem, just a visual thing, but when i resize the bottom docked window and the workspace tree's scrollbar shows up it sometimes overlaps
![overdraw](https://user-images.githubusercontent.com/5874861/174919958-e8fa3864-f0fd-43a1-8c7d-8b2125ac69df.png)
s

resizing up further and wiggeling around a bit seems to fix it. i dont really have a foolproof way to reproduce it as wel. Ill report back if i find out a reproduction path.

**Comment by slynch8** [comment]
fixed (0.33.6)
