### ISSUE TITLE
Switching from native to Parsec desktop causes 100% hang

### ISSUE THREAD

**Issue by SimpsonGSD** [slynch8/10x#955]
Selecting 10x to focus will cause a hang that does not recover, when using 10x in native (sat at desk) mode and switching to using Parsec client or vice versa. 

If 10x is opened during a Parsec or native session, switching to the other will hang.

This is the only app that does this.

This is with using Parsec's virtual desktop driver. I have not tested without it.

**Comment by slynch8** [comment]
I just tried this and can't get it to hang. I connect with a client, start 10x, then kick the client from the host. Is this right or are you switching in a different way?

**Comment by slynch8** [comment]
How do I set it to use "Parsec's virtual desktop driver"?

**Comment by slynch8** [comment]
try changing the parsec renderer to Direct3D 9

**Comment by SimpsonGSD** [comment]
It still crashes. That option is on the client so I suspect it doesn't affect it. 

The repro steps are open 10x as the local user (no parsec, no RDP). 
Connect with parsec using a different computer.
Select the open 10x instance, the app which go into a not responding state and crash.

**Comment by slynch8** [comment]
I've tried that repro but it still doesn't happen. All I can suggest is make sure you are on the latest parsec and have the latest drivers. Hopefully this will be fixed once I move to dx11 which I'll try and get to soon.

**Comment by slynch8** [comment]
fixed (0.33.11)
