### ISSUE TITLE
Text is invisible in undefined regions.

### ISSUE THREAD

**Issue by hsjunnesson** [slynch8/10x#958]
The text is the same color as the background inside the scope of a `if defined()` that isn't truthy. Unless I drag a selection around the code it's the same color as the background. I'd like to turn this dimming feature off, if possible. I can't seem to find a setting for it.

**Comment by slynch8** [comment]
Glad it's fixed. I'm just wondering why it wasn't there, had you updated from an old version?

**Comment by hsjunnesson** [comment]
Yes, I've updated multiple times on this install. Maybe since a year go.

**Comment by slynch8** [comment]
Ok. In case you are missing other settings it might be worth deleting the file and letting it re-generate.
