### ISSUE TITLE
Window size on window restore

### ISSUE THREAD

**Issue by Roman-Skabin** [slynch8/10x#967]
I don't know how to handle it 100%, but sometimes 10x does not restore window size to a previous non maximized size and restores it to screen size or near that.

For example:
Last time the size of the window was 960 x 540.
Your monitor size is 2560 x 1440.
You maximize your window, so now your window size is 2560 x 1440 (that's correct).
After a while you restore your window. And the problem is that your window does not resize to 960 x 540, it remains 2560 x 1440 or something near that but in a restored mode (not maximized).

"After a while" can be:
1. Right after maximization,
2. After 10x restart,
3. After computer reboot

\
By "maximize" and "restore" I mean SIZE_MAXIMIZED and SIZE_RESTORED in [WM_SIZE](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size) in wParam in WindowProc.

\
\-----------------------
Version: 0.32.107

**Comment by Roman-Skabin** [comment]
Well, it doesn't happens sometimes, it happens very often. Especially after PC reboot.

**Comment by slynch8** [comment]
ok, I 'll take a look at this as soon as I can

**Comment by slynch8** [comment]
I can't get this. Do you have multiple monitors?

**Comment by Roman-Skabin** [comment]
Yep. On another machine - no. But I'm not quite sure does it happen on machine with 1 monitor too.

**Comment by Roman-Skabin** [comment]
Idk maybe it's windows bug since windows must store non maximized window size in lParam on WM_SIZE message when wParam == SIZE_RESTORED. I reproduced this bug, but only once 😞. Anyway:
1. Open 10x
2. Resize the window to any non maximized size (640x480 for instance)
3. Maximize the window via the "maximize" button
4. Close the window
5. Open 10x (opens maximized, good)
6. Pull the window down with the mouse to make it non maximized. The size of the window remains 2560x1440 instead of 640x480.

Again, I was able to reproduce it only once. Maybe there are another ways to reproduce it.

**Comment by slynch8** [comment]
That's interesting, I didn't know that Windows stored the restore rect. Because I take over all NC client painting and window placement I've been storing it myself. I realised that I don't have to set the restore rect in SetWindowPlacement, I can just use the one from GetWindowPlacement. Hopefully this fixes it.

Can you try this build
https://e1.pcloud.link/publink/show?code=XZdCwLZAFnrW6k2Icz3GAEu6Yda9megvtDk

**Comment by Roman-Skabin** [comment]
Sure

**Comment by Roman-Skabin** [comment]
I tried this build, it seems like it works. I do not know how to handle it every time.

**Comment by slynch8** [comment]
Hopefully it's fixed now, I'll close this bug. Please re-open if you get it again.
